### ISSUE TITLE
Cannot load library .

### ISSUE THREAD

**Issue by sahana-tib** [facebook/fresco#1005]
The exception is raised when I try to run My App on Xolo.
I have a list and I am using the library to load images from the URL. The images are large in size and hence I am using the Image re-sizing option. This crashes the app in Xolo. Please help.

 java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1647): could not load library "libwebp.so" needed by "libimagepipeline.so"; caused by load_library(linker.cpp:757): library "libwebp.so" not found
            at java.lang.Runtime.loadLibrary(Runtime.java:372)
            at java.lang.System.loadLibrary(System.java:514)
            at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
            at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
            at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:43)
            at com.facebook.imagepipeline.nativecode.JpegTranscoder.<clinit>(JpegTranscoder.java:26)
            at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.doTransform(ResizeAndRotateProducer.java:154)
            at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.access$000(ResizeAndRotateProducer.java:72)
            at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer$1.run(ResizeAndRotateProducer.java:89)
            at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
            at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
            at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
            at java.lang.Thread.run(Thread.java:838)

**Comment by Zhuinden** [comment]
I got this exact same crash on a Sony C1905 today.

The solution is for Fresco to use [RELINKER ](https://github.com/KeepSafe/ReLinker) library to load the native libs, instead of `System.findLibrary()`. The only change is adding Relinker dependency, and calling `Relinker.findLibrary()` instead.

**Comment by JChord** [comment]
you can try this one:
```
ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this)
                .setDownsampleEnabled(true).build();
Fresco.initialize(this, config);

RequestManager.init(this);
```
to support PNG and Webp.
