### ISSUE TITLE
Canvas: trying to use a recycled bitmap >> app crash

### ISSUE THREAD

**Issue by karun2189** [facebook/fresco#1021]
> Fatal Exception: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@1375947c
       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1303)
       at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:599)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
       at com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha(FadeDrawable.java:306)
       at com.facebook.drawee.drawable.FadeDrawable.draw(FadeDrawable.java:293)
       at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:140)
       at com.facebook.drawee.generic.RootDrawable.draw(RootDrawable.java:85)
       at android.widget.ImageView.onDraw(ImageView.java:1179)
       at android.view.View.draw(View.java:16472)
       at android.view.View.updateDisplayListIfDirty(View.java:15402)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
       at android.view.View.updateDisplayListIfDirty(View.java:15362)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
       at android.view.View.updateDisplayListIfDirty(View.java:15362)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
       at android.view.View.updateDisplayListIfDirty(View.java:15362)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
       at android.view.View.updateDisplayListIfDirty(View.java:15362)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
       at android.view.View.updateDisplayListIfDirty(View.java:15362)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.View.draw(View.java:16194)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3709)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3502)
       at android.view.View.draw(View.java:16475)
       at android.view.View.updateDisplayListIfDirty(View.java:15402)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
       at android.view.View.updateDisplayListIfDirty(View.java:15362)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
       at android.view.View.updateDisplayListIfDirty(View.java:15362)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
       at android.view.View.updateDisplayListIfDirty(View.java:15362)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
       at android.view.View.updateDisplayListIfDirty(View.java:15362)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
       at android.view.View.updateDisplayListIfDirty(View.java:15362)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
       at android.view.View.updateDisplayListIfDirty(View.java:15362)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
       at android.view.View.updateDisplayListIfDirty(View.java:15362)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
       at android.view.View.updateDisplayListIfDirty(View.java:15362)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
       at android.view.View.updateDisplayListIfDirty(View.java:15362)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3693)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3672)
       at android.view.View.updateDisplayListIfDirty(View.java:15362)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:310)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:316)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:355)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2889)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2683)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2270)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1264)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6944)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
       at android.view.Choreographer.doFrame(Choreographer.java:560)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6843)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by aagnes** [comment]
Can you show how you try to use bitmap?

**Comment by oprisnik** [comment]
I guess you are using Fresco to get the Bitmap directly. If you do so, you should not manually call `bitmap.close()`. If you use a `CloseableReference<Bitmap>` or `CloseableReference<CloseableImage>`, make sure to hold on to the reference until you are done and then close the reference.
If you do not hold on to it, the finalizer of the reference will close the bitmap for you in order to avoid memory leaks.
