### ISSUE TITLE
java.lang.Class<com.facebook.imagepipeline.nativecode.JpegTranscoder>

### ISSUE THREAD

**Issue by ikkyu0319** [facebook/fresco#1032]
dlopen("/data/app/com.qyer.android.plan-1/lib/arm/libimagepipeline.so", RTLD_LAZY) failed: dlopen failed: library "libwebp.so" not found

 java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.imagepipeline.nativecode.JpegTranscoder; see exception in other thread
                                                                           at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.doTransform(ResizeAndRotateProducer.java:154)
                                                                           at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.access$000(ResizeAndRotateProducer.java:72)
                                                                           at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer$1.run(ResizeAndRotateProducer.java:89)
                                                                           at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                                                                           at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                                                                           at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                           at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                                           at java.lang.Thread.run(Thread.java:818)

**Comment by michalgr** [comment]
Do you use proguard ? Can you make sure this is included in proguard config: https://github.com/facebook/fresco/blob/master/proguard-fresco.pro ?

**Comment by binqiangsun** [comment]
@michalgr do latest version need this proguard config?

**Comment by imliujun** [comment]
java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libwebp.so" needed by "libimagepipeline.so"; caused by load_library(linker.cpp:745): library "libwebp.so" not found
	at java.lang.Runtime.loadLibrary(Runtime.java:365)
	at java.lang.System.loadLibrary(System.java:514)
	at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
	at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
	at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:43)
	at com.facebook.imagepipeline.nativecode.JpegTranscoder.(JpegTranscoder.java:26)
	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.doTransform(ResizeAndRotateProducer.java:154)
	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.access$000(ResizeAndRotateProducer.java:72)
	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer$1.run(ResizeAndRotateProducer.java:89)
	at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
	at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
	at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
	at java.lang.Thread.run(Thread.java:838)

**Comment by massimocarli** [comment]
@imliujun Have you tired the solution here? https://github.com/facebook/fresco/issues/410

Thanks

**Comment by erikandre** [comment]
The suggested solution for this type of issue is to use https://github.com/facebook/SoLoader
