### ISSUE TITLE
Failed to register native method com.facebook.imagepipeline.memory.NativeMemoryChunk.nativeReadByte(J)B

### ISSUE THREAD

**Issue by orospakr** [facebook/fresco#105]
```
E/art     ( 6015): ----- class 'Lcom/facebook/imagepipeline/memory/NativeMemoryChunk;' cl=0x12c83de0 -----
E/art     ( 6015):   objectSize=440 (412 from super)
E/art     ( 6015):   access=0x8008.0001
E/art     ( 6015):   super='java.lang.Class<java.lang.Object>' (cl=0x0)
E/art     ( 6015):   interfaces (1):
E/art     ( 6015):      0: java.lang.Class<java.io.Closeable> (cl=0x0)
E/art     ( 6015):   vtable (8 entries, 11 in super):
E/art     ( 6015):      0: void com.facebook.imagepipeline.memory.NativeMemoryChunk.close()
E/art     ( 6015):      1: void com.facebook.imagepipeline.memory.NativeMemoryChunk.copy(int, com.facebook.imagepipeline.memory.NativeMemoryChunk, int, int)
E/art     ( 6015):      2: void com.facebook.imagepipeline.memory.NativeMemoryChunk.finalize()
E/art     ( 6015):      3: long com.facebook.imagepipeline.memory.NativeMemoryChunk.getNativePtr()
E/art     ( 6015):      4: int com.facebook.imagepipeline.memory.NativeMemoryChunk.getSize()
E/art     ( 6015):      5: boolean com.facebook.imagepipeline.memory.NativeMemoryChunk.isClosed()
E/art     ( 6015):      6: int com.facebook.imagepipeline.memory.NativeMemoryChunk.read(int, byte[], int, int)
E/art     ( 6015):      7: int com.facebook.imagepipeline.memory.NativeMemoryChunk.write(int, byte[], int, int)
E/art     ( 6015):   direct methods (11 entries):
E/art     ( 6015):      0: void com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>()
E/art     ( 6015):      1: void com.facebook.imagepipeline.memory.NativeMemoryChunk.<init>()
E/art     ( 6015):      2: void com.facebook.imagepipeline.memory.NativeMemoryChunk.<init>(int)
E/art     ( 6015):      3: int com.facebook.imagepipeline.memory.NativeMemoryChunk.adjustByteCount(int, int)
E/art     ( 6015):      4: void com.facebook.imagepipeline.memory.NativeMemoryChunk.checkBounds(int, int, int, int)
E/art     ( 6015):      5: void com.facebook.imagepipeline.memory.NativeMemoryChunk.doCopy(int, com.facebook.imagepipeline.memory.NativeMemoryChunk, int, int)
E/art     ( 6015):      6: long com.facebook.imagepipeline.memory.NativeMemoryChunk.nativeAllocate(int)
E/art     ( 6015):      7: void com.facebook.imagepipeline.memory.NativeMemoryChunk.nativeCopyFromByteArray(long, byte[], int, int)
E/art     ( 6015):      8: void com.facebook.imagepipeline.memory.NativeMemoryChunk.nativeCopyToByteArray(long, byte[], int, int)
E/art     ( 6015):      9: void com.facebook.imagepipeline.memory.NativeMemoryChunk.nativeFree(long)
E/art     ( 6015):     10: void com.facebook.imagepipeline.memory.NativeMemoryChunk.nativeMemcpy(long, long, int)
E/art     ( 6015):   instance fields (3 entries):
E/art     ( 6015):      0: boolean com.facebook.imagepipeline.memory.NativeMemoryChunk.mClosed
E/art     ( 6015):      1: long com.facebook.imagepipeline.memory.NativeMemoryChunk.mNativePtr
E/art     ( 6015):      2: int com.facebook.imagepipeline.memory.NativeMemoryChunk.mSize
E/art     ( 6015): Failed to register native method com.facebook.imagepipeline.memory.NativeMemoryChunk.nativeReadByte(J)B in /data/app/com.joistapp.android.joist.dev-2/base.apk
E/libmemchunk( 6015): could not register NativeMemoryChunk methods
E/AndroidRuntime( 6015): FATAL EXCEPTION: OkHttp Dispatcher
E/AndroidRuntime( 6015): Process: com.joistapp.android.joist.dev, PID: 6015
E/AndroidRuntime( 6015): java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.joistapp.android.joist.dev-2/lib/arm/libmemchunk.so"
E/AndroidRuntime( 6015): 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
E/AndroidRuntime( 6015): 	at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime( 6015): 	at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:34)
E/AndroidRuntime( 6015): 	at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
E/AndroidRuntime( 6015): 	at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:37)
E/AndroidRuntime( 6015): 	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
E/AndroidRuntime( 6015): 	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
E/AndroidRuntime( 6015): 	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:264)
E/AndroidRuntime( 6015): 	at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
E/AndroidRuntime( 6015): 	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:141)
E/AndroidRuntime( 6015): 	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:26)
E/AndroidRuntime( 6015): 	at com.facebook.imagepipeline.producers.NetworkFetchProducer.processResult(NetworkFetchProducer.java:117)
E/AndroidRuntime( 6015): 	at com.facebook.imagepipeline.backends.okhttp.OkHttpNetworkFetchProducer.access$000(OkHttpNetworkFetchProducer.java:41)
E/AndroidRuntime( 6015): 	at com.facebook.imagepipeline.backends.okhttp.OkHttpNetworkFetchProducer$2.onResponse(OkHttpNetworkFetchProducer.java:101)
E/AndroidRuntime( 6015): 	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
E/AndroidRuntime( 6015): 	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
E/AndroidRuntime( 6015): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 6015): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 6015): 	at java.lang.Thread.run(Thread.java:818)
```

Our app, incidentally, is written in Kotlin, which I believe is probably the only relevant odd thing about it.  Device I was running this on at runtime is a N5 with 5.1.

**Comment by orospakr** [comment]
Incidentally, a worthwhile thing might be to include the result code from `RegisterNatives` in the log message.

**Comment by michalgr** [comment]
I guess you use proguard and it removes `nativeReadByte` which appears to be unused.

Can you try to instruct proguard not to remove anything annotated with @DoNotStrip ? Example here: https://github.com/facebook/fresco/blob/master/fbcore/src/main/java/com/facebook/common/internal/proguard_annotations.pro

**Comment by orospakr** [comment]
Oh dang!  That's done it. Thanks!

It seems I've opened the classic "ProGuard broke your library" ticket that every project inevitably gets.
