### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by jyh149129** [facebook/fresco#1050]
phone：vivo X510t Android 4.2.2

java.lang.NoClassDefFoundError
com/facebook/imagepipeline/nativecode/JpegTranscoder

03-11 11:01:35.139 13373 14295 E dalvikvm: dlopen("/mnt/asec/xxx-2/lib/libimagepipeline.so") failed: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libwebp.so" needed by "libimagepipeline.so"; caused by load_library(linker.cpp:745): library "libwebp.so" not found

03-11 11:01:35.139 13373 14295 W dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/facebook/imagepipeline/nativecode/JpegTranscoder;

**Comment by balazsbalazs** [comment]
cc @massimocarli

**Comment by ICECHN** [comment]
java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libwebp.so" needed by "libimagepipeline.so"; caused by load_library(linker.cpp:745): library "libwebp.so" not found
	at java.lang.Runtime.loadLibrary(Runtime.java:365)
	at java.lang.System.loadLibrary(System.java:514)
	at com.facebook.common.i.c.a(Unknown Source)
	at com.facebook.common.i.a.a(Unknown Source)
	at com.facebook.imagepipeline.nativecode.a.a(Unknown Source)
	at com.facebook.imagepipeline.nativecode.JpegTranscoder.<clinit>(Unknown Source)
	at com.facebook.imagepipeline.k.cg.b(Unknown Source)
	at com.facebook.imagepipeline.k.cg.a(Unknown Source)
	at com.facebook.imagepipeline.k.ch.a(Unknown Source)
	at com.facebook.imagepipeline.k.aj.e(Unknown Source)
	at com.facebook.imagepipeline.k.aj.a(Unknown Source)
	at com.facebook.imagepipeline.k.ak.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at com.facebook.imagepipeline.e.s.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:838)
![qq 20160323092320](https://cloud.githubusercontent.com/assets/11832023/13972980/f7a56eac-f0d8-11e5-9947-70cc7d3baa44.jpg)

**Comment by erikandre** [comment]
Our general recommendation for this type of issue is to use SoLoader: https://github.com/facebook/SoLoader
