### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libwebp.so" needed by "libimagepipeline.so"; caused by load_library(linker.cpp:745): library "libwebp.so" not found

### ISSUE THREAD

**Issue by liangxianshen** [facebook/fresco#1057]
The problem appeared in the MX2/SONYs39h devices.  API 4.2.1 、4.2.2
And I have used  **request = ImageRequestBuilder.newBuilderWithSource(uri)
                    .setResizeOptions(new ResizeOptions(width, height))
                    .build();**
Another problem is loading the format is JPG images,PNG, there is no problem.

**Comment by EugineKidoz** [comment]
I have the same issue - device running **android 4.4.2 armv7**:

**Before **adding : (**compile 'com.facebook.fresco:webpsupport:0.9.0**)
I get this crash:
`java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1652): could not load library "libwebp.so" needed by "libimagepipeline.so"; caused by load_library(linker.cpp:759): library "libwebp.so" not found
                                                                  at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                  at java.lang.System.loadLibrary(System.java:514)
                                                                  at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
                                                                  at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
                                                                  at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:43)
                                                                  at com.facebook.imagepipeline.nativecode.JpegTranscoder.<clinit>(JpegTranscoder.java:26)
                                                                  at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.doTransform(ResizeAndRotateProducer.java:154)
                                                                  at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.access$000(ResizeAndRotateProducer.java:72)
                                                                  at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer$1.run(ResizeAndRotateProducer.java:89)
                                                                  at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                                                                  at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                                                                  at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                  at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                                  at java.lang.Thread.run(Thread.java:838)`

And after inserting :+1: (**compile 'com.facebook.fresco:webpsupport:0.9.0**)
I get this crash : 

`03-17 13:00:59.230 11894-12104/com.kidoz.tv W/System.err: java.lang.NoClassDefFoundError: com/facebook/imagepipeline/nativecode/JpegTranscoder
03-17 13:00:59.230 11894-12105/com.kidoz.tv D/dalvikvm: threadid=49 (Thread-590): calling run()
03-17 13:00:59.232 11894-12104/com.kidoz.tv W/System.err:     at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.doTransform(ResizeAndRotateProducer.java:154)
03-17 13:00:59.232 11894-12104/com.kidoz.tv W/System.err:     at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.access$000(ResizeAndRotateProducer.java:72)
03-17 13:00:59.233 11894-12104/com.kidoz.tv W/System.err:     at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer$1.run(ResizeAndRotateProducer.java:89)
03-17 13:00:59.233 11894-12104/com.kidoz.tv W/System.err:     at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
03-17 13:00:59.233 11894-12104/com.kidoz.tv W/System.err:     at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
03-17 13:00:59.233 11894-12104/com.kidoz.tv W/System.err:     at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
03-17 13:00:59.233 11894-12104/com.kidoz.tv W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
03-17 13:00:59.233 11894-12104/com.kidoz.tv W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
03-17 13:00:59.234 11894-12104/com.kidoz.tv W/System.err:     at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
03-17 13:00:59.234 11894-12104/com.kidoz.tv W/System.err:     at java.lang.Thread.run(Thread.java:838)
03-17 13:00:59.234 11894-12104/com.kidoz.tv W/dalvikvm: threadid=48: calling UncaughtExceptionHandler
03-17 13:00:59.234 11894-12104/com.kidoz.tv E/KidozApplication: Uncaught Exception: com/facebook/imagepipeline/nativecode/JpegTranscoder`

**Comment by EugineKidoz** [comment]
Forgot to add - Version **0.8.1** is working fine!

**Comment by massimocarli** [comment]
please try the solution described here. https://github.com/facebook/fresco/issues/933

**Comment by liangxianshen** [comment]
Thanks , perfect!
