### ISSUE TITLE
java.lang.NoSuchMethodError: no static or non-static method "Lcom/facebook/imagepipeline/nativecode/Bitmaps;.nativeCopyBitmap(Landroid/graphics/Bitmap;ILandroid/graphics/Bitmap;II)V"

### ISSUE THREAD

**Issue by darrennight** [facebook/fresco#1077]
java.lang.NoSuchMethodError: no static or non-static method "Lcom/facebook/imagepipeline/nativecode/Bitmaps;.nativeCopyBitmap(Landroid/graphics/Bitmap;ILandroid/graphics/Bitmap;II)V"
                                                     at java.lang.Runtime.nativeLoad(Native Method)
                                                     at java.lang.Runtime.doLoad(Runtime.java:421)
                                                     at java.lang.Runtime.loadLibrary(Runtime.java:362)
                                                     at java.lang.System.loadLibrary(System.java:538)
                                                     at com.facebook.common.g.b.a(Unknown Source)
                                                     at com.facebook.common.g.a.a(Unknown Source)
                                                     at com.facebook.imagepipeline.nativecode.Bitmaps.<clinit>(Unknown Source)
                                                     at com.facebook.imagepipeline.h.b.a(Unknown Source)
                                                     at com.facebook.imagepipeline.h.d.a(Unknown Source)
                                                     at com.facebook.imagepipeline.h.b.a(Unknown Source)
                                                     at com.facebook.imagepipeline.h.d.a(Unknown Source)
                                                     at com.facebook.imagepipeline.e.a.a(Unknown Source)
                                                     at com.facebook.imagepipeline.e.a.a(Unknown Source)
at com.facebook.imagepipeline.producers.t.c(Unknown Source)
                                                     at com.facebook.imagepipeline.producers.t.a(Unknown Source)
                                                     at com.facebook.imagepipeline.producers.u.a(Unknown Source)
                                                     at com.facebook.imagepipeline.producers.JobScheduler.e(Unknown Source)
                                                     at com.facebook.imagepipeline.producers.JobScheduler.a(Unknown Source)
                                                     at com.facebook.imagepipeline.producers.aj.run(Unknown Source)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at com.facebook.imagepipeline.c.m.run(Unknown Source)
                                                     at java.lang.Thread.run(Thread.java:841)

**Comment by massimocarli** [comment]
Please provide more information.
Thanks

**Comment by aagnes** [comment]
merge in #410

**Comment by maikoulin** [comment]
java.lang.NoSuchMethodError: no static or non-static method "Lcom/facebook/imagepipeline/nativecode/Bitmaps;.nativeGetByteBuffer(Landroid/graphics/Bitmap;JJ)Ljava/nio/ByteBuffer;"
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.doLoad(Runtime.java:421)
	at java.lang.Runtime.loadLibrary(Runtime.java:362)
	at java.lang.System.loadLibrary(System.java:526)
	at com.facebook.common.f.b.a(Unknown Source)
	at com.facebook.common.f.a.a(Unknown Source)
	at com.facebook.imagepipeline.nativecode.Bitmaps.<clinit>(Unknown Source)
	at com.facebook.imagepipeline.i.b.a(Unknown Source)
	at com.facebook.imagepipeline.i.d.a(Unknown Source)
	at com.facebook.imagepipeline.i.b.a(Unknown Source)
	at com.facebook.imagepipeline.i.d.a(Unknown Source)
	at com.facebook.imagepipeline.f.a.a(Unknown Source)
	at com.facebook.imagepipeline.f.a.a(Unknown Source)
	at com.facebook.imagepipeline.producers.t.c(Unknown Source)
	at com.facebook.imagepipeline.producers.t.a(Unknown Source)
	at com.facebook.imagepipeline.producers.u.a(Unknown Source)
	at com.facebook.imagepipeline.producers.JobScheduler.e(Unknown Source)
	at com.facebook.imagepipeline.producers.JobScheduler.a(Unknown Source)
	at com.facebook.imagepipeline.producers.ak.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at com.facebook.imagepipeline.d.n.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:841)
|

**Comment by SephirothLT** [comment]
you should add [http://frescolib.org/docs/proguard.html](url) this to your proguard-rules  if your minifyEnabled true

**Comment by SephirothLT** [comment]
[https://raw.githubusercontent.com/facebook/fresco/master/proguard-fresco.pro](url)
