### ISSUE TITLE
InflateException:  Error inflating class com.facebook.drawee.view.SimpleDraweeView

### ISSUE THREAD

**Issue by yarolegovich** [facebook/fresco#1081]
Hi, I have InflateException on Pre-Lollipop devices, on 21+ everything is ok.
```java
Fresco.initialize(context);
```
Call is made during application's onCreate().
I'm using Fresco v.0.9.0

Stacktrace:
```
FATAL EXCEPTION: main
Process: co.samepinch.android.app, PID: 15158
android.view.InflateException: Binary XML file line #33: Error inflating class com.facebook.drawee.view.SimpleDraweeView at android.view.LayoutInflater.createView(LayoutInflater.java:620)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
at co.samepinch.android.app.helpers.adapters.PostCursorRecyclerViewAdapter.onCreateViewHolder(PostCursorRecyclerViewAdapter.java:28)
at co.samepinch.android.app.helpers.adapters.PostCursorRecyclerViewAdapter.onCreateViewHolder(PostCursorRecyclerViewAdapter.java:16)
at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5228)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4453)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
 at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:584)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1037)
at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:747)
at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1156)
at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:760)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at com.flipboard.bottomsheet.BottomSheetLayout.onLayout(BottomSheetLayout.java:180)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
at android.view.View.layout(View.java:14817)
at android.view.ViewGroup.layout(ViewGroup.java:4631)
at android.widget
```

**Comment by chandanbenjaram** [comment]
I am running into this too! Please advice.

**Comment by aagnes** [comment]
Can you provide the piece of XML that specifies SimpleDraweeView?

**Comment by yarolegovich** [comment]
This doesn't play any role. Crash will appear on any xml declaration
be it 
```
<com.facebook.drawee.view.SimpleDraweeView
    android:id="@+id/view_avatar"
    android:layout_width="@dimen/signup_avatar_size"
    android:layout_height="@dimen/signup_avatar_size"
    android:layout_gravity="center_horizontal"
    android:adjustViewBounds="true"
    android:background="@drawable/avatar_border"
    fresco:placeholderImage="@drawable/camera_blue"
    fresco:placeholderImageScaleType="centerCrip"
    fresco:roundAsCircle="true" />
```
or
```
<com.facebook.drawee.view.SimpleDraweeView
    android:id="@+id/view_avatar"
    android:layout_width="@dimen/signup_avatar_size"
    android:layout_height="@dimen/signup_avatar_size"  />
```
or whatever.

**Comment by tcking** [comment]
did u called `Fresco.initialize(context)` in application  onCreate ?

**Comment by Anler2015** [comment]
I have the same problem. But when i put `Fresco.initialize(context)` before the Activity's `setContentView(R.layout.activity_main); `  That's ok.

**Comment by yarolegovich** [comment]
Hi, yes I did.

2016-04-01 4:27 GMT+03:00 tom <notifications@github.com>:

> did u called Fresco.initialize(context) in application onCreate ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/fresco/issues/1081#issuecomment-204199134>
>



-- 
Best regards

**Comment by sungerk** [comment]
besause of  oom,I've had this problem too.

**Comment by tyronen** [comment]
These problems are usually caused by not calling `Fresco.initialize` as @Anier2015 said.

If you have called it, please open a new issue, and paste in the section of the stack trace below any text like "Caused by".

**Comment by aneeshATgithub** [comment]
use following version, and you can initialize fresco in Application class

compile 'com.facebook.fresco:fresco:0.12.0'
