### ISSUE TITLE
OOM In 5.0 over the system. Samsung GALAXY S6 ...

### ISSUE THREAD

**Issue by liangxianshen** [facebook/fresco#1090]
java.lang.OutOfMemoryError: Failed to allocate a 31961100 byte allocation with 1855268 free bytes and 1811KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
	at android.graphics.Bitmap.nativeCreate(Bitmap.java)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:842)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:779)
	at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
	at com.facebook.imagepipeline.memory.BitmapPool.free(BitmapPool.java:30)
	at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
	at com.facebook.imagepipeline.platform.ArtDecoder.decodeStaticImageFromStream(ArtDecoder.java:137)
	at com.facebook.imagepipeline.platform.ArtDecoder.decodeJPEGFromEncodedImage(ArtDecoder.java:120)
	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeJpeg(ImageDecoder.java:151)
	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:85)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:189)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.onNewResultImpl(DecodeProducer.java:97)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:97)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$400(DecodeProducer.java:97)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:129)
	at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
	at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
	at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
	at java.lang.Thread.run(Thread.java:833)

**Comment by aagnes** [comment]
please try with downsampling or resizeOption for your jpeg image. You don't need to load full image of 30MB.
