### ISSUE TITLE
Android Marshmallow can't recycle memory in Recyclerview

### ISSUE THREAD

**Issue by sungerk** [facebook/fresco#1113]
```
04-09 22:57:50.567 17733-17804/sunger.org.net.meishi E/AndroidRuntime: FATAL EXCEPTION: Thread-392
                                                                       Process: sunger.org.net.meishi, PID: 17733
                                                                       Theme: themes:{}
                                                                       java.lang.OutOfMemoryError: Failed to allocate a 921612 byte allocation with 563712 free bytes and 550KB until OOM
                                                                           at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                           at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                           at android.graphics.Bitmap.createBitmap(Bitmap.java:832)
                                                                           at android.graphics.Bitmap.createBitmap(Bitmap.java:809)
                                                                           at android.graphics.Bitmap.createBitmap(Bitmap.java:776)
                                                                           at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
                                                                           at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
                                                                           at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
                                                                           at com.facebook.imagepipeline.platform.ArtDecoder.decodeStaticImageFromStream(ArtDecoder.java:137)
                                                                           at com.facebook.imagepipeline.platform.ArtDecoder.decodeJPEGFromEncodedImage(ArtDecoder.java:120)
                                                                           at com.facebook.imagepipeline.decoder.ImageDecoder.decodeJpeg(ImageDecoder.java:151)
                                                                           at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:85)
                                                                           at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:189)
                                                                           at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:97)
                                                                           at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:129)
                                                                           at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                                                                           at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                                                                           at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                           at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                                           at java.lang.Thread.run(Thread.java:818)
```

**Comment by aagnes** [comment]
We have a comparison sample app for using RecyclerView. You can refer on that app. Also can you show how you use RecyclerView with Drawee?

**Comment by sungerk** [comment]
[RecyclerView](https://github.com/sungerk/meiShi/blob/master/app/src/main/java/org/sunger/net/ui/fragmet/HomeMediasFragment.java)

[Adapter](https://github.com/sungerk/meiShi/blob/master/app/src/main/java/org/sunger/net/ui/adapter/MediasAdapter.java)

**Comment by kirwan** [comment]
Thanks for sharing your code. I believe it's helped me find the solution.

Take a look at [this line in our sample](https://github.com/facebook/fresco/blob/master/samples/comparison/src/main/java/com/facebook/samples/comparison/holders/FrescoHolder.java#L52). By calling `setOldController()` like this, the existing controller may actually be reused and the old image is cleared from memory.

In you case this should be done in `MediasAdapter` in the chained build which starts at line 73.

**Comment by kirwan** [comment]
Feel free to reopen the issue if you continue to have a problem.

**Comment by sungerk** [comment]
thanks.I will try

**Comment by sungerk** [comment]
@kirwan i calling  the setOldController as sample.  the but it's still has the problem
