### ISSUE TITLE
Windows build failing

### ISSUE THREAD

**Issue by yarinkos** [facebook/fresco#1114]
windows 7,
BUILD_TOOLS_VERSION=23.0.1
COMPILE_SDK_VERSION=23
latest source vesion

I get this error when try to build the from source.

```
`:animated-gif:androidSourcesJar
[armeabi-v7a] Compile        : bitmaps <= Bitmaps.c
:animated-base-test:processDebugUnitTestJavaRes UP-TO-DATE
make: Circular C:\dev\Android <- C:\dev\Android dependency dropped.
make: Circular projects\fresco\imagepipeline\build\tmp\ndk_build_bitmaps/local/arm64-v8a/libbitmaps.so <- C:\dev\Android dependency dropped.
make: Circular C:\dev\Android <- C:\dev\Android dependency dropped.
make: Circular C:\dev\Android <- C:\dev\Android dependency dropped.
:animated-base-test:mockableAndroidJar
[armeabi] Compile        : bitmaps <= Bitmaps.c
make: Circular C:\dev\Android <- C:\dev\Android dependency dropped.
make: Circular projects\fresco\imagepipeline\build\tmp\ndk_build_bitmaps/local/x86/libbitmaps.so <- C:\dev\Android dependency dropped.
make: Circular C:\dev\Android <- C:\dev\Android dependency dropped.
[arm64-v8a] Compile        : bitmaps <= Bitmaps.c
process_begin: CreateProcess(NULL, C:/Users/yarin.kossover/AppData/Local/Android/sdk/ndk-bundle/build//../toolchains/arm-linux-androideabi-4.8/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc -MMD -MP -MF C:\dev\Android projects\fresco\imagepipeline\build\tmp\ndk_build_bitmaps/local/armeabi-v7a/objs/bitmaps/Bitmaps.o.d -I. -DANDROID -Wall -Wextra -Werror -std=c11 -fvisibility=hidden -Wa,--noexecstack -Wformat -Werror=format-security -isystem C:/Users/yarin.kossover/AppData/Local/Android/sdk/ndk-bundle/build//../platforms/android-9/arch-arm/usr/include -c ./Bitmaps.c -o C:\dev\Android projects\fresco\imagepipeline\build\tmp\ndk_build_bitmaps/local/armeabi-v7a/objs/bitmaps/Bitmaps.o, ...) failed.

make: *** [projects\fresco\imagepipeline\build\tmp\ndk_build_bitmaps/local/armeabi-v7a/objs/bitmaps/Bitmaps.o] Error 2
make: *** Waiting for unfinished jobs....
process_begin: CreateProcess(NULL, C:/Users/yarin.kossover/AppData/Local/Android/sdk/ndk-bundle/build//../toolchains/arm-linux-androideabi-4.8/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc -MMD -MP -MF C:\dev\Android projects\fresco\imagepipeline\build\tmp\ndk_build_bitmaps/local/armeabi/objs/bitmaps/Bitmaps.o.d -I. -DANDROID -Wall -Wextra -Werror -std=c11 -fvisibility=hidden -Wa,--noexecstack -Wformat -Werror=format-security -isystem C:/Users/yarin.kossover/AppData/Local/Android/sdk/ndk-bundle/build//../platforms/android-9/arch-arm/usr/include -c ./Bitmaps.c -o C:\dev\Android projects\fresco\imagepipeline\build\tmp\ndk_build_bitmaps/local/armeabi/objs/bitmaps/Bitmaps.o, ...) failed.

make: *** [projects\fresco\imagepipeline\build\tmp\ndk_build_bitmaps/local/armeabi/objs/bitmaps/Bitmaps.o] Error 2
[x86] Compile        : bitmaps <= Bitmaps.c
process_begin: CreateProcess(NULL, C:/Users/yarin.kossover/AppData/Local/Android/sdk/ndk-bundle/build//../toolchains/x86-4.8/prebuilt/windows-x86_64/bin/x86-gcc -MMD -MP -MF C:\dev\Android projects\fresco\imagepipeline\build\tmp\ndk_build_bitmaps/local/x86/objs/bitmaps/Bitmaps.o.d -O2 -g -DNDEBUG -fomit-frame-pointer -fstrict-aliasing -funswitch-loops -finline-limit=300 -I. -DANDROID -Wall -Wextra -Werror -std=c11 -fvisibility=hidden -Wa,--noexecstack -Wformat -Werror=format-security -isystem C:/Users/yarin.kossover/AppData/Local/Android/sdk/ndk-bundle/build//../platforms/android-9/arch-x86/usr/include -c ./Bitmaps.c -o C:\dev\Android projects\fresco\imagepipeline\build\tmp\ndk_build_bitmaps/local/x86/objs/bitmaps/Bitmaps.o, ...) failed.

make: *** [projects\fresco\imagepipeline\build\tmp\ndk_build_bitmaps/local/x86/objs/bitmaps/Bitmaps.o] Error 2
:animated-base-test:mockableAndroidJar UP-TO-DATE
:animated-base-test:processReleaseUnitTestJavaRes UP-TO-DATE
:animated-webp:androidJavadocJar
:animated-webp:androidSourcesJar
:animated-gif:preBuild UP-TO-DATE
:animated-gif:preDebugBuild UP-TO-DATE
:animated-gif:compileDebugNdk UP-TO-DATE
:animated-gif:compileLint
:animated-gif:copyDebugLint UP-TO-DATE
:animated-gif:checkDebugManifest
:animated-gif:preDebugAndroidTestBuild UP-TO-DATE
:animated-gif:preDebugUnitTestBuild UP-TO-DATE
:animated-gif:preReleaseBuild UP-TO-DATE
:animated-gif:preReleaseUnitTestBuild UP-TO-DATE
:animated-gif:generateDebugBuildConfig
:animated-webp:preBuild UP-TO-DATE
:animated-webp:preDebugBuild UP-TO-DATE
:animated-webp:compileDebugNdk UP-TO-DATE
:animated-webp:compileLint
:animated-webp:copyDebugLint UP-TO-DATE
:animated-webp:checkDebugManifest
:animated-webp:preDebugAndroidTestBuild UP-TO-DATE
:animated-webp:preDebugUnitTestBuild UP-TO-DATE
:animated-webp:preReleaseBuild UP-TO-DATE
:animated-webp:preReleaseUnitTestBuild UP-TO-DATE
:animated-webp:generateDebugBuildConfig
:animated-webp:generateDebugAssets UP-TO-DATE
:animated-webp:generateDebugResValues
make: Leaving directory `C:/dev/Android projects/fresco/imagepipeline/src/main/jni/bitmaps'
:animated-webp:generateDebugResValues UP-TO-DATE
:animated-webp:createNativeDepsDirectories UP-TO-DATE
:animated-webp:downloadLibwebp UP-TO-DATE
aarch64-linux-android-gcc: error: projects\fresco\imagepipeline\build\tmp\ndk_build_bitmaps/local/arm64-v8a/objs/bitmaps/Bitmaps.o.d: No such file or directory
aarch64-linux-android-gcc: error: projects\fresco\imagepipeline\build\tmp\ndk_build_bitmaps/local/arm64-v8a/objs/bitmaps/Bitmaps.o: No such file or directory
make: *** [projects\fresco\imagepipeline\build\tmp\ndk_build_bitmaps/local/arm64-v8a/objs/bitmaps/Bitmaps.o] Error 1
:animated-webp:unpackLibwebp
:imagepipeline:ndk_build_bitmaps FAILED
:animated-webp:unpackLibwebp UP-TO-DATE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':imagepipeline:ndk_build_bitmaps'.
> Process 'command 'C:\Users\yarin.kossover\AppData\Local\Android\sdk\ndk-bundle\ndk-build.cmd'' finished with non-zero exit value 2
`
```

any idea?

Thanks !

**Comment by yarinkos** [comment]
I just installed NDK from the sdk manager,
should i install one of the system images?
it wasn't specify in the contributors guide

**Comment by aagnes** [comment]
please follow the guide, it tells you all the essential steps to build fresco. And let me know which step you fail from there.

**Comment by wgykontage** [comment]
i have the same problem, i try every mothod, but no one can work, someone could tell me?  What went wrong:
Execution failed for task ':imagepipeline:ndk_build_bitmaps'.
> Process 'command 'D:\android-sdk\ndk-bundle\ndk-build.cmd'' finished with non-zero exit value 2
             
* Try:       
Run with --info or --debug option to get more log output.
             
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':imagepipeline:ndk_build_bitmaps'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)

**Comment by ivyspirit** [comment]
First of all, If you downloaded the latest ndk from Android studio or downloaded it from http://developer.android.com/ndk/downloads/index.html 
search "NDK_TOOLCHAIN_VERSION" in your project directory. Change the version from 4.8 to 4.9. 

If you downloaded the ndk from Android studio sdk manger, version 12. after you fix the above setting you will get tons of errors:
error: 'mutex' in namespace 'std' does not name a type
error: field 'm_noreThreadFuture' has incomplete type 'std::future<int>'
error: 'thread' in namespace 'std' does not name a type

The ndk r12 is broken. So download the ndk r11, and point your ndk path to the rc11 in your gradle.properties and local.properties files. Should work.

**Comment by pungrue26** [comment]
I had the same problem, and @ivyspirit changing "NDK_TOOLCHAIN_VERSION" to 4.9 didn't solve my problem.

I am going to create a new issue, because I use Mac and this thread is reported for Windows.

**Comment by plamenko** [comment]
`getNdkBuildFullPath` is broken again and gradle script can't get path for `ndk-build.cmd`. I added NDK path to environment variables and that worked. Btw, if you have white spaces anywhere in your path, you are doomed.

**Comment by erikandre** [comment]
Closing as it's been more than a year since the last update.
