### ISSUE TITLE
Fresco crashes when proguard is true

### ISSUE THREAD

**Issue by Androider92** [facebook/fresco#1115]
this error occurs only when proguard  "minifyEnabled true"

please note that i excluded Facebook from proguard  rules 

#Facebook
-keep class com.facebook.**
-keep interface com.facebook.**
-keep enum com.facebook.**

#Fresco
-keep class com.facebook.fresco.**
-keep interface com.facebook.fresco.**
-keep enum com.facebook.fresco.**

`AndroidRuntime: FATAL EXCEPTION: Thread-6712
                                                                         Process: com.whatshudoin.android, PID: 30386
                                                                         java.lang.NoSuchMethodError: no static or non-static method "Lcom/facebook/imagepipeline/nativecode/Bitmaps;.nativeCopyBitmap(Landroid/graphics/Bitmap;ILandroid/graphics/Bitmap;II)V"
                                                                             at java.lang.Runtime.nativeLoad(Native Method)
                                                                             at java.lang.Runtime.doLoad(Runtime.java:435)
                                                                             at java.lang.Runtime.loadLibrary(Runtime.java:363)
                                                                             at java.lang.System.loadLibrary(System.java:526)
                                                                             at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.a(SoLoaderShim.java:32)
                                                                             at com.facebook.common.soloader.SoLoaderShim.a(SoLoaderShim.java:56)
                                                                             at com.facebook.imagepipeline.nativecode.Bitmaps.<clinit>(Bitmaps.java:27)
                                                                             at com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.a(DalvikPurgeableDecoder.java:155)
                                                                             at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.a(KitKatPurgeableDecoder.java:32)
                                                                             at com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.a(DalvikPurgeableDecoder.java:61)
                                                                             at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.a(KitKatPurgeableDecoder.java:32)
                                                                             at com.facebook.imagepipeline.decoder.ImageDecoder.a(ImageDecoder.java:127)
                                                                             at com.facebook.imagepipeline.decoder.ImageDecoder.a(ImageDecoder.java:94)
                                                                             at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.c(DecodeProducer.java:189)
                                                                             at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.a(DecodeProducer.java:97)
                                                                             at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.a(DecodeProducer.java:129)
                                                                             at com.facebook.imagepipeline.producers.JobScheduler.e(JobScheduler.java:207)
                                                                             at com.facebook.imagepipeline.producers.JobScheduler.a(JobScheduler.java:27)
                                                                             at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                             at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                                             at java.lang.Thread.run(Thread.java:841)`

**Comment by kenilt** [comment]
I think you should change your proguard rule like this.
http://frescolib.org/docs/proguard.html

And bellow is this proguard rule:
`# Keep our interfaces so they can be used by other ProGuard rules.
# See http://sourceforge.net/p/proguard/bugs/466/
-keep,allowobfuscation @interface com.facebook.common.internal.DoNotStrip

# Do not strip any method/class that is annotated with @DoNotStrip
-keep @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers class * {
    @com.facebook.common.internal.DoNotStrip *;
}

# Keep native methods
-keepclassmembers class * {
    native <methods>;
}

-dontwarn okio.**
-dontwarn javax.annotation.**
-dontwarn com.android.volley.toolbox.**`

**Comment by Androider92** [comment]
@kenilt thanks a lot it works now.
