### ISSUE TITLE
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/nativecode/JpegTranscoder

### ISSUE THREAD

**Issue by ytwind** [facebook/fresco#1118]
android 4.2.2    [vivo Y 13]   [vivoY11i T]

java.lang.NoClassDefFoundError: com/facebook/imagepipeline/nativecode/JpegTranscoder
	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.doTransform(ResizeAndRotateProducer.java:154)
	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.access$000(ResizeAndRotateProducer.java:72)
	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer$1.run(ResizeAndRotateProducer.java:89)
	at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
	at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
	at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
	at java.lang.Thread.run(Thread.java:838)

//-----------------------------------------------------------------------------------------------------
android 4.2.2    [vivo Y 13]   [vivoY11i T]
java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1652): could not load library "libwebp.so" needed by "libimagepipeline.so"; caused by load_library(linker.cpp:759): library "libwebp.so" not found
	at java.lang.Runtime.loadLibrary(Runtime.java:372)
	at java.lang.System.loadLibrary(System.java:514)
	at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
	at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
	at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:43)
	at com.facebook.imagepipeline.nativecode.JpegTranscoder.<clinit>(JpegTranscoder.java:26)
	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.doTransform(ResizeAndRotateProducer.java:154)
	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.access$000(ResizeAndRotateProducer.java:72)
	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer$1.run(ResizeAndRotateProducer.java:89)
	at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
	at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
	at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
	at java.lang.Thread.run(Thread.java:838)

**Comment by ytwind** [comment]
phone no so?

**Comment by jyh149129** [comment]
跟我提的这个 #1050 一样 机器也是vivo的， X510t Android 4.2.2，

**Comment by aagnes** [comment]
dup of #410
