### ISSUE TITLE
i find a bug.

### ISSUE THREAD

**Issue by wangjing53406** [facebook/fresco#1132]
when i use this api set place holder image, it's crashed.

SimpleDraweeView.getHierarchy().setPlaceholderImage(Drawable drawable)

I use last displayed drawable to set a place holder image with next display.

java.lang.StackOverflowError
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:342)
                                                       at com.facebook.drawee.drawable.ForwardingDrawable.invalidateDrawable(ForwardingDrawable.java:185)
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:344)
                                                       at com.facebook.drawee.drawable.FadeDrawable.invalidateSelf(FadeDrawable.java:100)
                                                       at com.facebook.drawee.drawable.ArrayDrawable.invalidateDrawable(ArrayDrawable.java:331)
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:344)
                                                       at com.facebook.drawee.drawable.ForwardingDrawable.invalidateDrawable(ForwardingDrawable.java:185)
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:344)
                                                       at com.facebook.drawee.drawable.FadeDrawable.invalidateSelf(FadeDrawable.java:100)
                                                       at com.facebook.drawee.drawable.ArrayDrawable.invalidateDrawable(ArrayDrawable.java:331)
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:344)
                                                       at com.facebook.drawee.drawable.ForwardingDrawable.invalidateDrawable(ForwardingDrawable.java:185)
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:344)
                                                       at com.facebook.drawee.drawable.FadeDrawable.invalidateSelf(FadeDrawable.java:100)
                                                       at com.facebook.drawee.drawable.ArrayDrawable.invalidateDrawable(ArrayDrawable.java:331)
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:344)
                                                       at com.facebook.drawee.drawable.ForwardingDrawable.invalidateDrawable(ForwardingDrawable.java:185)
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:344)
                                                       at com.facebook.drawee.drawable.FadeDrawable.invalidateSelf(FadeDrawable.java:100)
                                                       at com.facebook.drawee.drawable.ArrayDrawable.invalidateDrawable(ArrayDrawable.java:331)
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:344)
                                                       at com.facebook.drawee.drawable.ForwardingDrawable.invalidateDrawable(ForwardingDrawable.java:185)
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:344)
                                                       at com.facebook.drawee.drawable.FadeDrawable.invalidateSelf(FadeDrawable.java:100)
                                                       at com.facebook.drawee.drawable.ArrayDrawable.invalidateDrawable(ArrayDrawable.java:331)
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:344)
                                                       at com.facebook.drawee.drawable.ForwardingDrawable.invalidateDrawable(ForwardingDrawable.java:185)
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:344)
                                                       at com.facebook.drawee.drawable.FadeDrawable.invalidateSelf(FadeDrawable.java:100)
                                                       at com.facebook.drawee.drawable.ArrayDrawable.invalidateDrawable(ArrayDrawable.java:331)
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:344)
                                                       at com.facebook.drawee.drawable.ForwardingDrawable.invalidateDrawable(ForwardingDrawable.java:185)
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:344)
                                                       at com.facebook.drawee.drawable.FadeDrawable.invalidateSelf(FadeDrawable.java:100)
                                                       at com.facebook.drawee.drawable.ArrayDrawable.invalidateDrawable(ArrayDrawable.java:331)
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:344)
                                                       at com.facebook.drawee.drawable.ForwardingDrawable.invalidateDrawable(ForwardingDrawable.java:185)
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:344)
                                                       at com.facebook.drawee.drawable.FadeDrawable.invalidateSelf(FadeDrawable.java:100)
                                                       at com.facebook.drawee.drawable.ArrayDrawable.invalidateDrawable(ArrayDrawable.java:331)
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:344)
                                                       at com.facebook.drawee.drawable.ForwardingDrawable.invalidateDrawable(ForwardingDrawable.java:185)
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:344)
                                                       at com.facebook.drawee.drawable.FadeDrawable.invalidateSelf(FadeDrawable.java:100)
                                                       at com.facebook.drawee.drawable.ArrayDrawable.invalidateDrawable(ArrayDrawable.java:331)
                                                       at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:344)
                                                       at com.facebook.drawee.drawable.ForwardingDrawable.invalidateDrawable(ForwardingDrawable.java:185)
                                                   	at android.gra

**Comment by kirwan** [comment]
Can you please share a snippet of your code?

You say you're using the last displayed drawable but I wonder if you're somehow setting a drawable inside the same hierarchy twice, creating an infinite loop.

**Comment by plamenko** [comment]
This will happen if there is a loop in the hierarchy tree. Setting the top-level-drawable as a placeholder in the same hierarchy would do that. If you are trying to show the previously set image as a placeholder, this is a wrong way to do it.

Instead, you should build a `DraweeController` with `setLowResIamgeRequest` pointing to the old image and `setImageRequest` pointing to the new one as explained [here](http://frescolib.org/docs/requesting-multiple-images.html).
