### ISSUE TITLE
An error occurred after upgrading to the v0.9.0

### ISSUE THREAD

**Issue by imliujun** [facebook/fresco#1143]
```
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/nativecode/JpegTranscoder
	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.doTransform(ResizeAndRotateProducer.java:154)
	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.access$000(ResizeAndRotateProducer.java:72)
	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer$1.run(ResizeAndRotateProducer.java:89)
	at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
	at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
	at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
	at java.lang.Thread.run(Thread.java:838)
```

## Error device (TOP5)
![image](https://cloud.githubusercontent.com/assets/9779970/14735051/3c0ef97a-08a1-11e6-83d6-518136906d17.png)

## System version (TOP5)
![image](https://cloud.githubusercontent.com/assets/9779970/14735134/c4ab53f0-08a1-11e6-9496-d1e09b119354.png)

```
java.lang.ExceptionInInitializerError
	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.doTransform(ResizeAndRotateProducer.java:154)
	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.access$000(ResizeAndRotateProducer.java:72)
	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer$1.run(ResizeAndRotateProducer.java:89)
	at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
	at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
	at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libwebp.so" needed by "libimagepipeline.so"; caused by load_library(linker.cpp:745): library "libwebp.so" not found
	at java.lang.Runtime.loadLibrary(Runtime.java:371)
	at java.lang.System.loadLibrary(System.java:535)
	at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
	at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
	at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:43)
	at com.facebook.imagepipeline.nativecode.JpegTranscoder.(JpegTranscoder.java:26)
	... 10 more
```
## Error device (TOP5)
![image](https://cloud.githubusercontent.com/assets/9779970/14735214/4c48214e-08a2-11e6-888c-a1338fa709d5.png)

## System version (TOP5)
![image](https://cloud.githubusercontent.com/assets/9779970/14735242/6ee3f3d6-08a2-11e6-9873-1fe980b0927b.png)

**Comment by imliujun** [comment]
In the version of v10.10.0 didn't happen again
