### ISSUE TITLE
java.lang.InternalError: Thread starting during runtime shutdown 

### ISSUE THREAD

**Issue by harinlin** [facebook/fresco#1144]
```
java.lang.InternalError: Thread starting during runtime shutdown
    at java.lang.Thread.nativeCreate(Thread.java)
    at java.lang.Thread.start(Thread.java:1063)
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
    at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:988)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
    at java.lang.Thread.run(Thread.java:818)
```

does someone has idea?

**Comment by Allsimon** [comment]
Same here
Crashlytics tells me that this happens mainly on Samsung (100% of my crashes but this might just be pure luck considering I only have in the 1000s daily users) 
Android versions where this happens is 5.0 and 5.0.1

**Comment by PiotrWpl** [comment]
The same for me. Only Samsung, Android 5 and 6

`Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
       at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:988)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
       at java.lang.Thread.run(Thread.java:818)`

<img width="1049" alt="zrzut ekranu 2016-07-04 o 16 42 58" src="https://cloud.githubusercontent.com/assets/1515300/16564202/7de62bae-4206-11e6-8c60-95a6e10740b1.png">
<img width="694" alt="zrzut ekranu 2016-07-04 o 16 43 06" src="https://cloud.githubusercontent.com/assets/1515300/16564203/7de84d6c-4206-11e6-8f32-19b36b987955.png">

**Comment by ziad-halabi9** [comment]
Any update regarding this issue?
In addition to Samsung devices, it is also happening on "HUAWEI CRR-UL00" devices in our case.

**Comment by KaleXia** [comment]
the same problem for me , happening on  HTC M8Et(6.0) and  Samsung GALAXY S5(5.0) devices.

**Comment by perseusyang** [comment]
the same problem for me , happening on MEIZU PRO5 （6.0.1）PRO 6 （6.0）.小米M2（6.0） devices.

**Comment by Hellozhongxin** [comment]
the same problem for me , happening on vivo Y51 A (5.0.2）vivo Y35 （5.0.2） devices.

**Comment by foghina** [comment]
There is not much that we can do here. As the exception suggests, this happens when your app shuts down while Fresco is initializing (e.g. because of a different crash, or because of user exit). There's not much we can do here, there is no way to detect this condition. Furthermore, because the app is already shutting down, there isn't much user impact here (they're not getting thrown out of the app because of this).

Since there's no action that we can take here, I'll close this now.
