### ISSUE TITLE
compile 'com.facebook.fresco:fresco:0.9.0+' but have com.android.build.api.transform.TransformException: 

### ISSUE THREAD

**Issue by itcheng** [facebook/fresco#1151]
my project always run is ok,but i do  compile 'com.facebook.fresco:fresco:0.9.0+',i project have these problem

com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_73\bin\java.exe'' finished with non-zero exit value 2

i google why,get answer is add 

```groovy
defaultConfig { 
    multiDexEnabled true 
}
```

but,i add  multiDexEnabled true after ，get have erro 

Error:Execution failed for task ':app-dx:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/nineoldandroids/animation/Animator$AnimatorListener.class

this is my build.gradle

```groovy
apply plugin: 'com.android.application'
apply plugin: 'maven'
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.baimes.dx"
        minSdkVersion 17
        targetSdkVersion 23
        versionCode 117
        versionName "DX_V1.1.7_20160328"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
    }
    dexOptions {
        incremental true
    }
}


dependencies {
    provided fileTree(include: ['*.jar'], dir: 'libs')
    //    testCompile 'junit:junit:4.12'
    compile project(':frontend-base')
    compile 'com.bigkoo:convenientbanner:2.0.5'
    compile 'com.ToxicBakery.viewpager.transforms:view-pager-transforms:1.2.32@aar'
    compile 'com.android.support:recyclerview-v7:23.+'
    compile 'jp.wasabeef:recyclerview-animators:2.2.1'
    compile 'com.facebook.fresco:fresco:0.9.0+'


}
```

**Comment by itcheng** [comment]
who can help me,thanks

**Comment by eldk** [comment]
Hello,

Which gradle plugin are you using ?

If you are using 2.0.0, try to revert to 1.3.0

Eric

**Comment by itcheng** [comment]
i use gradle classpath 'com.android.tools.build:gradle:1.5.0'

and my is 1.5.1  



chengchunhuiit@163.com
 
From: eldk
Date: 2016-04-24 20:05
To: facebook/fresco
CC: Android_Learner; Author
Subject: Re: [facebook/fresco] compile 'com.facebook.fresco:fresco:0.9.0+' but have com.android.build.api.transform.TransformException: (#1151)
Hello,
Which gradle plugin are you using ?
If you are using 2.0.0, try to revert to 1.3.0
Eric

**Comment by itcheng** [comment]
i use gradle1.3.0 replace my gradle 1.5.0  donot have erro,my project build is ok  ,but running have some erro:

my XML is   only a  SimpleDraweeView 
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:fresco="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
<com.facebook.drawee.view.SimpleDraweeView
    android:id="@+id/my_image_view"
    android:layout_width="20dp"
    android:layout_height="20dp"
    fresco:placeholderImage="@drawable/bm_filmshows_adapterbody"
    />
</RelativeLayout>
04-24 04:33:51.592 15418-15418/com.baimes.dx E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.baimes.dx, PID: 15418
                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.baimes.dx/com.baimes.fe.dx.activity.TestActivity}: android.view.InflateException: Binary XML file line #13: Error inflating class com.facebook.drawee.view.SimpleDraweeView
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5030)
                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                   at dalvik.system.NativeStart.main(Native Method)
                                                                Caused by: android.view.InflateException: Binary XML file line #13: Error inflating class com.facebook.drawee.view.SimpleDraweeView
                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                   at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:293)
                                                                   at android.app.Activity.setContentView(Activity.java:1929)
                                                                   at com.baimes.fe.dx.activity.TestActivity.onCreate(TestActivity.java:14)
                                                                   at android.app.Activity.performCreate(Activity.java:5231)
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5030) 
                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                   at dalvik.system.NativeStart.main(Native Method) 
                                                                Caused by: java.lang.reflect.InvocationTargetException
                                                                   at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                   at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:293) 
                                                                   at android.app.Activity.setContentView(Activity.java:1929) 
                                                                   at com.baimes.fe.dx.activity.TestActivity.onCreate(TestActivity.java:14) 
                                                                   at android.app.Activity.performCreate(Activity.java:5231) 
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5030) 
                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                   at dalvik.system.NativeStart.main(Native Method) 
                                                                Caused by: java.lang.NullPointerException: SimpleDraweeView was not initialized!
                                                                   at com.facebook.common.internal.Preconditions.checkNotNull(Preconditions.java:226)
                                                                   at com.facebook.drawee.view.SimpleDraweeView.init(SimpleDraweeView.java:79)
                                                                   at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:61)
                                                                   at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                   at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:293) 
                                                                   at android.app.Activity.setContentView(Activity.java:1929) 
                                                                   at com.baimes.fe.dx.activity.TestActivity.onCreate(TestActivity.java:14) 
                                                                   at android.app.Activity.performCreate(Activity.java:5231) 
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5030) 
                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                   at dalvik.system.NativeStart.main(Native Method) 


chengchunhuiit@163.com
 
From: chengchunhuiit@163.com
Date: 2016-04-24 20:24
To: facebook/fresco
Subject: Re: Re: [facebook/fresco] compile 'com.facebook.fresco:fresco:0.9.0+' but have com.android.build.api.transform.TransformException: (#1151)
i use gradle classpath 'com.android.tools.build:gradle:1.5.0'

and my is 1.5.1  



chengchunhuiit@163.com
 
From: eldk
Date: 2016-04-24 20:05
To: facebook/fresco
CC: Android_Learner; Author
Subject: Re: [facebook/fresco] compile 'com.facebook.fresco:fresco:0.9.0+' but have com.android.build.api.transform.TransformException: (#1151)
Hello,
Which gradle plugin are you using ?
If you are using 2.0.0, try to revert to 1.3.0
Eric

**Comment by eldk** [comment]
Have a look here : http://stackoverflow.com/questions/36724100/error-inflating-class-com-facebook-drawee-view-simpledraweeview

and here :  http://frescolib.org/docs/configure-image-pipeline.html#main_wrap : 	
`Fresco.initialize(context);`

**Comment by itcheng** [comment]
why i use gradle 1.3.0 donot have  erro,use 1.5.0 have erro

.but my project need gradle1.5.0,i want not use gradle 1.3.0  ,i do sth?



chengchunhuiit@163.com
 
From: eldk
Date: 2016-04-24 20:59
To: facebook/fresco
CC: Android_Learner; Author
Subject: Re: [facebook/fresco] compile 'com.facebook.fresco:fresco:0.9.0+' but have com.android.build.api.transform.TransformException: (#1151)
Have a look here : http://stackoverflow.com/questions/36724100/error-inflating-class-com-facebook-drawee-view-simpledraweeview
and here : http://frescolib.org/docs/configure-image-pipeline.html#main_wrap :

Fresco.initialize(context);

**Comment by tyronen** [comment]
@eidk is correct, you need to call Fresco.initialize.
