### ISSUE TITLE
Uncaught translation error: com.android.dx.cf.code.SimException

### ISSUE THREAD

**Issue by jubincn** [facebook/fresco#1188]
I got SimException using proguard after upgrading fresco from 0.9.0 to 0.10.0.  Since the exception disappears when I turn proguard off with 0.10.0, I think this exception is caused by proguard, The exception appeared after transformClassesWithDexForStageRelease. There is no progurad configuration in [docs for fresco set up](http://frescolib.org/docs/index.html). Is this a bug or some proguard rules missed.?
`app:transformClassesWithMultidexlistForStageRelease UP-TO-DATE
:app:transformClassesWithDexForStageRelease
Uncaught translation error: com.android.dx.cf.code.SimException
1 error; aborting
:app:transformClassesWithDexForStageRelease FAILED`

The stacktrace from gradle is：
`rg.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexForStageRelease'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
    at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:54)
    at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:57)
    at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:47)
    at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:244)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:231)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 14 more
Caused by: com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
    at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:421)
    at com.android.build.gradle.internal.pipeline.TransformTask$3.call(TransformTask.java:178)
    at com.android.build.gradle.internal.pipeline.TransformTask$3.call(TransformTask.java:174)
    at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:55)
    ... 23 more
Caused by: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
    at com.android.builder.core.AndroidBuilder.dexInProcess(AndroidBuilder.java:1518)
    at com.android.builder.core.AndroidBuilder.runDexer(AndroidBuilder.java:1493)
    at com.android.builder.core.AndroidBuilder.convertByteCode(AndroidBuilder.java:1482)
    at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:251)
    ... 26 more
Caused by: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
    at com.android.builder.core.AndroidBuilder.dexInProcess(AndroidBuilder.java:1507)
    ... 29 more
Caused by: com.android.ide.common.process.ProcessException: Return code 1 for dex process
    at com.android.builder.internal.compiler.DexWrapper$DexProcessResult.assertNormalExitValue(DexWrapper.java:105)
    at com.android.builder.core.AndroidBuilder$2.call(AndroidBuilder.java:1512)
    at com.android.builder.core.AndroidBuilder$2.call(AndroidBuilder.java:1507)`

**Comment by oprisnik** [comment]
Hi! Did you set up ProGuard according to http://frescolib.org/docs/proguard.html ?

**Comment by jubincn** [comment]
@oprisnik I put those proguard rules into my proguard-rules.pro and it still not work for 0.10.0.

**Comment by erikandre** [comment]
Closing since there has been no further updates or reports of this since May 2016
