### ISSUE TITLE
WebP transcoder not found in 0.10.0

### ISSUE THREAD

**Issue by ChansEbm** [facebook/fresco#1189]
Here is the issue

```
A/MobUncaughtExceptionHandler: no static or non-static method "Lcom/facebook/imagepipeline/nativecode/WebpTranscoder;.nativeTranscodeWebpToJpeg(Ljava/io/InputStream;Ljava/io/OutputStream;I)V"
                                                                          java.lang.NoSuchMethodError: no static or non-static method "Lcom/facebook/imagepipeline/nativecode/WebpTranscoder;.nativeTranscodeWebpToJpeg(Ljava/io/InputStream;Ljava/io/OutputStream;I)V"
                                                                              at java.lang.Runtime.nativeLoad(Native Method)
                                                                              at java.lang.Runtime.doLoad(Runtime.java:421)
                                                                              at java.lang.Runtime.loadLibrary(Runtime.java:362)
                                                                              at java.lang.System.loadLibrary(System.java:526)
                                                                              at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
                                                                              at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
                                                                              at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:43)
                                                                              at com.facebook.imagepipeline.nativecode.JpegTranscoder.<clinit>(JpegTranscoder.java:26)
                                                                              at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.doTransform(ResizeAndRotateProducer.java:154)
                                                                              at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.access$000(ResizeAndRotateProducer.java:72)
                                                                              at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer$1.run(ResizeAndRotateProducer.java:89)
                                                                              at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                                                                              at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                                                                              at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                              at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                                              at java.lang.Thread.run(Thread.java:841)
```

Could somebody help me ?

**Comment by oprisnik** [comment]
Did you add the support version for WebP to your project according to [Adding Fresco to your Project](http://frescolib.org/docs/index.html)?
We made the core library smaller by making things like WebP support optional.

**Comment by ChansEbm** [comment]
I just added the support version for WebP in my project , but the issue still thrown @oprisnik

**Comment by oprisnik** [comment]
If you're using ProGuard, also make sure that you set it up correctly, see http://frescolib.org/docs/proguard.html

**Comment by oprisnik** [comment]
We changed some ProGuard configurations. Please let us know if you still have this issue.
