### ISSUE TITLE
Throwing OutOfMemoryError "Failed to allocate a 9216012 byte allocation with 8745148 free bytes and 8MB until OOM

### ISSUE THREAD

**Issue by winnerliu** [facebook/fresco#1196]
AndroidRuntime: FATAL EXCEPTION: Thread-2905
                                                                 Process: com.winner.demo, PID: 23260
                                                                 java.lang.OutOfMemoryError: Failed to allocate a 9216012 byte allocation with 8745148 free bytes and 8MB until OOM
                                                                     at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                     at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
                                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
                                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
                                                                     at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
                                                                     at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
                                                                     at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
                                                                     at com.facebook.imagepipeline.platform.ArtDecoder.decodeStaticImageFromStream(ArtDecoder.java:137)
                                                                     at com.facebook.imagepipeline.platform.ArtDecoder.decodeJPEGFromEncodedImage(ArtDecoder.java:120)
                                                                     at com.facebook.imagepipeline.decoder.ImageDecoder.decodeJpeg(ImageDecoder.java:151)
                                                                     at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:85)
                                                                     at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:189)
                                                                     at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:97)
                                                                     at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:129)
                                                                     at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                                                                     at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                                                                     at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by IanChilds** [comment]
There are numerous examples of similar issues. See `OOMs and failing to allocate a bitmap` on this page: http://frescolib.org/docs/troubleshooting.html
