### ISSUE TITLE
64-bit support

### ISSUE THREAD

**Issue by orospakr** [facebook/fresco#120]
One of our QA testers somehow has a Galaxy S6 early, but the native components (libmemchunk and its depenencies) in Fresco lack 64-bit ARM builds.  And so, the following crash happens.

I can't find much documentation from Google about expectations from developers about handling 64-bit devices (I know that 64-bit Android on 64-bit ARM is capable of running 32-bit only apps), but for some reason it seems like in my company's app we've inadvertently opted into our app being run in 64-bit mode (and presumably compiled as such by AOT at install time).  However, one would expect that 32-bit only native apps surely must be supported, so Angry Birds and such will keep working on these new phones.  Most peculiar.

```
04-09 11:07:49.786: E/AndroidRuntime(5325): FATAL EXCEPTION: pool-4-thread-1
04-09 11:07:49.786: E/AndroidRuntime(5325): Process: com.joistapp.android.joist.alpha, PID: 5325
04-09 11:07:49.786: E/AndroidRuntime(5325): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.joistapp.android.joist.alpha-1/base.apk"],nativeLibraryDirectories=[/data/app/com.joistapp.android.joist.alpha-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libgnustl_shared.so"
04-09 11:07:49.786: E/AndroidRuntime(5325): at java.lang.Runtime.loadLibrary(Runtime.java:366)
04-09 11:07:49.786: E/AndroidRuntime(5325): at java.lang.System.loadLibrary(System.java:989)
04-09 11:07:49.786: E/AndroidRuntime(5325): at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:34)
04-09 11:07:49.786: E/AndroidRuntime(5325): at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
04-09 11:07:49.786: E/AndroidRuntime(5325): at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:36)
04-09 11:07:49.786: E/AndroidRuntime(5325): at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
04-09 11:07:49.786: E/AndroidRuntime(5325): at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
04-09 11:07:49.786: E/AndroidRuntime(5325): at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:264)
04-09 11:07:49.786: E/AndroidRuntime(5325): at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
04-09 11:07:49.786: E/AndroidRuntime(5325): at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:36)
04-09 11:07:49.786: E/AndroidRuntime(5325): at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:131)
04-09 11:07:49.786: E/AndroidRuntime(5325): at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:26)
04-09 11:07:49.786: E/AndroidRuntime(5325): at com.facebook.imagepipeline.producers.NetworkFetchProducer.processResult(NetworkFetchProducer.java:119)
04-09 11:07:49.786: E/AndroidRuntime(5325): at com.facebook.imagepipeline.producers.HttpURLConnectionNetworkFetchProducer$1.run(HttpURLConnectionNetworkFetchProducer.java:62)
04-09 11:07:49.786: E/AndroidRuntime(5325): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-09 11:07:49.786: E/AndroidRuntime(5325): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-09 11:07:49.786: E/AndroidRuntime(5325): at java.lang.Thread.run(Thread.java:818)
```

**Comment by orospakr** [comment]
Modifying ImagePipeline's Application.mk to enable 64-bit ARM and x86 support produces:

```
[~/code/joist/fresco]$ ./gradlew build                                                                                                                                                                                                                      *[master][2.1.5]
Download https://jcenter.bintray.com/org/easytesting/fest-assert-core/2.0M10/fest-assert-core-2.0M10.pom
Download https://jcenter.bintray.com/org/mockito/mockito-core/1.3/mockito-core-1.3.pom
Download https://jcenter.bintray.com/org/powermock/powermock-mockito-release-full/1.5.5/powermock-mockito-release-full-1.5.5.pom
Download https://jcenter.bintray.com/org/powermock/powermock/1.5.5/powermock-1.5.5.pom
Download https://jcenter.bintray.com/org/powermock/powermock-module-junit4-rule/1.6.1/powermock-module-junit4-rule-1.6.1.pom
Download https://jcenter.bintray.com/org/powermock/powermock-modules/1.6.1/powermock-modules-1.6.1.pom
Download https://jcenter.bintray.com/org/powermock/powermock/1.6.1/powermock-1.6.1.pom
Download https://jcenter.bintray.com/org/objenesis/objenesis/1.0/objenesis-1.0.pom
Download https://jcenter.bintray.com/cglib/cglib-nodep/2.1_3/cglib-nodep-2.1_3.pom
Download https://jcenter.bintray.com/org/powermock/powermock-core/1.5.5/powermock-core-1.5.5.pom
Download https://jcenter.bintray.com/org/powermock/powermock-api-mockito/1.5.5/powermock-api-mockito-1.5.5.pom
Download https://jcenter.bintray.com/org/powermock/powermock-api/1.5.5/powermock-api-1.5.5.pom
Download https://jcenter.bintray.com/org/powermock/powermock-module-junit4-common/1.5.5/powermock-module-junit4-common-1.5.5.pom
Download https://jcenter.bintray.com/org/powermock/powermock-modules/1.5.5/powermock-modules-1.5.5.pom
Download https://jcenter.bintray.com/org/powermock/powermock-module-junit4/1.5.5/powermock-module-junit4-1.5.5.pom
Download https://jcenter.bintray.com/org/powermock/powermock-module-junit4-legacy/1.5.5/powermock-module-junit4-legacy-1.5.5.pom
Download https://jcenter.bintray.com/org/powermock/powermock-module-junit3/1.5.5/powermock-module-junit3-1.5.5.pom
Download https://jcenter.bintray.com/org/powermock/powermock-reflect/1.5.5/powermock-reflect-1.5.5.pom
Download https://jcenter.bintray.com/org/powermock/powermock-api-support/1.5.5/powermock-api-support-1.5.5.pom
Download https://jcenter.bintray.com/org/powermock/powermock-module-testng/1.5.5/powermock-module-testng-1.5.5.pom
Download https://jcenter.bintray.com/org/powermock/powermock-module-testng-common/1.5.5/powermock-module-testng-common-1.5.5.pom
Download https://jcenter.bintray.com/org/powermock/powermock-classloading-base/1.5.5/powermock-classloading-base-1.5.5.pom
Download https://jcenter.bintray.com/org/mockito/mockito-all/1.9.5/mockito-all-1.9.5.pom
Download https://jcenter.bintray.com/org/testng/testng/6.8.8/testng-6.8.8.pom
Download https://jcenter.bintray.com/org/sonatype/oss/oss-parent/3/oss-parent-3.pom
Download https://jcenter.bintray.com/com/beust/jcommander/1.27/jcommander-1.27.pom
Download https://jcenter.bintray.com/org/powermock/powermock-classloading-base/1.6.1/powermock-classloading-base-1.6.1.pom
Download https://jcenter.bintray.com/org/powermock/powermock-core/1.6.1/powermock-core-1.6.1.pom
Download https://jcenter.bintray.com/org/javassist/javassist/3.18.2-GA/javassist-3.18.2-GA.pom
Download https://jcenter.bintray.com/org/powermock/powermock-api-support/1.6.1/powermock-api-support-1.6.1.pom
Download https://jcenter.bintray.com/org/powermock/powermock-api/1.6.1/powermock-api-1.6.1.pom
Download https://jcenter.bintray.com/org/powermock/powermock-reflect/1.6.1/powermock-reflect-1.6.1.pom
Download https://jcenter.bintray.com/junit/junit/4.12/junit-4.12.jar
Download https://jcenter.bintray.com/org/easytesting/fest-assert-core/2.0M10/fest-assert-core-2.0M10.jar
Download https://jcenter.bintray.com/cglib/cglib-nodep/2.1_3/cglib-nodep-2.1_3.jar
Download https://jcenter.bintray.com/org/mockito/mockito-core/1.3/mockito-core-1.3.jar
Download https://jcenter.bintray.com/org/powermock/powermock-reflect/1.6.1/powermock-reflect-1.6.1.jar
Download https://jcenter.bintray.com/org/powermock/powermock-reflect/1.6.1/powermock-reflect-1.6.1-sources.jar
Download https://jcenter.bintray.com/org/javassist/javassist/3.18.2-GA/javassist-3.18.2-GA.jar
Download https://jcenter.bintray.com/org/powermock/powermock-core/1.6.1/powermock-core-1.6.1.jar
Download https://jcenter.bintray.com/org/powermock/powermock-core/1.6.1/powermock-core-1.6.1-sources.jar
Download https://jcenter.bintray.com/org/mockito/mockito-all/1.9.5/mockito-all-1.9.5.jar
Download https://jcenter.bintray.com/org/powermock/powermock-api-support/1.6.1/powermock-api-support-1.6.1.jar
Download https://jcenter.bintray.com/org/powermock/powermock-api-support/1.6.1/powermock-api-support-1.6.1-sources.jar
Download https://jcenter.bintray.com/org/powermock/powermock-api-mockito/1.5.5/powermock-api-mockito-1.5.5.jar
Download https://jcenter.bintray.com/org/powermock/powermock-api-mockito/1.5.5/powermock-api-mockito-1.5.5-sources.jar
Download https://jcenter.bintray.com/org/powermock/powermock-module-junit4-common/1.5.5/powermock-module-junit4-common-1.5.5.jar
Download https://jcenter.bintray.com/org/powermock/powermock-module-junit4-common/1.5.5/powermock-module-junit4-common-1.5.5-sources.jar
Download https://jcenter.bintray.com/org/powermock/powermock-module-junit4/1.5.5/powermock-module-junit4-1.5.5.jar
Download https://jcenter.bintray.com/org/powermock/powermock-module-junit4/1.5.5/powermock-module-junit4-1.5.5-sources.jar
Download https://jcenter.bintray.com/org/powermock/powermock-module-junit4-legacy/1.5.5/powermock-module-junit4-legacy-1.5.5.jar
Download https://jcenter.bintray.com/org/powermock/powermock-module-junit4-legacy/1.5.5/powermock-module-junit4-legacy-1.5.5-sources.jar
Download https://jcenter.bintray.com/org/powermock/powermock-module-junit3/1.5.5/powermock-module-junit3-1.5.5.jar
Download https://jcenter.bintray.com/org/powermock/powermock-module-junit3/1.5.5/powermock-module-junit3-1.5.5-sources.jar
Download https://jcenter.bintray.com/com/beust/jcommander/1.27/jcommander-1.27.jar
Download https://jcenter.bintray.com/org/testng/testng/6.8.8/testng-6.8.8.jar
Download https://jcenter.bintray.com/org/powermock/powermock-module-testng-common/1.5.5/powermock-module-testng-common-1.5.5.jar
Download https://jcenter.bintray.com/org/powermock/powermock-module-testng/1.5.5/powermock-module-testng-1.5.5.jar
Download https://jcenter.bintray.com/org/powermock/powermock-module-testng/1.5.5/powermock-module-testng-1.5.5-sources.jar
Download https://jcenter.bintray.com/org/powermock/powermock-classloading-base/1.6.1/powermock-classloading-base-1.6.1.jar
Download https://jcenter.bintray.com/org/powermock/powermock-classloading-base/1.6.1/powermock-classloading-base-1.6.1-sources.jar
Download https://jcenter.bintray.com/org/powermock/powermock-module-junit4-rule/1.6.1/powermock-module-junit4-rule-1.6.1.jar
Download https://jcenter.bintray.com/com/mcxiaoke/volley/library/1.0.6/library-1.0.6.pom
Download https://jcenter.bintray.com/com/mcxiaoke/volley/library/1.0.6/library-1.0.6.jar
Download https://jcenter.bintray.com/com/github/bumptech/glide/glide/3.5.1/glide-3.5.1.pom
Download https://jcenter.bintray.com/com/nostra13/universalimageloader/universal-image-loader/1.9.3/universal-image-loader-1.9.3.pom
Download https://jcenter.bintray.com/com/nostra13/universalimageloader/parent/1.9.3/parent-1.9.3.pom
Download https://jcenter.bintray.com/com/github/bumptech/glide/glide/3.5.1/glide-3.5.1.jar
Download https://jcenter.bintray.com/com/nostra13/universalimageloader/universal-image-loader/1.9.3/universal-image-loader-1.9.3.jar
:drawee:androidJavadocJar
:drawee:androidSourcesJar
:drawee:compileLint
:drawee:copyDebugLint UP-TO-DATE
:drawee:preBuild
:drawee:preDebugBuild
:drawee:checkDebugManifest
:drawee:preDebugTestBuild
:drawee:preReleaseBuild
:fbcore:compileLint
:fbcore:copyReleaseLint UP-TO-DATE
:fbcore:mergeReleaseProguardFiles
:fbcore:preBuild
:fbcore:preReleaseBuild
:fbcore:checkReleaseManifest
:fbcore:prepareReleaseDependencies
:fbcore:compileReleaseAidl
:fbcore:compileReleaseRenderscript
:fbcore:generateReleaseBuildConfig
:fbcore:generateReleaseAssets UP-TO-DATE
:fbcore:mergeReleaseAssets
:fbcore:generateReleaseResValues
:fbcore:generateReleaseResources
:fbcore:packageReleaseResources
:fbcore:processReleaseManifest
:fbcore:processReleaseResources
:fbcore:generateReleaseSources
:fbcore:compileReleaseJava
Note: /Users/orospakr/code/joist/fresco/fbcore/src/main/java/com/facebook/common/statfs/StatFsHelper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:fbcore:processReleaseJavaRes UP-TO-DATE
:fbcore:packageReleaseJar
:fbcore:compileReleaseNdk
:fbcore:packageReleaseJniLibs UP-TO-DATE
:fbcore:packageReleaseLocalJar UP-TO-DATE
:fbcore:packageReleaseRenderscript UP-TO-DATE
:fbcore:bundleRelease
:drawee:prepareComAndroidSupportSupportV42103Library
:drawee:prepareComFacebookFrescoFbcore020Library
:drawee:prepareDebugDependencies
:drawee:compileDebugAidl
:drawee:compileDebugRenderscript
:drawee:generateDebugBuildConfig
:drawee:generateDebugAssets UP-TO-DATE
:drawee:mergeDebugAssets
:drawee:generateDebugResValues
:drawee:generateDebugResources
:drawee:mergeDebugResources
:drawee:processDebugManifest
:drawee:processDebugResources
:drawee:generateDebugSources
:drawee:compileDebugJava
Note: /Users/orospakr/code/joist/fresco/drawee/src/main/java/com/facebook/drawee/view/SimpleDraweeView.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:drawee:extractDebugAnnotations
:drawee:mergeDebugProguardFiles
:drawee:processDebugJavaRes UP-TO-DATE
:drawee:packageDebugJar
:drawee:compileDebugNdk
:drawee:packageDebugJniLibs UP-TO-DATE
:drawee:packageDebugLocalJar UP-TO-DATE
:drawee:packageDebugRenderscript UP-TO-DATE
:drawee:packageDebugResources
:drawee:bundleDebug
:drawee:assembleDebug
:drawee:copyReleaseLint UP-TO-DATE
:drawee:checkReleaseManifest
:drawee:prepareReleaseDependencies
:drawee:compileReleaseAidl
:drawee:compileReleaseRenderscript
:drawee:generateReleaseBuildConfig
:drawee:generateReleaseAssets UP-TO-DATE
:drawee:mergeReleaseAssets
:drawee:generateReleaseResValues
:drawee:generateReleaseResources
:drawee:mergeReleaseResources
:drawee:processReleaseManifest
:drawee:processReleaseResources
:drawee:generateReleaseSources
:drawee:compileReleaseJava
Note: /Users/orospakr/code/joist/fresco/drawee/src/main/java/com/facebook/drawee/view/SimpleDraweeView.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:drawee:extractReleaseAnnotations
:drawee:mergeReleaseProguardFiles
:drawee:processReleaseJavaRes UP-TO-DATE
:drawee:packageReleaseJar
:drawee:compileReleaseNdk
:drawee:packageReleaseJniLibs UP-TO-DATE
:drawee:packageReleaseLocalJar UP-TO-DATE
:drawee:packageReleaseRenderscript UP-TO-DATE
:drawee:packageReleaseResources
:drawee:bundleRelease
:drawee:assembleRelease
:drawee:sourcesJar
:drawee:signArchives SKIPPED
:drawee:assemble
:drawee:lint
Ran lint on variant release: 1 issues found
Ran lint on variant debug: 1 issues found
Wrote HTML report to file:/Users/orospakr/code/joist/fresco/drawee/build/outputs/lint-results.html
Wrote XML report to /Users/orospakr/code/joist/fresco/drawee/build/outputs/lint-results.xml
:drawee:generateTestSources
:drawee:prepareDebugTestDependencies
:drawee:compileTestDebugJava UP-TO-DATE
:drawee:processTestDebugResources UP-TO-DATE
:drawee:testDebugClasses UP-TO-DATE
:drawee:testDebug
:drawee:test UP-TO-DATE
:drawee:check
:drawee:build
:fbcore:androidJavadocJar
:fbcore:androidSourcesJar
:fbcore:copyDebugLint UP-TO-DATE
:fbcore:mergeDebugProguardFiles
:fbcore:preDebugBuild
:fbcore:checkDebugManifest
:fbcore:prepareDebugDependencies
:fbcore:compileDebugAidl
:fbcore:compileDebugRenderscript
:fbcore:generateDebugBuildConfig
:fbcore:generateDebugAssets UP-TO-DATE
:fbcore:mergeDebugAssets
:fbcore:generateDebugResValues
:fbcore:generateDebugResources
:fbcore:packageDebugResources
:fbcore:processDebugManifest
:fbcore:processDebugResources
:fbcore:generateDebugSources
:fbcore:compileDebugJava
Note: /Users/orospakr/code/joist/fresco/fbcore/src/main/java/com/facebook/common/statfs/StatFsHelper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:fbcore:processDebugJavaRes UP-TO-DATE
:fbcore:packageDebugJar
:fbcore:compileDebugNdk
:fbcore:packageDebugJniLibs UP-TO-DATE
:fbcore:packageDebugLocalJar UP-TO-DATE
:fbcore:packageDebugRenderscript UP-TO-DATE
:fbcore:bundleDebug
:fbcore:assembleDebug
:fbcore:assembleRelease
:fbcore:sourcesJar
:fbcore:signArchives SKIPPED
:fbcore:assemble
:fbcore:lint
Ran lint on variant release: 1 issues found
Ran lint on variant debug: 1 issues found
Wrote HTML report to file:/Users/orospakr/code/joist/fresco/fbcore/build/outputs/lint-results.html
Wrote XML report to /Users/orospakr/code/joist/fresco/fbcore/build/outputs/lint-results.xml
:fbcore:generateTestSources
:fbcore:preDebugTestBuild
:fbcore:prepareDebugTestDependencies
:fbcore:compileTestDebugJava UP-TO-DATE
:fbcore:processTestDebugResources UP-TO-DATE
:fbcore:testDebugClasses UP-TO-DATE
:fbcore:testDebug
:fbcore:test UP-TO-DATE
:fbcore:check
:fbcore:build
:imagepipeline:androidJavadocJar
:imagepipeline:androidSourcesJar
:imagepipeline:compileLint
:imagepipeline:copyDebugLint UP-TO-DATE
:imagepipeline:preBuild
:imagepipeline:preDebugBuild
:imagepipeline:checkDebugManifest
:imagepipeline:preDebugTestBuild
:imagepipeline:preReleaseBuild
:imagepipeline:prepareComAndroidSupportSupportV42103Library
:imagepipeline:prepareComFacebookFrescoFbcore020Library
:imagepipeline:prepareDebugDependencies
:imagepipeline:compileDebugAidl
:imagepipeline:compileDebugRenderscript
:imagepipeline:generateDebugBuildConfig
:imagepipeline:generateDebugAssets UP-TO-DATE
:imagepipeline:mergeDebugAssets
:imagepipeline:generateDebugResValues
:imagepipeline:generateDebugResources
:imagepipeline:mergeDebugResources
:imagepipeline:processDebugManifest
:imagepipeline:processDebugResources
:imagepipeline:generateDebugSources
:imagepipeline:directories UP-TO-DATE
:imagepipeline:downloadFiles
Download http://downloads.sourceforge.net/project/giflib/giflib-5.1.1.tar.gz
Download http://downloads.sourceforge.net/project/libjpeg-turbo/1.3.1/libjpeg-turbo-1.3.1.tar.gz
Download http://downloads.sourceforge.net/project/libpng/libpng16/older-releases/1.6.10/libpng-1.6.10.tar.gz
:imagepipeline:unpackGiflib
:imagepipeline:copyGiflib
:imagepipeline:ndk_build_gifimage
make: Entering directory `/Users/orospakr/code/joist/fresco/imagepipeline/src/main/jni/gifimage'
[armeabi-v7a] Compile++ thumb: gifimage <= jni.cpp
[armeabi-v7a] Compile++ thumb: gifimage <= gif.cpp
[armeabi-v7a] Compile++ thumb: gifimage <= jni_helpers.cpp
[armeabi-v7a] Compile thumb  : gif <= dgif_lib.c
[armeabi-v7a] Compile thumb  : gif <= gifalloc.c
[armeabi-v7a] Prebuilt       : libgnustl_shared.so <= <NDK>/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/thumb/
[armeabi] Compile++ thumb: gifimage <= jni.cpp
[armeabi] Compile++ thumb: gifimage <= gif.cpp
[armeabi] Compile++ thumb: gifimage <= jni_helpers.cpp
[armeabi] Compile thumb  : gif <= dgif_lib.c
[armeabi] Compile thumb  : gif <= gifalloc.c
[armeabi] Prebuilt       : libgnustl_shared.so <= <NDK>/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi/thumb/
[arm64-v8a] Compile++      : gifimage <= jni.cpp
[arm64-v8a] Compile++      : gifimage <= gif.cpp
[arm64-v8a] Compile++      : gifimage <= jni_helpers.cpp
[arm64-v8a] Compile        : gif <= dgif_lib.c
[arm64-v8a] Compile        : gif <= gifalloc.c
[arm64-v8a] Prebuilt       : libgnustl_shared.so <= <NDK>/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/
[x86] Compile++      : gifimage <= jni.cpp
[x86] Compile++      : gifimage <= gif.cpp
[x86] Compile++      : gifimage <= jni_helpers.cpp
[x86] Compile        : gif <= dgif_lib.c
[x86] Compile        : gif <= gifalloc.c
[x86] Prebuilt       : libgnustl_shared.so <= <NDK>/sources/cxx-stl/gnu-libstdc++/4.8/libs/x86/
[x86_64] Compile++      : gifimage <= jni.cpp
[x86_64] Compile++      : gifimage <= gif.cpp
[x86_64] Compile++      : gifimage <= jni_helpers.cpp
./gif.cpp: In function '_jobject* GifImage_nativeCreateFromByteVector(JNIEnv*, std::vector<unsigned char>&)':
./gif.cpp:545:34: error: cast from 'std::unique_ptr<GifImageNativeContext>::pointer {aka GifImageNativeContext*}' to 'jint {aka int}' loses precision [-fpermissive]
       (jint) spNativeContext.get());
                                  ^
./gif.cpp: In function 'std::unique_ptr<GifImageNativeContext, GifImageNativeContextReleaser> getGifImageNativeContext(JNIEnv*, jobject)':
./gif.cpp:594:83: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
       (GifImageNativeContext*) pEnv->GetIntField(thiz, sGifImageFieldNativeContext);
                                                                                   ^
./gif.cpp: In function '_jobject* GifImage_nativeGetFrame(JNIEnv*, jobject, jint)':
./gif.cpp:784:39: error: cast from 'std::unique_ptr<GifFrameNativeContext>::pointer {aka GifFrameNativeContext*}' to 'jint {aka int}' loses precision [-fpermissive]
       (jint) spFrameNativeContext.get());
                                       ^
./gif.cpp: In function 'std::unique_ptr<GifFrameNativeContext, GifFrameNativeContextReleaser> getGifFrameNativeContext(JNIEnv*, jobject)':
./gif.cpp:833:83: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
       (GifFrameNativeContext*) pEnv->GetIntField(thiz, sGifFrameFieldNativeContext);
                                                                                   ^
./gif.cpp: In function 'void GifImage_nativeDispose(JNIEnv*, jobject)':
./gif.cpp:868:83: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
       (GifImageNativeContext*) pEnv->GetIntField(thiz, sGifImageFieldNativeContext);
[x86_64] Compile        : gif <= dgif_lib.c
                                                                                   ^
./gif.cpp: In function 'void GifFrame_nativeDispose(JNIEnv*, jobject)':
./gif.cpp:1160:83: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
       (GifFrameNativeContext*) pEnv->GetIntField(thiz, sGifFrameFieldNativeContext);
                                                                                   ^
[x86_64] Compile        : gif <= gifalloc.c
[x86_64] Prebuilt       : libgnustl_shared.so <= <NDK>/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86_64/
[armeabi-v7a] SharedLibrary  : libgif.so
make: *** [/Users/orospakr/code/joist/fresco/imagepipeline/build/tmp/ndk_build_gifimage/local/arm64-v8a/objs/gifimage/gif.o] Error 1
make: *** Waiting for unfinished jobs....
./gif.cpp: In function '_jobject* GifImage_nativeCreateFromByteVector(JNIEnv*, std::vector<unsigned char>&)':
./gif.cpp:545:34: error: cast from 'std::unique_ptr<GifImageNativeContext>::pointer {aka GifImageNativeContext*}' to 'jint {aka int}' loses precision [-fpermissive]
       (jint) spNativeContext.get());
                                  ^
./gif.cpp: In function 'std::unique_ptr<GifImageNativeContext, GifImageNativeContextReleaser> getGifImageNativeContext(JNIEnv*, jobject)':
./gif.cpp:594:83: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
       (GifImageNativeContext*) pEnv->GetIntField(thiz, sGifImageFieldNativeContext);
                                                                                   ^
./gif.cpp: In function '_jobject* GifImage_nativeGetFrame(JNIEnv*, jobject, jint)':
./gif.cpp:784:39: error: cast from 'std::unique_ptr<GifFrameNativeContext>::pointer {aka GifFrameNativeContext*}' to 'jint {aka int}' loses precision [-fpermissive]
       (jint) spFrameNativeContext.get());
                                       ^
./gif.cpp: In function 'std::unique_ptr<GifFrameNativeContext, GifFrameNativeContextReleaser> getGifFrameNativeContext(JNIEnv*, jobject)':
./gif.cpp:833:83: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
       (GifFrameNativeContext*) pEnv->GetIntField(thiz, sGifFrameFieldNativeContext);
                                                                                   ^
./gif.cpp: In function 'void GifImage_nativeDispose(JNIEnv*, jobject)':
./gif.cpp:868:83: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
       (GifImageNativeContext*) pEnv->GetIntField(thiz, sGifImageFieldNativeContext);
                                                                                   ^
./gif.cpp: In function 'void GifFrame_nativeDispose(JNIEnv*, jobject)':
./gif.cpp:1160:83: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
       (GifFrameNativeContext*) pEnv->GetIntField(thiz, sGifFrameFieldNativeContext);
                                                                                   ^
make: *** [/Users/orospakr/code/joist/fresco/imagepipeline/build/tmp/ndk_build_gifimage/local/x86_64/objs/gifimage/gif.o] Error 1
make: Leaving directory `/Users/orospakr/code/joist/fresco/imagepipeline/src/main/jni/gifimage'
:imagepipeline:ndk_build_gifimage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':imagepipeline:ndk_build_gifimage'.
> Process 'command 'ndk-build'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 44.855 secs
```

**Comment by orospakr** [comment]
Looks like -Werror is turned on, and there's some 64-bit unclean pointer use in giflib. :(

**Comment by orospakr** [comment]
I've opened a PR with my changes, such as they are, at https://github.com/facebook/fresco/pull/121.

**Comment by plamenko** [comment]
I am closing this so that we can continue discussion in #121
