### ISSUE TITLE
fresco version "0.10.0" can't display gif ?

### ISSUE THREAD

**Issue by liubaoyua** [facebook/fresco#1214]
I use the following code to display a gif ,
`Uri uri = Uri.parse(url);
        SimpleDraweeView draweeView = (SimpleDraweeView) imageView;
        if (MimeTypeMap.getFileExtensionFromUrl(url).equals("gif")) {
            DraweeController controller = Fresco.newDraweeControllerBuilder()
                    .setUri(uri)
                    .setAutoPlayAnimations(true)
                    .build();
            draweeView.setController(controller);
        } else {
            draweeView.setImageURI(uri);
        }`

and in fresco"0.9.0" it works fine. but in "0.10.0",  I get an exception below.
`java.lang.NullPointerException: Attempt to invoke interface method 'com.facebook.imagepipeline.image.CloseableImage com.facebook.imagepipeline.animated.factory.AnimatedImageFactory.decodeGif(com.facebook.imagepipeline.image.EncodedImage, com.facebook.imagepipeline.common.ImageDecodeOptions, android.graphics.Bitmap$Config)' on a null object reference
                                                                                                                             at com.facebook.imagepipeline.decoder.ImageDecoder.decodeGif(ImageDecoder.java:113)
                                                                                                                             at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:88)
                                                                                                                             at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:189)
                                                                                                                             at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:97)
                                                                                                                             at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:129)
                                                                                                                             at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                                                                                                                             at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                                                                                                                             at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                                             at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                                                                                             at java.lang.Thread.run(Thread.java:818)`

**Comment by IanChilds** [comment]
Does the fix from #1209 work for you?

**Comment by oprisnik** [comment]
If you're using our pre-built Maven / jCenter AARs, try with `compile 'com.facebook.fresco:animated-gif:0.10.0'` instead of `compile project(':animated-gif')` mentioned in #1209

**Comment by liubaoyua** [comment]
thank you,  it works.
