### ISSUE TITLE
Easy crash frequently on 5.0 + caused by oom with viewpager

### ISSUE THREAD

**Issue by Rickyballs** [facebook/fresco#1245]
My Application is construct of viewpager+fragment.Each of the fragment contains a recyclerview which holds 1500 pictures.
First,When I slide list,memory keeps growing up until 80M memory.
Second,I began to slide the list of second page,the memory went to 120M soon and nerver went down.. 
And then,it is easy to throw OOM.
I also do as it(http://frescolib.org/docs/resizing-rotating.html#downsampling) puts,but nothing changed.

Here is the log.

```
05-26 22:47:10.769 20335-23333/com.xz.rd V/unknown:NativeMemoryChunkPool: release (reuse) (object, size) = (75bae42, 16384)
05-26 22:47:10.769 20335-23333/com.xz.rd V/unknown:NativeMemoryChunkPool: Used = (30, 6127616); Free = (19, 2313216)
05-26 22:47:10.779 20335-20335/com.xz.rd V/unknown:AbstractDraweeController: controller 6b78ed1 244: set_final_result @ onNewResult: image: CloseableReference 26160c18
05-26 22:47:10.779 20335-23333/com.xz.rd V/unknown:NativeMemoryChunkPool: Used = (31, 6193152); Free = (19, 2313216)
05-26 22:47:10.779 20335-23333/com.xz.rd V/unknown:NativeMemoryChunkPool: get (alloc) (object, size) = (21a2a671, 65536)
05-26 22:47:10.779 20335-23333/com.xz.rd V/unknown:NativeMemoryChunkPool: release (reuse) (object, size) = (486245, 32768)
05-26 22:47:10.779 20335-23333/com.xz.rd V/unknown:NativeMemoryChunkPool: Used = (30, 6160384); Free = (20, 2345984)
05-26 22:47:10.789 20335-23333/com.xz.rd I/unknown:TiffUtil: Unsupported orientation
05-26 22:47:10.789 20335-22163/com.xz.rd V/unknown:BitmapPool: Used = (31, 33432724); Free = (0, 0)
05-26 22:47:10.789 20335-22163/com.xz.rd V/unknown:BitmapPool: get (alloc) (object, size) = (2d3454d7, 701784)
05-26 22:47:10.799 20335-22163/com.xz.rd V/unknown:NativeMemoryChunkPool: release (free) (object, size) = (21a2a671, 65536)
05-26 22:47:10.799 20335-22163/com.xz.rd V/unknown:NativeMemoryChunkPool: Used = (29, 6094848); Free = (20, 2345984)
05-26 22:47:10.809 20335-20395/com.xz.rd I/art: Explicit concurrent mark sweep GC freed 78552(3MB) AllocSpace objects, 21(11MB) LOS objects, 16% free, 83MB/99MB, paused 2.563ms total 160.614ms
05-26 22:47:10.829 20335-20335/com.xz.rd V/unknown:AbstractDraweeController: controller cb4855e 243: set_final_result @ onNewResult: image: CloseableReference 266bd1c4
05-26 22:47:11.149 20335-20395/com.xz.rd I/art: hprof: heap dump "/storage/emulated/0/Download/leakcanary-com.xz.rd/suspected_leak_heapdump.hprof" starting...
05-26 22:47:18.707 20335-20395/com.xz.rd I/art: hprof: heap dump completed (100MB) in 7.555s
05-26 22:47:18.737 20335-20335/com.xz.rd I/Choreographer: Skipped 455 frames!  The application may be doing too much work on its main thread.
05-26 22:47:18.767 20335-20342/com.xz.rd W/art: Suspending all threads took: 11.535ms
```

keep slide for a while

```
05-26 22:47:21.549 20335-20335/com.xz.rd V/unknown:AbstractDraweeController: controller 13f09686 248: ignore_old_datasource @ onProgress: failure: null
05-26 22:47:21.549 20335-20335/com.xz.rd V/unknown:AbstractDraweeController: controller 13f09686 248: ignore_old_datasource @ onProgress: failure: null
05-26 22:47:21.549 20335-20335/com.xz.rd V/unknown:AbstractDraweeController: controller 13f09686 248: ignore_old_datasource @ onProgress: failure: null
05-26 22:47:21.549 20335-23333/com.xz.rd I/unknown:TiffUtil: Unsupported orientation
05-26 22:47:21.549 20335-23333/com.xz.rd V/unknown:NativeMemoryChunkPool: release (reuse) (object, size) = (22eeabd4, 1048576)
05-26 22:47:21.549 20335-23333/com.xz.rd V/unknown:NativeMemoryChunkPool: Used = (28, 5898240); Free = (20, 2345984)
05-26 22:47:21.549 20335-22168/com.xz.rd V/unknown:BitmapPool: Used = (32, 33906312); Free = (0, 0)
05-26 22:47:21.549 20335-22168/com.xz.rd V/unknown:BitmapPool: get (alloc) (object, size) = (160843d5, 1579008)
05-26 22:47:21.549 20335-20335/com.xz.rd V/unknown:AbstractDraweeController: controller 275f91ac 254: set_final_result @ onNewResult: image: CloseableReference 217b64e1
05-26 22:47:21.559 20335-20335/com.xz.rd V/unknown:AbstractDraweeController: controller 12372d44 253: set_final_result @ onNewResult: image: CloseableReference 3334b6f4
05-26 22:47:21.559 20335-20335/com.xz.rd V/unknown:AbstractDraweeController: controller 236ab249 255: set_final_result @ onNewResult: image: CloseableReference 38f1e892
05-26 22:47:21.559 20335-20335/com.xz.rd V/unknown:AbstractDraweeController: controller 17cc5c05 256: set_final_result @ onNewResult: image: CloseableReference 328a11bf
05-26 22:47:21.579 20335-22168/com.xz.rd V/unknown:BitmapPool: release (free) (object, size) = (3bd11826, 887288)
05-26 22:47:21.579 20335-22168/com.xz.rd V/unknown:BitmapPool: Used = (31, 33019024); Free = (0, 0)
05-26 22:47:21.579 20335-22168/com.xz.rd V/unknown:NativeMemoryChunkPool: release (free) (object, size) = (1041fbde, 65536)
05-26 22:47:21.579 20335-22168/com.xz.rd V/unknown:NativeMemoryChunkPool: Used = (27, 5832704); Free = (20, 2345984)
05-26 22:47:21.589 20335-20335/com.xz.rd V/unknown:AbstractDraweeController: controller 6b78ed1 252: set_final_result @ onNewResult: image: CloseableReference 31edf7ea
05-26 22:48:05.752 25074-25115/com.xz.rd:leakcanary I/art: WaitForGcToComplete blocked for 58.746ms for cause Alloc
05-26 22:48:06.163 25074-25088/com.xz.rd:leakcanary I/art: Clamp target GC heap from 132MB to 128MB
05-26 22:48:06.163 25074-25115/com.xz.rd:leakcanary I/art: WaitForGcToComplete blocked for 265.777ms for cause Alloc
05-26 22:48:07.624 25074-25115/com.xz.rd:leakcanary I/art: Clamp target GC heap from 130MB to 128MB
05-26 22:48:09.106 25074-25115/com.xz.rd:leakcanary I/art: WaitForGcToComplete blocked for 86.212ms for cause Alloc
05-26 22:48:10.427 25074-25088/com.xz.rd:leakcanary I/art: Clamp target GC heap from 133MB to 128MB
05-26 22:48:10.427 25074-25115/com.xz.rd:leakcanary I/art: WaitForGcToComplete blocked for 443.969ms for cause Alloc
05-26 22:48:17.574 25074-25088/com.xz.rd:leakcanary I/art: WaitForGcToComplete blocked for 600.311ms for cause Background
05-26 22:48:18.695 25074-25087/com.xz.rd:leakcanary I/art: WaitForGcToComplete blocked for 379.180ms for cause HomogeneousSpaceCompact
05-26 22:48:24.571 25074-25115/com.xz.rd:leakcanary I/art: Clamp target GC heap from 135MB to 128MB
05-26 22:48:24.571 25074-25115/com.xz.rd:leakcanary E/art: Throwing OutOfMemoryError "Failed to allocate a 48 byte allocation with 12 free bytes and 12B until OOM"
05-26 22:48:29.936 25074-25090/com.xz.rd:leakcanary E/art: Throwing OutOfMemoryError "Failed to allocate a 28 byte allocation with 12 free bytes and 12B until OOM" (recursive case)
05-26 22:48:29.936 25074-25074/com.xz.rd:leakcanary I/art: WaitForGcToComplete blocked for 1.079s for cause Alloc
05-26 22:48:29.956 25074-25090/com.xz.rd:leakcanary E/art: "Binder_2" prio=5 tid=10 Runnable
05-26 22:48:29.956 25074-25090/com.xz.rd:leakcanary E/art:   | group="main" sCount=0 dsCount=0 obj=0x32c08380 self=0xad25c400
05-26 22:48:29.956 25074-25090/com.xz.rd:leakcanary E/art:   | sysTid=25090 nice=0 cgrp=apps sched=0/0 handle=0xae926080
05-26 22:48:29.956 25074-25090/com.xz.rd:leakcanary E/art:   | state=R schedstat=( 0 0 0 ) utm=268 stm=5 core=0 HZ=100
05-26 22:48:29.956 25074-25090/com.xz.rd:leakcanary E/art:   | stack=0xb3c6e000-0xb3c70000 stackSize=1012KB
05-26 22:48:29.956 25074-25090/com.xz.rd:leakcanary E/art:   | held mutexes= "mutator lock"(shared held)
05-26 22:48:29.956 25074-25090/com.xz.rd:leakcanary E/art:     at java.lang.ThreadLocal$Values.initializeTable(ThreadLocal.java:244)
05-26 22:48:29.956 25074-25090/com.xz.rd:leakcanary E/art:     at java.lang.ThreadLocal$Values.<init>(ThreadLocal.java:181)
05-26 22:48:29.956 25074-25090/com.xz.rd:leakcanary E/art:     at java.lang.ThreadLocal.initializeValues(ThreadLocal.java:114)
05-26 22:48:29.956 25074-25090/com.xz.rd:leakcanary E/art:     at java.lang.ThreadLocal.set(ThreadLocal.java:89)
05-26 22:48:29.956 25074-25090/com.xz.rd:leakcanary E/art:     at android.os.StrictMode.clearGatheredViolations(StrictMode.java:1443)
05-26 22:48:29.956 25074-25090/com.xz.rd:leakcanary E/art:     at android.os.Binder.execTransact(Binder.java:480)
05-26 22:48:35.081 25074-25090/com.xz.rd:leakcanary E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
05-26 22:48:35.331 20335-26629/com.xz.rd D/LeakCanary: In com.xz.rd:1.0:1.
                                                                 * FAILURE:
                                                                 java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack available

                                                                 * Reference Key: 0f80ac95-e8f7-4b29-a172-889ef0010918
                                                                 * Device: samsung samsung GT-I9507V jftddzn
                                                                 * Android Version: 5.0.1 API: 21 LeakCanary: 1.4-beta2 3799172
                                                                 * Durations: watch=5016ms, gc=265ms, heap dump=8408ms, analysis=72756ms
                                                                 * Excluded Refs:
                                                                 | Field: android.app.ActivityThread$ActivityClientRecord.nextIdle
                                                                 | Field: android.view.inputmethod.InputMethodManager.mNextServedView
                                                                 | Field: android.view.inputmethod.InputMethodManager.mServedView
                                                                 | Field: android.view.inputmethod.InputMethodManager.mServedInputConnection
                                                                 | Field: android.view.inputmethod.InputMethodManager.mCurRootView
                                                                 | Field: android.animation.LayoutTransition$1.val$parent
                                                                 | Field: android.view.textservice.SpellCheckerSession$1.this$0
                                                                 | Field: android.support.v7.internal.widget.ActivityChooserModel.mActivityChoserModelPolicy
                                                                 | Field: android.widget.ActivityChooserModel.mActivityChoserModelPolicy
                                                                 | Field: android.accounts.AccountManager$AmsTask$Response.this$1
                                                                 | Field: android.media.MediaScannerConnection.mContext
                                                                 | Field: android.os.UserManager.mContext
                                                                 | Field: android.appwidget.AppWidgetHost$Callbacks.this$0
                                                                 | Field: android.sec.clipboard.ClipboardUIManager.mContext
                                                                 | Field: android.media.AudioManager$1.this$0
                                                                 | Field: android.widget.Editor$Blink.this$0
                                                                 | Field: android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue (always)
                                                                 | Static field: android.media.session.MediaSessionLegacyHelper.sInstance
                                                                 | Static field: android.text.TextLine.sCached
                                                                 | Static field: android.widget.TextView.mLastHoveredView
                                                                 | Thread:FinalizerWatchdogDaemon (always)
                                                                 | Thread:main (always)
                                                                 | Thread:LeakCanary-Heap-Dump (always)
                                                                 | Class:java.lang.ref.WeakReference (always)
                                                                 | Class:java.lang.ref.SoftReference (always)
                                                                 | Class:java.lang.ref.PhantomReference (always)
                                                                 | Class:java.lang.ref.Finalizer (always)
                                                                 | Class:java.lang.ref.FinalizerReference (always)
                                                                 | Root Class:android.os.Binder (always)
```

**Comment by Rickyballs** [comment]
@tyronen @kangax @daaku @bricooke @aizatto @daaku 
How to deal with viewpager+fragment+recyclerview(staggeredGridLayoutManager)?The memory just growing up!

**Comment by Rickyballs** [comment]
Fresco Version:fresco:0.9.0+

**Comment by plamenko** [comment]
Are you clearing the controller in `destroyItem` of your `PagerAdapter`? for example:

```
	public void destroyItem(ViewGroup container, int position, Object object) {
		FrameLayout page = (FrameLayout) container.getChildAt(position);
		SimpleDraweeView draweeView = (SimpleDraweeView) page.getChildAt(0);
		draweeView.setController(null);
	}
```

**Comment by Rickyballs** [comment]
I have done it at Friday.The memory temporarily stabilized at around 100M, I'll check it again tomorrow to see if there is any problem.Besides,there are stil a little nibble while sliding fast.Do you have any advise？Thanks a lot~

**Comment by aryandiputra** [comment]
i have the same problem, I have a fragment inside viewpager, and the fragment contain list of sticker inside gridlayout. When I swipe to first index then the next index, the memory always growth. Even I finish the activity, the memory still look the same (do not decrease).

**Comment by erikandre** [comment]
Closing due to lack or progress and/or updates since 2016
