### ISSUE TITLE
Unable to load full screen image on an android 4.2.1 device

### ISSUE THREAD

**Issue by moyi** [facebook/fresco#1248]
Hi, 
I am developing an App which is required to load a full screen image via a http url. Fresco(0.9.0+) works perfectly on an other testing device, Samsung SM-E7009 Android 4.4.4; however, it failed to load on a Lenovo device, K860 Android 4.2.1 (resolution-720x1280).  Logcat shows the error message as below. Hopefully somebody can give me a hand to solve this issue. If you need more info, please let me know. Many thanks.

```
05-27 14:57:59.651 31353-31916/com.wenming.views E/unknown:WebpTranscodeConsumer: unhandled exception
java.lang.NullPointerException
at com.facebook.imagepipeline.producers.WebpTranscodeProducer.shouldTranscode(WebpTranscodeProducer.java:160)
at com.facebook.imagepipeline.producers.WebpTranscodeProducer.access$000(WebpTranscodeProducer.java:37)
at com.facebook.imagepipeline.producers.WebpTranscodeProducer$WebpTranscodeConsumer.onNewResultImpl(WebpTranscodeProducer.java:75)
at com.facebook.imagepipeline.producers.WebpTranscodeProducer$WebpTranscodeConsumer.onNewResultImpl(WebpTranscodeProducer.java:59)
at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
at com.facebook.imagepipeline.producers.NetworkFetchProducer.notifyConsumer(NetworkFetchProducer.java:168)
at com.facebook.imagepipeline.producers.NetworkFetchProducer.handleFinalResult(NetworkFetchProducer.java:155)
at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:110)
at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:37)
at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:72)
at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher$1.run(HttpUrlConnectionNetworkFetcher.java:65)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:856)
```

**Comment by tyronen** [comment]
You need to add this line to your `build.gradle` file as [explained](http://frescolib.org/docs/index.html) in ths docs:

```groovy
  compile 'com.facebook.fresco:webpsupport:0.10.0'
```

This is needed to display WebP images on older Android devices.

In the next release of Fresco your app won't crash in this case, but still won't show the image.
