### ISSUE TITLE
Sumsung GT-N7102 4.1.2 can not show images.

### ISSUE THREAD

**Issue by taoweiji** [facebook/fresco#1278]
`unknown:WebpTranscodeProducer$WebpTranscodeConsumer: unhandled exception
                                                                                                    java.lang.NullPointerException
                                                                                                        at com.facebook.imagepipeline.producers.WebpTranscodeProducer.shouldTranscode(WebpTranscodeProducer.java:161)
                                                                                                        at com.facebook.imagepipeline.producers.WebpTranscodeProducer.access$000(WebpTranscodeProducer.java:37)
                                                                                                        at com.facebook.imagepipeline.producers.WebpTranscodeProducer$WebpTranscodeConsumer.onNewResultImpl(WebpTranscodeProducer.java:75)
                                                                                                        at com.facebook.imagepipeline.producers.WebpTranscodeProducer$WebpTranscodeConsumer.onNewResultImpl(WebpTranscodeProducer.java:59)
                                                                                                        at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
                                                                                                        at com.facebook.imagepipeline.producers.NetworkFetchProducer.notifyConsumer(NetworkFetchProducer.java:168)
                                                                                                        at com.facebook.imagepipeline.producers.NetworkFetchProducer.handleFinalResult(NetworkFetchProducer.java:155)
                                                                                                        at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:110)
                                                                                                        at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:37)
                                                                                                        at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:72)
                                                                                                        at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher.fetchSync(HttpUrlConnectionNetworkFetcher.java:83)
                                                                                                        at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher$1.run(HttpUrlConnectionNetworkFetcher.java:61)
                                                                                                        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
                                                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                                                        at java.lang.Thread.run(Thread.java:856)`

**Comment by kirwan** [comment]
This was a bug which will be fixed in the next release but it suggests you're using WebP images but haven't included the necessary optional dependency for WebP support.

http://frescolib.org/docs/webp-support.html

**Comment by taoweiji** [comment]
Thanks
