### ISSUE TITLE
eclipse java.lang.NoClassDefFoundError: com.facebook.drawee.backends.pipeline.Fresco

### ISSUE THREAD

**Issue by zhangcf2012** [facebook/fresco#1281]
use eclipse adt

06-02 11:49:02.760: E/AndroidRuntime(22082): FATAL EXCEPTION: main
06-02 11:49:02.760: E/AndroidRuntime(22082): java.lang.NoClassDefFoundError: com.facebook.drawee.backends.pipeline.Fresco
06-02 11:49:02.760: E/AndroidRuntime(22082): 	at com.greenstone.exp.GStoneApplication.onCreate(GStoneApplication.java:56)
06-02 11:49:02.760: E/AndroidRuntime(22082): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1010)
06-02 11:49:02.760: E/AndroidRuntime(22082): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4507)
06-02 11:49:02.760: E/AndroidRuntime(22082): 	at android.app.ActivityThread.access$1300(ActivityThread.java:144)
06-02 11:49:02.760: E/AndroidRuntime(22082): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
06-02 11:49:02.760: E/AndroidRuntime(22082): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-02 11:49:02.760: E/AndroidRuntime(22082): 	at android.os.Looper.loop(Looper.java:137)
06-02 11:49:02.760: E/AndroidRuntime(22082): 	at android.app.ActivityThread.main(ActivityThread.java:5166)
06-02 11:49:02.760: E/AndroidRuntime(22082): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-02 11:49:02.760: E/AndroidRuntime(22082): 	at java.lang.reflect.Method.invoke(Method.java:525)
06-02 11:49:02.760: E/AndroidRuntime(22082): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
06-02 11:49:02.760: E/AndroidRuntime(22082): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:561)
06-02 11:49:02.760: E/AndroidRuntime(22082): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by aagnes** [comment]
#410

**Comment by diewu0421** [comment]
I have the same error when I call Fresco.initialize(context) in application file.
My environment is as follows：
IDE: Android studio 3.4.0       
min_sdk :  19
target_sdk : 27
compile_sdk :28
buildtools:   28.0.3
support :   27.1.1

By the way, the error only reported on android devices  with version 4.4 ,and 4.4 with the above is  no problem.
java.lang.NoClassDefFoundError: com.facebook.drawee.backends.pipeline.Fresco
        at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.onCreate(BUGLY:189)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4696)
        at android.app.ActivityThread.access$1500(ActivityThread.java:174)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1458)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:222)
        at android.app.ActivityThread.main(ActivityThread.java:5484)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
        at dalvik.system.NativeStart.main(Native Method)
