### ISSUE TITLE
fresco show java.lang.UnsatisfiedLinkError:and java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by LPJXLOVE** [facebook/fresco#1283]
When i used ImageRequest and setResizeOptions in Android API 16,It show error like this:
  java.lang.ExceptionInInitializerError
                                                                             at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.doTransform(ResizeAndRotateProducer.java:154)
                                                                             at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.access$000(ResizeAndRotateProducer.java:72)
                                                                             at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer$1.run(ResizeAndRotateProducer.java:89)
                                                                             at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                                                                             at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                                                                             at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
                                                                             at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                                             at java.lang.Thread.run(Thread.java:856)
                                                                          Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1891]:   129 could not load needed library 'libwebp.so' for 'libimagepipeline.so' (load_library[1093]: Library 'libwebp.so' not found)
                                                                             at java.lang.Runtime.loadLibrary(Runtime.java:370)
                                                                             at java.lang.System.loadLibrary(System.java:535)
                                                                             at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
                                                                             at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
                                                                             at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:43)
                                                                             at com.facebook.imagepipeline.nativecode.JpegTranscoder.<clinit>(JpegTranscoder.java:26)
                                                                             at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.doTransform(ResizeAndRotateProducer.java:154) 
                                                                             at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.access$000(ResizeAndRotateProducer.java:72) 
                                                                             at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer$1.run(ResizeAndRotateProducer.java:89) 
                                                                             at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207) 
                                                                             at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27) 
                                                                             at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78) 
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
                                                                             at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43) 
                                                                             at java.lang.Thread.run(Thread.java:856) 

How can i solve this problems?

**Comment by aagnes** [comment]
Try solution in #410
