### ISSUE TITLE
 java.lang.NullPointerException

### ISSUE THREAD

**Issue by sapeksh** [facebook/fresco#1309]
FATAL EXCEPTION: main
                                                                          Process: com.example.sapeksh.maitra, PID: 5491
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.sapeksh.maitra/com.example.sapeksh.maitra.Appointment_New}: java.lang.NullPointerException
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                                              at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:136)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                              at dalvik.system.NativeStart.main(Native Method)
                                                                           Caused by: java.lang.NullPointerException
                                                                              at com.example.sapeksh.maitra.Appointment_New.init(Appointment_New.java:178)
                                                                              at com.example.sapeksh.maitra.Appointment_New.onCreate(Appointment_New.java:42)
                                                                              at android.app.Activity.performCreate(Activity.java:5231)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                              at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:136) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                              at dalvik.system.NativeStart.main(Native Method) 

AND JAVA CODE

public class Appointment_New extends ActionBarActivity{
    ActionBar actionBar;
    Button btn_nxt_new;
    Spinner spn_gender_new;
    SQLiteDatabase db;
    ArrayAdapter<CharSequence> Array_spn_gender_new;
    String temp,activityID,complain_catagery,ward;
    ArrayAdapter<CharSequence> spnActivityAdapter;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.appointment_new);

        actionBar = getSupportActionBar();
        actionBar.setHomeButtonEnabled(true);
        actionBar.setDisplayHomeAsUpEnabled(true);
        actionBar.setBackgroundDrawable(new ColorDrawable(Color.parseColor(getString(R.color.transparent_green))));
        actionBar.setTitle("New Appointment");
        init();
        insertActivity();
        //insertUNITSpinner();
        btn_nxt_new.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(Appointment_New.this, Appointment_common_both.class);
                startActivity(intent);
                finish();

                spn_gender_new.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {

                    @Override
                    public void onItemSelected(AdapterView<?> arg0, View arg1,
                                               int position, long arg3) {
                        // TODO Auto-generated method stub

                        temp = spn_gender_new.getSelectedItem().toString();
                        Log.d("TEST", "TEMP :::" + temp);

                        Cursor cursorDivision = db.rawQuery(
                                "select GenderId from Get_Gender where GenderName=" + "'"
                                        + temp + "'", null);

                        while (cursorDivision.moveToNext()) {
                            activityID = cursorDivision.getString(0);

                            Log.d("test", "Complaint code====" + activityID);
                        }
                    }

                    @Override
                    public void onNothingSelected(AdapterView<?> arg0) {
                        // TODO Auto-generated method stub

                    }
                });

              /*  spn_gender_new.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {

                    @Override
                    public void onItemSelected(AdapterView<?> arg0, View arg1,
                                               int arg2, long arg3) {

                        String temp;
                        temp = spn_gender_new.getSelectedItem().toString();
                        Log.d("TEST", "TEMP :::" + temp);
                        Cursor cursor = db.rawQuery(
                                "select * from Get_Gender where GenderName='"
                                        + temp + "'", null);
                        Log.d("TEST", "Get_Gender UNIT_TOPIC :::" + cursor);
                        while (cursor.moveToNext()) {
                            String GenderId = cursor.getString(0);
                            Log.d("TEST", "selected GenderId :::" +GenderId);
                          *//*  String UNIT_DESC = cursor.getString(2);
                            Log.d("TEST", "selected UNIT_DESC :::" + UNIT_DESC);
                            String UNIT_TOPIC = cursor.getString(3);
                            Log.d("TEST", "selected UNIT_TOPIC :::" + UNIT_TOPIC);
                            String NO_OF_LEC = cursor.getString(4);
                            Log.d("TEST", "selected NO_OF_LEC :::" + NO_OF_LEC);*//*

                            //text_topic1.setText(UNIT_TOPIC);

                        }

                    }

                    @Override
                    public void onNothingSelected(AdapterView<?> arg0) {

                    }
                });*/

            }
        });
    }

    public void insertActivity() {

        spnActivityAdapter.clear();
        spnActivityAdapter.notifyDataSetChanged();
        spnActivityAdapter.add("-Select Catagory-");

        Cursor cursor = db.rawQuery("select * from compactivity", null);

        if (cursor.moveToFirst()) {
            do {

                complain_catagery = cursor.getString(0);
                ward = cursor.getString(1);
                spnActivityAdapter.add(cursor.getString(1));
                spnActivityAdapter.notifyDataSetChanged();
                Log.d("test", "Activity" + cursor.getString(1));
            } while (cursor.moveToNext());

        }

    }

   /* private void insertUNITSpinner() {
        Log.d("test", "Get_Gender regular button ------ ");
        Array_spn_gender_new.clear();
        Array_spn_gender_new.notifyDataSetChanged();

        Cursor cursor = db.rawQuery("select * from Get_Gender ", null);
        int count = cursor.getCount();
        Log.d("test", "Get_Gender values count ------ " + count);
        if (cursor.moveToFirst()) {

            do {
                String Unitdescripation = cursor.getString(1);
                Log.d("test", "Get_Gender values Unitdescripation ------ " + Unitdescripation);
                Array_spn_gender_new.add(cursor.getString(1));

                Log.d("test", "Get_Gender Activity" + cursor.getString(1));
            } while (cursor.moveToNext());

        }
       spn_gender_new.setAdapter(Array_spn_gender_new);

    }*/

    private void init() {

        spnActivityAdapter = new ArrayAdapter<CharSequence>(this,
                R.layout.my_spinner_item);
        spnActivityAdapter.setDropDownViewResource(R.layout.my_spinner);
        spn_gender_new.setAdapter(spnActivityAdapter);

     /*   Array_spn_gender_new = new ArrayAdapter<CharSequence>(this,
                R.layout.my_spinner_item);
        spn_gender_new.setAdapter(Array_spn_gender_new);*/
        Sqliteopenhelper helper = new Sqliteopenhelper(this);
        db = helper.getWritableDatabase();
        btn_nxt_new=(Button)findViewById(R.id.btn_ntx);
        spn_gender_new=(Spinner)findViewById(R.id.spn_gender);
    }
    @Override
    public void onBackPressed() {
        // TODO Auto-generated method stub
        super.onBackPressed();
        Intent intent = new Intent(Appointment_New.this, Appointment.class);
        startActivity(intent);
        finish();
    }
}

**Comment by sapeksh** [comment]
please tell my answer early i am waiting for ans.

**Comment by massimocarli** [comment]
Hi @sapeksh 
Sorry but I don't think this is related to Fresco. Please provide us the log where Fresco is involved.
Thanks
