### ISSUE TITLE
android.view.InflateException: Binary XML file line #79: Error inflating class com.facebook.drawee.view.SimpleDraweeView

### ISSUE THREAD

**Issue by leelei** [facebook/fresco#131]
```
    <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/imageView_single_photo"
        xmlns:fresco="http://schemas.android.com/apk/res-auto"
        android:layout_below="@id/gridView_pics"
        android:layout_width="400dp"
        android:layout_height="400dp"
        />
```

    android.view.InflateException: Binary XML file line #79: Error inflating class com.facebook.drawee.view.SimpleDraweeView
            at android.view.LayoutInflater.createView(LayoutInflater.java:633)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at com.lucas.billow.ui.adapter.AbsViewHolderAdapter.generateView(AbsViewHolderAdapter.java:366)
            at com.lucas.billow.ui.adapter.AbsViewHolderAdapter.onCreateViewHolder(AbsViewHolderAdapter.java:281)
            at com.lucas.billow.ui.adapter.AbsViewHolderAdapter.onCreateViewHolder(AbsViewHolderAdapter.java:20)
            at com.lucas.billow.ui.adapter.EndlessRecyclerAdapter.onCreateViewHolder(EndlessRecyclerAdapter.java:57)
            at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:4121)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3431)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3340)
            at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1810)
            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1306)
            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1269)
            at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:523)
            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:1988)
            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2237)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:561)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:907)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)

**Comment by leelei** [comment]
sorry, i forgot add
        Fresco.initialize(getApplicationContext());

**Comment by leelei** [comment]
sorry, i forgot add
```
Fresco.initialize(getApplicationContext());
```

**Comment by lkw103037** [comment]
it's right

**Comment by ManMegh** [comment]
I have placed the Fresco.initialize(this); in my application, but still error is there...

@Override
protected void onCreate(Bundle savedInstanceState)
{

    super.onCreate(savedInstanceState);
    Fresco.initialize(this);
    setContentView(R.layout.activity_main);



    Uri uri = Uri.parse("https://raw.githubusercontent.com/facebook/fresco/gh-pages/static/fresco-logo.png");
    SimpleDraweeView draweeView = (SimpleDraweeView) findViewById(R.id.my_image_view);
    draweeView.setImageURI(uri);
}

**Comment by jimmyleeking** [comment]
@ManMegh，
do not to set the src property for SimpleDraweeView in xml resource.

**Comment by veereshkalmath** [comment]
Process: com.wdc.albums.production, PID: 15086
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime: android.view.InflateException: Binary XML file line #66: Error inflating class <unknown>
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.LayoutInflater.createView(LayoutInflater.java:640)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at com.wdc.collect.screens.collections.CollectionsAdapter.onCreateViewHolder(CollectionsAdapter.java:192)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at com.wdc.collect.screens.collections.CollectionsAdapter.onCreateViewHolder(CollectionsAdapter.java:39)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:4783)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4089)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3999)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1892)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1338)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1301)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:534)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2411)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2709)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.View.layout(View.java:16550)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5303)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.View.layout(View.java:16550)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5303)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.View.layout(View.java:16550)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5303)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.View.layout(View.java:16550)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5303)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.View.layout(View.java:16550)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5303)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:494)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.View.layout(View.java:16550)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5303)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.View.layout(View.java:16550)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.ViewGroup.layout(ViewGroup.java:5303)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2312)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2025)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1180)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6563)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:590)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:560)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:145)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5835)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
11-04 10:31:36.282 15086-15086/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

I'm facing the same issue? Is there a work around for this?

**Comment by tyronen** [comment]
Please open a new issue and post your XML. Make sure you are calling Fresco.initialize.

**Comment by 756718646** [comment]
@ManMegh，I have the same problem with you，How do you solve??

**Comment by 756718646** [comment]
I write that there is no problem
       Fresco.initialize(this.getApplicationContext());
        
        setContentView(R.layout.activity_main);
        
        mBaselineJpegView = new SimpleDraweeView(this.getApplicationContext());
        
        this.addContentView(mBaselineJpegView, new LayoutParams(50,50));

but i write in xml  have this problem:
  Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class com.facebook.drawee.view.SimpleDraweeView

  java.lang.RuntimeException: Unable to start activity ComponentInfo{app.shuangying.com.frescotest/app.shuangying.com.frescotest.MainActivity}: android.view.InflateException: Binary XML file line #19: Error inflating class com.facebook.drawee.view.SimpleDraweeView
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2406)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
                                                                                   at android.app.ActivityThread.access$1200(ActivityThread.java:152)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5539)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                                Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class com.facebook.drawee.view.SimpleDraweeView
                                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:652)
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:825)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:523)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:425)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:368)
                                                                                   at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:380)
                                                                                   at android.app.Activity.setContentView(Activity.java:2188)
                                                                                   at app.shuangying.com.frescotest.MainActivity.onCreate(MainActivity.java:14)
                                                                                   at android.app.Activity.performCreate(Activity.java:6013)
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466) 
                                                                                   at android.app.ActivityThread.access$1200(ActivityThread.java:152) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:135) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5539) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                                Caused by: java.lang.reflect.InvocationTargetException
                                                                                   at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:626)
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:825) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:523) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:425) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:368) 
                                                                                   at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:380) 
                                                                                   at android.app.Activity.setContentView(Activity.java:2188) 
                                                                                   at app.shuangying.com.frescotest.MainActivity.onCreate(MainActivity.java:14) 
                                                                                   at android.app.Activity.performCreate(Activity.java:6013) 
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466) 
                                                                                   at android.app.ActivityThread.access$1200(ActivityThread.java:152) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:135) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5539) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                                Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/drawee/R$styleable;
                                                                                   at com.facebook.drawee.view.GenericDraweeView.inflateHierarchy(GenericDraweeView.java:120)
                                                                                   at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:75)
                                                                                   at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:58)
                                                                                   at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:626) 
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:825) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:523) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:425) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:368) 
                                                                                   at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:380) 
                                                                                   at android.app.Activity.setContentView(Activity.java:2188) 
                                                                                   at app.shuangying.com.frescotest.MainActivity.onCreate(MainActivity.java:14) 
                                                                                   at android.app.Activity.performCreate(Activity.java:6013) 
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466) 
                                                                                   at android.app.ActivityThread.access$1200(ActivityThread.java:152) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:135) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5539) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.drawee.R$styleable" on path: DexPathList[[zip file "/data/app/app.shuangying.com.frescotest-2/base.apk"],nativeLibraryDirectories=[/data/app/app.shuangying.com.frescotest-2/lib/arm, /vendor/lib, /system/lib]]
                                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                   at com.facebook.drawee.view.GenericDraweeView.inflateHierarchy(GenericDraweeView.java:120) 
                                                                                   at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:75) 
                                                                                   at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:58) 
                                                                                   at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                                   at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                                   at android.view.LayoutInflater.createView(LayoutInflater.java:626) 
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:825) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:523) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:425) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:368) 
                                                                                   at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:380) 
                                                                                   at android.app.Activity.setContentView(Activity.java:2188) 
                                                                                   at app.shuangying.com.frescotest.MainActivity.onCreate(MainActivity.java:14) 
                                                                                   at android.app.Activity.performCreate(Activity.java:6013) 
                                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2359) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466) 
                                                                                   at android.app.ActivityThread.access$1200(ActivityThread.java:152) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:135) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5539) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                                                                               	Suppressed: java.lang.ClassNotFoundException: com.facebook.drawee.R$styleable
                                                                                   at java.lang.Class.classForName(Native Method)
                                                                                   at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                   at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                   		... 28 more
                                                                                Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available


how to  use in the xml??thank

**Comment by igcarun** [comment]
thanks :)

**Comment by aneeshATgithub** [comment]
use following version, and you can initialize fresco in Application class

compile 'com.facebook.fresco:fresco:0.12.0'

**Comment by forYueji** [comment]
layout file 


 <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/welcome_image_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent" /> 

ime: FATAL EXCEPTION: main
                                                                 Process: com.ihandy.fund, PID: 14740
                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ihandy.fund/com.ihandy.fund.welcome.SplashActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class com.facebook.drawee.view.SimpleDraweeView
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2341)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2403)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5298)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:708)
                                                                  Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.facebook.drawee.view.SimpleDraweeView
