### ISSUE TITLE
Can not fetch any picture on fresco0.2.0

### ISSUE THREAD

**Issue by Kester4android** [facebook/fresco#134]
I import the project , add the ndk.dir in local.properties. run "sample" but it only show me the error below.
04-12 18:01:35.278    7015-7188/com.facebook.fresco.sample E/unknown:FrescoSample﹕ Exception fetching album
    java.net.UnknownHostException: Unable to resolve host "api.imgur.com": No address associated with hostname
            at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
            at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
            at java.net.InetAddress.getAllByName(InetAddress.java:214)
            at com.android.okhttp.internal.Dns$1.getAllByName(Dns.java:28)
            at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:216)
            at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:122)
            at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:292)
            at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
            at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
            at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:161)
            at com.facebook.fresco.sample.urlsfetcher.ImageUrlsFetcher.downloadContentAsString(ImageUrlsFetcher.java:110)
            at com.facebook.fresco.sample.urlsfetcher.ImageUrlsFetcher.getImageUrls(ImageUrlsFetcher.java:75)
            at com.facebook.fresco.sample.urlsfetcher.ImageUrlsFetcher.access$000(ImageUrlsFetcher.java:41)
            at com.facebook.fresco.sample.urlsfetcher.ImageUrlsFetcher$1.doInBackground(ImageUrlsFetcher.java:63)
            at com.facebook.fresco.sample.urlsfetcher.ImageUrlsFetcher$1.doInBackground(ImageUrlsFetcher.java:60)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: libcore.io.GaiException: getaddrinfo failed: EAI_NODATA (No address associated with hostname)
            at libcore.io.Posix.getaddrinfo(Native Method)
            at libcore.io.ForwardingOs.getaddrinfo(ForwardingOs.java:61)
            at java.net.InetAddress.lookupHostByName(InetAddress.java:405)
            at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
            at java.net.InetAddress.getAllByName(InetAddress.java:214)
            at com.android.okhttp.internal.Dns$1.getAllByName(Dns.java:28)
            at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:216)
            at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:122)
            at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:292)
            at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
            at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
            at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:161)
            at com.facebook.fresco.sample.urlsfetcher.ImageUrlsFetcher.downloadContentAsString(ImageUrlsFetcher.java:110)
            at com.facebook.fresco.sample.urlsfetcher.ImageUrlsFetcher.getImageUrls(ImageUrlsFetcher.java:75)
            at com.facebook.fresco.sample.urlsfetcher.ImageUrlsFetcher.access$000(ImageUrlsFetcher.java:41)
            at com.facebook.fresco.sample.urlsfetcher.ImageUrlsFetcher$1.doInBackground(ImageUrlsFetcher.java:63)
            at com.facebook.fresco.sample.urlsfetcher.ImageUrlsFetcher$1.doInBackground(ImageUrlsFetcher.java:60)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

**Comment by Kester4android** [comment]
Net's not connected.
