### ISSUE TITLE
Preconditions.checkArgument error when setResizeOptions

### ISSUE THREAD

**Issue by wsychina** [facebook/fresco#1375]
We have received a lot of errors from our users. The records are as below.
java.lang.IllegalArgumentException
	at com.facebook.common.internal.Preconditions.checkArgument(Preconditions.java:108)
	at com.facebook.imagepipeline.common.ResizeOptions.<init>(ResizeOptions.java:34)
	at love.cosmo.android.show.adapter.ImagePickerRecyclerAdapter.onBindViewHolder(ImagePickerRecyclerAdapter.java:78)
	at love.cosmo.android.show.adapter.ImagePickerRecyclerAdapter.onBindViewHolder(ImagePickerRecyclerAdapter.java:28)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5768)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5801)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5037)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
	at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:531)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
	at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3069)
	at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1478)
	at android.support.v7.widget.RecyclerView.access$400(RecyclerView.java:151)
	at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4333)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:786)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:559)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:772)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5143)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
	at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by wsychina** [comment]
The resize code is in a recyclerAdapter.
`int width = ScreenUtils.dp2px(60);
            int height = ScreenUtils.dp2px(60);

            ImageRequest request = ImageRequestBuilder.newBuilderWithSource(Uri.parse(filePath))
                    .setResizeOptions(new ResizeOptions(width, height))
//                    .setAutoRotateEnabled(false)
                    .build();
            PipelineDraweeController controller = (PipelineDraweeController) Fresco.newDraweeControllerBuilder()
                    .setOldController(holder.mImage.getController())
                    .setImageRequest(request)
                    .build();

            holder.mImage.setController(controller);`

**Comment by wsychina** [comment]
All errors are from Android 4.4.4 until now.

**Comment by aneophyte** [comment]
Sure that `ScreenUtils.dp2px()` returns a non-zero positive integer? It throws that exception if not.

**Comment by wsychina** [comment]
@aneophyte Thank you, it's a good suggestion and I have added default value if it is zero. But I need to know whether it caused the problem for certain, because ScreenUtils.dp2px() seems seldom gets wrong.

**Comment by kirwan** [comment]
-1 is an illegal value for either parameter in the `ResizeOptions` constructor and will throw that exception. If `ScreenUtils.dp2px(int)` can return -1 I suggest checking the `width` and `height` values you have before creating `ResizeOptions`.

**Comment by aneophyte** [comment]
@wsychina you're welcome to go through the sources from your IDE, it's very clear there.

**Comment by wsychina** [comment]
ok, thank you @kirwan @aneophyte

**Comment by leaderliang** [comment]
```
ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(Uri.parse(mImageUrl))
                    .setResizeOptions(new ResizeOptions(width, height))
                    .build();
```
width and height should   >  0

**Comment by simonwangtx** [comment]
Thx @leaderliang , this project I've no longer maintained. And the error must exist in dp2px procedure and may occur in some devices that do not support the functions in dp2px.
