### ISSUE TITLE
java.lang.NoSuchMethodError: no static or non-static method "Lcom/facebook/imagepipeline/nativecode/Bitmaps;.nativeGetByteBuffer(Landroid/graphics/Bitmap;JJ)Ljava/nio/ByteBuffer;"

### ISSUE THREAD

**Issue by maikoulin** [facebook/fresco#1387]
java.lang.NoSuchMethodError: no static or non-static method "Lcom/facebook/imagepipeline/nativecode/Bitmaps;.nativeGetByteBuffer(Landroid/graphics/Bitmap;JJ)Ljava/nio/ByteBuffer;"
    at java.lang.Runtime.nativeLoad(Native Method)
    at java.lang.Runtime.doLoad(Runtime.java:421)
    at java.lang.Runtime.loadLibrary(Runtime.java:362)
    at java.lang.System.loadLibrary(System.java:526)
    at com.facebook.common.f.b.a(Unknown Source)
    at com.facebook.common.f.a.a(Unknown Source)
    at com.facebook.imagepipeline.nativecode.Bitmaps.<clinit>(Unknown Source)
    at com.facebook.imagepipeline.i.b.a(Unknown Source)
    at com.facebook.imagepipeline.i.d.a(Unknown Source)
    at com.facebook.imagepipeline.i.b.a(Unknown Source)
    at com.facebook.imagepipeline.i.d.a(Unknown Source)
    at com.facebook.imagepipeline.f.a.a(Unknown Source)
    at com.facebook.imagepipeline.f.a.a(Unknown Source)
    at com.facebook.imagepipeline.producers.t.c(Unknown Source)
    at com.facebook.imagepipeline.producers.t.a(Unknown Source)
    at com.facebook.imagepipeline.producers.u.a(Unknown Source)
    at com.facebook.imagepipeline.producers.JobScheduler.e(Unknown Source)
    at com.facebook.imagepipeline.producers.JobScheduler.a(Unknown Source)
    at com.facebook.imagepipeline.producers.ak.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at com.facebook.imagepipeline.d.n.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:841)

**Comment by lambdapioneer** [comment]
Hi @maikoulin, can you provide us with some more details? Especially, I'd like to know if you've followed the steps http://frescolib.org/docs/proguard.html and if the issue also appears in debug builds without obfuscation.

**Comment by nscastelli** [comment]
Hello, I'm having a similar issue while trying to use OkHttp in the image pipeline.
Here I send you my build.gradle and MainApplication.java files, and also the error log.

**build.gradle**
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion '24.0.0'

    defaultConfig {
        applicationId "com.vmbc.quest"
        minSdkVersion 14
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        jackOptions {
            enabled true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    productFlavors {
        ...
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.google.android.gms:play-services-location:9.6.1'
    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.android.support:design:24.2.1'
    compile 'com.google.code.gson:gson:2.4'
    compile 'com.squareup.okhttp3:okhttp:3.4.1'
    compile 'com.android.support:support-v4:24.2.1'
    compile 'com.facebook.fresco:fresco:0.14.0'
    compile 'com.facebook.fresco:imagepipeline-okhttp:0.14.0'
    compile 'org.apache.directory.studio:org.apache.commons.io:2.4'
}

```

**MainApplication.java**
```
package com.vmbc.quest;

import android.app.Application;
import android.text.TextUtils;

import com.facebook.drawee.backends.pipeline.Fresco;
import com.facebook.imagepipeline.backends.okhttp3.OkHttpImagePipelineConfigFactory;
import com.facebook.imagepipeline.core.ImagePipelineConfig;
import com.vmbc.quest.utils.SharedPreferencesHelper;

import java.io.IOException;
import java.util.concurrent.TimeUnit;

import okhttp3.Interceptor;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

public class MainApplication extends Application {

    @Override
    public void onCreate() {

        super.onCreate();

        OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .connectTimeout(120, TimeUnit.SECONDS)
                .writeTimeout(120, TimeUnit.SECONDS)
                .readTimeout(120, TimeUnit.SECONDS)
                .addNetworkInterceptor(new Interceptor() {
                    @Override
                    public Response intercept(Chain chain) throws IOException {

                        Request.Builder builder = chain.request().newBuilder();
                        String token = SharedPreferencesHelper.getInstance(getApplicationContext()).getAuthToken();

                        if (!TextUtils.isEmpty(token)) {
                            builder.addHeader("Authorization", "Bearer " + token);
                        }

                        return chain.proceed(builder.build());
                    }
                })
                .build();

        ImagePipelineConfig config = OkHttpImagePipelineConfigFactory
                .newBuilder(getApplicationContext(), okHttpClient)
                .build();
        Fresco.initialize(getApplicationContext(), config);
    }
}
```

**Error Log**
```
09-26 16:25:43.050 25225-25225/? E/Zygote: MountEmulatedStorage()
09-26 16:25:43.050 25225-25225/? E/Zygote: v2
09-26 16:25:43.055 25225-25225/? E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
09-26 16:25:43.220 25225-25225/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.vmbc.quest, PID: 25225
                                                   java.lang.NoSuchMethodError: No static method get(Lcom/facebook/common/internal/Supplier;Lcom/facebook/common/memory/MemoryTrimmableRegistry;Lcom/facebook/imagepipeline/bitmaps/PlatformBitmapFactory;Z)Lcom/facebook/imagepipeline/cache/CountingMemoryCache; in class Lcom/facebook/imagepipeline/cache/BitmapCountingMemoryCacheFactory; or its super classes (declaration of 'com.facebook.imagepipeline.cache.BitmapCountingMemoryCacheFactory' appears in /data/app/com.vmbc.quest-1/base.apk)
                                                       at com.facebook.imagepipeline.core.ImagePipelineFactory.getBitmapCountingMemoryCache(ImagePipelineFactory.java:129)
                                                       at com.facebook.imagepipeline.core.ImagePipelineFactory.getBitmapMemoryCache(ImagePipelineFactory.java:142)
                                                       at com.facebook.imagepipeline.core.ImagePipelineFactory.getProducerFactory(ImagePipelineFactory.java:331)
                                                       at com.facebook.imagepipeline.core.ImagePipelineFactory.getProducerSequenceFactory(ImagePipelineFactory.java:347)
                                                       at com.facebook.imagepipeline.core.ImagePipelineFactory.getImagePipeline(ImagePipelineFactory.java:236)
                                                       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:48)
                                                       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:40)
                                                       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:34)
                                                       at com.facebook.drawee.backends.pipeline.Fresco.initializeDrawee(Fresco.java:43)
                                                       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:39)
                                                       at com.vmbc.quest.MainApplication.onCreate(MainApplication.java:49)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5122)
                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:177)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1510)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:145)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5951)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

```

**Comment by oprisnik** [comment]
Please update to the latest Fresco version and update your proguard configuration according to http://frescolib.org/docs/shipping.html
