### ISSUE TITLE
java.lang.OutOfMemoryError: Failed to allocate a 4147212 byte allocation with 2012184 free bytes and 1965KB until OOM

### ISSUE THREAD

**Issue by jmheart** [facebook/fresco#1390]
图库选择多次操作发生omm了 
java.lang.OutOfMemoryError: Failed to allocate a 4147212 byte allocation with 2012184 free bytes and 1965KB until OOM
                                                                                                        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                                                        at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:847)
                                                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:817)
                                                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:784)
                                                                                                        at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
                                                                                                        at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
                                                                                                        at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
                                                                                                        at com.facebook.imagepipeline.platform.ArtDecoder.decodeStaticImageFromStream(ArtDecoder.java:137)
                                                                                                        at com.facebook.imagepipeline.platform.ArtDecoder.decodeFromEncodedImage(ArtDecoder.java:81)
                                                                                                        at com.facebook.imagepipeline.decoder.ImageDecoder.decodeStaticImage(ImageDecoder.java:128)
                                                                                                        at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:94)
                                                                                                        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:189)
                                                                                                        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:97)
                                                                                                        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:129)
                                                                                                        at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                                                                                                        at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                                                                                                        at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                                        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                                                                        at java.lang.Thread.run(Thread.java:831)

**Comment by henryloveself** [comment]
Hello, when I use Fresco to display image it happens the same situation! Can u tell me the resolution?Thanks
