### ISSUE TITLE
Draw to canvas without displaying a SimpleDraweeView

### ISSUE THREAD

**Issue by soapsign** [facebook/fresco#1403]
I am trying to capture a layout with SimpleDraweeView into bitmap without showing the view. And I got this when call `layout.draw(canvas);`. Anyway to fix this issues?

```
E/unknown:DraweeEventTracker: 2d27a76: Draw requested for a non-attached controller 2324877. DraweeHolder{controllerAttached=false, holderAttached=false, drawableVisible=true, activityStarted=true, events=[ON_SET_HIERARCHY, ON_SET_CONTROLLER]}
Process: com.grandsoft.instagrab, PID: 2293
java.lang.IllegalStateException
   at com.facebook.common.internal.Preconditions.checkState(Preconditions.java:158)
   at com.facebook.drawee.components.DeferredReleaser.ensureOnUiThread(DeferredReleaser.java:103)
   at com.facebook.drawee.components.DeferredReleaser.cancelDeferredRelease(DeferredReleaser.java:98)
   at com.facebook.drawee.controller.AbstractDraweeController.onAttach(AbstractDraweeController.java:336)
   at com.facebook.drawee.view.DraweeHolder.attachController(DraweeHolder.java:276)
   at com.facebook.drawee.view.DraweeHolder.attachOrDetachController(DraweeHolder.java:293)
   at com.facebook.drawee.view.DraweeHolder.onDraw(DraweeHolder.java:177)
   at com.facebook.drawee.generic.RootDrawable.draw(RootDrawable.java:83)
   at android.widget.ImageView.onDraw(ImageView.java:1228)
   at android.view.View.draw(View.java:16270)
```

**Comment by lambdapioneer** [comment]
In general, Drawees are not supposed to be called this way. They should be used inside the normal layout of your application. Have a look at the `BaseBitmapDataSubscriber` (http://frescolib.org/docs/datasources-datasubscribers.html) if you are interested in getting a Bitmap.

If you really want to go this way: From the stack trace it looks like you call the `onDraw` from a non-UI thread. Try out calling this from a runnable scheduled using `Activity#runOnUiThread`. You also want to pass in a controller to avoid the warning message.

**Comment by oprisnik** [comment]
Also, take a look at [how to write custom views](http://frescolib.org/docs/writing-custom-views.html). You can take the top level Drawable from the DraweeHierarchy and draw it manually (and properly forward attach / detach calls).
