### ISSUE TITLE
UnsatisfiedLinkError:couldn't find "libimagepipeline.so"

### ISSUE THREAD

**Issue by ylbkoo** [facebook/fresco#1415]
I use aar lib to import fresco，but when try to run app, it crash.
How to fix it？

 at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                      at java.lang.System.loadLibrary(System.java:1076)
                                                                      at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
                                                                      at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
                                                                      at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:43)
                                                                      at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:36)
                                                                      at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
                                                                      at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
                                                                      at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
                                                                      at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
                                                                      at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:36)
                                                                      at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:59)
                                                                      at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
                                                                      at com.facebook.imagepipeline.producers.LocalFetchProducer.getByteBufferBackedEncodedImage(LocalFetchProducer.java:97)
                                                                      at com.facebook.imagepipeline.producers.LocalFetchProducer.getEncodedImage(LocalFetchProducer.java:119)
                                                                      at com.facebook.imagepipeline.producers.LocalContentUriFetchProducer.getEncodedImage(LocalContentUriFetchProducer.java:80)
                                                                      at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:66)
                                                                      at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:62)
                                                                      at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                      at java.lang.Thread.run(Thread.java:818)

**Comment by massimocarli** [comment]
Hi @ylbkoo 
can you provide more info please? Does this happen on specific case or always?
Thanks

**Comment by ylbkoo** [comment]
This happen always.

I use mk file to import fresco lib, then that compile to apk, but in apk file, not contain so file.

The mk file follows.
Thanks.

LOCAL_STATIC_JAVA_AAR_LIBRARIES += libfbdrawee
LOCAL_STATIC_JAVA_AAR_LIBRARIES += libfbcore
LOCAL_STATIC_JAVA_AAR_LIBRARIES += libfresco
LOCAL_STATIC_JAVA_AAR_LIBRARIES += libfbimgpipe
LOCAL_STATIC_JAVA_AAR_LIBRARIES += libfbimgpipebase

LOCAL_AAPT_FLAGS := \
	--auto-add-overlay \
	--extra-packages com.facebook

LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES += libfbdrawee:libs/drawee-0.12.0.aar
LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES += libfbcore:libs/fbcore-0.12.0.aar
LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES += libfresco:libs/fresco-0.12.0.aar
LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES += libfbimgpipe:libs/imagepipeline-0.12.0.aar
LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES += libfbimgpipebase:libs/imagepipeline-base-0.12.0.aar

**Comment by romichandra** [comment]
Hello I am in need of help. facing the same issue when my app is build in release mode. sadly, everything works fine when i build my app in debug mode.

Any help regarding this topic would be appreciated :)

**Comment by romichandra** [comment]
Hello, I am facing the same issue when my app is build in release mode. sadly, everything works fine when i build my app in debug mode.

Any help regarding this topic would be appreciated :)

**Comment by lambdapioneer** [comment]
Hi @romichandra, have you followed the instructions from http://frescolib.org/docs/index.html and http://frescolib.org/docs/proguard.html ? Do the sample apps in our repository build and run when you build them locally?

**Comment by romichandra** [comment]
Thanks lambda,
for linking me to proguard-fresco.pro, it solved the UnsatisfiedLinkError but has introduced me to a new exception now. Now the app doesnot crash but still the log is filled by "Failed to decrypt db property" runtime exception. 

follow the trace:
[ex-fresco-db.txt](https://github.com/facebook/fresco/files/533453/ex-fresco-db.txt)

**Comment by lambdapioneer** [comment]
This seems to come from another (Facebook) app. It's not related to Fresco.

**Comment by romichandra** [comment]
I'd connect with you if i ever face a problem again. Ty :)

**Comment by erikandre** [comment]
Closing as this is not a supported way of including Fresco in your app. Please use gradle to include the library as documented here: http://frescolib.org/docs/getting-started.html
