### ISSUE TITLE
OutOfMemoryError with GenericDraweeHierarchy

### ISSUE THREAD

**Issue by Lee-Wang-Jing** [facebook/fresco#1416]
```
java.lang.OutOfMemoryError:
android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:594)
android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:429)
android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:840)
android.content.res.Resources.loadDrawable(Resources.java:2174)
android.content.res.Resources.getDrawable(Resources.java:716)
com.facebook.drawee.generic.GenericDraweeHierarchyInflater.getDrawable(GenericDraweeHierarchyInflater.java:227)
com.facebook.drawee.generic.GenericDraweeHierarchyInflater.updateBuilder(GenericDraweeHierarchyInflater.java:116)
com.facebook.drawee.generic.GenericDraweeHierarchyInflater.inflateBuilder(GenericDraweeHierarchyInflater.java:77)
com.facebook.drawee.view.GenericDraweeView.inflateHierarchy(GenericDraweeView.java:58)
com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:43)
com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:62)
```

I use GenericDraweeHierarchy to change PlaceholderImage with different color
![image](https://github.com/Lee-Wang-Jing/GitImageSave/blob/master/ImageSave/differentcolor.png?raw=true)

```
    /**
     * 为SimpleDraweeView设置Controller
     *
     * @param simpleDraweeView 加载图片的simpleDraweeView
     * @param gifView          表示图片是否是gif的imageview
     * @param infos            图片数据
     * @param position         选中图片的位置
     * @param context          Context
     */
    private void setController(SimpleDraweeView simpleDraweeView, ImageView gifView, final List<AttachesEntity> infos, final int position, final Context context) {
        String filepath = "" + infos.get(position).getUrl();
        GenericDraweeHierarchy hierarchy = simpleDraweeView.getHierarchy();
        if (random == null) {
            random = new Random();
        }
        Drawable drawable = StaticUtil.ChangeColorsDrawable[random.nextInt(7)];
        hierarchy.setPlaceholderImage(drawable);
        hierarchy.setFailureImage(drawable);
        ImageRequest request = ImageRequestBuilder.newBuilderWithSource(getUriWithPath(filepath))
                .setResizeOptions(new ResizeOptions(500, 500))
                .build();
        PipelineDraweeController controller = (PipelineDraweeController) Fresco.newDraweeControllerBuilder()
                .setOldController(simpleDraweeView.getController())
                .setImageRequest(request)
                .build();
        simpleDraweeView.setController(controller);
        simpleDraweeView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startViewpagerActivity(infos, position, context);
            }
        });
    }
```

**Comment by Lee-Wang-Jing** [comment]
use version is 0.12.0,but old version is no problem

**Comment by massimocarli** [comment]
Hi @Lee-Wang-Jing ,
how big is the original image? Is the image from resource right? It looks like Android is decoding the Image from the resources but this is too big. 
Thanks

**Comment by Lee-Wang-Jing** [comment]
Hi @massimocarli 
The PlaceholderImage and FailureImage is some colors
Like this:
![image](https://github.com/Lee-Wang-Jing/GitImageSave/blob/master/ImageSave/differentcolor.png?raw=true)
OutOfMemory On this device
![image](https://github.com/Lee-Wang-Jing/GitImageSave/blob/master/ImageSave/%E8%AE%BE%E5%A4%87%E4%BF%A1%E6%81%AF.png?raw=true)
Error Messages Like this

**Comment by Lee-Wang-Jing** [comment]
Hi @massimocarli 
Today,I set "android:largeHeap="true"",it's ok

**Comment by ladia12** [comment]
I am having the same issue.

```
Caused by java.lang.OutOfMemoryError: Failed to allocate a 8843124 byte allocation with 7598648 free bytes and 7MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:726)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:547)
       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1014)
       at android.content.res.Resources.loadDrawableForCookie(Resources.java:3730)
       at android.content.res.Resources.loadDrawable(Resources.java:3603)
       at android.content.res.Resources.getDrawable(Resources.java:1852)
       at android.content.res.Resources.getDrawable(Resources.java:1818)
       at com.facebook.drawee.generic.GenericDraweeHierarchyInflater.getDrawable(GenericDraweeHierarchyInflater.java:227)
       at com.facebook.drawee.generic.GenericDraweeHierarchyInflater.updateBuilder(GenericDraweeHierarchyInflater.java:116)
       at com.facebook.drawee.generic.GenericDraweeHierarchyInflater.inflateBuilder(GenericDraweeHierarchyInflater.java:77)
       at com.facebook.drawee.view.GenericDraweeView.inflateHierarchy(GenericDraweeView.java:58)
       at com.facebook.drawee.view.GenericDraweeView.(GenericDraweeView.java)
       at com.facebook.drawee.view.SimpleDraweeView.(SimpleDraweeView.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:614)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
```

**Comment by oprisnik** [comment]
Looks like largeHeap fixed this issue.

**Comment by ishaan-khan** [comment]
I don't think using largeHeap=true is a solution is it?

**Comment by hljstardust** [comment]
i also think so
