### ISSUE TITLE
DiskStorageCache.evictAboveSize produces OOM

### ISSUE THREAD

**Issue by arge128** [facebook/fresco#1467]
please fix,stack traces are as follows:
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 32780 byte allocation with 16777120 free bytes and 98MB until OOM; failed due to fragmentation (required continguous free 36864 bytes where largest contiguous free 32768 bytes)
       at java.util.HashMap.makeTable(HashMap.java:550)
       at java.util.HashMap.(HashMap.java)
       at java.util.HashMap.(HashMap.java)
       at android.app.SharedPreferencesImpl$EditorImpl.commitToMemory(SharedPreferencesImpl.java:399)
       at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:359)
       at com.facebook.cache.disk.DiskStorageCacheUtil.deleteDiskCacheEntry(SourceFile:42)
       at com.facebook.cache.disk.DiskStorageCache.removeKeyFromIndex(SourceFile:835)
       at com.facebook.cache.disk.DiskStorageCache.removeValueFromIndex(SourceFile:842)
       at com.facebook.cache.disk.DiskStorageCache.evictAboveSize(SourceFile:537)
       at com.facebook.cache.disk.DiskStorageCache.maybeEvictFilesInCacheDir(SourceFile:505)
       at com.facebook.cache.disk.DiskStorageCache.startInsert(SourceFile:343)
       at com.facebook.cache.disk.DiskStorageCache.insert(SourceFile:383)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.writeToDiskCache(SourceFile:364)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.access$100(SourceFile:38)
       at com.facebook.imagepipeline.cache.BufferedDiskCache$3.run(SourceFile:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by oprisnik** [comment]
Please take a look at the other OOM issues. We need more information about the image type, size, how many, how you use Fresco, configuration etc.

https://github.com/facebook/fresco/issues?utf8=%E2%9C%93&q=is%3Aissue%20OOM

**Comment by arge128** [comment]
sorry, it seems there is a fix in 0.13.0

**Comment by oprisnik** [comment]
Good to hear that :)
