### ISSUE TITLE
Strange transcoder error: java.lang.RuntimeException: Bogus Huffman table definition

### ISSUE THREAD

**Issue by jobpav1984** [facebook/fresco#1470]
I create custom view with MultiDraweeHolder. In this view I have the custom logic for drawing several images. Main big image and two rows below whith preview, but some images take this stack:
`java.lang.RuntimeException: Bogus Huffman table definition
                                                                            at com.facebook.imagepipeline.nativecode.JpegTranscoder.nativeTranscodeJpeg(Native Method)
                                                                            at com.facebook.imagepipeline.nativecode.JpegTranscoder.transcodeJpeg(JpegTranscoder.java:66)
                                                                            at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.doTransform(ResizeAndRotateProducer.java:154)
                                                                            at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.access$000(ResizeAndRotateProducer.java:72)
                                                                            at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer$1.run(ResizeAndRotateProducer.java:89)
                                                                            at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                                                                            at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                                                                            at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                                            at java.lang.Thread.run(Thread.java:818)`
Image for example: http://mobs.mail.ru/pthumb/2442026b434dd1533aa66027adf1bd73/r/-x-/news/pic/91/53/image403989_68937dd070195913eb586485d90dcb8e.jpg

Please, help me! Thanx!
PS: there is my custom views implementation.
[GalleriesArticleView.txt](https://github.com/facebook/fresco/files/479532/GalleriesArticleView.txt)

**Comment by lambdapioneer** [comment]
Hi @jobpav1984 , from the error message this looks like the JpegTranscoder that Fresco is using has a problem while resizing the file. Unfortunately, I cannot reproduce this error using the provided image in our sample apps.

The message you are seeing can be an indicator that the file was not fetched completely or was corrupted during transport.

Can you provide me details on the following questions:
 - Which version of Fresco are you using?
 - Does the bug reproduce consistently? (i.e. are always the same images failing)
 - Do you use a custom network fetcher?
 - Does the bug reproduce when you store the file on the device and replace the uri with `Uri.parse("file:///path/to/the/image.jpg")`?

**Comment by jobpav1984** [comment]
Hi @lambdapioneer 
I use fresco 0.13.0 .
I use this view in RecyclerView. Bug reproduce consistently,  but not always are the same images failing.  
I use default network fetcher
Bug not reproduce when I store the file on the device and replace the uri with filepath

**Comment by jobpav1984** [comment]
this is FLog from device.
[fresco_log.txt](https://github.com/facebook/fresco/files/480121/fresco_log.txt)

**Comment by lambdapioneer** [comment]
I've tried the URL in our `scroll_perf` sample app (with resizing) and everything seems to work fine. I'm getting a 415 by the server sometimes though, but that's something that I also see in my browser.

Can you try out the following to help me debug this:
 - Add logging for image requests and repost the FLog. The current one does not have the exceptions in it. See code below for the necessary changes to your image pipeline configuration
 - What does your current ImagePipelineConfig look like?
 - Use the OkHttp3 network fetcher: http://frescolib.org/docs/using-other-network-layers.html

```
FLog.setMinimumLoggingLevel(FLog.VERBOSE);
Set<RequestListener> requestListeners = new HashSet<>(1);
requestListeners.add(new RequestLoggingListener());
ImagePipelineConfig imagePipelineConfig = ImagePipelineConfig.newBuilder(this)
    /** you probably have your own settings here */
    .setRequestListeners(s)
```

**Comment by jobpav1984** [comment]
I think this happens when I try loading in my class 7 images with equal resolution. Now I load images with lower resolution and bug not happen.
