### ISSUE TITLE
Compilation Error with 0.14.0

### ISSUE THREAD

**Issue by bluef** [facebook/fresco#1478]
Hi I just try to upgrade our fresco lib from 0.13.0 to 0.14.0 to use the new PlatformBitmapFactory, but I got these compilation errors

```
:app:transformClassesWithDexForChinaDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForChinaDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexForChinaDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted
        at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:54)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:158)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more
Caused by: com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted
        at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:443)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:178)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:174)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        ... 22 more
Caused by: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted
        at com.android.builder.core.DexByteCodeConverter.dexInProcess(DexByteCodeConverter.java:179)
        at com.android.builder.core.DexByteCodeConverter.runDexer(DexByteCodeConverter.java:157)
        at com.android.builder.core.DexByteCodeConverter.convertByteCode(DexByteCodeConverter.java:146)
        at com.android.builder.core.AndroidBuilder.convertByteCode(AndroidBuilder.java:1422)
        at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:272)
        ... 25 more
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted
        at com.android.builder.core.DexByteCodeConverter.dexInProcess(DexByteCodeConverter.java:177)
        ... 29 more
Caused by: java.lang.RuntimeException: Translation has been interrupted
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:631)
        at com.android.dx.command.dexer.Main.runMultiDex(Main.java:376)
        at com.android.dx.command.dexer.Main.run(Main.java:290)
        at com.android.builder.internal.compiler.DexWrapper.run(DexWrapper.java:54)
        at com.android.builder.core.DexByteCodeConverter.lambda$dexInProcess$0(DexByteCodeConverter.java:173)
Caused by: java.lang.InterruptedException: Too many errors
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:623)
        ... 4 more


BUILD FAILED
```

0.13.0 works perfectly.

**Comment by kirwan** [comment]
Your build has failed during Proguard. A quick Google search suggests this is due to [duplicate class definitions](http://stackoverflow.com/questions/35092586/exception-while-dexing-files-translation-has-been-interrupted).

The first thing that occurs to me is that we've [updated the support library version to 24.2.1](https://github.com/facebook/fresco/blob/master/gradle.properties#L42). You may need to upgrade your support lib dependency too.

If that doesn't fix it, please check your other dependencies and see what might be out of sync.

**Comment by raylee4204** [comment]
@kirwan 
Is there any way to use an older version of support lib?

I'm waiting until other bugs get fixed in the support lib so currently still using 24.1.1. Due to this, I can't upgrade Fresco to 0.14 anymore

**Comment by kirwan** [comment]
You can certainly fork Fresco and modify your fork to achieve that. Otherwise I'm afraid you may have to stick with 0.13.0 until you can upgrade.

If you have further questions, comment here and I can reopen the issue.

**Comment by bluef** [comment]
and I figure out how to upgrade to 0.14.x without upgrading support library. The key is class duplication, which was introduce from support-v4 24.2.0 and the split of support-v4. So those new dependency could be excluded with the script like this

```
compile('com.facebook.fresco:fresco:0.14.1') {
    exclude group: 'com.android.support', module: 'support-annotations'
    exclude group: 'com.android.support', module: 'support-compat'
    exclude group: 'com.android.support', module: 'support-core-utils'
}
```

**Comment by kirwan** [comment]
I'm happy if this has helped you. We have a plan for how to avoid clashes due to support library versioning (Fresco uses very little of the support library).

That will be included in the next release.
