### ISSUE TITLE
illegal rotation angle caused exception with default RotationOptions 

### ISSUE THREAD

**Issue by victorxxie** [facebook/fresco#1482]
Recently the library in our project is upgraded to 0.14.0, sometimes get the following exception:

E/unknown:TransformingConsumer: unhandled exception
                                                                               java.lang.IllegalArgumentException
                                                                                   at com.facebook.common.internal.Preconditions.checkArgument(Preconditions.java:108)
                                                                                   at com.facebook.imagepipeline.producers.ResizeAndRotateProducer.getRotationAngle(ResizeAndRotateProducer.java:288)
                                                                                   at com.facebook.imagepipeline.producers.ResizeAndRotateProducer.shouldRotate(ResizeAndRotateProducer.java:301)
                                                                                   at com.facebook.imagepipeline.producers.ResizeAndRotateProducer.shouldTransform(ResizeAndRotateProducer.java:228)
                                                                                   at com.facebook.imagepipeline.producers.ResizeAndRotateProducer.access$600(ResizeAndRotateProducer.java:43)
                                                                                   at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.onNewResultImpl(ResizeAndRotateProducer.java:128)
                                                                                   at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.onNewResultImpl(ResizeAndRotateProducer.java:76)
                                                                                   at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
                                                                                   at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:48)
                                                                                   at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:32)
                                                                                   at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
                                                                                   at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onNextResult(MultiplexProducer.java:442)
                                                                                   at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:499)
                                                                                   at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:496)
                                                                                   at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
                                                                                   at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$1.onNewResultImpl(EncodedMemoryCacheProducer.java:94)
                                                                                   at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$1.onNewResultImpl(EncodedMemoryCacheProducer.java:89)
                                                                                   at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
                                                                                   at com.facebook.imagepipeline.producers.DiskCacheProducer$DiskCacheConsumer.onNewResultImpl(DiskCacheProducer.java:234)
                                                                                   at com.facebook.imagepipeline.producers.DiskCacheProducer$DiskCacheConsumer.onNewResultImpl(DiskCacheProducer.java:206)
                                                                                   at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
                                                                                   at com.facebook.imagepipeline.producers.NetworkFetchProducer.notifyConsumer(NetworkFetchProducer.java:168)
                                                                                   at com.facebook.imagepipeline.producers.NetworkFetchProducer.maybeHandleIntermediateResult(NetworkFetchProducer.java:145)
                                                                                   at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:104)
                                                                                   at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:37)
                                                                                   at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:72)
                                                                                   at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher.fetchSync(HttpUrlConnectionNetworkFetcher.java:83)
                                                                                   at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher$1.run(HttpUrlConnectionNetworkFetcher.java:61)
                                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                   at java.lang.Thread.run(Thread.java:841)

After debugging the code, found that it caused by the illegal rotation angle (-1, the default value in the EncodedImage).  

For some reason, it failed to decode the dimension information, which means the following expression returns null in the EncodedImage.java
Pair<Integer, Integer> dimensions = BitmapUtil.decodeDimensions(getInputStream());

I think mRotationAngle should be set to Zero in this case, right?

**Comment by johnzheng00** [comment]
The same issue with me

**Comment by kirwan** [comment]
I'm looking into this right now and there's an easy way to stop this happening but I'd like to understand if there's a specific combination of factors which results in the issue as I've not been able to reproduce it myself.

Can you provide a particular image which results in this error? It would be useful to know whether you have any changes to the default `ImagePipelineConfig` or `ImageRequest` too.

**Comment by kirwan** [comment]
This should be fixed by 573986ac0530300a42941534898b534234745c24.

I'd still be interested in knowing specifics of an image that reproduces this issue if it's possible to share one.

**Comment by victorxxie** [comment]
@kirwan, if I remembered, <a href="http://7xjqxd.com1.z0.glb.clouddn.com/image/201609/27/51091ebcf76d07f88ca20bf9832aa682.jpg">this picture</a> has the problem

And this is the request code in our project:

            ImageRequest request = ImageRequestBuilder.newBuilderWithSource(Uri.parse(url))
                    .setProgressiveRenderingEnabled(true)
                    .setRotationOptions(RotationOptions.forceRotation(RotationOptions.NO_ROTATION))
                    .build();
            DraweeController controller = Fresco.newDraweeControllerBuilder()
                    .setImageRequest(request)
                    .setOldController(view.getController())
                    .setRetainImageOnFailure(true)
                    .setAutoPlayAnimations(true)
                    .build();
            view.setController(controller);

For ImagePipelineConfig, only the memory configuration is changed.

**Comment by kirwan** [comment]
Thanks @victorxxie, that's enabled me to verify the original cause and the fix.

The image you sent me isn't progressive and that's what showed the bug. If a non-progressive JPEG comes through for a request where progressive rendering is turned on, the dimensions can't be loaded and the error occurred.

It is fixed by my change. We'll discuss whether it's necessary to push out a patch release now this is fixed.
