### ISSUE TITLE
java.lang.ClassCastException: com.facebook.drawee.view.SimpleDraweeView cannot be cast to com.facebook.drawee.view.SimpleDraweeView

### ISSUE THREAD

**Issue by maikoulin** [facebook/fresco#1496]
java.lang.ClassCastException: com.facebook.drawee.view.SimpleDraweeView cannot be cast to com.facebook.drawee.view.SimpleDraweeView
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5025)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:603)
                                                                     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:136)
                                                                     at dalvik.system.NativeStart.main(Native Method)
                                                                  Caused by: java.lang.ClassCastException: com.facebook.drawee.view.SimpleDraweeView cannot be cast to com.facebook.drawee.view.SimpleDraweeView
                                                                     at com.chinanetcenter.appmarket.LoadActivity.c(Unknown Source)
                                                                     at com.chinanetcenter.appmarket.LoadActivity.onCreate(Unknown Source)
                                                                     at android.app.Activity.performCreate(Activity.java:5258)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1101)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)?
                                                                     at android.app.ActivityThread.access$800(ActivityThread.java:135)?
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)?
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)?
                                                                     at android.os.Looper.loop(Looper.java:136)?
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5025)?
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)?
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)?
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)?
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:603)?
                                                                     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:136)?
                                                                     at dalvik.system.NativeStart.main(Native Method)?

**Comment by oprisnik** [comment]
How do yo use Fresco? XML, Java? Did you follow all setup steps? Could the Xposed framework be a problem?

**Comment by oprisnik** [comment]
I assume the problem has been resolved. Please let us know if you're still experiencing this issue.
