### ISSUE TITLE
OOM Error even with (relatively) small, resized, and downsampled JPGs in RecyclerView

### ISSUE THREAD

**Issue by Byte-Sized** [facebook/fresco#1520]
In my activity, I have a single RecyclerView widget that displays an image and text. When users push a button to request more photos, image URLs are fetched asynchronously in batches of 24 at a time (for testing purposes only).

These images are JPGs that are originally 640x 480 pxs in size (these are the smallest high-res photos I can obtain), but the application resizes them down to 320 x 180 pxs (just enough to prevent blurriness). The XML for my ViewHolder contains a  SimpleDraweeView and has the following setup:
```XML
<com.facebook.drawee.view.SimpleDraweeView 
        android:id="@+id/itemholder_thumbnail"
        android:layout_width="120dp"
        android:layout_height="wrap_content"
        fresco:fadeDuration="300"
        fresco:viewAspectRatio="1.79"/>
```

In my RecyclerView Adapter class I have an inner class for my ViewHolder. I have a method `bindData(ItemModel item)` that binds the data to the ViewHolders SimpleDraweeView, `itemThumbnail`,and TextView (not shown) :
```java
    Uri uri = Uri.parse(item.getThumbnailURL());
    ImageRequestBuilder request = ImageRequestBuilder.newBuilderWithSource(uri);
    request.setResizeOptions(new ResizeOptions(320,180));
    request.setProgressiveRenderingEnabled(true);

    DraweeController controller = Fresco.newDraweeControllerBuilder()
                    .setImageRequest(request.build())
                    .setOldController(itemThumbnail.getController())
                    .build();
    itemThumbnail.setController(controller);
```

And my Adapter keeps a running list of my ItemModels like this:
```
private List<VideoItem> videoList;
```

Now, in the Application class, `GlobalState` , I have configured the ImagePipeline and initialized Fresco as follows. I researched several closed bug reports and the Fresco Docs that suggested [ to implement a MemoryTrimmableInterface](http://frescolib.org/docs/configure-image-pipeline.html) and made attempts to do that:
```java

public class GlobalState extends Application {
    private List<MemoryTrimmable> trimmables = new ArrayList<>();

    @Override
    public void onCreate() {
        super.onCreate();

        ImagePipelineConfig config = ImagePipelineConfig.newBuilder(this)
                .setDownsampleEnabled(true)
                .setMemoryTrimmableRegistry(new MemoryTrimmableRegistry() {

                    @Override
                    public void registerMemoryTrimmable(MemoryTrimmable trimmable) {
                       trimmables.add(trimmable);
                       Log.d("Global State : ", " Trimmables Size = " + trimmables.size());
                    }

                    @Override
                    public void unregisterMemoryTrimmable(MemoryTrimmable trimmable) {}
                })
                .build();
        Fresco.initialize(this, config);
    }

    @Override
    public void onTrimMemory(int level) {
        /*if (level >= TRIM_MEMORY_MODERATE){
            Fresco.getImagePipelineFactory().getEncodedCountingMemoryCache().clear();
            Fresco.getImagePipelineFactory().getBitmapCountingMemoryCache().clear();
        }*/

        if (!trimmables.isEmpty()) {
            for (MemoryTrimmable t : trimmables) {
                Log.d(Config.DEBUG_APPLICATION, "Trimmable = " + t);
                // t.trim(MemoryTrimType.OnCloseToDalvikHeapLimit);
                t.trim(MemoryTrimType.OnSystemLowMemoryWhileAppInForeground);
            }

            //Fresco.getImagePipeline().clearDiskCaches();
            //Fresco.getImagePipeline().clearCaches();
            super.onTrimMemory(level);
        }
    }
```

**Problem:**
Now if I run my application, the RecyclerView loads the ViewHolders and displays the images relatively quickly. Once 200 images have loaded, I noticed the RecyclerView scrolling becomes a bit slow. However, every time I reach ViewHolder position 300 or more my application crashes with an OOM error:
```
0-31 14:06:01.470 4006-4776/bytesized_productproject.productproject E/art: Throwing OutOfMemoryError "Failed to allocate a 307212 byte allocation with 152872 free bytes and 149KB until OOM"
10-31 14:06:01.580 4006-4776/bytesized_productproject.productproject E/AndroidRuntime: FATAL EXCEPTION: Thread-492
                                                                               Process: bytesized_productproject.productproject, PID: 4006
                                                                               java.lang.OutOfMemoryError: Failed to allocate a 307212 byte allocation with 152872 free bytes and 149KB until OOM
                                                                                   at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                                   at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                                   at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
                                                                                   at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
                                                                                   at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
                                                                                   at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
                                                                                   at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
                                                                                   at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
                                                                                   at com.facebook.imagepipeline.platform.ArtDecoder.decodeStaticImageFromStream(ArtDecoder.java:137)
                                                                                   at com.facebook.imagepipeline.platform.ArtDecoder.decodeJPEGFromEncodedImage(ArtDecoder.java:120)
                                                                                   at com.facebook.imagepipeline.decoder.ImageDecoder.decodeJpeg(ImageDecoder.java:149)
                                                                                   at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:82)
                                                                                   at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:194)
                                                                                   at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:97)
                                                                                   at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:129)
                                                                                   at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                                                                                   at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                                                                                   at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                   at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                                                   at java.lang.Thread.run(Thread.java:818)
10-31 14:06:01.650 4006-4775/bytesized_productproject.productproject E/art: Throwing OutOfMemoryError "Failed to allocate a 307212 byte allocation with 160184 free bytes and 156KB until OOM"
```

And just prior in my logcat I notice this:
```
10-31 14:12:07.677 27718-27725/bytesized_productproject.productproject A/art: art/runtime/runtime.cc:284] "HeapTrimmerDaemon" prio=5 tid=8 Waiting
10-31 14:12:07.677 27718-27725/bytesized_productproject.productproject A/art: art/runtime/runtime.cc:284]   - waiting on <0x1d6edc75> (a java.lang.Daemons$HeapTrimmerDaemon)
10-31 14:12:07.677 27718-27725/bytesized_productproject.productproject A/art: art/runtime/runtime.cc:284]   at java.lang.Daemons$HeapTrimmerDaemon.run(Daemons.java:314)
10-31 14:12:07.677 27718-27725/bytesized_productproject.productproject A/art: art/runtime/runtime.cc:284]   - locked <0x1d6edc75> (a java.lang.Daemons$HeapTrimmerDaemon)
```

Is there anyway to resolve this? I was hoping I could release SimpleDraweeViews that I have already surpassed in the RecyclerView (Because they aren't being shown anyway) to free up some memory space, but I am not sure how to do this. Or if there is a better method to handling this type of scenario.

@oprisnik or @kirwan (who I have seen responding to these type of issues) - any tips?

Thank You :)

**Comment by Byte-Sized** [comment]
Nobody has any idea?

**Comment by oprisnik** [comment]
I guess the issue is that you hold on to all images with `private List<MemoryTrimmable> trimmables = new ArrayList<>();`. Hence, Fresco cannot correctly clear the caches and at some point there will be no more memory left.

What exactly do you want to achieve with your code?

**Comment by oprisnik** [comment]
Does the issue still repro if you try removing either downsampling or the `MemoryTrimmableRegistry`?

**Comment by erikandre** [comment]
Closing as there was no response from the original poster
