### ISSUE TITLE
 java.lang.NoSuchMethodError: android.os.StatFs.getBlockSizeLong in Android 4.3 operating system oppo brand mobile phone

### ISSUE THREAD

**Issue by xiaoyao27610** [facebook/fresco#1539]
fresco 0.14.1:in Android 4.3 operating system oppo brand mobile phone
java.lang.NoSuchMethodError: android.os.StatFs.getBlockSizeLong
at com.facebook.common.statfs.StatFsHelper.getAvailableStorageSpace(StatFsHelper.java:137)
at com.facebook.common.statfs.StatFsHelper.testLowDiskSpace(StatFsHelper.java:114)
at com.facebook.cache.disk.DiskStorageCache.updateFileCacheSizeLimit(DiskStorageCache.java:584)
at com.facebook.cache.disk.DiskStorageCache.maybeEvictFilesInCacheDir(DiskStorageCache.java:485)
at com.facebook.cache.disk.DiskStorageCache.startInsert(DiskStorageCache.java:342)
at com.facebook.cache.disk.DiskStorageCache.insert(DiskStorageCache.java:377)
at com.facebook.imagepipeline.cache.BufferedDiskCache.writeToDiskCache(BufferedDiskCache.java:364)
at com.facebook.imagepipeline.cache.BufferedDiskCache.access$500(BufferedDiskCache.java:38)
at com.facebook.imagepipeline.cache.BufferedDiskCache$3.run(BufferedDiskCache.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:838)

**Comment by lambdapioneer** [comment]
Hi @xiaoyao27610, thanks for the bug report. As the method appears to be correctly gated to switch behavior depending on the phones API level, I suspect this might be device/model specific.

Can you provide me with the concrete model number? Does this reproduce consistently on that phone?

**Comment by erikandre** [comment]
Additional details needed but no response from submitter
