### ISSUE TITLE
java.lang.NoSuchMethodError: no static or non-static method "Lcom/facebook/imagepipeline/nativecode/WebpTranscoder;.nativeTranscodeWebpToJpeg(Ljava/io/InputStream;Ljava/io/OutputStream;I)V"

### ISSUE THREAD

**Issue by lph2012** [facebook/fresco#1568]
12-06 11:13:27.175 1257-1300/com.dy.dyth E/dalvikvm: Requested: Lcom/facebook/imagepipeline/nativecode/WebpTranscoder;.nativeTranscodeWebpToJpeg:(Ljava/io/InputStream;Ljava/io/OutputStream;I)V
12-06 11:13:27.175 1257-1300/com.dy.dyth E/libimagepipeline: could not register WebpTranscoder methods
12-06 11:13:27.175 1257-1300/com.dy.dyth E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                           Process: com.dy.dyth, PID: 1257
                                                           java.lang.NoSuchMethodError: no static or non-static method "Lcom/facebook/imagepipeline/nativecode/WebpTranscoder;.nativeTranscodeWebpToJpeg(Ljava/io/InputStream;Ljava/io/OutputStream;I)V"
                                                               at java.lang.Runtime.nativeLoad(Native Method)
                                                               at java.lang.Runtime.doLoad(Runtime.java:421)
                                                               at java.lang.Runtime.loadLibrary(Runtime.java:362)
                                                               at java.lang.System.loadLibrary(System.java:526)
                                                               at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
                                                               at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
                                                               at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:43)
                                                               at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:36)
                                                               at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
                                                               at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
                                                               at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
                                                               at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
                                                               at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:141)
                                                               at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:26)
                                                               at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:94)
                                                               at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:37)
                                                               at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:72)
                                                               at com.facebook.imagepipeline.backends.okhttp3.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:122)
                                                               at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
                                                               at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                               at java.lang.Thread.run(Thread.java:841)
12-06 11:13:27.335 417-463/system_process E/InputDispatcher: channel '422bb350 com.dy.dyth/com.dy.dyth.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by lph2012** [comment]
When I put the my apk on the  / system / app directory, and then start the app, it will crash. If it is a normal application installation, the program can run successfully.please help me.

**Comment by lph2012** [comment]
I copied "libimagepipeline.so" file to /system/lib directory ,solved my problem.
