### ISSUE TITLE
Webp Animation OOM on 5.0+

### ISSUE THREAD

**Issue by simple-jie** [facebook/fresco#1569]
I have 4 WebP animation，and I played them in a SimpleDraweeView circularly.
The Webp pixel is 480 * 850, because it's a full screen Animation.
like this  https://d.rings.me/gift/super/islands_480.webp

Code
```
PipelineDraweeControllerBuilder builder = Fresco.newDraweeControllerBuilder()
                .setUri(url)
                .setAutoPlayAnimations(true)
                .setOldController(view.getController())
                .setControllerListener(listener);

        view.setController(builder.build());
```

before start next, i try to release the old one
```
if (animatable != null) 
{
      animatable.stop();
}
Fresco.getImagePipeline().evictFromMemoryCache(Uri.parse(url));

startNext();
```

MemoryCacheParams
````
new MemoryCacheParams(
                (int) Runtime.getRuntime().maxMemory() / 4,
                Integer.MAX_VALUE,
                getMaxCacheSize(),
                Integer.MAX_VALUE,
                Integer.MAX_VALUE);
````

THE MEMORY KEEP INCREASE.
About half an hour,  OOM will occur

track
```
java.lang.OutOfMemoryError: Failed to allocate a 1639692 byte allocation with 1140520 free bytes and 1113KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:975)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:913)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.createNewBitmap(AnimatedDrawableCachingBackendImpl.java:149)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.obtainBitmapInternal(AnimatedDrawableCachingBackendImpl.java:342)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.runPrefetch(AnimatedDrawableCachingBackendImpl.java:452)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.access$200(AnimatedDrawableCachingBackendImpl.java:53)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl$3.call(AnimatedDrawableCachingBackendImpl.java:412)
	at bolts.Task$4.run(Task.java:357)
	at com.facebook.common.executors.ConstrainedExecutorService$Worker.run(ConstrainedExecutorService.java:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by oprisnik** [comment]
You should not need to do `Fresco.getImagePipeline().evictFromMemoryCache(Uri.parse(url));`. Fresco handles everything for you.

What does `startNext()` do? You have to make sure that you correctly release the previous animation so that the memory can be freed. If anything still holds on to the image, Fresco can't release all resources.
Do you have 1 DraweeView where you change the URI? Multiple DraweeViews?

**Comment by simple-jie** [comment]
I only have one DraweeView.

```
public void onFinalImageSet(String id, @Nullable ImageInfo imageInfo, @Nullable final Animatable animatable) {
                        if (animatable instanceof AbstractAnimatedDrawable) { //load success
                            AbstractAnimatedDrawable animatedDrawable = (AbstractAnimatedDrawable) animatable;
                            int animationDuration = animatedDrawable.getDuration();

                           
                            //auto stop or next, a delay task
                            new KTask(new ITaskHandler() {
                                @Override
                                public void handlerTask(int msg, int arg1, int arg2, Object obj) {
                                    if (animatable != null) { 
                                        animatable.stop(); //release the previous animation, do I right?
                                    } 
                                    Fresco.getImagePipeline().evictFromMemoryCache(Uri.parse(giftMessage.getGiftObject().getValidImageUrl()));
                                    startNext();
                                }
                            }).PostToUI(null, animationDuration + 100);
                        }
                    }
```

and startNext(), i reuse the DraweeView, and set DraweeController to play next animation
```
PipelineDraweeControllerBuilder builder = Fresco.newDraweeControllerBuilder()
                .setUri(url)
                .setAutoPlayAnimations(true)
                .setOldController(view.getController())
                .setControllerListener(listener);

        view.setController(builder.build());
```

**Comment by simple-jie** [comment]
I only hold a DraweeView.

**Comment by simple-jie** [comment]
Hi! @oprisnik can you help me

**Comment by simple-jie** [comment]
@oprisnik Hello! I need help

**Comment by oprisnik** [comment]
Can you create a minimal example that reproduces the issue? Judging from your code this should be just 1 drawee view and a listener with `onFinalImageSet` where you load the next animation after some time.

**Comment by oprisnik** [comment]
I assume the problem has been resolved. If not, please let us know.
