### ISSUE TITLE
java.lang.UnsatisfiedLinkError: on android oppo r8207/r8205  4.4.4 operating system

### ISSUE THREAD

**Issue by xiaoyao27610** [facebook/fresco#1572]
java.lang.UnsatisfiedLinkError: Native method not found: com.facebook.imagepipeline.memory.NativeMemoryChunk.nativeAllocate:(I)J
	at com.facebook.imagepipeline.memory.NativeMemoryChunk.nativeAllocate(NativeMemoryChunk.java)
	at com.facebook.imagepipeline.memory.NativeMemoryChunk.<init>(NativeMemoryChunk.java:58)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:98)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
	at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:338)
	at com.facebook.imagepipeline.cache.BufferedDiskCache.access$400(BufferedDiskCache.java:38)
	at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:184)
	at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:168)
	at bolts.Task$4.run(Task.java:357)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

**Comment by oprisnik** [comment]
Please take a look at #1552. Using SoLoader / ReLinker should help here.
