### ISSUE TITLE
UnsatisfiedLinkError when load gif

### ISSUE THREAD

**Issue by linchaolong** [facebook/fresco#1576]
E/art: No implementation found for com.facebook.animated.gif.GifImage com.facebook.animated.gif.GifImage.nativeCreateFromNativeMemory(long, int) (tried Java_com_facebook_animated_gif_GifImage_nativeCreateFromNativeMemory and Java_com_facebook_animated_gif_GifImage_nativeCreateFromNativeMemory__JI)
E/AndroidRuntime: FATAL EXCEPTION: Thread-3090
     Process: com.linchaolong.android.app, PID: 25275
     java.lang.UnsatisfiedLinkError: No implementation found for com.facebook.animated.gif.GifImage com.facebook.animated.gif.GifImage.nativeCreateFromNativeMemory(long, int) (tried Java_com_facebook_animated_gif_GifImage_nativeCreateFromNativeMemory and Java_com_facebook_animated_gif_GifImage_nativeCreateFromNativeMemory__JI)
         at com.facebook.animated.gif.GifImage.nativeCreateFromNativeMemory(Native Method)
         at com.facebook.animated.gif.GifImage.create(GifImage.java:70)
         at com.facebook.animated.gif.GifImage.decode(GifImage.java:75)
         at com.facebook.imagepipeline.animated.factory.AnimatedImageFactoryImpl.decodeGif(AnimatedImageFactoryImpl.java:85)
         at com.facebook.imagepipeline.decoder.ImageDecoder.decodeGif(ImageDecoder.java:110)
         at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:84)
         at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:194)
         at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:97)
         at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:129)
         at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
         at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
         at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
         at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
         at java.lang.Thread.run(Thread.java:818)
E/CRASHLOG: CRASH   35fa863dadcbb47453b0  2016-12-14/18:06:41  JAVACRASH /data/logs/crashlog2
E/InputDispatcher: channel '1fd181e6 com.linchaolong.android.app/com.linchaolong.android.app.home.HomeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by linchaolong** [comment]
my app build.gradle config:
`
  compile "com.facebook.fresco:fresco:${fresco}"
  compile "com.facebook.fresco:imagepipeline-okhttp3:${fresco}"
  compile "com.facebook.fresco:animated-gif:${fresco}"
`
fresco = '0.14.1'

**Comment by linchaolong** [comment]
code：
    DraweeController controller = Fresco.newDraweeControllerBuilder()
        .setUri(uri)
        .setAutoPlayAnimations(true)
        .build();
    draweeView.setController(controller);

**Comment by oprisnik** [comment]
Does it work if you manually add `compile "com.facebook.fresco:animated-base:${fresco}"` ?

**Comment by linchaolong** [comment]
I am update build.gradle as follow ,  but did not solve the problem：
  compile "com.facebook.fresco:fresco:${fresco}"
  compile "com.facebook.fresco:imagepipeline-okhttp3:${fresco}"
  compile "com.facebook.fresco:animated-base:${fresco}"
  compile "com.facebook.fresco:animated-base-support:${fresco}"
  compile "com.facebook.fresco:animated-gif:${fresco}"

**Comment by oprisnik** [comment]
Can you take a look and see if the suggestions in #1552 fix the issue? If not, what's your Fresco version?

**Comment by linchaolong** [comment]
I added the following code to solve the problem, thank you , Fresco version is 0.14.1. @oprisnik  

  static {
    try {
      SoLoaderShim.loadLibrary("gifimage");
    } catch(UnsatisfiedLinkError e) {
      e.printStackTrace();
    }
  }

compile 'com.facebook.soloader:soloader:0.1.0'

**Comment by oprisnik** [comment]
Glad to hear that you've resolved the issue.
