### ISSUE TITLE
DiskCacheCofig

### ISSUE THREAD

**Issue by Christain** [facebook/fresco#158]
I use

    DiskCacheConfig diskCacheConfig = 
        DiskCacheConfig.newBuilder().setBaseDirectoryPath(file).build();

in Application.class, always crash:

    Caused by: java.lang.NullPointerException
            at com.facebook.common.internal.Preconditions.checkNotNull(Preconditions.java:210)
            at com.facebook.cache.disk.DiskCacheConfig.<init>(DiskCacheConfig.java:42)
            at com.facebook.cache.disk.DiskCacheConfig.<init>(DiskCacheConfig.java:28)
            at com.facebook.cache.disk.DiskCacheConfig$Builder.build(DiskCacheConfig.java:205)

**Comment by pedant** [comment]
you should set value with builder like this:
```JAVA
DiskCacheConfig.newBuilder()
.setBaseDirectoryName("image_cache")
.setBaseDirectoryPath(file)
.build();
```

**Comment by tyronen** [comment]
@pedant is correct. BaseDirectoryName is a mandatory parameter. 

We should probably add string-comments to all the preconditions.
