### ISSUE TITLE
ANR setPlaceholderImage

### ISSUE THREAD

**Issue by maikoulin** [facebook/fresco#1583]
DALVIK THREADS:
(mutexes: tll=0 tsl=0 tscl=0 ghl=2)
"main" prio=5 tid=1 SUSPENDED
  | group="main" sCount=1 dsCount=0 obj=0x40f94460 self=0x129a0
  | sysTid=1730 nice=0 sched=0/0 cgrp=default handle=1074082952
  | schedstat=( 0 0 0 ) utm=1991 stm=235 core=0
  at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
  at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:488)
  at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:356)
  at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:773)
  at android.content.res.Resources.loadDrawable(Resources.java:1935)
  at android.content.res.Resources.getDrawable(Resources.java:664)
  at com.facebook.drawee.generic.GenericDraweeHierarchy.setPlaceholderImage(GenericDraweeHierarchy.java:446)
  at com.chinanetcenter.appmarket.AppDetailActivity.setDraweeHierarchy(AppDetailActivity.java:176)

**Comment by oprisnik** [comment]
Do other placeholder images work? Can you set the same image as a background for any view (or for an ImageView). How big is the placeholder? What imagme format etc.?
