### ISSUE TITLE
Latest version loading local GIF problem.

### ISSUE THREAD

**Issue by LucianWang** [facebook/fresco#1591]
I would like to ask the use of version 1.0.0 fresco loading local GIF why no effect? Has been added'com.facebook.fresco:webpsupport:0.12.0'. please give me a viable solution. Thank you very much.
My code:
View v = LayoutInflater.from (context).Inflate (R.layout.widget_r_player, this, true);
Uri URI = Uri.parse ("android.resource://" +context.getPackageName () + "/" +R.drawable.loading_player_cache);
SimpleDraweeView smallLabel = (SimpleDraweeView) v.findViewById (R.id.smallLabel);
AbstractDraweeController build = Fresco.newDraweeControllerBuilder ().SetAutoPlayAnimations (true).SetUri (URI)
.build ();
SmallLabel.setController (build);

**Comment by lambdapioneer** [comment]
Hi @LucianWang, the URI seems wrong. The correct one is of the format `Uri:///{resource_id}`. You can use `uri = UriUtil.getUriForResourceId(R.drawable.loading_player_cache)` in order to create the correct URI.

**Comment by LucianWang** [comment]
I have encountered such a problem
java.lang.NoSuchFieldError: No instance field forceOldAnimationCode of type Z in class Lcom/facebook/imagepipeline/common/ImageDecodeOptions; or its superclasses (declaration of 'com.facebook.imagepipeline.common.ImageDecodeOptions' appears in /data/data/readtv.ghs.tv/files/instant-run/dex/slice-com.facebook.fresco-imagepipeline-base-1.0.0_805d808bbc546341902d6f05b203ea4b3ada16f6-classes.dex)
                                                                   at com.facebook.imagepipeline.animated.factory.AnimatedImageFactoryImpl.decodeGif(AnimatedImageFactoryImpl.java:84)
                                                                   at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeGif(DefaultImageDecoder.java:142)
                                                                   at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:65)
                                                                   at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:123)
                                                                   at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:239)
                                                                   at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:111)
                                                                   at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:144)
                                                                   at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                                                                   at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                                                                   at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                   at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                                   at java.lang.Thread.run(Thread.java:818)

**Comment by LucianWang** [comment]
I'm sorry to have this problem again.
java.lang.NoSuchFieldError: No instance field forceOldAnimationCode of type Z in class Lcom/facebook/imagepipeline/common/ImageDecodeOptions; or its superclasses (declaration of 'com.facebook.imagepipeline.common.ImageDecodeOptions' appears in /data/app/readtv.ghs.tv-1/base.apk)
                                                     at com.facebook.imagepipeline.animated.factory.AnimatedImageFactoryImpl.decodeGif(AnimatedImageFactoryImpl.java:84)
                                                     at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeGif(DefaultImageDecoder.java:142)
                                                     at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:65)
                                                     at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:123)
                                                     at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:239)
                                                     at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:111)
                                                     at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:144)
                                                     at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                                                     at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                                                     at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                     at java.lang.Thread.run(Thread.java:818)

**Comment by LucianWang** [comment]
Has been solved. Thank you very much for your answer.
