### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'com.facebook.common.references.CloseableReference com.facebook.imagepipeline.cache.MemoryCache.get(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by yan269954107** [facebook/fresco#1597]
java.lang.NullPointerException: Attempt to invoke interface method 'com.facebook.common.references.CloseableReference com.facebook.imagepipeline.cache.MemoryCache.get(java.lang.Object)' on a null object reference
	at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer.produceResults(SourceFile:56)
	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.startInputProducerIfHasAttachedConsumers(SourceFile:336)
	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.access$000(SourceFile:125)
	at com.facebook.imagepipeline.producers.MultiplexProducer.produceResults(SourceFile:87)
	at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer.produceResults(SourceFile:29)
	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer.produceResults(SourceFile:74)
	at com.facebook.imagepipeline.producers.DecodeProducer.produceResults(SourceFile:94)
	at com.facebook.imagepipeline.producers.BitmapMemoryCacheProducer.produceResults(SourceFile:94)
	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.startInputProducerIfHasAttachedConsumers(SourceFile:336)
	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.access$000(SourceFile:125)
	at com.facebook.imagepipeline.producers.MultiplexProducer.produceResults(SourceFile:87)
	at com.facebook.imagepipeline.producers.ThreadHandoffProducer$1.onSuccess(SourceFile:43)
	at com.facebook.common.executors.StatefulRunnable.run(SourceFile:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(SourceFile:43)
	at java.lang.Thread.run(Thread.java:818)

**Comment by oprisnik** [comment]
When does this happen? How do you use Fresco? Did you call `Fresco.intialize`?

It looks like your encoded memory cache is null. Do you set custom cache parameters?

**Comment by erikandre** [comment]
Closing as the poster did not provide additional details that we need to proceed with any investigation.
