### ISSUE TITLE
 no static or non-static method WebpTranscoder;.nativeTranscodeWebpToJpeg

### ISSUE THREAD

**Issue by droidwolf** [facebook/fresco#1617]
Fatal Exception: java.lang.NoSuchMethodError: no static or non-static method "Lcom/facebook/imagepipeline/nativecode/WebpTranscoder;.nativeTranscodeWebpToJpeg(Ljava/io/InputStream;Ljava/io/OutputStream;I)V"
       at java.lang.Runtime.nativeLoad(Runtime.java)
       at java.lang.Runtime.doLoad(Runtime.java:421)
       at java.lang.Runtime.loadLibrary(Runtime.java:362)
       at java.lang.System.loadLibrary(System.java:526)
       at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
       at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
       at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:43)
       at com.facebook.imagepipeline.memory.NativeMemoryChunk.(NativeMemoryChunk.java)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.(NativePooledByteBufferOutputStream.java)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:98)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:338)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.access$400(BufferedDiskCache.java:38)
       at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:184)
       at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:168)
       at bolts.Task$4.run(Task.java:357)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

android  Operating Systems 5.1.1、5.0.2

**Comment by foghina** [comment]
Sounds like the native libraries haven't loaded correctly. Do you have a consistent repro? What device are you running on?
