### ISSUE TITLE
applicationContext.getFilesDir().getParent()  java.lang.NullPointerException

### ISSUE THREAD

**Issue by shenrh** [facebook/fresco#1618]
fresco 0.13, I got some crash message:,applicationContext.getFilesDir() return null?
/com/facebook/cache/disk/DiskStorageCache.java  
//TODO(t12287315): Remove the temp method for deleting created Preference in next release
  private static void maybeDeleteSharedPreferencesFile(
      Context context,
      String directoryName) {
    Context applicationContext = context.getApplicationContext();
    String path =
        applicationContext.getFilesDir().getParent() // java.lang.NullPointerException why??
            + File.separator
            + "shared_prefs"
            + File.separator
            + SHARED_PREFS_FILENAME_PREFIX
            + directoryName;
    File file = new File(path + ".xml");
    try {
      if (file.exists()) {
        file.delete();
      }
    } catch (Exception e) {
      FLog.e(TAG, "Fail to delete SharedPreference from file system. ");
    }
  }

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getParent()' on a null object reference
	at com.facebook.cache.disk.DiskStorageCache.maybeDeleteSharedPreferencesFile(SourceFile:782)
	at com.facebook.cache.disk.DiskStorageCache.access$300(SourceFile:50)
	at com.facebook.cache.disk.DiskStorageCache$1.run(SourceFile:193)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.j

**Comment by foghina** [comment]
Can you consistently repro this, or was it a one-off? Also, what device / OS version is this happening on?

**Comment by arso8** [comment]
I also caught this crash, but I haven't steps to reproduce. Nexus 5, 6.0.1. Fresco 1.0

`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getParent()' on a null object reference
                                                     at com.facebook.cache.disk.DiskStorageCache.maybeDeleteSharedPreferencesFile(DiskStorageCache.java:784)
                                                     at com.facebook.cache.disk.DiskStorageCache.access$400(DiskStorageCache.java:48)
                                                     at com.facebook.cache.disk.DiskStorageCache$2.run(DiskStorageCache.java:213)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                     at java.lang.Thread.run(Thread.java:818)`

**Comment by lambdapioneer** [comment]
Thanks @shenrh and @arso8 for the reports!

I've made sure that the code path won't make the app crash (see 72421c33b78db64dc66e1bd75de0f084372f2036). Older Android version seemed to have a RC in the `Context#getFilesDir` method (details in the commit). I don't know exactly what's causing the issue with 6.0.1, but it should be mitigated as well.

This code path is very optional and just does some clean-up of some files used by an older version of the disk cache.
