### ISSUE TITLE
App Crashing (no changes on my part)

### ISSUE THREAD

**Issue by irtefa** [facebook/fresco#164]
java.lang.StringIndexOutOfBoundsException: length=5; regionStart=0; regionLength=30
            at java.lang.String.startEndAndLength(String.java:504)
            at java.lang.String.substring(String.java:1333)
            at com.facebook.imagepipeline.core.ProducerSequenceFactory.getBasicDecodedImageSequence(ProducerSequenceFactory.java:195)
            at com.facebook.imagepipeline.core.ProducerSequenceFactory.getDecodedImageProducerSequence(ProducerSequenceFactory.java:143)
            at com.facebook.imagepipeline.core.ImagePipeline.fetchDecodedImage(ImagePipeline.java:137)
            at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilder.getDataSourceForRequest(PipelineDraweeControllerBuilder.java:82)
            at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilder.getDataSourceForRequest(PipelineDraweeControllerBuilder.java:31)
            at com.facebook.drawee.controller.AbstractDraweeControllerBuilder$2.get(AbstractDraweeControllerBuilder.java:322)
            at com.facebook.drawee.controller.AbstractDraweeControllerBuilder$2.get(AbstractDraweeControllerBuilder.java:319)
            at com.facebook.drawee.backends.pipeline.PipelineDraweeController.getDataSource(PipelineDraweeController.java:96)
            at com.facebook.drawee.controller.AbstractDraweeController.submitRequest(AbstractDraweeController.java:392)
            at com.facebook.drawee.controller.AbstractDraweeController.onAttach(AbstractDraweeController.java:332)
            at com.facebook.drawee.view.DraweeHolder.attachController(DraweeHolder.java:276)
            at com.facebook.drawee.view.DraweeHolder.attachOrDetatchController(DraweeHolder.java:293)
            at com.facebook.drawee.view.DraweeHolder.onAttach(DraweeHolder.java:117)
            at com.facebook.drawee.view.DraweeView.onAttachedToWindow(DraweeView.java:104)
            at android.view.View.dispatchAttachedToWindow(View.java:13525)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
            at android.view.ViewGroup.addViewInner(ViewGroup.java:3975)
            at android.view.ViewGroup.addViewInLayout(ViewGroup.java:3912)
            at com.etsy.android.grid.ExtendableListView.setupChild(ExtendableListView.java:1461)
            at com.etsy.android.grid.ExtendableListView.makeAndAddView(ExtendableListView.java:1410)
            at com.etsy.android.grid.ExtendableListView.fillDown(ExtendableListView.java:1294)
            at com.etsy.android.grid.ExtendableListView.fillFromTop(ExtendableListView.java:1342)
            at com.etsy.android.grid.ExtendableListView.layoutChildren(ExtendableListView.java:589)
            at com.etsy.android.grid.StaggeredGridView.layoutChildren(StaggeredGridView.java:358)
            at com.etsy.android.grid.ExtendableListView.onLayout(ExtendableListView.java:513)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:543)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1594)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:502)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at a

**Comment by irtefa** [comment]
Bug on my backend.
