### ISSUE TITLE
NullPointer on getHierarchy  on version 1.0.1

### ISSUE THREAD

**Issue by tzanou** [facebook/fresco#1642]
I have the following code 

```
ZoomableDraweeView image=(ZoomableDraweeView) v.findViewById(R.id.test);

   image.setController( Fresco.newDraweeControllerBuilder()
                .setUri(Uri.parse("https://img1.wsimg.com/fos/sales/cwh/8/images/cats-with-hats-shop-06.jpg"))
                .build());
        GenericDraweeHierarchy hierarchy =
                new GenericDraweeHierarchyBuilder(getActivity().getResources())
                        .setActualImageScaleType(ScalingUtils.ScaleType.FIT_CENTER)
                        .setProgressBarImage(new ProgressBarDrawable())
                        .build();
        image.setHierarchy(hierarchy);
```

and I am using this [ZoomableDraweeView](https://github.com/facebook/fresco/blob/master/samples/zoomable/src/main/java/com/facebook/samples/zoomable/ZoomableDraweeView.java)

and I get 

> Caused by: java.lang.NullPointerException
                                                       at com.facebook.common.internal.Preconditions.checkNotNull(Preconditions.java:210)
                                                       at com.facebook.drawee.view.DraweeHolder.getHierarchy(DraweeHolder.java:257)
                                                       at com.facebook.drawee.view.DraweeHolder.isControllerValid(DraweeHolder.java:321)
                                                       at com.facebook.drawee.view.DraweeHolder.setHierarchy(DraweeHolder.java:240)
                                                       at com.facebook.drawee.view.DraweeView.setHierarchy(DraweeView.java:90)
                                                       at xxx.iku.fragments.MainFragment.onCreateView(MainFragment.java:126)
                                                       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
                                                       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
                                                       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:181)
                                                       at xxx.iku.activities.MainActivity.onStart(MainActivity.java:1740)
                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
                                                       at android.app.Activity.performStart(Activity.java:6320)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5441) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628) 

on version 1.0.0 works fine

**Comment by kirwan** [comment]
I think I've found the cause and am sorting out a fix.

In the meantime, it looks like setting the hierarchy before the controller should make the crash go away.
