### ISSUE TITLE
No instance field forceOldAnimationCode of type Z in class Lcom/facebook/imagepipeline/common/ImageDecodeOptions

### ISSUE THREAD

**Issue by remyat** [facebook/fresco#1660]
I Configured a project using Fresco for a gif image

1)Added dependencies:compile 'com.facebook.fresco:animated-base-support:0.12.0'
                                                 compile 'com.facebook.fresco:animated-gif:0.12.0'

2)Added intrnet permission

3)Configured SimpleDraweeView and controller
Fresco.initialize(this);
        setContentView(R.layout.activity_main);
        Uri uri = Uri.parse("http://katemobile.ru/tmp/sample3.gif");
        draweeView = (SimpleDraweeView) findViewById(R.id.draweeView);
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setUri(uri)
                .setOldController(draweeView.getController())
                .setControllerListener(controllerListener)
                .setAutoPlayAnimations(true)
                .build();
        draweeView.setController(controller);

4)Added control listener and in "onFinalImageSet"
@Override
        public void onFinalImageSet(String id, Object imageInfo, Animatable animatable) {
        if (animatable != null) {
            animatable.start();
        }
        }

**But the app crashes with the error**
java.lang.NoSuchFieldError: No instance field forceOldAnimationCode of type Z in class Lcom/facebook/imagepipeline/common/ImageDecodeOptions; or its superclasses (declaration of 'com.facebook.imagepipeline.common.ImageDecodeOptions' appears in /data/app/com.attinad.samplegiffresco-1/base.apk)
                                                                                 at com.facebook.imagepipeline.animated.factory.AnimatedImageFactoryImpl.decodeGif(AnimatedImageFactoryImpl.java:84)
                                                                                 at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeGif(DefaultImageDecoder.java:142)
                                                                                 at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:65)
                                                                                 at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:123)
                                                                                 at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:239)
                                                                                 at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:111)
                                                                                 at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:144)
                                                                                 at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                                                                                 at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                                                                                 at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                 at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                                                 at java.lang.Thread.run(Thread.java:818)

Can anyone help to solv this issue ?????

**Comment by oprisnik** [comment]
Looks like you're trying to mix different Fresco versions. We've removed the flag that can't be found in 9726a768f419ff319d01501d6780cdfecc203193. Make sure that you're using the same version everywhere. You should also consider updating to v1.0.1 (which should also fix the issue).

**Comment by remyat** [comment]
Thanks @oprisnik . The issue got resolved
