### ISSUE TITLE
java.lang.NumberFormatException: Invalid int:

### ISSUE THREAD

**Issue by quietUncle** [facebook/fresco#1663]
the log:
java.lang.NumberFormatException: Invalid int: "q592283716"
	at java.lang.Integer.invalidInt(Integer.java:138)
	at java.lang.Integer.parse(Integer.java:410)
	at java.lang.Integer.parseInt(Integer.java:367)
	at java.lang.Integer.parseInt(Integer.java:334)
	at com.facebook.cache.disk.e.a(DiskStorageCacheUtil.java:56)
	at com.facebook.cache.disk.d.e(DiskStorageCache.java:763)
	at com.facebook.cache.disk.d.d(DiskStorageCache.java:717)
	at com.facebook.cache.disk.d.b(DiskStorageCache.java:52)
	at com.facebook.cache.disk.d$1.run(DiskStorageCache.java:200)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

fresco version 0.12.0

**Comment by lambdapioneer** [comment]
Hello @quietUncle, this should be fixed in Fresco 1.x. We don't have the `DiskStorageCacheUtil` class anymore since July 2016 and the contained logic is gone from this codebase.

If the issue persists, please feel free to re-open this issue.

**Comment by quietUncle** [comment]
ok,thx
