### ISSUE TITLE
Comparison demo crash when select Volley + network

### ISSUE THREAD

**Issue by hangduykhiem** [facebook/fresco#1664]
### Description

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.facebook.samples.comparison, PID: 4529
    java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
       at java.util.HashMap$ValueIterator.next(HashMap.java:879)
       at com.android.volley.toolbox.ImageLoader$4.run(ImageLoader.java:464)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

### Reproduction

Select Volley and Network in the Comparison demo application 

### Additional Information

* Fresco version: 1.0.1
* Platform version: 5.1 - Xiaomi Redmi Note 3, 7.0 - Android Emulator

**Comment by lambdapioneer** [comment]
Hi @hangduykhiem, thanks for your report. I've been able to reproduce this locally. It just seems to affect `VolleyDraweeHolder` not the `VolleyAdapter`.

As a temporary work-around you can disable "Use Drawee" from the options menu.

I'll mark this as a starter-task and a bug.

**Comment by YkSix** [comment]
Hi @lambdapioneer,
I dug into this issue.
The issue is because that _Volley_ notifies `listeners` inside a `for-loop` uses `mBatchedResponses.values()`:
```
for (BatchedImageRequest bir : mBatchedResponses.values()) {`
  ...
  mListener.onResponse(...)
}
```
After some methods calling inside the `onResponse`, finally, the `mBatchedResponses.remove` will be called.

The stacktrace will look like:
```
inoke mBatchedResponses.remove(mCacheKey)
at com.android.volley.toolbox.ImageLoader$ImageContainer.cancelRequest(ImageLoader.java:365)
at com.facebook.drawee.backends.volley.VolleyDataSource.close(VolleyDataSource.java:66)
at com.facebook.datasource.BaseDataSubscriber.onNewResult(BaseDataSubscriber.java:51)
at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:181)
at com.facebook.common.executors.UiThreadImmediateExecutorService.execute(UiThreadImmediateExecutorService.java:40)
at com.facebook.datasource.AbstractDataSource.notifyDataSubscriber
at com.facebook.datasource.AbstractDataSource.notifyDataSubscribers(AbstractDataSource.java:163)
at com.facebook.datasource.AbstractDataSource.setResult(AbstractDataSource.java:215)
at com.facebook.drawee.backends.volley.VolleyDataSource$1.onResponse
at com.android.volley.toolbox.ImageLoader$4.run(ImageLoader.java:474)
```

A solution to this issue is using `Handler#post` in `VolleyDataSource.close` before calling `ImageContainer.cancelRequest`.

Is it fine to apply this solution?

**Comment by lambdapioneer** [comment]
@YkSix, thanks for fixing this (y) I'm on the PR and have a look now :)
