### ISSUE TITLE
Using media id feature cause database write error.

### ISSUE THREAD

**Issue by AlexCJW** [facebook/fresco#1667]
### Description

It happened when following code is called occasionally.

 public void setImageURI(
            final Uri uri,
            Object callerContext,
            ControllerListener listener,
            String mediaId,
            boolean foreRequest) {
        if (uri == null) {
            setController(null);
            return;
        }
        final ImagePipeline ip = Fresco.getImagePipeline();

        if (ip.isInBitmapMemoryCache(uri)) {
            getHierarchy().setFadeDuration(0);
        } else {
            getHierarchy().setFadeDuration(300);
        }

        ImageRequest request;
        if (mediaId == null) {
            request = ImageRequestBuilder
                    .newBuilderWithSource(uri)
                    .setAutoRotateEnabled(true)
                    .setProgressiveRenderingEnabled(false)
                    .build();
        } else {
            final MediaVariations.Builder mvb = MediaVariations.newBuilderForMediaId(mediaId);
            mvb.setForceRequestForSpecifiedUri(foreRequest);
            request = ImageRequestBuilder
                    .newBuilderWithSource(uri)
                    .setMediaVariations(mvb.build())
                    .setAutoRotateEnabled(true)
                    .setProgressiveRenderingEnabled(false)
                    .build();
        }
        PipelineDraweeController controller = (PipelineDraweeController) Fresco.getDraweeControllerBuilderSupplier().get()
                .setControllerListener(listener)
                .setCallerContext(callerContext)
                .setImageRequest(request)
                .setTapToRetryEnabled(bTapToRetry)
                .setOldController(getController())
                .setAutoPlayAnimations(bAnimationAutoStart)
                .build();
        if (TextUtils.isEmpty(uri.toString())) {
            mSkipFailedId = controller.getId();
        } else {
            mSkipFailedId = MyConstant._EMPTY_;
        }
        setController(controller);
    }

### Reproduction
Just set a image with media id.

## Additional Information

Following is the logcat output.

java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.mao.zx.metome/databases/FrescoMediaVariationsIndex.db
                                                                             at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
                                                                             at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:530)
                                                                             at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:443)
                                                                             at com.facebook.imagepipeline.producers.MediaVariationsIndexDatabase$2.run(MediaVariationsIndexDatabase.java:135)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                             at java.lang.Thread.run(Thread.java:776)
02-15 11:03:16.959 31286-31476/? W/TDLog: UncaughtException in Thread pool-4-thread-2
                                          java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.mao.zx.metome/databases/FrescoMediaVariationsIndex.db
                                              at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
                                              at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:547)
                                              at com.facebook.imagepipeline.producers.MediaVariationsIndexDatabase$2.run(MediaVariationsIndexDatabase.java:151)
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                              at java.lang.Thread.run(Thread.java:776)

**Comment by kirwan** [comment]
This looks like a synchronization issue around the database helper. Reads are protected but writes aren't.
