### ISSUE TITLE
OOM at ForwardingDrawable using VectorDrawableCompat

### ISSUE THREAD

**Issue by raylee4204** [facebook/fresco#1669]
I use VectorDrawableCompat as a placeholder to show for a list of images.

```java
GenericDraweeHierarchy hierarchy = view.getHierarchy();
VectorDrawableCompat drawable = VectorDrawableCompat.create(context.getResources(), R.drawable.avatar_placeholder, context.getTheme());
drawable.mutate();
hierarchy.setPlaceholderImage(drawable);
```

The following error gets reported consistently on Crashlytics

```
Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:928)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:868)
       at android.support.graphics.drawable.VectorDrawableCompat$VectorDrawableCompatState.createCachedBitmapIfNeeded(VectorDrawableCompat.java:1024)
       at android.support.graphics.drawable.VectorDrawableCompat.draw(VectorDrawableCompat.java:366)
       at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:142)
       at com.facebook.drawee.drawable.ScaleTypeDrawable.draw(ScaleTypeDrawable.java:126)
       at com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha(FadeDrawable.java:306)
       at com.facebook.drawee.drawable.FadeDrawable.draw(FadeDrawable.java:293)
       at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:142)
       at com.facebook.drawee.generic.RootDrawable.draw(RootDrawable.java:85)
       at android.widget.ImageView.onDraw(ImageView.java:1040)
       at android.view.View.draw(View.java:15430)
       at android.view.View.getDisplayList(View.java:14324)
       at android.view.View.getDisplayList(View.java:14366)
       at android.view.View.draw(View.java:15144)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
       at android.view.View.draw(View.java:15433)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.view.View.getDisplayList(View.java:14324)
       at android.view.View.getDisplayList(View.java:14366)
       at android.view.View.draw(View.java:15144)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
       at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4248)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
       at android.view.View.draw(View.java:15433)
       at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3657)
       at android.view.View.getDisplayList(View.java:14324)
       at android.view.View.getDisplayList(View.java:14366)
       at android.view.View.draw(View.java:15144)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
       at android.view.View.getDisplayList(View.java:14319)
       at android.view.View.getDisplayList(View.java:14366)
       at android.view.View.draw(View.java:15144)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
       at android.view.View.draw(View.java:15433)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at android.widget.ScrollView.draw(ScrollView.java:2236)
       at android.view.View.getDisplayList(View.java:14324)
       at android.view.View.getDisplayList(View.java:14366)
       at android.view.View.draw(View.java:15144)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
       at android.view.View.getDisplayList(View.java:14319)
       at android.view.View.getDisplayList(View.java:14366)
       at android.view.View.draw(View.java:15144)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
       at android.view.View.getDisplayList(View.java:14319)
       at android.view.View.getDisplayList(View.java:14366)
       at android.view.View.draw(View.java:15144)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
       at android.view.View.draw(View.java:15433)
       at android.view.View.getDisplayList(View.java:14324)
       at android.view.View.getDisplayList(View.java:14366)
       at android.view.View.draw(View.java:15144)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
       at android.view.View.getDisplayList(View.java:14319)
       at android.view.View.getDisplayList(View.java:14366)
       at android.view.View.draw(View.java:15144)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
       at android.view.View.getDisplayList(View.java:14319)
       at android.view.View.getDisplayList(View.java:14366)
       at android.view.View.draw(View.java:15144)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
       at android.view.View.getDisplayList(View.java:14319)
       at android.view.View.getDisplayList(View.java:14366)
       at android.view.View.draw(View.java:15144)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
       at android.view.View.getDisplayList(View.java:14319)
       at android.view.View.getDisplayList(View.java:14366)
       at android.view.View.draw(View.java:15144)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3322)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3158)
       at android.view.View.draw(View.java:15433)
       at android.widget.FrameLayout.draw(FrameLayout.java:472)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2602)
       at android.view.View.getDisplayList(View.java:14324)
       at android.view.View.getDisplayList(View.java:14366)
       at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1597)
       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1469)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2782)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2648)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2216)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1256)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6658)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
       at android.view.Choreographer.doCallbacks(Choreographer.java:613)
       at android.view.Choreographer.doFrame(Choreographer.java:583)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5692)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

* Fresco version: 1.0.1
* Platform version: 4.2.2 - 6.0

**Comment by kirwan** [comment]
Sorry for the slow response.

The error is happening when you create the VectorDrawableCompat's bitmap, not anything in Fresco itself.

I'd suggest checking a few things:

What are the layout params for the DraweeView?
Is the resulting placeholder the correct size for that?
Are the views being recycled properly so you only create as many as you need on screen?
Is it necessary to mutate the drawable?

**Comment by raylee4204** [comment]
What are the layout params for the DraweeView?
```xml
<com.facebook.drawee.view.SimpleDraweeView
                android:id="@+id/img_item"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="16dp"
                app:actualImageScaleType="centerCrop" />
```
And I set aspect ratio when I get width/height data from the backend.

Is the resulting placeholder the correct size for that?
- How do you mean by this? Is there a way to set the size for the placeholder?

Are the views being recycled properly so you only create as many as you need on screen?
- Yes
Is it necessary to mutate the drawable?
- I can try removing this

**Comment by kirwan** [comment]
When I asked if the placeholder is the correct size, I meant you could debug the app and ensure the drawable and bitmap aren't bigger than the view needs them to be.
