### ISSUE TITLE
Error : Failed to slurp image 0

### ISSUE THREAD

**Issue by bigstark** [facebook/fresco#167]
When I loaded some gif images, some gif was occured Failed to slurp image 0

What happens?

java.lang.IllegalStateException: Failed to slurp image 0
    at com.facebook.imagepipeline.gif.GifImage.nativeCreateFromNativeMemory(Native Method)
    at com.facebook.imagepipeline.gif.GifImage.create(GifImage.java:65)
    at com.facebook.imagepipeline.animated.factory.AnimatedImageFactory.decodeGif(AnimatedImageFactory.java:62)
    at com.facebook.imagepipeline.decoder.ImageDecoder.decodeAnimatedGif(ImageDecoder.java:105)
    at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:86)
    at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:231)
    at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:92)
    at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$3.run(DecodeProducer.java:202)
    at com.facebook.common.executors.SerialDelegatingExecutor.executeSingleCommand(SerialDelegatingExecutor.java:76)
    at com.facebook.common.executors.SerialDelegatingExecutor.access$000(SerialDelegatingExecutor.java:24)
    at com.facebook.common.executors.SerialDelegatingExecutor$1.run(SerialDelegatingExecutor.java:47)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)

**Comment by IanChilds** [comment]
Can you give us the uri of the GIF that failed please?

**Comment by plamenko** [comment]
reaping

**Comment by EricRGC** [comment]
Have this bug been fixed ? I use 0.6.0 and still find this bug.

**Comment by michalgr** [comment]
EricRGC: can you provide urls ?

**Comment by bu2zhouzhu** [comment]
Having this problem too. Gif url:
https://striker.teambition.net/thumbnail/110b4cc3dff19b7c1ec06cda1a81b54a24f6/w/240/h/240
@EricRGC

**Comment by WoookLiu** [comment]
And this Gif: https://striker.teambition.net/thumbnail/110bdf95db58544e26dddd684ab9339a5556/w/200/h/200

**Comment by LiuDeng** [comment]
@IanChilds @plamenko 
i use 0.8.1 it still happend and http://ww4.sinaimg.cn/bmiddle/6d87e02fjw1ezjzc314x2g20ao0607uw.gif

**Comment by LiuDeng** [comment]
hope fix this and release 0.8.2 soon we are wait for this to be fixed to upload our app
Thank you for your great jobs!

**Comment by LiuDeng** [comment]
this still not fixed in 0.9.0

**Comment by LiuDeng** [comment]
http://p3.pstatp.com/large/2ce000064e9f0b034f1

**Comment by TmRobust** [comment]
http://kelu.oss-cn-hangzhou.aliyuncs.com/image/1005481_1460285224582_baorv1bj00mmm2gib4ji
this still not fixed in 0.9.0

**Comment by erikandre** [comment]
Gif and animation support has been rewritten since 0.9.
If the problem still exists in the latest release, please file a new bug report.
