### ISSUE TITLE
android 4.4.4 vivo Y913 ava.lang.StackOverflowError,The crash is serious

### ISSUE THREAD

**Issue by xiaoyao27610** [facebook/fresco#1696]
java.lang.StackOverflowError
	at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
	at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:145)
	at java.lang.StringBuilder.append(StringBuilder.java:216)
	at java.io.File.join(File.java:215)
	at java.io.File.<init>(File.java:157)
	at java.io.File.<init>(File.java:124)
	at java.io.File.filenamesToFiles(File.java:850)
	at java.io.File.listFiles(File.java:789)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:34)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:38)
	at com.facebook.common.fil

**Comment by erikandre** [comment]
Hi @xiaoyao27610 ! 

Thank you for submitting the issue. Is this crash reproducible? Does it occur on other devices besides the Vivo Y913?

**Comment by MattFoley** [comment]
This occurs on the Droid Ultra as well.

**Comment by oprisnik** [comment]
Closing due to inactivity.
