### ISSUE TITLE
Loading the GIF causes the project to crash

### ISSUE THREAD

**Issue by bxhuhu** [facebook/fresco#1703]
```java
//my code

 Uri uri = Uri.parse(address);
        DraweeController draweeController =
                Fresco.newDraweeControllerBuilder()
                        .setUri(uri)
                        .setAutoPlayAnimations(true) 
                        .build();
        nivShowImg.setController(draweeController);
```

```java
//my version
compile 'com.facebook.fresco:fresco:1.1.0'
compile 'com.facebook.fresco:animated-gif:1.1.0'
```

```java
//my error
 java.lang.NoSuchFieldError: com.facebook.imagepipeline.common.ImageDecodeOptions.forceOldAnimationCode
                                                               at com.facebook.imagepipeline.animated.factory.AnimatedImageFactoryImpl.decodeGif(AnimatedImageFactoryImpl.java:84)
                                                               at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeGif(DefaultImageDecoder.java:142)
                                                               at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:65)
                                                               at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:123)
                                                               at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:239)
                                                               at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:111)
                                                               at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:144)
                                                               at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                                                               at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                                                               at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                               at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                               at java.lang.Thread.run(Thread.java:841)

```
#question
What is the solution to this problem, or what is the cause of the problem

**Comment by oprisnik** [comment]
I guess some of your Gradle dependencies got mixed up. We removed `forceOldAnimationCode`. Try updating Fresco to a recent version (e.g. 1.1.0) and clean/rebuild your project

**Comment by oprisnik** [comment]
See also #1660

**Comment by bxhuhu** [comment]
Thanks @oprisnik
