### ISSUE TITLE
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk

### ISSUE THREAD

**Issue by lindow2009** [facebook/fresco#171]
```
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool(SourceFile:60)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool(SourceFile:22)
	at com.facebook.imagepipeline.memory.PoolParams(SourceFile:264)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream(SourceFile:53)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream(SourceFile:36)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory(SourceFile:131)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory(SourceFile:26)
	at com.facebook.imagepipeline.producers.NetworkFetchProducer(SourceFile:97)
	at com.facebook.imagepipeline.producers.NetworkFetchProducer(SourceFile:36)
	at com.facebook.imagepipeline.producers.NetworkFetchProducer(SourceFile:73)
	at com.facebook.imagepipeline.producers.NetworkFetchProducer(SourceFile:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:838)
```
why this happen?

**Comment by tyronen** [comment]
Can you tell us about your build setup? How is Fresco included in your build.gradle file?

**Comment by michalgr** [comment]
Is this caused by proguard as well ? (https://github.com/facebook/fresco/issues/172, https://github.com/facebook/fresco/issues/105)

**Comment by gewuxy** [comment]
classpath 'com.android.tools.build:gradle:2.3.0'

compile 'com.facebook.fresco:fresco:0.12.0'
compile "com.facebook.fresco:imagepipeline-okhttp3:0.12.0+"

here is my setup

**Comment by erikandre** [comment]
@gewuxy Please update to a newer release of Fresco, the latest is 1.2.0. It is much safer not to use + in a gradle import since that means that you can get mismatched versions (like in your case).
