### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by artyomdangizyan** [facebook/fresco#1711]
Hello, our released app have started to crash with UnsatisfiedLinkError on Samsung devices with android version 4 (4.2.2, 4.3, ...), we are using fresco version 1.0.1, and added custom okhttp client 
```java
java.lang.ExceptionInInitializerError
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(ProGuard:60)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(ProGuard:22)
	at com.facebook.imagepipeline.memory.BasePool.get(ProGuard:259)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(ProGuard:53)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(ProGuard:141)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(ProGuard:26)
                                                                    newOutputStream
	at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(ProGuard:94)
	at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(ProGuard:37)
	at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(ProGuard:72)
	at com.app.fresco.backends.OkHttpNetworkFetcher$2.onResponse(ProGuard:147)
	at okhttp3.RealCall$AsyncCall.execute(ProGuard:135)
	at okhttp3.internal.NamedRunnable.run(ProGuard:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.UnsatisfiedLinkError: Couldn't load imagepipeline: findLibrary returned null
	at java.lang.Runtime.loadLibrary(Runtime.java:365)
	at java.lang.System.loadLibrary(System.java:535)
	at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(ProGuard:32)
	at com.facebook.common.soloader.SoLoaderShim.loadLibrary(ProGuard:56)
	at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ProGuard:43)
	at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(ProGuard:36)
	... 15 more
```

**Comment by oprisnik** [comment]
Using ReLinker should fix this issue. See #1336, #1005, #410
