### ISSUE TITLE
Crash NativeMemoryChunk.nativeAllocate

### ISSUE THREAD

**Issue by Geppetto76** [facebook/fresco#1712]
In our app we have a third-party library which .so files are inserted into armeabi-v7 and x_86 folders. To manage all types of terminals  was inserted the filter in gradle:

ndk {
    abiFilters 'x86', 'armeabi-v7a'
}

using Fresco in the project occurs several times crash, unsystematic:

```
Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for long com.facebook.imagepipeline.memory.NativeMemoryChunk.nativeAllocate(int) (tried Java_com_facebook_imagepipeline_memory_NativeMemoryChunk_nativeAllocate and Java_com_facebook_imagepipeline_memory_NativeMemoryChunk_nativeAllocate__I)
       at com.facebook.imagepipeline.memory.NativeMemoryChunk.nativeAllocate(SourceFile)
       at com.facebook.imagepipeline.memory.NativeMemoryChunk.(SourceFile)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(SourceFile:60)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(SourceFile:22)
       at com.facebook.imagepipeline.memory.BasePool.get(SourceFile:259)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.(SourceFile)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(SourceFile:141)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(SourceFile:26)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(SourceFile:94)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(SourceFile:37)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(SourceFile:72)
       at com.facebook.imagepipeline.backends.okhttp3.OkHttpNetworkFetcher$2.onResponse(SourceFile:153)
       at okhttp3.RealCall$AsyncCall.execute(SourceFile:133)
       at okhttp3.internal.NamedRunnable.run(SourceFile:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

 By placing all the missing types in abifilters the third-party library causes crash as file search in armeabi-V8a folder.
Can you help me to manage the two libraries and avoid the crash described above
Thanks in advance

**Comment by foghina** [comment]
See #1552, #192 or a [quick search for `UnsatisfiedLinkError`](https://github.com/facebook/fresco/search?q=UnsatisfiedLinkError&type=Issues&utf8=%E2%9C%93)
