### ISSUE TITLE
Crash when used Image component

### ISSUE THREAD

**Issue by BennyTian** [facebook/fresco#1732]
my code:

`<Image source={ { uri: picUrl } } />`

got exception:

`java.lang.AbstractMethodError: abstract method "void com.facebook.imagepipeline.producers.ProducerListener.onUltimateProducerReached(java.lang.String, java.lang.String, boolean)"
	at com.facebook.imagepipeline.listener.ForwardingRequestListener.onUltimateProducerReached(ForwardingRequestListener.java:144)
	at com.facebook.imagepipeline.producers.NetworkFetchProducer.handleFinalResult(NetworkFetchProducer.java:155)
	at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:110)
	at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:37)
	at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:72)
	at com.facebook.imagepipeline.backends.okhttp3.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:122)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)`

react native version: 0.41.2 
android version: 6.0

thanks a lot.

**Comment by erikandre** [comment]
Hi @BennyTian! 

What does your gradle config look like, for including Fresco and related libraries?

**Comment by butterf1y** [comment]
@BennyTian :
hi friend, I met the same problem days ago. 
in my case, i compile another repository  'com.facebook.fresco:animated-gif:latest.integration'.
JUST REMOVE IT! and it works.
good luck.

**Comment by BennyTian** [comment]
thanks all .   fixed~~~

the fresco was auto updated ..

the bug code:

`compile 'com.facebook.fresco:animated-gif:+'
compile 'com.facebook.fresco:animated-webp:+'
compile 'com.facebook.fresco:webpsupport:+'`


fixed code:

`compile 'com.facebook.fresco:animated-gif:1.2.0'
compile 'com.facebook.fresco:animated-webp:1.2.0'
compile 'com.facebook.fresco:webpsupport:1.2.0'
`


thanks all .

**Comment by BennyTian** [comment]
Thanks  @erikandre   The problem was fixed. 


change my code 

`compile 'com.facebook.fresco:animated-gif:+' 
compile 'com.facebook.fresco:animated-webp:+' 
compile 'com.facebook.fresco:webpsupport:+'`

 to 

`compile 'com.facebook.fresco:animated-gif:1.2.0' 
compile 'com.facebook.fresco:animated-webp:1.2.0' 
compile 'com.facebook.fresco:webpsupport:1.2.0'`

thank you very much .

**Comment by erikandre** [comment]
No problem @BennyTian ! I'm glad it worked out :)
