### ISSUE TITLE
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk

### ISSUE THREAD

**Issue by vivienhao** [facebook/fresco#1738]
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk
	com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(Unknown Source)
	com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(Unknown Source)
	com.facebook.imagepipeline.memory.BasePool.get(Unknown Source)
	com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.(Unknown Source)
	com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(Unknown Source)
	com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(Unknown Source)
	com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(Unknown Source)
	com.facebook.imagepipeline.cache.BufferedDiskCache.access$400(Unknown Source)
	com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(Unknown Source)
	com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(Unknown Source)
	bolts.n.run(Unknown Source)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	java.lang.Thread.run(Thread.java:838)

    compile 'com.facebook.stetho:stetho-okhttp3:1.3.1'
    compile 'com.facebook.stetho:stetho:1.3.1'
    compile 'com.facebook.fresco:fresco:1.2.0'
    compile 'com.facebook.fresco:animated-gif:1.2.0'

**Comment by erikandre** [comment]
Hi @vivienhao 

1. Is this crash reproducible?
2. What device does it occur on?

**Comment by vivienhao** [comment]
1. Occasionally
2. HUAWEIY560-CL00、HUAWEI:PE-UL00、HUAWEI:H60-L01、HUAWEI P7-L09、HUAWEI:PE-TL10、HUAWEI:CHM-TL00H、YuLong:Coolpad8675-HD、HUAWEI:H60-L03、HUAWEI:Hol-U10、ViVO X9、HTC X9u

**Comment by dongorigin** [comment]
I have same question

### Description
OS: Android 4.4.4
phone: OPPO R8200
stack trace:
```
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.i(NativeMemoryChunkPool.java:60)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.b(NativeMemoryChunkPool.java:22)
	at com.facebook.imagepipeline.memory.BasePool.a(BasePool.java:260)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.b(NativePooledByteBufferFactory.java:100)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.a(NativePooledByteBufferFactory.java:28)
	at com.facebook.imagepipeline.cache.BufferedDiskCache.g(BufferedDiskCache.java:341)
	at com.facebook.imagepipeline.cache.BufferedDiskCache.b(BufferedDiskCache.java:38)
	at com.facebook.imagepipeline.cache.BufferedDiskCache$2.a(BufferedDiskCache.java:185)
	at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:168)
	at bolts.h$10.run(Task.java:357)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
```

### Reproduction
only 1 user hit this problem, but with very high frequency

### Additional Information
- Fresco version: 1.2.0
- Platform version: Android 4.4.4

**Comment by RocLiuYC** [comment]
I have the same issue:

fresco:
    compile 'com.facebook.fresco:fresco:1.3.0'
    compile "com.facebook.fresco:imagepipeline-okhttp3:1.3.0"
    compile 'com.facebook.fresco:animated-webp:1.3.0'
    compile 'com.facebook.fresco:webpsupport:1.3.0'

crash on android 4.x.x

**Comment by oprisnik** [comment]
There are many similar issues, see https://github.com/facebook/fresco/search?q=NativeMemoryChunk&type=Issues&utf8=%E2%9C%93

**Comment by golden110** [comment]
@vivienhao 
Has it been solved?

**Comment by kongsonida** [comment]
![image](https://user-images.githubusercontent.com/2419054/54457627-77abf200-4794-11e9-9a1c-4f7e1601ce13.png)
