### ISSUE TITLE
NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk

### ISSUE THREAD

**Issue by meanliang** [facebook/fresco#1743]
### Description
OS: Android 4.4.4
phone: OPPO R8207
stack trace:
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk
	at com.facebook.imagepipeline.memory.m.i(NativeMemoryChunkPool.java:60)
	at com.facebook.imagepipeline.memory.m.b(NativeMemoryChunkPool.java:22)
	at com.facebook.imagepipeline.memory.a.a(BasePool.java:259)
	at com.facebook.imagepipeline.memory.p.<init>(NativePooledByteBufferOutputStream.java:53)
	at com.facebook.imagepipeline.memory.o.a(NativePooledByteBufferFactory.java:98)
	at com.facebook.imagepipeline.memory.o.b(NativePooledByteBufferFactory.java:26)
	at com.facebook.imagepipeline.c.e.g(BufferedDiskCache.java:341)
	at com.facebook.imagepipeline.c.e.b(BufferedDiskCache.java:38)
	at com.facebook.imagepipeline.c.e$2.a(BufferedDiskCache.java:185)
	at com.facebook.imagepipeline.c.e$2.call(BufferedDiskCache.java:168)
	at b.j$10.run(Task.java:357)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

### Reproduction

only 2 users hit this problem, with very high frequency

### Additional Information

* Fresco version: 1.0.0
* Platform version: Android 4.4.4

**Comment by foghina** [comment]
Same as #1724, #1738, #1723 and, ultimately, #933. Please check those issues for potential fixes.
