### ISSUE TITLE
java.lang.RuntimeException: android.os.DeadObjectException

### ISSUE THREAD

**Issue by KaleXia** [facebook/fresco#1746]
my gradle:
`    compile 'com.facebook.fresco:imagepipeline-okhttp3:1.2.0'
    compile  'com.facebook.fresco:fresco:1.2.0'
    compile  'com.facebook.fresco:animated-gif:1.2.0'
    compile  'com.facebook.fresco:animated-base-support:1.2.0'`

and my error log
`java.lang.RuntimeException: android.os.DeadObjectException
	at android.os.storage.StorageManager.getVolumeList(StorageManager.java:920)
	at android.os.Environment$UserEnvironment.getExternalDirs(Environment.java:99)
	at android.os.Environment.getExternalStorageDirectory(Environment.java:353)
	at com.facebook.common.statfs.StatFsHelper.ensureInitialized(StatFsHelper.java:90)
	at com.facebook.common.statfs.StatFsHelper.testLowDiskSpace(StatFsHelper.java:112)
	at com.facebook.cache.disk.DiskStorageCache.updateFileCacheSizeLimit(DiskStorageCache.java:576)
	at com.facebook.cache.disk.DiskStorageCache.maybeEvictFilesInCacheDir(DiskStorageCache.java:477)
	at com.facebook.cache.disk.DiskStorageCache.startInsert(DiskStorageCache.java:334)
	at com.facebook.cache.disk.DiskStorageCache.insert(DiskStorageCache.java:369)
	at com.facebook.imagepipeline.cache.BufferedDiskCache.writeToDiskCache(BufferedDiskCache.java:367)
	at com.facebook.imagepipeline.cache.BufferedDiskCache.access$500(BufferedDiskCache.java:38)
	at com.facebook.imagepipeline.cache.BufferedDiskCache$3.run(BufferedDiskCache.java:246)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:511)
	at android.content.pm.IPackageManager$Stub$Proxy.getPackageUid(IPackageManager.java:2251)
	at android.os.storage.StorageManager.getVolumeList(StorageManager.java:914)`

**Comment by oprisnik** [comment]
Can you please fill in the issue template? We need additional information.

**Comment by oprisnik** [comment]
I assume the problem has been resolved. If not, please let us know.
