### ISSUE TITLE
It's crash sometimes when I start my app

### ISSUE THREAD

**Issue by wind24** [facebook/fresco#1754]
Hi.
I got a crash When I used a FlagImageView which extends the SimpleDraweeView.The crash message said StringBlock.get∫ is NullPointerException.
My device is HTC one M8.android os is 5.1.1.

```
05-08 15:20:42.260 27991-27991/com.hellotalk W/System.err: android.view.InflateException: Binary XML file line #54: Error inflating class <unknown>
05-08 15:20:42.261 27991-27991/com.hellotalk W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:633)
05-08 15:20:42.261 27991-27991/com.hellotalk W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
05-08 15:20:42.261 27991-27991/com.hellotalk W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
05-08 15:20:42.261 27991-27991/com.hellotalk W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
05-08 15:20:42.261 27991-27991/com.hellotalk W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
05-08 15:20:42.261 27991-27991/com.hellotalk W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
05-08 15:20:42.261 27991-27991/com.hellotalk W/System.err:     at com.hellotalkx.modules.talks.logic.ChattedAdapter.onCreateViewHolder(ChattedAdapter.java:186)
05-08 15:20:42.262 27991-27991/com.hellotalk W/System.err:     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5288)
05-08 15:20:42.262 27991-27991/com.hellotalk W/System.err:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4551)
05-08 15:20:42.262 27991-27991/com.hellotalk W/System.err:     at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4461)
05-08 15:20:42.262 27991-27991/com.hellotalk W/System.err:     at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1962)
05-08 15:20:42.262 27991-27991/com.hellotalk W/System.err:     at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1371)
05-08 15:20:42.262 27991-27991/com.hellotalk W/System.err:     at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1334)
05-08 15:20:42.262 27991-27991/com.hellotalk W/System.err:     at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:563)
05-08 15:20:42.262 27991-27991/com.hellotalk W/System.err:     at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2847)
05-08 15:20:42.262 27991-27991/com.hellotalk W/System.err:     at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3145)
05-08 15:20:42.262 27991-27991/com.hellotalk W/System.err:     at android.view.View.layout(View.java:15678)
05-08 15:20:42.262 27991-27991/com.hellotalk W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5045)
05-08 15:20:42.262 27991-27991/com.hellotalk W/System.err:     at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:596)
05-08 15:20:42.262 27991-27991/com.hellotalk W/System.err:     at android.view.View.layout(View.java:15678)
05-08 15:20:42.262 27991-27991/com.hellotalk W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5045)
05-08 15:20:42.262 27991-27991/com.hellotalk W/System.err:     at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
05-08 15:20:42.262 27991-27991/com.hellotalk W/System.err:     at android.view.View.layout(View.java:15678)
05-08 15:20:42.263 27991-27991/com.hellotalk W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5045)
05-08 15:20:42.263 27991-27991/com.hellotalk W/System.err:     at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1695)
05-08 15:20:42.263 27991-27991/com.hellotalk W/System.err:     at android.view.View.layout(View.java:15678)
05-08 15:20:42.263 27991-27991/com.hellotalk W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5045)
05-08 15:20:42.263 27991-27991/com.hellotalk W/System.err:     at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1009)
05-08 15:20:42.263 27991-27991/com.hellotalk W/System.err:     at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:719)
05-08 15:20:42.263 27991-27991/com.hellotalk W/System.err:     at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:733)
05-08 15:20:42.263 27991-27991/com.hellotalk W/System.err:     at android.view.View.layout(View.java:15678)
05-08 15:20:42.263 27991-27991/com.hellotalk W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5045)
05-08 15:20:42.263 27991-27991/com.hellotalk W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
05-08 15:20:42.263 27991-27991/com.hellotalk W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
05-08 15:20:42.263 27991-27991/com.hellotalk W/System.err:     at android.view.View.layout(View.java:15678)
05-08 15:20:42.263 27991-27991/com.hellotalk W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5045)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.view.View.layout(View.java:15678)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5045)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.view.View.layout(View.java:15678)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5045)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.view.View.layout(View.java:15678)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5045)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.view.View.layout(View.java:15678)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5045)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.view.View.layout(View.java:15678)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5045)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.view.View.layout(View.java:15678)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.view.ViewGroup.layout(ViewGroup.java:5045)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5897)
05-08 15:20:42.264 27991-27991/com.hellotalk W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
05-08 15:20:42.265 27991-27991/com.hellotalk W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
05-08 15:20:42.265 27991-27991/com.hellotalk W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:550)
05-08 15:20:42.265 27991-27991/com.hellotalk W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
05-08 15:20:42.265 27991-27991/com.hellotalk W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
05-08 15:20:42.265 27991-27991/com.hellotalk W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
05-08 15:20:42.265 27991-27991/com.hellotalk W/System.err:     at android.os.Looper.loop(Looper.java:135)
05-08 15:20:42.265 27991-27991/com.hellotalk W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5343)
05-08 15:20:42.265 27991-27991/com.hellotalk W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
05-08 15:20:42.265 27991-27991/com.hellotalk W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
05-08 15:20:42.265 27991-27991/com.hellotalk W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
05-08 15:20:42.265 27991-27991/com.hellotalk W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
05-08 15:20:42.266 27991-27991/com.hellotalk W/System.err: Caused by: java.lang.reflect.InvocationTargetException
05-08 15:20:42.267 27991-27991/com.hellotalk W/System.err:     at java.lang.reflect.Constructor.newInstance(Native Method)
05-08 15:20:42.267 27991-27991/com.hellotalk W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
05-08 15:20:42.267 27991-27991/com.hellotalk W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:607)
05-08 15:20:42.267 27991-27991/com.hellotalk W/System.err: 	... 78 more
05-08 15:20:42.270 27991-27991/com.hellotalk W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.content.res.StringBlock.get∫' on a null object reference
05-08 15:20:42.276 27991-27991/com.hellotalk W/System.err:     at android.content.res.AssetManager.getPooledStringForCookie(AssetManager.java:290)
05-08 15:20:42.276 27991-27991/com.hellotalk W/System.err:     at android.content.res.TypedArray.loadStringValueAt(TypedArray.java:996)
05-08 15:20:42.276 27991-27991/com.hellotalk W/System.err:     at android.content.res.TypedArray.getValueAt(TypedArray.java:982)
05-08 15:20:42.276 27991-27991/com.hellotalk W/System.err:     at android.content.res.TypedArray.getDrawable(TypedArray.java:745)
05-08 15:20:42.276 27991-27991/com.hellotalk W/System.err:     at android.view.View.<init>(View.java:3738)
05-08 15:20:42.276 27991-27991/com.hellotalk W/System.err:     at android.widget.ImageView.<init>(ImageView.java:139)
05-08 15:20:42.276 27991-27991/com.hellotalk W/System.err:     at android.widget.ImageView.<init>(ImageView.java:135)
05-08 15:20:42.276 27991-27991/com.hellotalk W/System.err:     at android.widget.ImageView.<init>(ImageView.java:131)
05-08 15:20:42.276 27991-27991/com.hellotalk W/System.err:     at com.facebook.drawee.view.DraweeView.<init>(DraweeView.java:57)
05-08 15:20:42.276 27991-27991/com.hellotalk W/System.err:     at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:42)
05-08 15:20:42.276 27991-27991/com.hellotalk W/System.err:     at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:62)
05-08 15:20:42.276 27991-27991/com.hellotalk W/System.err:     at com.hellotalk.view.FlagImageView.<init>(FlagImageView.java:31)
05-08 15:20:42.277 27991-27991/com.hellotalk W/System.err: 	... 81 more
```

**Comment by foghina** [comment]
Would you mind posting the contents of `FlagImageView.java`, or just the constructor? It's hard to tell what's going on without looking at the code.

Just guessing however, this doesn't look like a problem with `DraweeView`, as the exception actually happens in `ImageView`'s constructor (which `DraweeView` extends).

**Comment by kirwan** [comment]
I took a quick look at the [source for the Android `View` class](https://android.googlesource.com/platform/frameworks/base/+/android-5.1.1_r38/core/java/android/view/View.java) and it looks like line 3738 from your stack trace points to a problem loading the background drawable.

I'm closing this as I don't think it points to a problem in Fresco but if you find something else please comment and we can reopen if necessary.
