### ISSUE TITLE
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk

### ISSUE THREAD

**Issue by MissBears** [facebook/fresco#1758]
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(SourceFile:60)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(SourceFile:22)
	at com.facebook.imagepipeline.memory.BasePool.get(SourceFile:259)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(SourceFile:53)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(SourceFile:98)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(SourceFile:26)
	at com.facebook.imagepipeline.producers.LocalFetchProducer.getByteBufferBackedEncodedImage(SourceFile:99)
	at com.facebook.imagepipeline.producers.LocalFetchProducer.getEncodedImage(SourceFile:119)
	at com.facebook.imagepipeline.producers.LocalResourceFetchProducer.getEncodedImage(SourceFile:42)
	at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(SourceFile:66)
	at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(SourceFile:62)
	at com.facebook.common.executors.StatefulRunnable.run(SourceFile:45)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at java.lang.Thread.run(Thread.java:856)

how to resolve this bug

**Comment by foghina** [comment]
What version of Fresco are you using?

**Comment by smallsilver** [comment]
my app is also throw this question.
my fresco version  is 
```
compile 'com.facebook.fresco:fresco:0.12.0'
compile 'com.facebook.fresco:imagepipeline-okhttp3:0.12.0'
```
and it occured in Android 4.4.4、4.4.2 version。
thank you！

**Comment by oprisnik** [comment]
There are many similar issues, see https://github.com/facebook/fresco/search?q=NativeMemoryChunk&type=Issues&utf8=%E2%9C%93
