### ISSUE TITLE
 I don't  kown how to do  for this issue??  Thanks  

### ISSUE THREAD

**Issue by Troll4it** [facebook/fresco#1760]
java.io.IOException: Invalid marker: 89
                                                                    at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1604)
                                                                    at android.media.ExifInterface.loadAttributes(ExifInterface.java:1335)
                                                                    at android.media.ExifInterface.<init>(ExifInterface.java:1053)
                                                                    at com.facebook.imagepipeline.producers.LocalExifThumbnailProducer.getExifInterface(LocalExifThumbnailProducer.java:136)
                                                                    at com.facebook.imagepipeline.producers.LocalExifThumbnailProducer$1.getResult(LocalExifThumbnailProducer.java:103)
                                                                    at com.facebook.imagepipeline.producers.LocalExifThumbnailProducer$1.getResult(LocalExifThumbnailProducer.java:97)
                                                                    at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                    at java.lang.Thread.run(Thread.java:831)

**Comment by foghina** [comment]
Can you post a link to the file you're trying to display?

**Comment by Troll4it** [comment]
sorry,My English is poor。。。 
The problem is the local photo album, with recyclerView loading of pictures, use fresco "load

**Comment by kirwan** [comment]
It looks like the image probably isn't a JPEG. I've found a simple fix we can add to that producer.

**Comment by kirwan** [comment]
We already had a report of this in #1558. I'm going to reopen that issue and produce the fix.

**Comment by Troll4it** [comment]
Thanks
