### ISSUE TITLE
java.lang.UnsatisfiedLinkError. Couldn't load imagepipeline

### ISSUE THREAD

**Issue by yihuaqi** [facebook/fresco#1767]
### Description

I observed some crash reports when using Fresco.

```
Fatal Exception: java.lang.UnsatisfiedLinkError: Couldn't load imagepipeline from loader dalvik.system.PathClassLoader[dexPath=/data/app/com.ss.android.article.master-12.apk,libraryPath=/data/app-lib/com.ss.android.article.master-12]: findLibrary returned null
       at java.lang.Runtime.loadLibrary(Runtime.java:358)
       at java.lang.System.loadLibrary(System.java:526)
       at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
       at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
       at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:48)
       at com.facebook.imagepipeline.memory.NativeMemoryChunk.(NativeMemoryChunk.java)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.free(NativeMemoryChunkPool.java:22)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:260)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.(NativePooledByteBufferOutputStream.java)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:143)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:28)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:94)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:37)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:72)
       at com.facebook.imagepipeline.backends.okhttp3.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:160)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

Looks like it happens constantly on users. Right now there're only two affected users, so I can't tell if it's related to specific model or android version. They're a Galaxy Note3 running Android 4.4.2, and a Xperia E3 Dual running Android 4.4.4.

### Reproduction

No. The crash are collected in the field.

### Solution

I tried to use ReLinker in SoLoaderShim, but I doubt if it would work since I'm not sure what the root cause is.

### Additional Information

* Fresco version: 1.2.0
* Platform version: Galaxy Note3 running Android 4.4.2, and Xperia E3 Dual running Android 4.4.4

**Comment by kirwan** [comment]
Use SoLoader or ReLinker to increase robustness of the native library loading.

This have been covered several times before, see #1336, #1005, #410
