### ISSUE TITLE
java.io.IOException with url containing  Katakana characters

### ISSUE THREAD

**Issue by trangchongcheng** [facebook/fresco#1768]
When i load image from url containing Katakana characters then java.io.IOException
This is url: https://s3-ap-northeast-1.amazonaws.com/arubaitotest/images/1494900363207-3MBよりも大きな画像.jpg_width730
` Error loading 14
                                                             java.io.IOException: Image URL https://s3-ap-northeast-1.amazonaws.com/arubaitotest/images/1494900363207-3MBよりも大きな画像.jpg_width730 returned HTTP code 403
                                                                 at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher.downloadFrom(HttpUrlConnectionNetworkFetcher.java:130)
                                                                 at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher.fetchSync(HttpUrlConnectionNetworkFetcher.java:81)
                                                                 at com.facebook.imagepipeline.producers.HttpUrlConnectionNetworkFetcher$1.run(HttpUrlConnectionNetworkFetcher.java:62)
                                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                 at java.lang.Thread.run(Thread.java:841)`

How to fix? Please help me

**Comment by kirwan** [comment]
That simple network fetcher converts a `Uri` into a `URL` for the `HttpURLConnection` API and calls `Uri.toString()`, which doesn't URL-encode as needed.

I have three suggestions.

1) You could try using the `OkHttpNetworkFetcher` and see if that works better. [Instructions here](http://frescolib.org/docs/using-other-network-layers.html#using-okhttp).
2) You could send us a pull request that fixes the [translation in `HttpUrlConnection`](https://github.com/facebook/fresco/blob/master/imagepipeline/src/main/java/com/facebook/imagepipeline/producers/HttpUrlConnectionNetworkFetcher.java#L136).
3) You could simply ensure your URIs are url-encoded before the `ImageRequest` is built.

**Comment by erikandre** [comment]
Closing, if the none of the 3 suggested solutions worked out then please comment here and we can reopen the issue.
