### ISSUE TITLE
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk

### ISSUE THREAD

**Issue by dongorigin** [facebook/fresco#1771]
### Description
Application startup crash
stack trace:
```
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.i(NativeMemoryChunkPool.java:60)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.b(NativeMemoryChunkPool.java:22)
	at com.facebook.imagepipeline.memory.BasePool.a(BasePool.java:260)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.b(NativePooledByteBufferFactory.java:100)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.a(NativePooledByteBufferFactory.java:28)
	at com.facebook.imagepipeline.cache.BufferedDiskCache.g(BufferedDiskCache.java:341)
	at com.facebook.imagepipeline.cache.BufferedDiskCache.b(BufferedDiskCache.java:38)
	at com.facebook.imagepipeline.cache.BufferedDiskCache$2.a(BufferedDiskCache.java:185)
	at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:168)
	at bolts.h$10.run(Task.java:357)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
```

### Reproduction
Only 1 device has this problem, but with very high frequency.
The device is OPPO:R8200 Android 4.4.4

### Additional Information
* Fresco version: [1.2.0]
* Platform version: [OPPO:R8200 Android 4.4.4]
* Android Studio 2.3.1
* build Fresco from AAR
* app hitting the 65k method limit, enable Multidex
* set up Fresco correctly

**Comment by kirwan** [comment]
I can see you're using Proguard.

Take a look at the [Using Proguard](http://frescolib.org/docs/proguard.html) section of the docs to see how to avoid stripping that and other classes.

**Comment by dongorigin** [comment]
I have set up Proguard correctly, and only one device has this problem.

**Comment by lambdapioneer** [comment]
@dongorigin Is it just that one particular device or all devices with that configuration?

**Comment by dongorigin** [comment]
Just one particular device

**Comment by 401885064** [comment]
what is last work ???    do  you   tall  me?
