### ISSUE TITLE
Crash when using useProguard false

### ISSUE THREAD

**Issue by saantiaguilera** [facebook/fresco#1773]
### Description

When using `useProguard false` for the built in shrinker of android as minifier, im getting the following crash:

```
05-18 20:55:43.124 23074-23074/? W/dalvikvm: Link of class 'Lcom/facebook/imagepipeline/animated/base/AnimatedDrawable;' failed
05-18 20:55:43.124 23074-23074/? E/dalvikvm: Could not find class 'com.facebook.imagepipeline.animated.base.AnimatedDrawable', referenced from method com.facebook.imagepipeline.animated.factory.AnimatedDrawableFactoryImpl.createAnimatedDrawable
05-18 20:55:43.124 23074-23074/? W/dalvikvm: VFY: unable to resolve new-instance 2047 (Lcom/facebook/imagepipeline/animated/base/AnimatedDrawable;) in Lcom/facebook/imagepipeline/animated/factory/AnimatedDrawableFactoryImpl;
05-18 20:55:43.124 23074-23074/? W/dalvikvm: Link of class 'Lcom/facebook/imagepipeline/animated/base/AnimatedDrawable;' failed
05-18 20:55:43.124 23074-23074/? W/dalvikvm: VFY: unable to find class referenced in signature (Lcom/facebook/imagepipeline/animated/base/AnimatedDrawable;)
05-18 20:55:43.124 23074-23074/? W/dalvikvm: VFY: returning Ljava/lang/Object; (cl=0x0), declared Landroid/graphics/drawable/Drawable; (cl=0x0)
05-18 20:55:43.124 23074-23074/? W/dalvikvm: VFY:  rejecting opcode 0x11 at 0x0010
05-18 20:55:43.124 23074-23074/? W/dalvikvm: VFY:  rejected Lcom/facebook/imagepipeline/animated/factory/AnimatedDrawableFactoryImpl;.create (Lcom/facebook/imagepipeline/image/CloseableImage;)Landroid/graphics/drawable/Drawable;
05-18 20:55:43.124 23074-23074/? W/dalvikvm: Verifier rejected class Lcom/facebook/imagepipeline/animated/factory/AnimatedDrawableFactoryImpl;
05-18 20:55:43.124 23074-23074/? W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xaf7b8b20)
05-18 20:55:43.124 23074-23074/? E/UncaughtException: java.lang.VerifyError: com/facebook/imagepipeline/animated/factory/AnimatedDrawableFactoryImpl
                                                          at com.facebook.imagepipeline.animated.factory.AnimatedFactoryImpl.createAnimatedDrawableFactory(AnimatedFactoryImpl.java:158)
                                                          at com.facebook.imagepipeline.animated.factory.AnimatedFactoryImpl.buildAnimatedDrawableFactory(AnimatedFactoryImpl.java:82)
                                                          at com.facebook.imagepipeline.animated.factory.AnimatedFactoryImpl.getAnimatedDrawableFactory(AnimatedFactoryImpl.java:112)
                                                          at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:63)
                                                          at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:49)
                                                          at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:42)
                                                          at com.facebook.drawee.backends.pipeline.Fresco.initializeDrawee(Fresco.java:76)
                                                          at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:69)
                                                          at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:46)
                                                          at com.u.tallerify.MainApplication.initializeFresco(MainApplication.java:78)
                                                          at com.u.tallerify.MainApplication.onCreate(MainApplication.java:33)
                                                          at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
                                                          at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:136)
                                                          at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                          at dalvik.system.NativeStart.main(Native Method)
05-18 20:55:43.354 23074-23074/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.u.tallerify, PID: 23074
                                                   java.lang.VerifyError: com/facebook/imagepipeline/animated/factory/AnimatedDrawableFactoryImpl
                                                       at com.facebook.imagepipeline.animated.factory.AnimatedFactoryImpl.createAnimatedDrawableFactory(AnimatedFactoryImpl.java:158)
                                                       at com.facebook.imagepipeline.animated.factory.AnimatedFactoryImpl.buildAnimatedDrawableFactory(AnimatedFactoryImpl.java:82)
                                                       at com.facebook.imagepipeline.animated.factory.AnimatedFactoryImpl.getAnimatedDrawableFactory(AnimatedFactoryImpl.java:112)
                                                       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:63)
                                                       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:49)
                                                       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:42)
                                                       at com.facebook.drawee.backends.pipeline.Fresco.initializeDrawee(Fresco.java:76)
                                                       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:69)
                                                       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:46)
                                                       at com.u.tallerify.MainApplication.initializeFresco(MainApplication.java:78)
                                                       at com.u.tallerify.MainApplication.onCreate(MainApplication.java:33)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                       at dalvik.system.NativeStart.main(Native Method)
```

The MainApplication code is this:

```Java
    private void initializeFresco() {
        PoolFactory poolFactory = new PoolFactory(PoolConfig.newBuilder().build());

        Dispatcher dispatcher = new Dispatcher();
        dispatcher.setMaxRequests(poolFactory.getFlexByteArrayPoolMaxNumThreads());

        OkHttpClient okHttpClient = new OkHttpClient.Builder()
            .dispatcher(dispatcher)
            .build();

        final int MAX_HEAP_SIZE = (int) Runtime.getRuntime().maxMemory();
        final int MAX_DISK_CACHE_SIZE = 40 * ByteConstants.MB;
        final int MAX_MEMORY_CACHE_SIZE = MAX_HEAP_SIZE / 4;
        final String CACHE_DIR = "fresco_pipeline_cache";

        final MemoryCacheParams bitmapCacheParams = new MemoryCacheParams(
            MAX_MEMORY_CACHE_SIZE,
            Integer.MAX_VALUE, 
            MAX_MEMORY_CACHE_SIZE,
            Integer.MAX_VALUE,
            Integer.MAX_VALUE);

        ImagePipelineConfig pipelineConfig =
            OkHttpImagePipelineConfigFactory.newBuilder(this, okHttpClient)
                .setPoolFactory(poolFactory)
                .setDownsampleEnabled(true)
                .setBitmapMemoryCacheParamsSupplier(
                new Supplier<MemoryCacheParams>() {
                    public MemoryCacheParams get() {
                        return bitmapCacheParams;
                    }
                })
                .setMainDiskCacheConfig(
                    DiskCacheConfig.newBuilder(this)
                        .setBaseDirectoryPath(getCacheDir())
                        .setBaseDirectoryName(CACHE_DIR)
                        .setMaxCacheSize(MAX_DISK_CACHE_SIZE)
                        .build())
                .build();

        Fresco.initialize(this, pipelineConfig);
    }
```

### Reproduction

Have the code shown above in the Application class. 
Have gradle debug buildType as:
```gradle
        debug {
            minifyEnabled true
            debuggable true
            useProguard false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro', 'proguard-debug-rules.pro' // Rules for my repository. Fresco ones are added of course
        }
```

Run the application. Sometimes it fails, sometimes it doesnt. If using proguard or none, the issue doesnt happen (so its tied up with the built-in shrinker)

### Solution

No idea, but its definetily something tied up with the built-in shrinker. Maybe theres a missing rule, and we've to keep some classname/\<init>/method?

### Additional Information

* Fresco version: 1.1.0
* Platform version: Whichever. Happened on Emulator Google Pixel api 16 and 24, Moto G 3 api 24, Nexus S api 19, Nexus 6 api 22

**Comment by saantiaguilera** [comment]
The crash happens in this application (if you want, just clone it and running it in debug should generate the crash)

https://github.com/tallerify/fiuba-taller-II-tallerify-android

**Comment by kirwan** [comment]
This is strange and I'm inclined to suggest it's a problem with the shrinker, which I note is still [referred to as "experimental" in the docs](https://developer.android.com/studio/build/shrink-code.html#gradle-shrinker).

The class `AnimatedFactoryImpl` is annotated `@DoNotStrip` because it is instantiated by reflection and your stack trace suggests it has not been removed. However, `AnimatedDrawableFactoryImpl` is referenced directly within that class and has been stripped.

This suggests to me that the `@DoNotStrip` is being honoured but that the shrinker doesn't ensure it keeps everything referenced in such classes.

**Comment by kirwan** [comment]
I'm closing this issue as I believe the issue lies with the experimental shrinker.
