### ISSUE TITLE
Vector drawable does not work as placeholder image on API 17 (and probably below API 21)

### ISSUE THREAD

**Issue by Gericop** [facebook/fresco#1779]
### Description

I have a `SimpleDraweeView` and a vector drawable XML. I tried to use the said XML as a placeholder in the Drawee but on API 17 (so probably below API 21) could not inflate the view and crashed the app.

[`AppCompatDelegate.setCompatVectorFromResourcesEnabled(true)`](https://developer.android.com/reference/android/support/v7/app/AppCompatDelegate.html#setCompatVectorFromResourcesEnabled(boolean)) does not seem to be a viable option as
> This feature defaults to disabled, since enabling it can cause issues with memory usage, and problems updating Configuration instances.

### Reproduction

Define the layout XML for the Drawee:
```xml
 <com.facebook.drawee.view.SimpleDraweeView
	android:id="@+id/cover"
	android:layout_width="60dp"
	android:layout_height="87dp"
	android:layout_marginEnd="12dp"
	android:layout_marginRight="12dp"
	app:imageUri="@{item.cover}"
	fresco:actualImageScaleType="centerCrop"
	fresco:placeholderImage="@drawable/ic_image_white_24dp"
	fresco:placeholderImageScaleType="centerInside"/>
```
where `@drawable/ic_image_white_24dp` is `ic_image_white_24dp.xml`:
```xml
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="24dp"
        android:height="24dp"
        android:viewportWidth="24.0"
        android:viewportHeight="24.0">
    <path
        android:fillColor="#FFFFFFFF"
        android:pathData="M21,19V5c0,-1.1 -0.9,-2 -2,-2H5c-1.1,0 -2,0.9 -2,2v14c0,1.1 0.9,2 2,2h14c1.1,0 2,-0.9 2,-2zM8.5,13.5l2.5,3.01L14.5,12l4.5,6H5l3.5,-4.5z"/>
</vector>
```

Note that the `SimpleDraweeView` has an `app:imageUri` attribute this is here because the data binding would not work otherwise, the implementation is pretty simple (it is not relevant to the bug though):
```java
@BindingAdapter({"imageUri"})
public static void loadImage(SimpleDraweeView view, Uri imageUrl) {
    view.setImageURI(imageUrl);
}
```

The layout gets inflated by `DataBindingUtil` from a `RecyclerView.Adapter` located in a (support) `Fragment` that is attached to the parent `AppCompatActivity`.

The gradle file contains the necessary line for supporting vector drawables on lower API levels:
```gradle
android {
    defaultConfig {
        vectorDrawables.useSupportLibrary = true
    }
}
```

### Additional Information

* Fresco version: 1.3.0
* Platform version: API 17, HTC One X
* Support lib version: 25.3.1

**Comment by lambdapioneer** [comment]
Thanks @Gericop for the detailed issue. Can you also print the relevant error message output from logcat?

**Comment by Gericop** [comment]
Sure, here you go: [error_log.txt](https://github.com/facebook/fresco/files/1019809/error_log.txt)

The most important part is this:
```java
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:881)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
	at android.content.res.Resources.loadDrawable(Resources.java:1995)
	... 83 more
```

It's pretty easy to find the problem: the `GenericDraweeHierarchyInflater` class' `getDrawable(...)` method uses `context.getResources()` to inflate the drawable. However, this cannot be used on pre-lollipop devices to inflate vector drawables, that task requires `AppCompatResources.getDrawable(...)`.

**Comment by oprisnik** [comment]
#1176 describes why this is currently not working. However, for now you can set the drawable in Java and it should work. I don't think we can easily change the inflater to use `AppCompatResources` since the whole library would have to depend on `AppCompatResources` otherwise. Another solution would be to extend `SimpleDraweeView` and inflate the placeholder manually using `AppCompatResources`.

**Comment by Gericop** [comment]
I think there are two options to solve this:
- A factory that would resolve the drawable if set via `ImagePipelineConfig.Builder` similar to `setPlatformBitmapFactory(...)`.
- An extra module that depends on the support lib and can provide the necessary classes for the support methods / classes.

Extending `SimpleDraweeView` would only solve the problem if custom attributes were introduced for all of the image types because the default `placeholderImage` (and other image setter) attribute gets resolved before anything else due to the super call, which would result in the same exception. Custom attributes might also mean that the `*ScaleType` attributes would need to be parsed too for the custom attributes.

**Comment by Gericop** [comment]
Also, I don't know if this should have a new issue (or have an issue at all), but the `GenericDraweeHierarchyInflater`'s [`updateBuilder(...)`](https://github.com/facebook/fresco/blob/533759d14aeca6c50167cc0b4abb7b9c9a070d90/drawee/src/main/java/com/facebook/drawee/generic/GenericDraweeHierarchyInflater.java#L113) method would be more maintainable and optimized with `switch` instead of lots of control flow instructions. The `switch` would do a lookup in O(1) (thanks to tableswitch since there are no holes in the attribute constant list) while the `if-else` needs to be evaluated as it goes on, and also a switch is far more readable especially in this case where there are only single-line commands, yet 25 of them. So I think it's not premature optimization but a real improvement.

**Comment by vbuberen** [comment]
@Gericop
I don't have such issues and can use vector drawables in XML in `placeholderImage` and there are no crashes on APIs down to 16 (min version in the actual production app). 
You might have a problem because of `vectorDrawables.useSupportLibrary = true`  property in your Gradle file according to [this](https://stackoverflow.com/a/36484749/3140227) StackOverflow thread.
- Fresco version: 1.5.0 (worked well on 1.3.0 too)
- Support lib version: 25.3.1

I think this issue can be closed since it is not a Fresco problem.

**Comment by Gericop** [comment]
@vbuberen Do you use `AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);` instead? Because that is still a no-no for the memory issues it might introduce (see the [documentation](https://developer.android.com/reference/android/support/v7/app/AppCompatDelegate.html#setCompatVectorFromResourcesEnabled(boolean))).

**Comment by vbuberen** [comment]
Nope, I don`t. As you might know, for devices with API lower than 21 PNGs are generated instead of vectors automatically - on some really old devices with small resolution screen you can see that some drawables aren`t clear-cut like vector drawables should be. But still everything works fine with Fresco and placeholders.

**Comment by Gericop** [comment]
@vbuberen Well, I've always had `vectorDrawables.useSupportLibrary = true` in my build.gradle, yet it crashes on < API 21 devices.

**Comment by vbuberen** [comment]
@Gericop Kind of strange. Have you tried to check everything without `DataBinding`? I looked at other related issues here, like #1176 and for me it looks like the problem with binding these generated PNGs. I came to such conclusion after checking how the same view behaves if I attach `onClick` to this image - placeholder image is still visible (I just commented image request to see only placeholder) on device with API 18, but if I click on it I get the same `ResourseNotFoundException`.

**Comment by ibtisamasif** [comment]
@oprisnik  i was able to fix this issue by adding `AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);` in the onCreate of Application class. and this automatically fixes `fresco:placeholderImage="@drawable/vector_graphic"`

I have tested this in API level 19.

A similar question is posted on [stackoverflow](https://stackoverflow.com/a/37864531/5105583)

This should also be added on official documentation FAQ's section.

**Comment by Gericop** [comment]
@ibtisamasif The problem with that call is [clearly documented](https://developer.android.com/reference/android/support/v7/app/AppCompatDelegate.html#setCompatVectorFromResourcesEnabled(boolean)):
> This feature defaults to disabled, since enabling it can cause issues with memory usage, and problems updating Configuration instances. If you update the configuration manually, then you probably do not want to enable this. You have been warned.
