### ISSUE TITLE
 load webp gif OutOfMemoryError in android 4.4 or  below

### ISSUE THREAD

**Issue by xiaoyao27610** [facebook/fresco#1808]
java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:822)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:799)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:766)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.createNewBitmap(AnimatedDrawableCachingBackendImpl.java:149)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.obtainBitmapInternal(AnimatedDrawableCachingBackendImpl.java:342)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.runPrefetch(AnimatedDrawableCachingBackendImpl.java:452)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.access$200(AnimatedDrawableCachingBackendImpl.java:53)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl$3.call(AnimatedDrawableCachingBackendImpl.java:412)
	at bolts.Task$4.run(Task.java:357)
	at com.facebook.common.executors.ConstrainedExecutorService$Worker.run(ConstrainedExecutorService.java:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
	at java.lang.Thread.run(Thread.java:841)

**Comment by lambdapioneer** [comment]
@xiaoyao27610, please provide details to make this actionable for us. The issues have a template with the information that we'd need. In this case especially the image file would be interesting.
