### ISSUE TITLE
#442 java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by wuao** [facebook/fresco#1811]
dalvik.system.VMRuntime.newNonMovableArray(Native Method)
2 android.graphics.Bitmap.nativeCreate(Native Method)
3 android.graphics.Bitmap.createBitmap(Bitmap.java:825)
4 android.graphics.Bitmap.createBitmap(Bitmap.java:802)
5 android.graphics.Bitmap.createBitmap(Bitmap.java:769)
6 com.facebook.imagepipeline.memory.e.i(Unknown Source)
7 com.facebook.imagepipeline.memory.e.b(Unknown Source)
8 com.facebook.imagepipeline.memory.BasePool.a(Unknown Source)
9 com.facebook.imagepipeline.i.a.a(Unknown Source)
10 com.facebook.imagepipeline.i.a.a(Unknown Source)
11 com.facebook.imagepipeline.f.a.a(Unknown Source)
12 com.facebook.imagepipeline.f.a.a(Unknown Source)
13 com.facebook.imagepipeline.producers.t.c(Unknown Source)
14 com.facebook.imagepipeline.producers.t.a(Unknown Source)
15 com.facebook.imagepipeline.producers.u.a(Unknown Source)
16 com.facebook.imagepipeline.producers.JobScheduler.e(Unknown Source)
17 com.facebook.imagepipeline.producers.JobScheduler.a(Unknown Source)
18 com.facebook.imagepipeline.producers.ak.run(Unknown Source)
19 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
20 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
21 com.facebook.imagepipeline.d.p.run(Unknown Source)
22 java.lang.Thread.run(Thread.java:818)

 

because  OOM  ！ so   i think  in  init time  add Thread Pool cache .because init cache is 4M.

**Comment by kirwan** [comment]
I can't tell anything from this about what might have taken the memory.

Have you used the Android Studio memory profiler to see if you have a leak?

Also, have you looked at http://frescolib.org/docs/troubleshooting.html ?

**Comment by oprisnik** [comment]
I'm closing this issue due to inactivity. If this is still a problem, let us know!

**Comment by deepbhavsar** [comment]
Hello, I am posting the whole log. don't close it. I am facing the issue

Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 1784908 byte allocation with 696584 free bytes and 680KB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:975)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:913)
       at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java)
       at com.facebook.imagepipeline.memory.BitmapPool.getBucketedSizeForValue(BitmapPool.java)
       at com.facebook.imagepipeline.memory.BasePool.initialize(BasePool.java)
       at com.facebook.imagepipeline.platform.ArtDecoder.decodeFromEncodedImage(ArtDecoder.java)
       at com.facebook.imagepipeline.platform.ArtDecoder.decodeFromEncodedImage(ArtDecoder.java)
       at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeJpeg(DefaultImageDecoder.java)
       at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java)
       at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.onProgressUpdateImpl(DecodeProducer.java)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java)
       at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java)
       at com.facebook.imagepipeline.producers.JobScheduler.clearJob(JobScheduler.java)
       at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java)
       at java.lang.Thread.run(Thread.java:818)
