### ISSUE TITLE
Load gif too much cause OOM

### ISSUE THREAD

**Issue by zhudongya123** [facebook/fresco#1814]
I use this code block to load gif image.
```java
                final SimpleDraweeView src = gifShowView.getSrc();
                GenericDraweeHierarchy hierarchy = src.getHierarchy();
                hierarchy.setPlaceholderImage(R.drawable.placeholder_white_big, ScalingUtils.ScaleType.CENTER_CROP);
                hierarchy.setActualImageScaleType(ScalingUtils.ScaleType.CENTER_CROP);
                hierarchy.setProgressBarImage(new CircleShapeProgressDrawable(activity));
                DraweeController controller = Fresco.newDraweeControllerBuilder()
                        .setUri(gif_url)
                        .setAutoPlayAnimations(true)
                        .setOldController(src.getController())
                        .setControllerListener(new BaseControllerListener<ImageInfo>() {
                            @Override
                            public void onFinalImageSet(String id, ImageInfo imageInfo, Animatable animatable) {
                                super.onFinalImageSet(id, imageInfo, animatable);
                                ImageView progressButton = gifShowView.getLoadButton();
                                progressButton.setVisibility(View.GONE);
                            }
                        })
                        .build();
                src.setHierarchy(hierarchy);
                src.setController(controller);
```
we have a viewpager contain some fragments, each fragment have a recyclerView, every recyclerView have 10+ and more gif images in adapter. most of gif size is from 200k to 5M. 

```java
java.lang.OutOfMemoryError: 
Failed to allocate a 10800012 byte allocation with 335920 free bytes and 328KB until OOM
                                                                       at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                       at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                                       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:613)
                                                                       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:446)
                                                                       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1080)
                                                                       at android.content.res.Resources.createFromResourceStream(Resources.java:2952)
                                                                       at android.content.res.Resources.loadDrawableForCookie(Resources.java:2684)
                                                                       at android.content.res.Resources.loadDrawable(Resources.java:2580)
                                                                       at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:387)
                                                                       at android.content.res.Resources.getDrawable(Resources.java:824)
                                                                       at android.content.res.Resources.getDrawable(Resources.java:789)
                                                                       at com.facebook.drawee.generic.GenericDraweeHierarchy.setPlaceholderImage(GenericDraweeHierarchy.java:456)
                                                                       at com.gif57.android.helper.ImageLoaderHelper.loadGifWithStrategyInternal(ImageLoaderHelper.java:154)
                                                                       at com.gif57.android.helper.ImageLoaderHelper.loadGifWithStrategy(ImageLoaderHelper.java:144)
                                                                       at com.gif57.android.ui.base.vh.BaseTopicViewHolder.bindBaseUI(BaseTopicViewHolder.java:119)
                                                                       at com.gif57.android.ui.fragment.first.home.HomeChildListFragment$HomeQuickAdapter.convert(HomeChildListFragment.java:108)
                                                                       at com.gif57.android.ui.fragment.first.home.HomeChildListFragment$HomeQuickAdapter.convert(HomeChildListFragment.java:95)
```

hprof file while run
![we used ](https://github.com/zhudongya123/Zdy_csdn_MarkDown/blob/master/ref/1.png)

**Comment by zhudongya123** [comment]
i noticed that the excption is thrown by setPlaceholderImage method, but our placeholder image isize is only 4KB.

**Comment by erikandre** [comment]
Hi @zhudongya123. About the placeholder, is 5KB the size on disk or the decoded bitmap size? (also, do you still get the crash if you don't set a placeholder drawable?)

You should also be able to use the hprof file to find out what is keeping the references to all those bitmaps.

**Comment by zhudongya123** [comment]
actually, when i remove the placeholder, the crash is dismiss. and about my placeholder,the file size is 5KB, but the resolution is 500 * 600.

**Comment by erikandre** [comment]
I see, that is quite strange. There are a few things that you might want to try

1. Try using a different drawable for placeholder and see if it still crashes
2. Use a shared drawable as placeholder and pass that in when binding the view
3. Check how much memory is used without the placeholder, maybe you are still close to running out of memory?

**Comment by zhudongya123** [comment]
Thanks, @erikandre.
Actually, 5KB is the size on disk, not bitmap size, our resolution of placeholder is 500 * 600, so the crash may be caused by the placeholder. When I removed the placeholder, it stopped crashing, and the memory reduced by 50% in this situation. I used MAT Tool to compare these two situations, here is the screenshot.
![](https://github.com/zhudongya123/Zdy_csdn_MarkDown/blob/master/ref/mat1.png)

**Comment by zhudongya123** [comment]
I change my resolution of placeholder from 500 * 600 to 100 *120, then everything is Ok, and I use a static Drawable to instead the id resource, the result is same.

**Comment by erikandre** [comment]
@zhudongya123, OK that's good :)

It's still a bit strange that when loading the original placeholder image was trying to allocate 10800012 bytes instead of the expected 1200000 bytes (600*500*4). The first number is almost exactly 9 times the expected (or exactly 9.00001).

I'm wondering if the device is somehow resizing the image incorrectly. It would be interesting to see what the actual dimensions are of the loaded placeholder (could be found out by getting the Bitmap from the loaded BitmapDrawable).

**Comment by erikandre** [comment]
btw. In which drawable folder in your project did you place the placeholder image?

**Comment by froxCZ** [comment]
+1

**Comment by zhudongya123** [comment]
@erikandre 
Your mean a picture with resolution of 500 * 600 in ARGB_8888 can consume 500 * 600 *4 bytes in application. And I found the original placeholder (500 * 600) is in the 'drawable' folder, no suffix. When I moved the file to the 'drawable-xxhdpi' folder , the problem was sovled, no more crash happened, when I move the file to 'drawable-mdpi' or 'drawable-ldpi' folder, the same crash happened again.
So, like you mentioned, imaged placed in wrong drawable folder may be the reason.  
I tested my app on RED MI NOTE 3, the resolution is 1920 *1080, 5.5 inch, and dpi is 400,using drawable-xxhdpi folder. Image allocated 9 times than origin space allocated, I guess the image was enlarged 3 times both in height and width.  a mdpi(160) resource placed in xxhdpi(480) folder, the allocation will be enlarged by (480/160)^2 times.

**Comment by zhudongya123** [comment]
And I encounter another error, this is Log.
```java
07-05 14:07:55.253 32047-32207/com.gif57.android E/AndroidRuntime: FATAL EXCEPTION: Thread-21395
                                                                   Process: com.gif57.android, PID: 32047
                                                                   java.lang.OutOfMemoryError: Failed to allocate a 546012 byte allocation with 424724 free bytes and 414KB until OOM
                                                                       at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                       at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
                                                                       at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.createNewBitmap(AnimatedDrawableCachingBackendImpl.java:149)
                                                                       at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.obtainBitmapInternal(AnimatedDrawableCachingBackendImpl.java:342)
                                                                       at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.runPrefetch(AnimatedDrawableCachingBackendImpl.java:452)
                                                                       at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl.access$200(AnimatedDrawableCachingBackendImpl.java:53)
                                                                       at com.facebook.imagepipeline.animated.impl.AnimatedDrawableCachingBackendImpl$3.call(AnimatedDrawableCachingBackendImpl.java:412)
                                                                       at bolts.Task$4.run(Task.java:357)
                                                                       at com.facebook.common.executors.ConstrainedExecutorService$Worker.run(ConstrainedExecutorService.java:178)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                                       at java.lang.Thread.run(Thread.java:818)
```
How to avoid this Error? Thanks :)
