### ISSUE TITLE
get java.lang.UnsatisfiedLinkError when load "libgifimage.so"

### ISSUE THREAD

**Issue by zjupure** [facebook/fresco#1817]
### Description

we use fresco in our app, in some devices there will load libgifimage.so failed. stacktrace as follow.
Is this error caused by so compile parameter? Is there a workaround to avoid this problem?

>>> backtrace <<<
java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "libgifimage.so" (built with --hash-style=gnu?)
	at java.lang.Runtime.loadLibrary(Runtime.java:372)
	at java.lang.System.loadLibrary(System.java:989)
	at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
	at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
	at com.facebook.animated.gif.GifImage.ensure(GifImage.java:46)
	at com.facebook.animated.gif.GifImage.create(GifImage.java:68)
	at com.facebook.animated.gif.GifImage.decode(GifImage.java:75)
	at com.facebook.imagepipeline.animated.factory.AnimatedImageFactoryImpl.decodeGif(AnimatedImageFactoryImpl.java:87)
	at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeGif(DefaultImageDecoder.java:145)
	at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:65)
	at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:126)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:240)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:112)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:145)
	at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
	at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
	at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
	at java.lang.Thread.run(Thread.java:818)

* Fresco version: 1.2.0
* Platform version: [5.0, vivo Y51A]

**Comment by erikandre** [comment]
Hi @zjupure!

Using SoLoader or ReLinker should fix this issue. More info for example in #1724, #1738, #1723, #933 and also here: https://github.com/facebook/SoLoader

If that does not help, please let us know and we can reopen this task. Thanks!
