### ISSUE TITLE
app crash width java.lang.NullPointerException

### ISSUE THREAD

**Issue by jacpy** [facebook/fresco#1839]
### Description

hi, there is a bug in my release app and crashed, here is all stack information width no delete, I cannot find the cause from my app.

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at com.facebook.drawee.drawable.RoundedBitmapDrawable.updateTransform(Unknown Source)
	at com.facebook.drawee.drawable.RoundedBitmapDrawable.draw(Unknown Source)
	at com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha(Unknown Source)
	at com.facebook.drawee.drawable.FadeDrawable.draw(Unknown Source)
	at com.facebook.drawee.drawable.ForwardingDrawable.draw(Unknown Source)
	at com.facebook.drawee.generic.RootDrawable.draw(Unknown Source)
	at android.widget.ImageView.onDraw(ImageView.java:1228)
	at android.view.View.draw(View.java:16320)
	at android.view.View.updateDisplayListIfDirty(View.java:15302)
	at android.view.View.draw(View.java:16090)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
	at android.view.View.updateDisplayListIfDirty(View.java:15297)
	at android.view.View.draw(View.java:16090)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
	at android.view.View.updateDisplayListIfDirty(View.java:15297)
	at android.view.View.draw(View.java:16090)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
	at android.view.View.updateDisplayListIfDirty(View.java:15297)
	at android.view.View.draw(View.java:16090)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
	at android.view.View.draw(View.java:16323)
	at android.widget.ScrollView.draw(ScrollView.java:1749)
	at android.view.View.updateDisplayListIfDirty(View.java:15302)
	at android.view.View.draw(View.java:16090)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
	at android.view.View.draw(View.java:16323)
	at android.view.View.updateDisplayListIfDirty(View.java:15302)
	at android.view.View.draw(View.java:16090)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
	at android.view.View.draw(View.java:16323)
	at android.view.View.updateDisplayListIfDirty(View.java:15302)
	at android.view.View.draw(View.java:16090)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
	at android.view.View.updateDisplayListIfDirty(View.java:15297)
	at android.view.View.draw(View.java:16090)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
	at android.view.View.draw(View.java:16323)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2769)
	at android.view.View.updateDisplayListIfDirty(View.java:15302)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:295)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:301)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:345)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2695)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2504)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2129)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1147)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6262)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:886)
	at android.view.Choreographer.doCallbacks(Choreographer.java:698)
	at android.view.Choreographer.doFrame(Choreographer.java:633)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:872)
	at android.os.Handler.handleCallback(Handler.java:743)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)

### Reproduction

my release app crash twice in the same place, but did not happen every times.

### Additional Information

* Fresco version: 1.3.0
* Platform version: HUAWEI NEM-AL10, EIMUI 4.1.2, android version 6.0.

**Comment by lambdapioneer** [comment]
Hi @jacpy, can you provide us with the code that you use for creating the image request and the drawee view?

Also the logcat output (see http://frescolib.org/docs/troubleshooting.html) would be very helpful.

**Comment by kirwan** [comment]
@jacpy It would also be useful to know if this happens for one specific image or if it's happened for different images.

**Comment by oprisnik** [comment]
Is this the same issue fixed by #1848 ?

**Comment by JuniperPhoton** [comment]
@oprisnik I think it is.

**Comment by kirwan** [comment]
#1848 is now merged so I'm closing this as fixed based on the stack trace here.
