### ISSUE TITLE
java.lang.UnsatisfiedLinkError in v1.4.0

### ISSUE THREAD

**Issue by wudongjiang333** [facebook/fresco#1852]
Process: com.desay_svautomotive.svmedia, PID: 3356
                                                                              java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/app/XXXMedia-release.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib, /system/vendor/vehicle/lib]]] couldn't find "libimagepipeline.so"
                                                                                  at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                                  at java.lang.System.loadLibrary(System.java:990)
                                                                                  at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
                                                                                  at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
                                                                                  at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:43)
                                                                                  at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:36)
                                                                                  at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
                                                                                  at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
                                                                                  at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:260)
                                                                                  at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
                                                                                  at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:100)
                                                                                  at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:28)
                                                                                  at com.facebook.imagepipeline.producers.LocalFetchProducer.getByteBufferBackedEncodedImage(LocalFetchProducer.java:90)
                                                                                  at com.facebook.imagepipeline.producers.LocalFetchProducer.getEncodedImage(LocalFetchProducer.java:102)
                                                                                  at com.facebook.imagepipeline.producers.LocalFileFetchProducer.getEncodedImage(LocalFileFetchProducer.java:35)
                                                                                  at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:55)
                                                                                  at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:51)
                                                                                  at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                  at java.lang.Thread.run(Thread.java:818)

**Comment by wudongjiang333** [comment]
My problem has been solved.Using ReLinker fix this issue. More info for example in #933
