### ISSUE TITLE
animate picture problem after version 1.4.0

### ISSUE THREAD

**Issue by lguipeng** [facebook/fresco#1869]
https://oexd4utdf.qnssl.com/5e008d091e074e8cef67_640_480.GIF
https://oexd4utdf.qnssl.com/a01dbf84723034ddd30f_640_480.GIF
https://oexd4utdf.qnssl.com/5063580c117dccb80db9_640_480.GIF

When those animate pictures play in the screen,  the List View UI lags seriously.
This only dose not happen on version 1.3.0, but after version 1.4.0

* Fresco version: 1.4.0  and 1.5.0
* Platform version: All Android Device

**Comment by oprisnik** [comment]
Do you have the same measurements for the old version? Could you post a comparison video? In all the tests I did, the new version performed way better.

**Comment by lguipeng** [comment]
http://oexd4utdf.qnssl.com/FhBwwD0FN0lFKHNZT16DDDpDUUKm
http://oexd4utdf.qnssl.com/Fk1K7Gy8gIFjjhLvuh6F9FWICKPZ
The first video is version 1.3.0,  and second one is version 1.5.0. I had used RecyclerView.
This is my content json file. [data.json](https://github.com/facebook/fresco/files/1231154/data.txt)
Thanks for your response!

**Comment by oprisnik** [comment]
Thanks for the videos and sample GIFs. I'll try to repro with one of our sample apps. This should not happen.

**Comment by lguipeng** [comment]
I also use setAspectRatio to make sure all content of image can been shown.
The image size can be gotten from image url, and .*_(\d+)_(\d+) is my regex. @oprisnik

**Comment by marcosalis** [comment]
Same thing happening here with 1.4, and the app is crashing with an `OutOfMemoryError`. The picture is a pretty big (in terms of frames resolution) animated gif of around 1.2 MB.

This is the stack trace I get:
`java.lang.OutOfMemoryError: Failed to allocate a 23890284 byte allocation with 10365672 free bytes and 9MB until OOM
                                                                                      at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                                      at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:977)
                                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
                                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:915)
                                                                                      at com.facebook.imagepipeline.animated.impl.AnimatedDrawableBackendImpl.renderImageDoesNotSupportScaling(AnimatedDrawableBackendImpl.java:217)
                                                                                      at com.facebook.imagepipeline.animated.impl.AnimatedDrawableBackendImpl.renderFrame(AnimatedDrawableBackendImpl.java:181)
                                                                                      at com.facebook.imagepipeline.animated.impl.AnimatedImageCompositor.renderFrame(AnimatedImageCompositor.java:121)
                                                                                      at com.facebook.imagepipeline.animated.factory.AnimatedImageFactoryImpl.createPreviewBitmap(AnimatedImageFactoryImpl.java:182)
                                                                                      at com.facebook.imagepipeline.animated.factory.AnimatedImageFactoryImpl.getCloseableImage(AnimatedImageFactoryImpl.java:144)
                                                                                      at com.facebook.imagepipeline.animated.factory.AnimatedImageFactoryImpl.decodeGif(AnimatedImageFactoryImpl.java:89)
                                                                                      at com.facebook.fresco.animation.factory.AnimatedFactoryV2Impl$1.decode(AnimatedFactoryV2Impl.java:90)
                                                                                      at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeGif(DefaultImageDecoder.java:146)
                                                                                      at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:64)
                                                                                      at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:125)
                                                                                      at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:248)
                                                                                      at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:112)
                                                                                      at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:145)
                                                                                      at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                                                                                      at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                                                                                      at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                      at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                                                      at java.lang.Thread.run(Thread.java:762)`

**Comment by kraghu** [comment]
@oprisnik can you suggest any workaround fix meanwhile ?

**Comment by ysh512** [comment]
I also met the same problem，but my app does not display the gif.

**Comment by Anilugale** [comment]
I also met the same problem

**Comment by Sai-Deepthi** [comment]
Is any solution available for this?
