### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by 654277633** [facebook/fresco#1911]
Fatal Exception: java.lang.UnsatisfiedLinkError: (<clinit> failed, see exception in other thread)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:58)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:20)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:257)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.(NativePooledByteBufferOutputStream.java)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:141)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:26)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:92)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:35)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:70)
       at com.xx.network.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:122)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

**Comment by kirwan** [comment]
This is usually due to issues loading the native library and we generally recommend using ReLinker or SoLoader. See the [comment here for steps](https://github.com/facebook/fresco/issues/933#issuecomment-186266187).
