### ISSUE TITLE
Crash when prepare animated drawable frame after update to 1.5.0

### ISSUE THREAD

**Issue by xjy2061** [facebook/fresco#1929]
### Description

java.lang.RuntimeException: Failed to pin Bitmap
at com.facebook.imagepipeline.nativecode.Bitmaps.nativePinBitmap(Native Method)
at com.facebook.imagepipeline.nativecode.Bitmaps.pinBitmap(ProGuard:41)
at com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.pinBitmap(ProGuard:156)
at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.pinBitmap(ProGuard:30)
at com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.decodeJPEGFromEncodedImage(ProGuard:91)
at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.decodeJPEGFromEncodedImage(ProGuard:30)
at com.facebook.imagepipeline.bitmaps.HoneycombBitmapFactory.createBitmapInternal(ProGuard:63)
at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap(ProGuard:76)
at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap(ProGuard:43)
at com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.prepareFrameAndCache(ProGuard:144)
at com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.prepareFrameAndCache(ProGuard:162)
at com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.run(ProGuard:112)
at com.facebook.common.executors.ConstrainedExecutorService$Worker.run(ProGuard:177)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(ProGuard:42)
at java.lang.Thread.run(Thread.java:841)

### Reproduction

We can not reproduction this crash, the stack trace come from our crash report system.

### Additional Information

* Fresco version: 1.5.0
* Platform version: android4.4.4, Xiaomi HM2A

**Comment by erikandre** [comment]
Merging with #1862
