### ISSUE TITLE
UnsatisfiedLinkError in Sample app on x86_64

### ISSUE THREAD

**Issue by robert-wallis** [facebook/fresco#193]
When scrolling fast in the sample app on a Galaxy S6 we get this error:

This is possibly related to #120 #121 #171 #176 and #192 .

```
04-23 20:56:16.452  25908-26161/? E/AndroidRuntime﹕ FATAL EXCEPTION: pool-2-thread-1
    Process: com.facebook.fresco.sample, PID: 25908
    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.facebook.fresco.sample-1/lib/arm64/libgifimage.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:371)
            at java.lang.System.loadLibrary(System.java:989)
            at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:34)
            at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
            at com.facebook.imagepipeline.gif.GifImage.ensure(GifImage.java:42)
            at com.facebook.imagepipeline.gif.GifImage.create(GifImage.java:64)
            at com.facebook.imagepipeline.animated.factory.AnimatedImageFactory.decodeGif(AnimatedImageFactory.java:62)
            at com.facebook.imagepipeline.decoder.ImageDecoder.decodeAnimatedGif(ImageDecoder.java:105)
            at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:86)
            at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:232)
            at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:92)
            at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$3.run(DecodeProducer.java:202)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by tyronen** [comment]
Hmm is this using #176? I think we'll need to edit the productFlavors closure in the sample app's build.gradle.

**Comment by robert-wallis** [comment]
Yes thank you, I tried with `master`, and I can't reproduce the crash.
After running `master`, I verified by building #176 again, and the sample app crashed again.

I'll add the above stacktrace to #176
