### ISSUE TITLE
System.loadlibimagepipeline.so error

### ISSUE THREAD

**Issue by crazies** [facebook/fresco#1941]
```
 ndk {
            //APP的build.gradle设置支持的SO库架构
            abiFilters 'armeabi'
        }
```
```
  compile 'com.facebook.fresco:fresco:0.12.0'
```

My mobile phone Android 7 glory 8 can't show pictures, and another phone crashes directly   error  
```
Build version: 3.4.2 
Build date: 1979-11-30 00:00:00 
Current date: 2017-10-19 15:15:39 
Device: OPPO R9s 
 
Stack trace:  
java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.imagepipeline.memory.NativeMemoryChunk; see exception in other thread
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:98)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
	at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:338)
	at com.facebook.imagepipeline.cache.BufferedDiskCache.access$400(BufferedDiskCache.java:38)
	at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:184)
	at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:168)
	at bolts.Task$4.run(Task.java:357)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

```

**Comment by erikandre** [comment]
Hi @crazies 

First of all, I would recommend that you update to the latest version of Fresco. v0.12.0 is more than a year old.

If you change the NDK abi filter to include armeabi-v7a. Does that make a difference?

**Comment by crazies** [comment]
嗯，我最后使用     abiFilters 'armeabi' 解决了这个问题 可能是其他库的so不完整导致
Well, I ended up ·using `abiFilters'armeabi' `to solve this problem, probably due to incomplete so of other libraries

**Comment by crazies** [comment]
And com.facebook.fresco:fresco:0.12.0, I thought it was the latest version, and I saw it from the official website SDK document
