### ISSUE TITLE
Problem with progressive loading 

### ISSUE THREAD

**Issue by artyomdangizyan** [facebook/fresco#1956]
I am using fresco version 1.5.0. When I am loading many at the same time with progressive loading I notice that some images are failing to load and when I am looking at fesco logs I this kind of log and this IllegalArgumentException is not telling what is wrong. And this happend after updated from 1.2.0 to 1.5.0
```
11-14 16:11:23.764 20024 22387 V unknown:RequestLoggingListener: time 57117739: onProducerFinishWithSuccess: {requestId: 689, producer: NetworkFetchProducer, elapsedTime: 1209 ms, extraMap: {fetch_time=1120, queue_time=89, image_size=18738, total_time=1209}}
11-14 16:11:23.764 20024 22387 V unknown:RequestLoggingListener: time 57117739: onUltimateProducerReached: {requestId: 689, producer: NetworkFetchProducer, elapsedTime: -1 ms, success: true}
11-14 16:11:23.765 20024 20428 V unknown:RequestLoggingListener: time 57117740: onProducerStart: {requestId: 689, producer: DecodeProducer}
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: time 57117740: onProducerFinishWithFailure: {requestId: 689, stage: DecodeProducer, elapsedTime: 0 ms, extraMap: {sampleSize=1, hasGoodQuality=true, imageFormat=JPEG, isFinal=false, encodedImageSize=240x358, queueTime=11, requestedImageSize=unknown}, throwable: java.lang.IllegalArgumentException}
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: java.lang.IllegalArgumentException
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: 	at com.facebook.common.internal.Preconditions.checkArgument(Preconditions.java:108)
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: 	at com.facebook.imagepipeline.memory.NativePooledByteBuffer.read(NativePooledByteBuffer.java:54)
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: 	at com.facebook.imagepipeline.image.EncodedImage.isCompleteAt(EncodedImage.java:267)
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: 	at com.facebook.imagepipeline.platform.ArtDecoder.decodeJPEGFromEncodedImage(ArtDecoder.java:101)
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: 	at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeJpeg(DefaultImageDecoder.java:184)
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: 	at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:59)
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: 	at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:122)
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: 	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:245)
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: 	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:109)
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: 	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:142)
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: 	at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:204)
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: 	at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:24)
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: 	at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:75)
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: 	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:42)
11-14 16:11:23.766 20024 20428 W unknown:RequestLoggingListener: 	at java.lang.Thread.run(Thread.java:818)
11-14 16:11:23.767 20024 20428 W unknown:RequestLoggingListener: time 57117742: onRequestFailure: {requestId: 689, elapsedTime: 1426 ms, throwable: java.lang.IllegalArgumentException}
```

**Comment by lambdapioneer** [comment]
@artyomdangizyan can you provide us with the image that fails here? Ideally, you can make it reproduce in the `samples:showcase` app that you can find in our repro

**Comment by HaykBrsoyan** [comment]
@artyomdangizyan details!!!

**Comment by oprisnik** [comment]
I'm closing this issue due to inactivity. If this is still a problem, let us know!
