### ISSUE TITLE
Error converting bytecode to dex

### ISSUE THREAD

**Issue by PeteSesto** [facebook/fresco#1957]
### "Error converting bytecode to dex" gradle error after updating Fresco from 1.3 > 1.5

```
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/facebook/imagepipeline/cache/MediaVariationsIndexDatabase;
Error:com.android.dex.DexException: Multiple dex files define Lcom/facebook/imagepipeline/cache/MediaVariationsIndexDatabase;
Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForNewyorkDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/facebook/imagepipeline/cache/MediaVariationsIndexDatabase;
```

* Fresco version: 1.5
* Platform version: Android Studio ver 3.0 stable. Gradle version 3.0.0

**Comment by PeteSesto** [comment]
Nevermind.  Was an issue with android studio not doing proper clean
