### ISSUE TITLE
BUG UnsatisfiedLinkError Android 4.4 use com.facebook.fresco:fresco:0.13.0 

### ISSUE THREAD

**Issue by fengruyi** [facebook/fresco#1960]
java.lang.UnsatisfiedLinkError: Native method not found: com.facebook.imagepipeline.memory.NativeMemoryChunk.nativeAllocate:(I)J
	at com.facebook.imagepipeline.memory.NativeMemoryChunk.nativeAllocate(Native Method)
	at com.facebook.imagepipeline.memory.NativeMemoryChunk.(NativeMemoryChunk.java:58)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.(NativePooledByteBufferOutputStream.java:53)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:141)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:26)
	at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:94)
	at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:37)
	at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:72)
	at com.oppo.community.app.n.onResponse(OkHttpNetworkFetcher.java:158)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

**Comment by efrohnhoefer** [comment]
There are number of issues loading native libraries on older versions of Android. There are a number of similar issues already reported. Give either [SoLoader](https://github.com/facebook/SoLoader) or [ReLinker](https://github.com/KeepSafe/ReLinker) a try.

If you want to use ReLinker you can just add the following before initializing Fresco:

```
        SoLoaderShim.setHandler(soName ->
                ReLinker.loadLibrary(context, soName)
        );
```
