### ISSUE TITLE
NullPointerException on views when using Fresco

### ISSUE THREAD

**Issue by coding-chick** [facebook/fresco#1977]
### Description

Getting a crash when using Fresco when transitioning between screens:

Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference Raw Text
--
 
Stack trace: 
For Android 7 and above:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
       at android.view.ViewGroup.dispatchVisibilityAggregated(ViewGroup.java:1302)
       at android.view.ViewGroup.dispatchVisibilityAggregated(ViewGroup.java:1303)
       at android.view.ViewGroup.dispatchVisibilityAggregated(ViewGroup.java:1303)
       at android.view.ViewGroup.dispatchVisibilityAggregated(ViewGroup.java:1303)
       at android.view.ViewGroup.dispatchVisibilityAggregated(ViewGroup.java:1303)
       at android.view.ViewGroup.dispatchVisibilityAggregated(ViewGroup.java:1303)
       at android.view.ViewGroup.dispatchVisibilityAggregated(ViewGroup.java:1303)
       at android.view.ViewGroup.dispatchVisibilityAggregated(ViewGroup.java:1303)
       at android.view.View.setFlags(View.java:11503)
       at android.view.View.setVisibility(View.java:8014)
       at com.pinterest.framework.screens.ScreenManagerV1.showScreen(SourceFile:306)
```

For lower OS versions:

```
android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:2887)
android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:2887)
android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:2887)
android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:2887)
android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:2887)
android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:2887)
android.view.ViewGroup.addViewInner (ViewGroup.java:4392)
android.view.ViewGroup.addView (ViewGroup.java:4189)
android.view.ViewGroup.addView (ViewGroup.java:4130)
com.pinterest.framework.screens.ScreenManagerV1.showScreen (SourceFile:313)
com.pinterest.framework.screens.ScreenManagerV1.pop$framework_screens_release (SourceFile:180)
com.pinterest.framework.screens.l.h (SourceFile:422)
com.pinterest.activity.task.activity.MainActivity.preActivityBackPress (SourceFile:19227)
com.pinterest.kit.activity.a.onBackPressed (SourceFile:369)
android.app.Activity.onKeyUp (Activity.java:2482)
```

### Reproduction

We see this crash in the wild, *only when Fresco is enabled* (100%) when navigating between two screens. 

### Solution

Is this related to attaching/ detaching fresco images?

### Additional Information

* Fresco version: 1.5.0

**Comment by halizton** [comment]
This actually happens on all the OS versions, we have seen a similar one on OS level < 7.

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference

android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:2887)
android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:2887)
android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:2887)
android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:2887)
android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:2887)
android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:2887)
android.view.ViewGroup.addViewInner (ViewGroup.java:4392)
android.view.ViewGroup.addView (ViewGroup.java:4189)
android.view.ViewGroup.addView (ViewGroup.java:4130)
com.pinterest.framework.screens.ScreenManagerV1.showScreen (SourceFile:313)
com.pinterest.framework.screens.ScreenManagerV1.pop$framework_screens_release (SourceFile:180)
com.pinterest.framework.screens.l.h (SourceFile:422)
com.pinterest.activity.task.activity.MainActivity.preActivityBackPress (SourceFile:19227)
com.pinterest.kit.activity.a.onBackPressed (SourceFile:369)
android.app.Activity.onKeyUp (Activity.java:2482)
```

**Comment by foghina** [comment]
This doesn't look like anything I've seen before :(. It looks like the call isn't even making it into some a DraweeView, or any Fresco code for that matter.

DraweeViews are leaf nodes, we don't have any `ViewGroup`s in Fresco that would potentially cause this.

Is there any chance that your A/B experiment is not fully initialized or something, thus returning a `null` view somewhere?

I'm really scratching my head at this one. It shouldn't be possible to have a null view in a hierarchy, which is probably why `dispatchVisibilityAggregated` isn't guarding against it. Could be an Android bug?

I'm guessing you're not able to repro this locally, right? Try switching screens really quickly / a lot (maybe even write an espresso test that does it). Could be some weird race condition.

I'm sorry this isn't more helpful, but I don't have a lot to go on without code / a repro.

**Comment by foghina** [comment]
I believe this was fixed :-)
