### ISSUE TITLE
java.lang.ClassCastException: com.facebook.drawee.generic.GenericDraweeHierarchy$RootFadeDrawable cannot be cast to com.facebook.drawee.drawable.RoundedCornersDrawable

### ISSUE THREAD

**Issue by zmingchun** [facebook/fresco#199]
hi,everyone,I want change the SimpleDraweeView roundingParams with JAVA code, code as
      
    SimpleDraweeView view = convertView.findViewById(viewId);
        ImageRequest imageRequest =
                ImageRequestBuilder.newBuilderWithSource(Uri.parse(imageUrl))
                        .setAutoRotateEnabled(true)
                        //缩放显示，just for JPEG
                        .setResizeOptions(new ResizeOptions(view.getLayoutParams().width, view.getLayoutParams().height))
                        .build();
        DraweeController draweeController = Fresco.newDraweeControllerBuilder()
                .setImageRequest(imageRequest)
                .setOldController(view.getController())
                .setAutoPlayAnimations(true)
                .build();
        view.setController(draweeController);
        //setting roundingParams
        if(roundingType != -1) {
            GenericDraweeHierarchy gdhConfig = new GenericDraweeHierarchyBuilder(context.getResources())
                    .setPlaceholderImage(ResourcesHelper.sPlaceholderDrawable)
                    .setFailureImage(ResourcesHelper.sErrorDrawable)
                    **.setRoundingParams(RoundingParams.asCircle())**
                    .setProgressBarImage(new ProgressBarDrawable())
                    .build();
            view.setHierarchy(gdhConfig);
            
            **RoundingParams roundingParams =
                    view.getHierarchy().getRoundingParams();**
            //roundingParams.setRoundAsCircle(true);
            switch (roundingType){
                case 0:
                    roundingParams.setCornersRadius(10f);//圆角半径设置
                    roundingParams.setBorder(R.color.bullred, 2.0f);
                    roundingParams.setOverlayColor(context.getResources().getColor(R.color.material_blue_grey_800));
                    break;
                case 1:
                    roundingParams.setCornersRadius(5f);//圆角半径设置
                    roundingParams.setBorder(R.color.bullred, 1.0f);
                    roundingParams.setOverlayColor(context.getResources().getColor(R.color.material_blue_grey_800));
                    break;
            }
           ** view.getHierarchy().setRoundingParams(roundingParams);**
        }

 when run , I got that Exception:

     04-25 10:50:41.455  22001-22001/cn.zmingchun.justforfun E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: cn.zmingchun.justforfun, PID: 22001
    **java.lang.ClassCastException: com.facebook.drawee.generic.GenericDraweeHierarchy$RootFadeDrawable cannot be cast to com.facebook.drawee.drawable.RoundedCornersDrawable**
            at com.facebook.drawee.generic.GenericDraweeHierarchy.setRoundingParams(GenericDraweeHierarchy.java:636)
            at cn.zmingchun.justforfun.common.AdapterHelper.BaseAdapterHelper.setImageUrl(BaseAdapterHelper.java:258)
            at cn.zmingchun.justforfun.ui.fragment.HomeMainChatGroupFragment$2.convert(HomeMainChatGroupFragment.java:229)
            at cn.zmingchun.justforfun.ui.fragment.HomeMainChatGroupFragment$2.convert(HomeMainChatGroupFragment.java:225)
            at cn.zmingchun.justforfun.common.AdapterHelper.BaseQuickAdapter.getView(BaseQuickAdapter.java:102)
            at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
            at android.widget.AbsListView.obtainView(AbsListView.java:2282)
            at android.widget.ListView.makeAndAddView(ListView.java:1790)
            at android.widget.ListView.fillDown(ListView.java:691)
            at android.widget.ListView.fillSpecific(ListView.java:1349)
            at android.widget.ListView.layoutChildren(ListView.java:1608)
            at android.widget.AbsListView.onLayout(AbsListView.java:2113)
            at android.view.View.layout(View.java:14841)
            at android.view.ViewGroup.layout(ViewGroup.java:4631)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
            at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1660)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1436)
            at android.view.View.layout(View.java:14841)
            at android.view.ViewGroup.layout(ViewGroup.java:4631)
            at in.srain.cube.views.ptr.PtrFrameLayout.layoutChildren(PtrFrameLayout.java:250)
            at in.srain.cube.views.ptr.PtrFrameLayout.onLayout(PtrFrameLayout.java:219)
            at android.view.View.layout(View.java:14841)
            at android.view.ViewGroup.layout(ViewGroup.java:4631)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
            at android.view.View.layout(View.java:14841)
            at android.view.ViewGroup.layout(ViewGroup.java:4631)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:14841)
            at android.view.ViewGroup.layout(ViewGroup.java:4631)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
            at android.view.View.layout(View.java:14841)
            at android.view.ViewGroup.layout(ViewGroup.java:4631)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:14841)
            at android.view.ViewGroup.layout(ViewGroup.java:4631)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
            at android.view.View.layout(View.java:14841)
            at android.view.ViewGroup.layout(ViewGroup.java:4631)
            at cn.zmingchun.justforfun.ui.widget.ResideMenu.TouchDisableView.onLayout(TouchDisableView.java:57)
            at android.view.View.layout(View.java:14841)
            at android.view.ViewGroup.layout(ViewGroup.java:4631)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:14841)
            at android.view.ViewGroup.layout(ViewGroup.java:4631)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:14841)
            at android.view.ViewGroup.layout(ViewGroup.java:4631)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1983)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1740)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.j

Is that anything I missing? Please help,thank you.

**Comment by zmingchun** [comment]
I fit it，just change my config instead of:

          SimpleDraweeView view = convertView.findViewById(viewId);
        ImageRequest imageRequest =
                ImageRequestBuilder.newBuilderWithSource(Uri.parse(imageUrl))
                        .setAutoRotateEnabled(true)
                        //缩放显示，just for JPEG
                        .setResizeOptions(new ResizeOptions(view.getLayoutParams().width, view.getLayoutParams().height))
                        .build();
        DraweeController draweeController = Fresco.newDraweeControllerBuilder()
                .setImageRequest(imageRequest)
                .setOldController(view.getController())
                .setAutoPlayAnimations(true)
                .build();
        view.setController(draweeController);
        //setting roundingParams
        if(roundingType != -1) {
            RoundingParams roundingParams = new RoundingParams();
            roundingParams.setRoundAsCircle(true);
            switch (roundingType){
                case 0://截图
                    roundingParams.setCornersRadius(10f);//圆角半径设置
                    roundingParams.setBorder(R.color.gray_light04, 2.0f);
                    break;
                case 1://头像
                    roundingParams.setCornersRadius(5f);//圆角半径设置
                    roundingParams.setBorder(R.color.gray_light04, 1.0f);
                    break;
            }
            GenericDraweeHierarchy gdhConfig = new GenericDraweeHierarchyBuilder(context.getResources())
                    .setPlaceholderImage(ResourcesHelper.sPlaceholderDrawable)
                    .setFailureImage(ResourcesHelper.sErrorDrawable)
                    .setRoundingParams(roundingParams)
                    .setProgressBarImage(new ProgressBarDrawable())
                    .build();
            view.setHierarchy(gdhConfig);
        }

Oh，how could I get the Best practices of Rresco? Maybe that is another issues.

**Comment by plamenko** [comment]
RoundingMethod cannot be changed when changing dynamically.
http://frescolib.org/docs/rounded-corners-and-circles.html#_

This was the issue:

     RoundingParams roundingParams = view.getHierarchy().getRoundingParams();
     roundingParams.setRoundAsCircle(true);
  
The workaround is to build a new hierarchy as you already did in your next comment.
