### ISSUE TITLE
Improve error handling for setFirstAvailableImageRequests()

### ISSUE THREAD

**Issue by yihuaqi** [facebook/fresco#2001]
### Description

We have found crashes on devices of old Android versions. I'm not sure what I have done wrong. Can you give me some clue that why it would happen so I can pinpoint the issue? 

Thanks very much.

Here's the stacktrace:

```
Fatal Exception: java.lang.IllegalArgumentException: List of suppliers is empty!
       at com.facebook.common.internal.Preconditions.checkArgument(Preconditions.java:122)
       at com.facebook.datasource.FirstAvailableDataSourceSupplier.(FirstAvailableDataSourceSupplier.java)
       at com.facebook.datasource.FirstAvailableDataSourceSupplier.create(FirstAvailableDataSourceSupplier.java:41)
       at com.facebook.drawee.controller.AbstractDraweeControllerBuilder.getFirstAvailableDataSourceSupplier(AbstractDraweeControllerBuilder.java:370)
       at com.facebook.drawee.controller.AbstractDraweeControllerBuilder.obtainDataSourceSupplier(AbstractDraweeControllerBuilder.java:337)
       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilder.obtainController(PipelineDraweeControllerBuilder.java:88)
       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilder.obtainController(PipelineDraweeControllerBuilder.java:37)
       at com.facebook.drawee.controller.AbstractDraweeControllerBuilder.buildController(AbstractDraweeControllerBuilder.java:311)
       at com.facebook.drawee.controller.AbstractDraweeControllerBuilder.build(AbstractDraweeControllerBuilder.java:295)
       at com.ss.android.application.app.image.FrescoLoader.getController(FrescoLoader.java:773)
       at com.ss.android.application.app.image.FrescoLoader.access$000(FrescoLoader.java:105)
       at com.ss.android.application.app.image.FrescoLoader$6.onPreDraw(FrescoLoader.java:347)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:680)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1848)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:990)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4359)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
       at android.view.Choreographer.doCallbacks(Choreographer.java:562)
       at android.view.Choreographer.doFrame(Choreographer.java:532)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:5092)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:564)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

### Reproduction
Cannot reproduce. It only happens in production. 

### Additional Information

* Fresco version: com.facebook.fresco:fresco:1.2.0
* Platform version: Most of the crashes Xperia Z1f, HTC J Butterfly. Android 4.2.2 and 4.1.1

**Comment by yihuaqi** [comment]
@erikandre Got it. I am using setFirstAvailableImageRequests(...) and forget to take care of the case that it might be empty. Thanks for your help!

Might it be better to throw the exception in setFirstAvailableImageRequests(...) at once if it would certainly result in crash later on? The stacktrace is hard to decypher.

**Comment by erikandre** [comment]
@yihuaqi, great :)

Yes, you're right, having a better error message for this would be very useful. I'll add it to the list of future improvements.
You are also very welcome to submit a pull request.

Thanks!

**Comment by yihuaqi** [comment]
@erikandre I start doubting if it is the real reason for that crash. The backend are pretty sure that they will not return an empty url list, and because of the fact that the crash only happens on Android 4.X, I don't think they are lying to me. Is it possible that somewhere else might go wrong on some OS version? 

I'll gather more debug information on next release to confirm my guess. The crash distribution on OS version really disturbs me.

**Comment by yihuaqi** [comment]
@erikandre With more detailed debug info, I finally found out the root cause of the problem is that JSONArray has some compatibility issue when doing serialization on those devices. Nothing wrong with Fresco. Thanks for your Great SDK!

**Comment by erikandre** [comment]
Fixed in https://github.com/facebook/fresco/commit/6449ca0162a856f32898ff82b6ce41250b038535

I've changed the behaviour to assert that the arguments are not empty at an earlier point. That should make it easier for others who might run into this.
