### ISSUE TITLE
out of OutOfMemoryError  

### ISSUE THREAD

**Issue by Yinzeyu** [facebook/fresco#2017]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.aimymusic.android, PID: 15590
                                                                       java.lang.OutOfMemoryError: Failed to allocate a 518412 byte allocation with 336456 free bytes and 328KB until OOM
                                                                           at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                           at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                           at android.graphics.Bitmap.createBitmap(Bitmap.java:977)
                                                                           at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
                                                                           at android.graphics.Bitmap.createBitmap(Bitmap.java:915)
                                                                           at com.facebook.imagepipeline.animated.impl.AnimatedDrawableBackendImpl.prepareTempBitmapForThisSize(AnimatedDrawableBackendImpl.java:196)
                                                                           at com.facebook.imagepipeline.animated.impl.AnimatedDrawableBackendImpl.renderImageSupportsScaling(AnimatedDrawableBackendImpl.java:211)
                                                                           at com.facebook.imagepipeline.animated.impl.AnimatedDrawableBackendImpl.renderFrame(AnimatedDrawableBackendImpl.java:179)
                                                                           at com.facebook.imagepipeline.animated.impl.AnimatedImageCompositor.renderFrame(AnimatedImageCompositor.java:108)
                                                                           at com.facebook.fresco.animation.bitmap.wrapper.AnimatedDrawableBackendFrameRenderer.renderFrame(AnimatedDrawableBackendFrameRenderer.java:74)
                                                                           at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.renderFrameInBitmap(BitmapAnimationBackend.java:305)
                                                                           at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback(BitmapAnimationBackend.java:209)
                                                                           at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback(BitmapAnimationBackend.java:229)
                                                                           at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback(BitmapAnimationBackend.java:229)
                                                                           at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrame(BitmapAnimationBackend.java:164)
                                                                           at com.facebook.fresco.animation.backend.AnimationBackendDelegate.drawFrame(AnimationBackendDelegate.java:61)
                                                                           at com.facebook.fresco.animation.backend.AnimationBackendDelegateWithInactivityCheck.drawFrame(AnimationBackendDelegateWithInactivityCheck.java:111)
                                                                           at com.facebook.fresco.animation.drawable.AnimatedDrawable2.draw(AnimatedDrawable2.java:208)
                                                                           at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:147)
                                                                           at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:147)
                                                                           at com.facebook.drawee.drawable.ScaleTypeDrawable.draw(ScaleTypeDrawable.java:125)
                                                                           at com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha(FadeDrawable.java:304)
                                                                           at com.facebook.drawee.drawable.FadeDrawable.draw(FadeDrawable.java:291)
                                                                           at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:147)
                                                                           at com.facebook.drawee.generic.RootDrawable.draw(RootDrawable.java:83)
                                                                           at android.widget.ImageView.onDraw(ImageView.java:1268)
                                                                           at android.view.View.draw(View.java:18319)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:17297)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
01-05 21:17:46.748 15590-15590/com.aimymusic.android E/AndroidRuntime:     at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                           at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3950)
                                                                           at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3930)
                                                                           at android.view.View.updateDisplayListIfDirty(View.java:17260)
                                                                           at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:666)
                                                                           at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:672)
                                                                           at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:780)
                                                                           at android.view.ViewRootImpl.draw(ViewRootImpl.java:3105)
                                                                           at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2901)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2495)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1502)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7044)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:702)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:638)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6646)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by erikandre** [comment]
Hi @Yinzeyu 

Could you please provide more details.

- What kind of images are you loading?
- How large are they?
- Are you setting any ResizeOptions when loading the image?

**Comment by Yinzeyu** [comment]
http://dev.storage.singworld.net/0/2/app_703d0eccbe9eba972c41efa96bb2d244.webp 的图片 每张1m  大概 100张左右，初始加载最多60张 ，设置了 ResizeOptions 180 180

  ControllerListener<ImageInfo> controllerListener = new BaseControllerListener<ImageInfo>() {
            @Override
            public void onFinalImageSet(String id, @Nullable ImageInfo imageInfo, @Nullable Animatable anim) {
                if (anim != null) {
                    simpleDraweeView.setTag(R.id.animatable, anim);
                    anim.start();
                }
            }
        };
        ImageRequest request = ImageRequestBuilder.newBuilderWithSource(Uri.parse(url == null ? "http://" : url))
                .setResizeOptions(new ResizeOptions(SizeUtils.dp2px(180), SizeUtils.dp2px(180)))
                .build();
        GenericDraweeHierarchy hierarchy = new
                GenericDraweeHierarchyBuilder(context.getResources())
                .setPlaceholderImage(holderResource)
                .setFailureImage(holderResource)
                .setActualImageScaleType(ScalingUtils.ScaleType.CENTER_CROP)//缩放类型—ScaleType：
                .build();
        simpleDraweeView.setHierarchy(hierarchy);
        DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setImageRequest(request).setControllerListener(controllerListener).build();
        simpleDraweeView.setController(controller);

**Comment by Yinzeyu** [comment]
现在的webp   应该在生成时候也做了压缩  没有也就几百k 的样子 ，但是同时在播放的话  在加载更多  就会出现问题

**Comment by S-Co** [comment]
@erikandre All are webp format animation, the size of each image between 100KB to 1.5M. OOM happens even if I set the ResizeOptions property.
