### ISSUE TITLE
I get a crash in KiaKat,when i load a gif

### ISSUE THREAD

**Issue by haodadaa** [facebook/fresco#2027]
hello,i get this exception
`Fatal Exception: java.lang.RuntimeException: Failed to pin Bitmap
       at com.facebook.imagepipeline.nativecode.Bitmaps.nativePinBitmap(SourceFile)
       at com.facebook.imagepipeline.nativecode.Bitmaps.pinBitmap(SourceFile:44)
       at com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.pinBitmap(SourceFile:155)
       at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.pinBitmap(SourceFile:32)
       at com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.decodeJPEGFromEncodedImage(SourceFile:90)
       at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.decodeJPEGFromEncodedImage(SourceFile:32)
       at com.facebook.imagepipeline.bitmaps.HoneycombBitmapFactory.createBitmapInternal(SourceFile:65)
       at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap(SourceFile:79)
       at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap(SourceFile:46)
       at com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.prepareFrameAndCache(SourceFile:146)
       at com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.prepareFrameAndCache(SourceFile:164)
       at com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.run(SourceFile:114)
       at com.facebook.common.executors.ConstrainedExecutorService$Worker.run(SourceFile:178)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(SourceFile:43)
       at java.lang.Thread.run(Thread.java:841)`
maybe In what version will be fixed, thanks?

**Comment by erikandre** [comment]
Hi @haodadaa 

This was supposed to be fixed in v1.8.0. Is it still reproducible for you after upgrading?

**Comment by oprisnik** [comment]
Thanks! As @erikandre said, this should have been fixed with 1.8.0 and we also released 1.8.1 recently. If this is still an issue, please fill out the issue template and let us know how to reproduce the error (e.g. sample image).
