### ISSUE TITLE
FATAL EXCEPTION: JavaBridge  java.lang.IllegalStateException

### ISSUE THREAD

**Issue by richso** [facebook/fresco#2033]
### Description

We are trying to display the array of images gotten from a remote HTML page in a Webview, the HTML with a Javascript to return the index of image clicked and the array of image URLs; however it caused the exception:

Full Exception:
FATAL EXCEPTION: JavaBridge
                                                                    Process: net.netrogen.hkmlapp, PID: 7195
                                                                    java.lang.IllegalStateException
                                                                        at com.facebook.common.internal.Preconditions.checkState(Preconditions.java:158)
                                                                        at com.facebook.drawee.components.DeferredReleaser.ensureOnUiThread(DeferredReleaser.java:101)
                                                                        at com.facebook.drawee.components.DeferredReleaser.cancelDeferredRelease(DeferredReleaser.java:96)
                                                                        at com.facebook.drawee.controller.AbstractDraweeController.onAttach(AbstractDraweeController.java:357)
                                                                        at com.facebook.drawee.view.DraweeHolder.attachController(DraweeHolder.java:264)
                                                                        at com.facebook.drawee.view.DraweeHolder.setController(DraweeHolder.java:202)
                                                                        at com.facebook.drawee.view.DraweeView.setController(DraweeView.java:122)
                                                                        at com.stfalcon.frescoimageviewer.ImageViewerAdapter$ImageViewHolder.setController(ImageViewerAdapter.java:152)
                                                                        at com.stfalcon.frescoimageviewer.ImageViewerAdapter$ImageViewHolder.bind(ImageViewerAdapter.java:122)
                                                                        at com.stfalcon.frescoimageviewer.ImageViewerAdapter.onBindViewHolder(ImageViewerAdapter.java:62)
                                                                        at com.stfalcon.frescoimageviewer.ImageViewerAdapter.onBindViewHolder(ImageViewerAdapter.java:27)
                                                                        at com.stfalcon.frescoimageviewer.adapter.RecyclingPagerAdapter.instantiateItem(RecyclingPagerAdapter.java:79)
                                                                        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1002)
                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1150)
                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)
                                                                        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
                                                                        at android.view.View.measure(View.java:18788)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                        at android.view.View.measure(View.java:18788)
                                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                        at android.view.View.measure(View.java:18788)
                                                                        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                        at android.view.View.measure(View.java:18788)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                        at android.view.View.measure(View.java:18788)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                        at android.view.View.measure(View.java:18788)
                                                                        at android.support.v7.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:133)
                                                                        at android.support.v7.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:63)
                                                                        at android.view.View.measure(View.java:18788)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                        at android.view.View.measure(View.java:18788)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                        at android.view.View.measure(View.java:18788)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                        at android.view.View.measure(View.java:18788)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                        at android.view.View.measure(View.java:18788)
                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                    	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(Phone

### Reproduction
this call reproduce the Exception (checked that the idx and urls parameters are properly passed from the javascript)

new ImageViewer.Builder(mContext, urls)
                        .setStartPosition(idx)
                        .show();

### Solution
don't know how to fix

### Additional Information

* Fresco version: 1.8.0
* Platform version: Android 6.0 (don't know whether its specific to this version)
* the creation of the CustomJavascriptInterface is inside a class that extends AsyncTask<MainActivity, Integer, Boolean> which is to do some (async) download of external javascript before inserting it into the webpage of the Webview

**Comment by dmitry-voronkevich** [comment]
@richso, Looks like you are trying to update ViewPager model outside of main thread. 
I can't see this from your stack trace for sure, but suspect this from exception.
It is likely that you fix this by moving your code which updates model to AsyncTask.onPostExecute()

**Comment by richso** [comment]
@dmitry-voronkevich 
thanks but what do you mean by "update ViewPager"? if you mean the call of new ImageViewer.Builder(mContext, urls)
.setStartPosition(idx)
.show();

then, it already happens in onPostExecute of the AsyncTask

**Comment by richso** [comment]
thanks @dmitry-voronkevich, I just fixed the problem by moving the logic that update the ViewPager to run in the UI Thread like this:
```
MainActivity.this.runOnUiThread(new Runnable() {

                    @Override
                    public void run() {
                        new ImageViewer.Builder(mContext, urls)
                                .setCustomDraweeHierarchyBuilder(hierarchyBuilder)
                                .setStartPosition(idx).show();
                    }
});
```

**Comment by richso** [comment]
thanks @dmitry-voronkevich, I just fixed the problem by moving the logic that update the ViewPager to run in the UI Thread like this:
```
MainActivity.this.runOnUiThread(new Runnable() {

                    @Override
                    public void run() {
                        new ImageViewer.Builder(mContext, urls)
                                .setCustomDraweeHierarchyBuilder(hierarchyBuilder)
                                .setStartPosition(idx).show();
                    }
});
```
