### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lcom/facebook/imagepipeline/core/ImagePipelineFactory

### ISSUE THREAD

**Issue by yleyvag** [facebook/fresco#2056]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/imagepipeline/core/ImagePipelineFactory;
                                                                            at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:70)
                                                                            at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:39)
                                                                            at com.xxxxxxx.android.XxxxxxxApplication.onCreate(XxxxxxxApplication.java:41)
                                                                            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6316)
                                                                            at android.app.ActivityThread.access$1800(ActivityThread.java:221)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:158)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.imagepipeline.core.ImagePipelineFactory" on path: DexPathList[[zip file "/data/app/com.xxxxxxx.android.beta-1/base.apk", zip file "/data/app/com.xxxxxxx.android.beta-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.xxxxxxx.android.beta-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.xxxxxxx.android.beta-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.xxxxxxx.android.beta-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.xxxxxxx.android.beta-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.xxxxxxx.android.beta-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.xxxxxxx.android.beta-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.xxxxxxx.android.beta-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.xxxxxxx.android.beta-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.xxxxxxx.android.beta-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.xxxxxxx.android.beta-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.xxxxxxx.android.beta-1/lib/arm, /data/app/com.xxxxxxx.android.beta-1/base.apk!/lib/armeabi-v7a, /data/app/com.xxxxxxx.android.beta-1/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.xxxxxxx.android.beta-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.xxxxxxx.android.beta-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.xxxxxxx.android.beta-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.xxxxxxx.android.beta-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.xxxxxxx.android.beta-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.xxxxxxx.android.beta-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.xxxxxxx.android.beta-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.xxxxxxx.android.beta-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.xxxxxxx.android.beta-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.xxxxxxx.android.beta-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                            at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:70) 
                                                                            at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:39) 
                                                                            at com.xxxxxxx.android.XxxxxxxApplication.onCreate(XxxxxxxApplication.java:41) 
                                                                            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036) 
                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6316) 
                                                                            at android.app.ActivityThread.access$1800(ActivityThread.java:221) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:158) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                        	Suppressed: java.lang.ClassNotFoundException: com.facebook.imagepipeline.core.ImagePipelineFactory
                                                                            at java.lang.Class.classForName(Native Method)
                                                                            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                            		... 14 more
                                                                         Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

### Description

I just imported the library on my project using:
implementation 'com.facebook.fresco:fresco:1.8.1'
In the onCreated method of my app I put:
Fresco.initialize(this);
When I run the app it crashes

### Additional Information

* Fresco version: 1.8.1
* Platform version: Android 6.0.1 Samsung Galaxy S5

**Comment by erikandre** [comment]
Hi @yleyvag , sorry for the slow response!

Going by what I see in the logs (lots of lines about split apks) I assume that you are running this from inside Android studio. It's possible that the crash is caused by a bug in Instant Run so I recommend turning this off (it's in the Android Studio settings) and check if that helps.

**Comment by oprisnik** [comment]
I assume that turning off instant run resolved this issue.
