### ISSUE TITLE
App crashed while loading image by controller

### ISSUE THREAD

**Issue by Hitesh12345678** [facebook/fresco#2091]
ProgressBarDrawable progressBarDrawable = new ProgressBarDrawable();
        progressBarDrawable.setColor(getResources().getColor(R.color.colorAccent));
        progressBarDrawable.setBackgroundColor(
                getResources().getColor(R.color.colorPrimary));
        progressBarDrawable
                .setRadius(10);

        mSimpleDraweeView = (SimpleDraweeView) findViewById(R.id.imgLoading);
        mSimpleDraweeView.getHierarchy().setProgressBarImage(progressBarDrawable);

        uri = Uri.parse(url);

ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                        //.setResizeOptions(new ResizeOptions(500, 500))
                        .setRequestPriority(Priority.HIGH)
                        .setLowestPermittedRequestLevel(ImageRequest.RequestLevel.FULL_FETCH)
                        .setProgressiveRenderingEnabled(true)
                        .build();
                DraweeController controller = Fresco.newDraweeControllerBuilder()
                        .setImageRequest(request)
                        .setRetainImageOnFailure(true)
                        .setCustomDrawableFactories(new DrawableFactory() {
                            @Override
                            public boolean supportsImageType(CloseableImage image) {
                                return false;
                            }

                            @Nullable
                            @Override
                            public Drawable createDrawable(CloseableImage image) {

                                return null;
                            }
                        })
                        .setControllerListener(new BaseControllerListener<ImageInfo>() {
                            @Override
                            public void onFinalImageSet(
                                    String id,
                                    ImageInfo imageInfo,
                                    Animatable animatable) {
                                if (imageInfo != null) {
                                    QualityInfo qualityInfo = imageInfo.getQualityInfo();
                                    Log.d("Fresco", "onFinalImageSet qualityInfo ::--> " + qualityInfo.getQuality() + "  " + imageInfo.getHeight() + " " + imageInfo.getWidth());
                                }
                            }

                            @Override
                            public void onIntermediateImageSet(
                                    String id, ImageInfo imageInfo) {
                                if (imageInfo != null) {
                                    QualityInfo qualityInfo = imageInfo.getQualityInfo();
                                    Log.d("Fresco", " onIntermediateImageSet qualityInfo ::--> " + qualityInfo.getQuality() + "  " + imageInfo.getHeight() + " " + imageInfo.getWidth());
                                }
                            }

                            @Override
                            public void onIntermediateImageFailed(String id, Throwable throwable) {

                            }
                        })
                        .build();
                mSimpleDraweeView.setController(controller);

java.lang.RuntimeException: Canvas: trying to draw too large(111111840bytes) bitmap.
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:260)
        at android.graphics.Canvas.drawBitmap(Canvas.java:1415)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
        at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:147)
        at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:147)
        at com.facebook.drawee.drawable.ScaleTypeDrawable.draw(ScaleTypeDrawable.java:125)
        at com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha(FadeDrawable.java:304)
        at com.facebook.drawee.drawable.FadeDrawable.draw(FadeDrawable.java:291)
        at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:147)
        at com.facebook.drawee.generic.RootDrawable.draw(RootDrawable.java:83)
        at android.widget.ImageView.onDraw(ImageView.java:1281)
        at android.view.View.draw(View.java:17086)
        at android.view.View.updateDisplayListIfDirty(View.java:16068)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:16031)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:16031)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:16031)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:16031)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:16031)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:16031)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3752)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3732)
        at android.view.View.updateDisplayListIfDirty(View.java:16031)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:657)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:663)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:771)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2808)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2616)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2223)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1258)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6348)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
        at android.view.Choreographer.doFrame(Choreographer.java:619)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by oprisnik** [comment]
The stack trace suggests that you're trying to draw a huge bitmap. How big is your image, what format, do you have a sample URL where this happens?

**Comment by Hitesh12345678** [comment]
resolution of image is 5285*5256.

**Comment by oprisnik** [comment]
Android cannot natively decode huge images (the exact maximum is device-dependent). You can either enable resizing or downsampling or if you only need a region, experiment with region decoding (still WIP).

There's not much else you can do since it's a device limitation. In theory it would be possible to split the huge bitmaps in smaller chunks, but we currently don't have plans to implement something like this. You could emulate this with the region decoder and multiple Drawee views with different regions.

See http://frescolib.org/docs/resizing.html and https://github.com/facebook/fresco/blob/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imagepipeline/ImagePipelineRegionDecodingFragment.java
