### ISSUE TITLE
ExceptionInInitializerError shows after upgrade to fresco 1.8.1

### ISSUE THREAD

**Issue by s1rius** [facebook/fresco#2094]
### Description
Use fresco 1.8.1, then Update android studio to 3.1 version, build and launch, App crashed.
After roll back fresco to 1.7.1, it works fine.
```
W/System.err: java.lang.ExceptionInInitializerError
                  at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:58)
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.facebook.imagepipeline.memory.NativeMemoryChunk>: java.lang.ExceptionInInitializerError: 
           at com.facebook.imagepipeline.memory.NativeMemoryChunk com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(int) (NativeMemoryChunkPool.java:58)
           at java.lang.Object com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(int) (NativeMemoryChunkPool.java:20)
           at java.lang.Object com.facebook.imagepipeline.memory.BasePool.get(int) (BasePool.java:257)
           at void com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(com.facebook.imagepipeline.memory.NativeMemoryChunkPool, int) (NativePooledByteBufferOutputStream.java:51)
           at com.facebook.imagepipeline.memory.NativePooledByteBuffer com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(java.io.InputStream, int) (NativePooledByteBufferFactory.java:98)
           at com.facebook.common.memory.PooledByteBuffer com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(java.io.InputStream, int) (NativePooledByteBufferFactory.java:26)
           at com.facebook.common.memory.PooledByteBuffer com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(com.facebook.cache.common.CacheKey) (BufferedDiskCache.java:336)
           at com.facebook.common.memory.PooledByteBuffer com.facebook.imagepipeline.cache.BufferedDiskCache.access$400(com.facebook.imagepipeline.cache.BufferedDiskCache, com.facebook.cache.common.CacheKey) (BufferedDiskCache.java:36)
           at com.facebook.imagepipeline.image.EncodedImage com.facebook.imagepipeline.cache.BufferedDiskCache$2.call() (BufferedDiskCache.java:182)
W/System.err:     at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:20)
I/art:     at java.lang.Object com.facebook.imagepipeline.cache.BufferedDiskCache$2.call() (BufferedDiskCache.java:166)
           at void bolts.Task$4.run() (Task.java:357)
           at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1133)
           at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:607)
           at void com.facebook.imagepipeline.core.PriorityThreadFactory$1.run() (PriorityThreadFactory.java:53)
           at void java.lang.Thread.run() (Thread.java:761)
W/System.err:     at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:257)
                  at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:51)
W/System.err:     at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:98)
                  at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
                  at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:336)
                  at com.facebook.imagepipeline.cache.BufferedDiskCache.access$400(BufferedDiskCache.java:36)
                  at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:182)
                  at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:166)
                  at bolts.Task$4.run(Task.java:357)
                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                  at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:53)
W/System.err:     at java.lang.Thread.run(Thread.java:761)
              Caused by: java.lang.RuntimeException: SoLoader.init() not yet called
                  at com.facebook.soloader.SoLoader.assertInitialized(SoLoader.java:562)
                  at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:353)
                  at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:335)
                  at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:42)
                  at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:33)
              	... 15 more
```

### Reproduction
Android studio 3.1   fresco 1.8.1  X
Android studio 3.0   fresco 1.8.1  X
Android studio 3.1   fresco 1.7.1  ✓
Android studio 3.0   fresco 1.7.1  ✓

### Additional Information

* Fresco version: **1.8.1**
* Platform version: **android 7.1.1**
* gradle build tool version: **2.2.0**
* use new proguard file : **yes**

**Comment by oprisnik** [comment]
Thanks! This seems like an issue with SoLoader, which was made the default recently. cc @foghina

**Comment by foghina** [comment]
Are you properly initializing Fresco, as described in [Getting Started](http://frescolib.org/docs/index.html)?

I tried to repro this by modifying the showcase app to use the maven 1.8.1 artifacts but didn't have any success.

**Comment by s1rius** [comment]
Thanks guys, The bug is gone after I upgrade fresco to 1.9.0
