### ISSUE TITLE
FATAL EXCEPTION: FrescoDecodeExecutor-2 java.lang.OutOfMemoryError:

### ISSUE THREAD

**Issue by windchime11** [facebook/fresco#2107]
### Description

Using Fresco 1.9.0 in Android App. After leaving the app open for about one minute, the app crashed due to the following:

E/AndroidRuntime: FATAL EXCEPTION: FrescoDecodeExecutor-2
                                                                  Process: com.xyz.myapp, PID: 26064
                                                                  java.lang.OutOfMemoryError: Failed to allocate a 1566732 byte allocation with 1251264 free bytes and 1221KB until OOM
                                                                      at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                      at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:977)
                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:948)
                                                                      at android.graphics.Bitmap.createBitmap(Bitmap.java:915)
                                                                      at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:51)
                                                                      at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:26)
                                                                      at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:255)
                                                                      at com.facebook.imagepipeline.platform.ArtDecoder.decodeStaticImageFromStream(ArtDecoder.java:147)
                                                                      at com.facebook.imagepipeline.platform.ArtDecoder.decodeJPEGFromEncodedImage(ArtDecoder.java:127)
                                                                      at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeJpeg(DefaultImageDecoder.java:173)
                                                                      at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:56)
                                                                      at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:119)
                                                                      at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:254)
                                                                      at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$300(DecodeProducer.java:113)
                                                                      at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:152)
                                                                      at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:202)
                                                                      at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:22)
                                                                      at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:73)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                      at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
                                                                      at java.lang.Thread.run(Thread.java:762)

### Reproduction

Not sure how to reproduce it here as it does not happen every time the app is running.

### Additional Information

How can I prevent this error from crashing the app?

* Fresco version: [1.9.0]
* Platform version: [Samsung Galaxy S7 Android 7.0]

**Comment by erikandre** [comment]
Hi @windchime11 

Are you loading very large images in your app? Perhaps you can describe how you are using Fresco and what types or images (or animations) you are displaying.

**Comment by niqmk** [comment]
> 29824-29898/? E/AndroidRuntime: FATAL EXCEPTION: FrescoDecodeExecutor-2
>     Process: com.helpio.ubiscreen, PID: 29824
>     java.lang.OutOfMemoryError: Failed to allocate a 4665612 byte allocation with 573488 free bytes and 560KB until OOM
>         at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
>         at android.graphics.Bitmap.nativeCreate(Native Method)
>         at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
>         at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
>         at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
>         at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:51)
>         at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:26)
>         at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
>         at com.facebook.imagepipeline.platform.ArtDecoder.decodeStaticImageFromStream(ArtDecoder.java:147)
>         at com.facebook.imagepipeline.platform.ArtDecoder.decodeJPEGFromEncodedImage(ArtDecoder.java:127)
>         at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeJpeg(DefaultImageDecoder.java:173)
>         at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:56)
>         at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:119)
>         at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:248)
>         at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:109)
>         at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:146)
>         at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:202)
>         at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:22)
>         at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:73)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>         at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
>         at java.lang.Thread.run(Thread.java:818)

And yes, I'm loading 700 - 2MB images (Total more than 17 images in 1 activity).
