### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by bigahega** [facebook/fresco#2112]
Fresco library internally crashes when I try to load an image with the following piece of code in a `ViewHolder`:

```
fun bind(liveMessage: LiveMessage, context: Context?, liveOwner: User) {
        context?.let {
            if(!liveMessage.profilePhotoURL.isNullOrEmpty()) {
                itemView.profileImageView.setImageURI(liveMessage.profilePhotoURL)
            }
        }
...
}
```

The following exception is thrown:

> java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
        at android.util.PathParser$PathDataNode.addCommand(PathParser.java:380)
        at android.util.PathParser$PathDataNode.nodesToPath(PathParser.java:260)
        at android.graphics.drawable.VectorDrawable$VPath.toPath(VectorDrawable.java:1265)
        at android.graphics.drawable.VectorDrawable$VPathRenderer.drawPath(VectorDrawable.java:950)
        at android.graphics.drawable.VectorDrawable$VPathRenderer.drawGroupTree(VectorDrawable.java:931)
        at android.graphics.drawable.VectorDrawable$VPathRenderer.drawGroupTree(VectorDrawable.java:927)
        at android.graphics.drawable.VectorDrawable$VPathRenderer.drawGroupTree(VectorDrawable.java:927)
        at android.graphics.drawable.VectorDrawable$VPathRenderer.draw(VectorDrawable.java:938)
        at android.graphics.drawable.VectorDrawable$VectorDrawableState.updateCachedBitmap(VectorDrawable.java:705)
        at android.graphics.drawable.VectorDrawable.draw(VectorDrawable.java:280)
        at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:145)
        at com.facebook.drawee.drawable.ScaleTypeDrawable.draw(ScaleTypeDrawable.java:123)
        at com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha(FadeDrawable.java:302)
        at com.facebook.drawee.drawable.FadeDrawable.draw(FadeDrawable.java:289)
        at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:145)
        at com.facebook.drawee.generic.RootDrawable.draw(RootDrawable.java:81)
        at android.widget.ImageView.onDraw(ImageView.java:1148)
        at android.view.View.draw(View.java:15038)
        at android.view.View.updateDisplayListIfDirty(View.java:13959)
        at android.view.View.getDisplayList(View.java:13982)
        at android.view.View.draw(View.java:14762)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3304)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3096)
        at android.view.View.updateDisplayListIfDirty(View.java:13954)
        at android.view.View.getDisplayList(View.java:13982)
        at android.view.View.draw(View.java:14762)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3304)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3096)
        at android.view.View.updateDisplayListIfDirty(View.java:13954)
        at android.view.View.getDisplayList(View.java:13982)
        at android.view.View.draw(View.java:14762)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3304)
        at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3096)
        at android.view.View.draw(View.java:15041)
        at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4107)
        at android.view.View.updateDisplayListIfDirty(View.java:13959)
        at android.view.View.getDisplayList(View.java:13982)
        at android.view.View.draw(View.java:14762)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3304)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3096)
        at com.bosphere.fadingedgelayout.FadingEdgeLayout.dispatchDraw(FadingEdgeLayout.java:205)
        at android.view.View.updateDisplayListIfDirty(View.java:13954)
        at android.view.View.getDisplayList(View.java:13982)
        at android.view.View.draw(View.java:14762)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3304)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3096)
        at android.view.View.updateDisplayListIfDirty(View.java:13954)
        at android.view.View.getDisplayList(View.java:13982)
        at android.view.View.draw(View.java:14762)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3304)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3096)
        at android.view.View.updateDisplayListIfDirty(View.java:13954)
        at android.view.View.getDisplayList(View.java:13982)
        at android.view.View.draw(View.java:14762)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3304)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3096)
        at android.view.View.updateDisplayListIfDirty(View.java:13954)
        at android.view.View.getDisplayList(View.java:13982)
        at android.view.View.draw(View.java:14762)
    	at android.view.ViewGroup.drawChild(V

### Additional Information

* Fresco version: com.facebook.fresco:fresco:1.9.0
* Platform version: Huawei P8 (Android 5.0.1)

**Comment by erikandre** [comment]
Hi @bigahega ,

I see references to VectorDrawable in the stack trace. Are you using a vector drawable as the placeholder image for the SimpleDraweeView?

If that's the case, please try removing the placeholder and see if it still crashes.

**Comment by bigahega** [comment]
After further inspection, I have seen that the error itself was caused by vector definitions involving scientific notations which were not supported on the device natively. I guess it is better to close this issue as it is actually not related to the Fresco library.
