### ISSUE TITLE
java.lang.IllegalArgumentException: bitmap size exceeds 32bits

### ISSUE THREAD

**Issue by sparsh77** [facebook/fresco#2120]
i am using the shimmer layout  and Fresco in the UI only and managing the visibility on the basis of API result .

i am getting the following Exception

STACK_TRACE=java.lang.IllegalArgumentException: bitmap size exceeds 32bits
at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java:842)
at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
at android.graphics.Bitmap.createBitmap(Bitmap.java:777)
at com.facebook.shimmer.ShimmerFrameLayout.createBitmapAndGcIfNecessary(ShimmerFrameLayout.java:943)
at com.facebook.shimmer.ShimmerFrameLayout.getMaskBitmap(ShimmerFrameLayout.java:822)
at com.facebook.shimmer.ShimmerFrameLayout.drawMasked(ShimmerFrameLayout.java:771)
at com.facebook.shimmer.ShimmerFrameLayout.dispatchDrawUsingBitmap(ShimmerFrameLayout.java:720)
at com.facebook.shimmer.ShimmerFrameLayout.dispatchDraw(ShimmerFrameLayout.java:697)
at android.view.View.draw(View.java:14536)
at android.widget.FrameLayout.draw(FrameLayout.java:472)
at android.view.View.getDisplayList(View.java:13417)
at android.view.View.getDisplayList(View.java:13459)
at android.view.View.draw(View.java:14250)
at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
at android.view.View.getDisplayList(View.java:13412)
at android.view.View.getDisplayList(View.java:13459)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
at android.view.View.getDisplayList(View.java:13355)
at android.view.View.getDisplayList(View.java:13459)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
at android.view.View.getDisplayList(View.java:13355)
at android.view.View.getDisplayList(View.java:13459)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
at android.view.View.getDisplayList(View.java:13355)
at android.view.View.getDisplayList(View.java:13459)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
at android.view.View.getDisplayList(View.java:13355)
at android.view.View.getDisplayList(View.java:13459)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
at android.view.View.getDisplayList(View.java:13355)
at android.view.View.getDisplayList(View.java:13459)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
at android.view.View.getDisplayList(View.java:13355)
at android.view.View.getDisplayList(View.java:13459)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
at android.view.View.getDisplayList(View.java:13355)
at android.view.View.getDisplayList(View.java:13459)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
at android.view.View.getDisplayList(View.java:13355)
at android.view.View.getDisplayList(View.java:13459)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
at android.view.View.getDisplayList(View.java:13355)
at android.view.View.getDisplayList(View.java:13459)
at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1612)
at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1483)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2477)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2333)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1953)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1048)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5952)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:787)
at android.view.Choreographer.doCallbacks(Choreographer.java:600)
at android.view.Choreographer.doFrame(Choreographer.java:569)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:773)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5291)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665)
at dalvik.system.NativeStart.main(Native Method)

******************* i have default initialization of fresco

**Comment by lambdapioneer** [comment]
This is not related to Fresco, but seems to be caused in the ShimmerLayout library.

I see that you've already created an issue there: https://github.com/facebook/shimmer-android/issues/56

Closing here :)
