### ISSUE TITLE
 java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@38c5c120

### ISSUE THREAD

**Issue by Iamrookie** [facebook/fresco#2127]
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@38c5c120
        at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1225)
        at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:600)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:544)
        at android.widget.ImageView.onDraw(ImageView.java:1187)
        at android.view.View.draw(View.java:16202)
        at android.view.View.updateDisplayListIfDirty(View.java:15122)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.view.View.updateDisplayListIfDirty(View.java:15117)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.widget.AbsListView.dispatchDraw(AbsListView.java:3084)
        at android.view.View.draw(View.java:16205)
        at android.widget.AbsListView.draw(AbsListView.java:5989)
        at android.view.View.updateDisplayListIfDirty(View.java:15122)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.view.View.draw(View.java:16205)
        at android.view.View.updateDisplayListIfDirty(View.java:15122)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:4582)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.view.View.draw(View.java:16205)
        at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3988)
        at android.view.View.updateDisplayListIfDirty(View.java:15122)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchDraw(SmartRefreshLayout.java:759)
        at android.view.View.updateDisplayListIfDirty(View.java:15117)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.view.View.updateDisplayListIfDirty(View.java:15117)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.view.View.draw(View.java:16205)
        at android.support.v4.view.ViewPager.draw(ViewPager.java:2418)
        at android.view.View.updateDisplayListIfDirty(View.java:15122)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.view.View.draw(View.java:16205)
        at android.view.View.updateDisplayListIfDirty(View.java:15122)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.view.View.updateDisplayListIfDirty(View.java:15117)
        at android.view.View.getDisplayList(View.java:15145)
        at android.view.View.draw(View.java:15923)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
        at android.view.View.updateDisplayListIfDirty(View.java:15117)
        at android.view.View.getDisplayList(View.java:15145)
    	at android

please help in this case.

**Comment by Iamrookie** [comment]
已经解决了
dataSource.subscribe(new MyBaseBitmapDataSubscriber(finalUrl, config.getWidth(), config.getHeight()) {
            @Override
            protected void onNewResultImpl(Bitmap bitmap, DataSource<CloseableReference<CloseableImage>> dataSource) {
                //注意，gif图片解码方法与普通图片不一样，是无法拿到bitmap的。如果要把gif的第一帧的bitmap返回，怎么做？
                //GifImage.create(bytes).decode(1l,9).getFrameInfo(1).
                if (bitmap != null) {

                    if (config.getShapeMode() == ShapeMode.OVAL) {
                        bitmap = MyUtil.cropCircle(bitmap, false);

                    } else if (config.getShapeMode() == ShapeMode.RECT_ROUND) {
                        bitmap = MyUtil.rectRound(bitmap, config.getRectRoundRadius(), 0);
                    }

                    //此处的bitmap不要直接拿到外面使用,拷贝一个副本在丢出去
                    Bitmap bitmap1 = Bitmap.createBitmap(bitmap.getWidth(), bitmap.getHeight(), bitmap.getConfig());
//                    config.getBitmapListener().onSuccess(bitmap1);
                    config.getBitmapListener().onSuccess(new WeakReference<Bitmap>(bitmap1));
                }
            }

            @Override
            protected void onFailureImpl(DataSource<CloseableReference<CloseableImage>> dataSource) {
                config.getBitmapListener().onFail();
            }
        }, CallerThreadExecutor.getInstance());
