### ISSUE TITLE
Which version is fresco more stable than 1.1.1?

### ISSUE THREAD

**Issue by Iamrookie** [facebook/fresco#2149]
I have tried the following version:
I tried it from 1.9.0 to 1.3.0. I don't want to try it. Please give it a stable version. Thank you.

app gradle config:
android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.zsz.testbase64demo"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

The error message is as follows：
1.8.0+
07-12 09:54:25.525 25768-25802/com.zsz.testbase64demo E/AndroidRuntime: FATAL EXCEPTION: FrescoLightWeightBackgroundExecutor-1
    Process: com.zsz.testbase64demo, PID: 25768
    java.lang.NoClassDefFoundError: android.support.v4.util.Pools$SynchronizedPool
        at com.facebook.imageutils.BitmapUtil.<clinit>(BitmapUtil.java:30)
        at com.facebook.imagepipeline.image.EncodedImage.readImageSize(EncodedImage.java:367)
        at com.facebook.imagepipeline.image.EncodedImage.parseMetaData(EncodedImage.java:334)
        at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:59)
        at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:50)
        at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45)
        at com.facebook.common.executors.CallerThreadExecutor.execute(CallerThreadExecutor.java:49)
        at com.facebook.imagepipeline.producers.LocalFetchProducer.produceResults(LocalFetchProducer.java:77)
        at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer.produceResults(AddImageTransformMetaDataProducer.java:29)
        at com.facebook.imagepipeline.producers.ResizeAndRotateProducer.produceResults(ResizeAndRotateProducer.java:93)
        at com.facebook.imagepipeline.producers.DecodeProducer.produceResults(DecodeProducer.java:112)
        at com.facebook.imagepipeline.producers.BitmapMemoryCacheProducer.produceResults(BitmapMemoryCacheProducer.java:95)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.startInputProducerIfHasAttachedConsumers(MultiplexProducer.java:337)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.access$000(MultiplexProducer.java:122)
        at com.facebook.imagepipeline.producers.MultiplexProducer.produceResults(MultiplexProducer.java:84)
        at com.facebook.imagepipeline.producers.ThreadHandoffProducer$1.onSuccess(ThreadHandoffProducer.java:43)
        at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:54)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:53)
        at java.lang.Thread.run(Thread.java:841)

1.7.0 
错误: 找不到符号
符号:   类 SimpleDraweeView
位置: 类 MainActivity

1.4.0
07-12 09:48:06.740 25427-25427/com.zsz.testbase64demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zsz.testbase64demo, PID: 25427
    java.lang.IllegalAccessError: tried to access method com.facebook.imagepipeline.core.ImagePipelineFactory.getAnimatedFactory:(Landroid/content/Context;Lcom/facebook/imagepipeline/core/ImagePipelineFactory;Ljava/util/Set;Lcom/facebook/drawee/backends/pipeline/DraweeConfig;)V from class com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier
        at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:60)
        at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:49)
        at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:42)
        at com.facebook.drawee.backends.pipeline.Fresco.initializeDrawee(Fresco.java:76)
        at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:69)
        at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:39)
        at com.zsz.MyApplication.onCreate(MyApplication.java:18)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1009)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4613)
        at android.app.ActivityThread.access$1800(ActivityThread.java:139)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5314)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by oprisnik** [comment]
Version 1.9.0 is the version that you should use.

For `java.lang.NoClassDefFoundError: android.support.v4.util.Pools$SynchronizedPool`, make sure you have a recent version of the support library included. See https://github.com/facebook/fresco/tree/master/samples/showcase for our Showcase sample app.

For the SimpleDraweeView not found error, make sure you set up ProGuard according to the docs on http://frescolib.org/docs/shipping.html and that Fresco is initialized in your `Application` class.

The last one seems to be resulted by conflicting Fresco versions for animations and normal images. Make sure that all Fresco dependencies have the same version.
