### ISSUE TITLE
No static method loadLibrary(Ljava/lang/String;

### ISSUE THREAD

**Issue by sapjax** [facebook/fresco#2172]
```
08-04 22:40:14.742 10059-10066/? E/art: Failed sending reply to debugger: Broken pipe
08-04 22:40:15.637 10059-10059/? E/unknown:ReactNative: Unable to display loading message because react activity isn't available
08-04 22:40:16.927 10059-10157/org.suplabs.kento E/AndroidRuntime: FATAL EXCEPTION: Thread-12
    Process: org.suplabs.kento, PID: 10059
    java.lang.NoSuchMethodError: No static method loadLibrary(Ljava/lang/String;)V in class Lcom/facebook/soloader/SoLoader; or its super classes (declaration of 'com.facebook.soloader.SoLoader' appears in /data/app/org.suplabs.kento-1/base.apk:classes4.dex)
        at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:18)
        at com.facebook.react.bridge.ProxyJavaScriptExecutor.<clinit>(ProxyJavaScriptExecutor.java:39)
        at com.facebook.react.bridge.ProxyJavaScriptExecutor$Factory.create(ProxyJavaScriptExecutor.java:34)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:912)
        at java.lang.Thread.run(Thread.java:761)
```

`compile 'com.facebook.fresco:animated-gif:1.10.0'`

### Additional Information

* Fresco version: **1.10.0**
* Platform version: React-Native 0.55.4 Android

**Comment by sapjax** [comment]
hi  @lambdapioneer：

These are no special content in gradle file.

after i change 
```compile 'com.facebook.fresco:animated-gif:1.10.0'```
 to 
```
    implementation 'com.facebook.fresco:fresco:1.8.1'
    implementation 'com.facebook.fresco:animated-gif:1.8.1'
```
it works well.

if I didn't add the first `implementation 'com.facebook.fresco:fresco:1.8.1'` line, it throws another error.

maybe something wrong with my grade file, but I don't want to waste your time, anyway it works now, so I just close this issue, thanks.
