### ISSUE TITLE
java.lang.RuntimeException: Could not initialize SoLoader

### ISSUE THREAD

**Issue by lttlang** [facebook/fresco#2176]
### Description
When initializing Fresco on app start:
Caused by java.io.FileNotFoundException: /data/user/0/com.remind101/lib-main/dso_lock: open failed: EACCES (Permission denied)
       at libcore.io.IoBridge.open(IoBridge.java:452)
       at java.io.FileOutputStream.(FileOutputStream.java:87)
       at java.io.FileOutputStream.(FileOutputStream.java:72)
       at com.facebook.soloader.FileLocker.(FileLocker.java:28)
       at com.facebook.soloader.FileLocker.lock(FileLocker.java:24)
       at com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:393)
       at com.facebook.soloader.SoLoader.initImpl(SoLoader.java:211)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:120)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:104)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:63)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:46)
Caused by android.system.ErrnoException: open failed: EACCES (Permission denied)
       at libcore.io.Posix.open(Posix.java)
       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
       at libcore.io.IoBridge.open(IoBridge.java:438)
       at java.io.FileOutputStream.(FileOutputStream.java:87)
       at java.io.FileOutputStream.(FileOutputStream.java:72)
       at com.facebook.soloader.FileLocker.(FileLocker.java:28)
       at com.facebook.soloader.FileLocker.lock(FileLocker.java:24)
       at com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:393)
       at com.facebook.soloader.SoLoader.initImpl(SoLoader.java:211)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:120)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:104)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:63)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:46)

### Reproduction
This is happening in production, but we have not be able to reproduce this ourselves with the emulator. Crashlytics is catching this crash on exactly one device, ZTE Grand X Max 2.  It happens when the application is first opened.

### Additional Information

* Fresco version: 1.8.1
* Platform version: ZTE Grand X Max 2 api level 23

**Comment by defHLT** [comment]
Hi,

Does it happen for one user or for all devices of this kind?

**Comment by lttlang** [comment]
From what we can tell, it looks like every user that has this device is running into this issue.

**Comment by RICEYRQ** [comment]
[My Notebook-2.xlsx](https://github.com/facebook/fresco/files/2454674/My.Notebook-2.xlsx)
There are some errors in our app group by device.
Hope this can help you some.

**Comment by sudeqiangxx** [comment]
java.lang.RuntimeException: Unsupported color conversion request
Lead to fail to load images
