### ISSUE TITLE
while inflating gif drawable crash

### ISSUE THREAD

**Issue by warkiz** [facebook/fresco#2180]
This lib. help me a lot , thanks.

I have some trouble when using , please help to review.
### Description
while inflating gif drawable crash , this gif put in recyclerView ' s item. I want the gif play automatic.

### Reproduction
layout:
 <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/thumbnail_pic"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:adjustViewBounds="true"/>

code:
String imagePath = "http://wx3.sinaimg.cn/thumbnail/006fiYtfly1fsy9ov8jiqg30870et7b9.gif";
DraweeController controller = Fresco.newDraweeControllerBuilder().setAutoPlayAnimations(true).setUri(Uri.parse(imagePath)).build();
        simpleDraweeView.setController(controller);

when the item which had gif drawable is coming showing to the screen , the crash happen.
### Additional Information

* Fresco version: 
implementation 'com.facebook.fresco:animated-base-support:0.12.0'
implementation 'com.facebook.fresco:fresco:1.10.0'
implementation 'com.facebook.fresco:animated-gif:1.5.0'

Crash log:

Process: com.test.test, PID: 15866
    java.lang.UnsatisfiedLinkError: No implementation found for com.facebook.animated.gif.GifImage com.facebook.animated.gif.GifImage.nativeCreateFromNativeMemory(long, int) (tried Java_com_facebook_animated_gif_GifImage_nativeCreateFromNativeMemory and Java_com_facebook_animated_gif_GifImage_nativeCreateFromNativeMemory__JI)
        at com.facebook.animated.gif.GifImage.nativeCreateFromNativeMemory(Native Method)
        at com.facebook.animated.gif.GifImage.create(GifImage.java:68)
        at com.facebook.animated.gif.GifImage.decode(GifImage.java:73)
        at com.facebook.imagepipeline.animated.factory.AnimatedImageFactoryImpl.decodeGif(AnimatedImageFactoryImpl.java:85)
        at com.facebook.fresco.animation.factory.AnimatedFactoryV2Impl$1.decode(AnimatedFactoryV2Impl.java:88)
        at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeGif(DefaultImageDecoder.java:134)
        at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:58)
        at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:119)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:248)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:109)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:146)
        at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:202)
        at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:22)
        at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:73)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
        at java.lang.Thread.run(Thread.java:784)
08-09 19:26:13.455 15866-15921/com.test.test E/AndroidRuntime: FATAL EXCEPTION: FrescoDecodeExecutor-8
    Process: com.test.test, PID: 15866
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/common/soloader/SoLoaderShim;
        at com.facebook.animated.gif.GifImage.ensure(GifImage.java:44)
        at com.facebook.animated.gif.GifImage.create(GifImage.java:66)
        at com.facebook.animated.gif.GifImage.decode(GifImage.java:73)
        at com.facebook.imagepipeline.animated.factory.AnimatedImageFactoryImpl.decodeGif(AnimatedImageFactoryImpl.java:85)
        at com.facebook.fresco.animation.factory.AnimatedFactoryV2Impl$1.decode(AnimatedFactoryV2Impl.java:88)
        at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeGif(DefaultImageDecoder.java:134)
        at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:58)
        at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:119)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:248)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:109)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:146)
        at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:202)
        at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:22)
        at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:73)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
        at java.lang.Thread.run(Thread.java:784)
08-09 19:26:13.455 15866-15920/com.test.test E/AndroidRuntime: FATAL EXCEPTION: FrescoDecodeExecutor-7
    Process: com.test.test, PID: 15866
    java.lang.UnsatisfiedLinkError: No implementation found for com.facebook.animated.gif.GifImage com.facebook.animated.gif.GifImage.nativeCreateFromNativeMemory(long, int) (tried Java_com_facebook_animated_gif_GifImage_nativeCreateFromNativeMemory and Java_com_facebook_animated_gif_GifImage_nativeCreateFromNativeMemory__JI)
        at com.facebook.animated.gif.GifImage.nativeCreateFromNativeMemory(Native Method)
        at com.facebook.animated.gif.GifImage.create(GifImage.java:68)
        at com.facebook.animated.gif.GifImage.decode(GifImage.java:73)
        at com.facebook.imagepipeline.animated.factory.AnimatedImageFactoryImpl.decodeGif(AnimatedImageFactoryImpl.java:85)
        at com.facebook.fresco.animation.factory.AnimatedFactoryV2Impl$1.decode(AnimatedFactoryV2Impl.java:88)
        at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeGif(DefaultImageDecoder.java:134)
        at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:58)
        at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:119)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:248)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:109)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:146)
        at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:202)
        at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:22)
        at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:73)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
        at java.lang.Thread.run(Thread.java:784)
08-09 19:26:13.456 15866-15919/com.test.test E/AndroidRuntime: FATAL EXCEPTION: FrescoDecodeExecutor-6
    Process: com.test.test, PID: 15866
    java.lang.UnsatisfiedLinkError: No implementation found for com.facebook.animated.gif.GifImage com.facebook.animated.gif.GifImage.nativeCreateFromNativeMemory(long, int) (tried Java_com_facebook_animated_gif_GifImage_nativeCreateFromNativeMemory and Java_com_facebook_animated_gif_GifImage_nativeCreateFromNativeMemory__JI)
        at com.facebook.animated.gif.GifImage.nativeCreateFromNativeMemory(Native Method)
        at com.facebook.animated.gif.GifImage.create(GifImage.java:68)
        at com.facebook.animated.gif.GifImage.decode(GifImage.java:73)
        at com.facebook.imagepipeline.animated.factory.AnimatedImageFactoryImpl.decodeGif(AnimatedImageFactoryImpl.java:85)
        at com.facebook.fresco.animation.factory.AnimatedFactoryV2Impl$1.decode(AnimatedFactoryV2Impl.java:88)
        at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeGif(DefaultImageDecoder.java:134)
        at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:58)
        at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:119)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:248)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:109)
        at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:146)
        at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:202)
        at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:22)
        at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:73)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
        at java.lang.Thread.run(Thread.java:784)
08-09 19:26:13.457 15866-15921/com.test.test E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.common.soloader.SoLoaderShim" on path: DexPathList[[zip file "/data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/base.apk", zip file "/data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_dependencies_apk.apk", zip file "/data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_resources_apk.apk", zip file "/data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_0_apk.apk", zip file "/data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_1_apk.apk", zip file "/data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_2_apk.apk", zip file "/data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_3_apk.apk", zip file "/data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_4_apk.apk", zip file "/data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_5_apk.apk", zip file "/data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_6_apk.apk", zip file "/data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_7_apk.apk", zip file "/data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_8_apk.apk", zip file "/data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/lib/arm64, /data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/base.apk!/lib/arm64-v8a, /data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 18 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.test.test-xGxARupSIWnNUl_MN72qaw==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexfullFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:75)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:38)
08-09 19:26:13.459 15866-15921/com.test.test E/AndroidRuntime:     at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:716)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:749)
        at android.app.LoadedApk.getResources(LoadedApk.java:996)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2489)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6398)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by defHLT** [comment]
Hi,

there was a similar issue #1576 which was resolved. Does it help you?

**Comment by warkiz** [comment]
Thank you, It helps me a lot!
