### ISSUE TITLE
OOM in CountingMemoryCache

### ISSUE THREAD

**Issue by LomikXP** [facebook/fresco#2184]
### Description

Taked from user. Just loading images many times.
Get stacktrace:
```
java.lang.OutOfMemoryError: Failed to allocate a 420546432 byte allocation with 25165824 free bytes and 237MB until OOM, max allowed footprint 313199056, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3139)
	at java.util.Arrays.copyOf(Arrays.java:3109)
	at java.util.ArrayList.grow(ArrayList.java:275)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:249)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
	at java.util.ArrayList.add(ArrayList.java:467)
	at com.facebook.imagepipeline.d.h.a(CountingMemoryCache.java:425)
	at com.facebook.imagepipeline.d.h.d(CountingMemoryCache.java:399)
	at com.facebook.imagepipeline.d.h.a(CountingMemoryCache.java:198)
	at com.facebook.imagepipeline.d.h.a(CountingMemoryCache.java:157)
	at com.facebook.imagepipeline.d.o.a(InstrumentedMemoryCache.java:37)
	at com.facebook.imagepipeline.k.h$1.a(BitmapMemoryCacheProducer.java:139)
	at com.facebook.imagepipeline.k.h$1.a(BitmapMemoryCacheProducer.java:102)
	at com.facebook.imagepipeline.k.b.b(BaseConsumer.java:97)
	at com.facebook.imagepipeline.k.m$c.a(DecodeProducer.java:368)
	at com.facebook.imagepipeline.k.m$c.c(DecodeProducer.java:290)
	at com.facebook.imagepipeline.k.m$c.a(DecodeProducer.java:109)
	at com.facebook.imagepipeline.k.m$c$1.a(DecodeProducer.java:146)
	at com.facebook.imagepipeline.k.v.e(JobScheduler.java:202)
	at com.facebook.imagepipeline.k.v.a(JobScheduler.java:22)
	at com.facebook.imagepipeline.k.v$1.run(JobScheduler.java:73)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at com.facebook.imagepipeline.e.k$1.run(PriorityThreadFactory.java:51)
	at java.lang.Thread.run(Thread.java:764)
```

### Reproduction

In progress

### Solution

Not yet

### Additional Information

* Fresco version: 1.10.0
* Platform version: 8.1.0

**Comment by oprisnik** [comment]
I guess you are trying to decode a huge image? Which format? How big? Is it in a RecyclerView?

**Comment by LomikXP** [comment]
Hm, no big image(-s), <400kb jpegs.
Its custom view, with PageAdapter where view is recycled (detach bitmaps)
How it can be, may be recursion crashes?

**Comment by oprisnik** [comment]
I don't know. Images don't even need to be the root cause of this, just the tipping point since you're allocating bigger memory chunks in one go. I would suggest you analyze your memory usage and see when it increases and what objects are causing it. For example, checking if you're still holding on to bitmaps that are actually not displayed any more or having memory leaks etc.

**Comment by oprisnik** [comment]
Also, a 400 kB image could be huge in actual image dimensions (pixels). You should make sure to load appropriately sized images and also use resizing / downsampling etc. according to frescolib.org guides.

**Comment by LomikXP** [comment]
Use guides. Its "one user bug", will try get heap image before crash.

**Comment by LomikXP** [comment]
Hm, I dont get enough info. For now its may be closed.
