### ISSUE TITLE
Native crash when SimpleDraweeView onDraw()

### ISSUE THREAD

**Issue by chenleejr** [facebook/fresco#2224]
### Description

We show images like that
```
final Uri uri = Uri.parse("file://" + mediaModel.getFilePath());
ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                .setResizeOptions(new ResizeOptions(mItemSize, mItemSize))
                .setPostprocessor(new CutLongImageProcessor(mMaxBitmapSize, mItemSize, mediaModel.getFilePath()))
                .build();
DraweeController controller = Fresco.newDraweeControllerBuilder()
                .setOldController(mImageView.getController())
                .setImageRequest(request)
                .build();
mImageView.setController(controller);
```
But many users feedback the crash
```
fatal signal no is : 06
#00 pc 0001aa2c /system/lib/libc.so (abort)
below is native thread corresponding java thread stack:
at android.graphics.BitmapShader.nativeCreate(Native Method)
at android.graphics.BitmapShader.createNativeInstance(BitmapShader.java:61)
at android.graphics.Shader.getNativeInstance(Shader.java:160)
at android.graphics.Paint.getNativeInstance(Paint.java:649)
at android.view.RecordingCanvas.drawPath(RecordingCanvas.java:283)
at com.facebook.drawee.drawable.RoundedBitmapDrawable.draw(SourceFile:54) 
at com.facebook.drawee.drawable.ForwardingDrawable.draw(SourceFile:145)
at com.facebook.drawee.drawable.ForwardingDrawable.draw(SourceFile:145)
at com.facebook.drawee.drawable.ScaleTypeDrawable.draw(SourceFile:123)
at com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha(SourceFile:302)
at com.facebook.drawee.drawable.FadeDrawable.draw(SourceFile:289)
at com.facebook.drawee.drawable.ForwardingDrawable.draw(SourceFile:145)
at com.facebook.drawee.generic.RootDrawable.draw(SourceFile:81)
at android.widget.ImageView.onDraw(ImageView.java:1353)
at android.view.View.draw(View.java:19248)
at android.view.View.updateDisplayListIfDirty(View.java:18198)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
at android.view.View.updateDisplayListIfDirty(View.java:18157)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
at android.view.View.updateDisplayListIfDirty(View.java:18157)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
at android.view.View.updateDisplayListIfDirty(View.java:18157)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
at android.view.View.updateDisplayListIfDirty(View.java:18157)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
at android.view.View.updateDisplayListIfDirty(View.java:18157)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
at android.view.View.updateDisplayListIfDirty(View.java:18157)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
at android.view.View.updateDisplayListIfDirty(View.java:18157)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4224)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4204)
at android.view.View.updateDisplayListIfDirty(View.java:18157)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:685)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:691)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:799)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:3084)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2861)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2414)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1447)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6902)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:968)
at android.view.Choreographer.doCallbacks(Choreographer.java:780)
at android.view.Choreographer.doFrame(Choreographer.java:715)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:171)
at android.app.ActivityThread.main(ActivityThread.java:6649)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```
### Reproduction

I am sorry we cannot reproduce this crash

### Additional Information

* Fresco version: 1.10.0
* Platform version: 8.0.0,8.1.0,7.0.0,5.1.0 and more

**Comment by zmroczek** [comment]
Hi @chenleejr 

Do you know if this happens on any specific devices? It's hard to figure out what is wrong without a consistent way to reproduce it.
