### ISSUE TITLE
Onresume ListView SimpleDraweeView crashed

### ISSUE THREAD

**Issue by xesun** [facebook/fresco#225]
java.lang.StackOverflowError
            at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:393)
            at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:139)
            at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:139)
            at com.facebook.drawee.drawable.ScaleTypeDrawable.draw(ScaleTypeDrawable.java:104)
            at com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha(FadeDrawable.java:306)
            at com.facebook.drawee.drawable.FadeDrawable.draw(FadeDrawable.java:293)
            at com.facebook.drawee.generic.GenericDraweeHierarchy$RootFadeDrawable.draw(GenericDraweeHierarchy.java:127)

**Comment by tyronen** [comment]
Do you have more of the stack trace than that? Can you show us the XML or code you built the hierarchy with?

**Comment by plamenko** [comment]
reaping
