### ISSUE TITLE
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again

### ISSUE THREAD

**Issue by 456838** [facebook/fresco#2251]
### Description

we use fresco as image framework display everywhere , bug get some crash in bug system. may u help us analyize this problem?  stack as follow:
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
2
    at java.lang.Thread.nativeCreate(Native Method)
3
    at java.lang.Thread.start(Thread.java:753)
4
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
5
    at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1038)
6
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1180)
7
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
8
    at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(SourceFile:51)
9
    at java.lang.Thread.run(Thread.java:784)

### Additional Information

* Fresco version: [1.9.0]
* Platform version: [HWI-AL00 8.0.0]

**Comment by oprisnik** [comment]
Please fill out the issue template. The stack trace could be caused by anything. There are various threads for OOMs as well where you could take a look.
