### ISSUE TITLE
DefaultImageFormatChecker Attempt to get length of null array

### ISSUE THREAD

**Issue by wwwtete** [facebook/fresco#2255]
Android OS: 9.0
fresco version: 1.11.0

This only happens on Android 9.0:
Caused by java.lang.NullPointerException: Attempt to get length of null array
       at com.facebook.imageformat.DefaultImageFormatChecker.(DefaultImageFormatChecker.java:202)
       at com.facebook.imageformat.ImageFormatChecker.(ImageFormatChecker.java:32)
       at com.facebook.imageformat.ImageFormatChecker.getInstance(ImageFormatChecker.java:114)
       at com.facebook.imageformat.ImageFormatChecker.getImageFormat(ImageFormatChecker.java:130)
       at com.facebook.imageformat.ImageFormatChecker.getImageFormat_WrapIOException(ImageFormatChecker.java:139)
       at com.facebook.imagepipeline.image.EncodedImage.parseMetaData(EncodedImage.java:347)
       at com.facebook.imagepipeline.image.EncodedImage.parseMetaDataIfNeeded(EncodedImage.java:341)
       at com.facebook.imagepipeline.image.EncodedImage.getImageFormat(EncodedImage.java:220)
       at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$EncodedMemoryCacheConsumer.onNewResultImpl(EncodedMemoryCacheProducer.java:140)
       at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$EncodedMemoryCacheConsumer.onNewResultImpl(EncodedMemoryCacheProducer.java:111)
       at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:97)
       at com.facebook.imagepipeline.producers.DiskCacheReadProducer$1.then(DiskCacheReadProducer.java:106)
       at com.facebook.imagepipeline.producers.DiskCacheReadProducer$1.then(DiskCacheReadProducer.java:87)
       at bolts.Task$14.run(Task.java:872)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
       at bolts.Task.completeImmediately(Task.java:863)
       at bolts.Task.access$000(Task.java:32)
       at bolts.Task$10.then(Task.java:654)
       at bolts.Task$10.then(Task.java:651)
       at bolts.Task.runContinuations(Task.java:956)
       at bolts.Task.trySetResult(Task.java:994)
       at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
       at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
       at bolts.Task$4.run(Task.java:357)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
       at java.lang.Thread.run(Thread.java:764)

**Comment by lambdapioneer** [comment]
Hi @wwwtete , can you provide us with full reproducing steps? I cannot reproduce this on an API 28 emulator.

I reckon it might be related to this line which uses "ASCII" but afaik only "US-ASCII" is guaranteed to be supported:

https://github.com/facebook/fresco/blob/5d419bcc450bd0e4fbc27546e94ac55ad20a3e60/imagepipeline-base/src/main/java/com/facebook/imageformat/ImageFormatCheckerUtils.java#L24-L32

However, I'd be vary trying to fix this without a way to reproduce the issue.
