### ISSUE TITLE
Fresco Crash on Initialize

### ISSUE THREAD

**Issue by nbortolussi** [facebook/fresco#2276]
### Description

On initialize there is a crash. Here is the error:

`Fatal Exception: java.lang.IncompatibleClassChangeError
Class 'com.facebook.imagepipeline.core.ImagePipelineConfig' does not implement interface 'com.facebook.imagepipeline.core.ExecutorSupplier' in call to 'java.util.concurrent.Executor com.facebook.imagepipeline.core.ExecutorSupplier.forLocalStorageWrite()' (declaration of 'com.facebook.imagepipeline.core.ImagePipelineFactory' appears in /data/app/com.winering.wine-1/base.apk)`

Here is the stack trace:

`Fatal Exception: java.lang.IncompatibleClassChangeError: Class 'com.facebook.imagepipeline.core.ImagePipelineConfig' does not implement interface 'com.facebook.imagepipeline.core.ExecutorSupplier' in call to 'java.util.concurrent.Executor com.facebook.imagepipeline.core.ExecutorSupplier.forLocalStorageWrite()' (declaration of 'com.facebook.imagepipeline.core.ImagePipelineFactory' appears in /data/app/com.winering.wine-1/base.apk)
       at com.facebook.imagepipeline.core.ImagePipelineFactory.getMainBufferedDiskCache(ImagePipelineFactory.java:241)
       at com.facebook.imagepipeline.core.ImagePipelineFactory.getProducerFactory(ImagePipelineFactory.java:358)
       at com.facebook.imagepipeline.core.ImagePipelineFactory.getProducerSequenceFactory(ImagePipelineFactory.java:378)
       at com.facebook.imagepipeline.core.ImagePipelineFactory.getImagePipeline(ImagePipelineFactory.java:259)
       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:51)
       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:42)
       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:35)
       at com.facebook.drawee.backends.pipeline.Fresco.initializeDrawee(Fresco.java:79)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:72)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:37)
       at com.winering.wine.tools.WineRing.onCreate(WineRing.java:28)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1037)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6322)
       at android.app.ActivityThread.access$1800(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1862)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7230)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

### Reproduction

I cannot myself - the bug I am seeing is coming through Crashlytics reporting. Seems to be happening to a Samsung Galaxy J7 running Android 6.

### Additional Information

* Fresco version: 1.10.0
* Platform version: Seems to be happening to a Samsung Galaxy J7 running Android 6.

**Comment by razzazcode** [comment]
i have the same error .. whenever I use 
fresco.initialize () ; the app crashes without logs ?

**Comment by oprisnik** [comment]
Can you give us some details about your Gradle setup?
Are you mixing different Fresco versions for different dependencies? Does this still repro with newer versions?
