### ISSUE TITLE
SoLoader initialize error with Android P

### ISSUE THREAD

**Issue by liusgh** [facebook/fresco#2280]
W/SoLoader: Cannot get nativeLoad method
            java.lang.NoSuchMethodException: nativeLoad [class java.lang.String, class java.lang.ClassLoader, class java.lang.String]
                at java.lang.Class.getMethod(Class.java:2068)
                at java.lang.Class.getDeclaredMethod(Class.java:2047)
                at com.facebook.soloader.SoLoader.getNativeLoadRuntimeMethod(SoLoader.java:281)
                at com.facebook.soloader.SoLoader.initSoLoader(SoLoader.java:233)
                at com.facebook.soloader.SoLoader.initImpl(SoLoader.java:141)
                at com.facebook.soloader.SoLoader.init(SoLoader.java:120)
                at com.facebook.soloader.SoLoader.init(SoLoader.java:104)
                at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:63)
                at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:46)
@zmroczek You have fixed the problem, but  I have some questions.I really need some help!!!
Under what circumstances do I need to update the version of this soLoader? We only used Fresco to load dynamic webp, and we haven't found any problems with this issue except for the warning message. So do we have to update the version of soLoader in Android P?
Many thanks.

**Comment by zmroczek** [comment]
Hi @liusgh 

Are you using the latest Fresco version (1.11.0) that has this bug fixed as mentioned in https://github.com/facebook/fresco/issues/2115 ?

**Comment by liusgh** [comment]
@zmroczek 
In fact, we only rely on a submodule, animated-webp (1.9.0), rather than relying directly on the entire Fresco. The version of the so-loader that the latest animated-webp (1.9.0) depends on is 0.3.0. Because we only use Fresco to load dynamic Webp. So this error stack will affect our current usage scenarios? Do we need to upgrade the dependency on animated-webp or so-loader?

**Comment by zmroczek** [comment]
Yes, this has been fixed in SoLoader version 0.5.0.
