### ISSUE TITLE
App is crashing on Samsung S8 only

### ISSUE THREAD

**Issue by hemantskycap** [facebook/fresco#2286]
### Description
App crashing on Samsung Galaxy S8 and working fine on other devices.

### Reproduction
Install app from this link: https://play.google.com/store/apps/details?id=skycap.kidsmeditation

### Solution
Looking for solution.

### Additional Information
* Fresco version: 1.11.0
* Platform version:  Samsung Galaxy S8, Android 8.

[crashlytics-logs.txt](https://github.com/facebook/fresco/files/2836119/skycap.kidsmeditation_issue_17_crash_5C59F70B004A000178226DF65A5A2246_DNE_0_v2.txt)

**Comment by defHLT** [comment]
Hi! From quick glance it seems to be related to fragments:
```
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(Unknown Source:40)
       at androidx.fragment.app.FragmentManagerImpl.modifiesAlpha(Unknown Source:2)
       at androidx.fragment.app.BackStackRecord.replace(Unknown Source:70)
       at androidx.fragment.app.BackStackRecord.detach(Unknown Source:1)
       at skycap.kidsmeditation.ui.main.MainFragment$mOnNavigationItemSelectedListener$1.onNavigationItemSelected(Unknown Source:142)
       at com.google.android.material.bottomnavigation.BottomNavigationView$1.onMenuItemSelected(Unknown Source:45)
       at androidx.appcompat.view.menu.MenuBuilder.setDefaultShowAsAction(Unknown Source:4)
       at androidx.appcompat.view.menu.MenuItemImpl.invoke(Unknown Source:14)
       at androidx.appcompat.view.menu.MenuBuilder.setDefaultShowAsAction(Unknown Source:12)
       at com.google.android.material.bottomnavigation.BottomNavigationMenuView$1.onClick(Unknown Source:19)
       at android.view.View.performClick(View.java:6935)
       at android.view.View$PerformClick.run(View.java:26211)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

 Why do you think Fresco is the culprit? Please reopen if needed.
