### ISSUE TITLE
Unable to load libimagepipeline.so

### ISSUE THREAD

**Issue by initishbhatt** [facebook/fresco#2287]
### Description
Getting Fatal issues on the production version of the application withe the `soLoader`. please find the stacktrace below:

```
Fatal Exception: java.lang.NoClassDefFoundError: com.facebook.imagepipeline.memory.NativeMemoryChunk
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:25)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:13)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:267)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.(MemoryPooledByteBufferOutputStream.java:51)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(MemoryPooledByteBufferFactory.java:106)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(MemoryPooledByteBufferFactory.java:24)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:96)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:73)
       at com.facebook.imagepipeline.backends.okhttp3.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:193)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)


Caused by java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: couldn't map "/data/data/appName/lib-0/libimagepipeline.so" segment 0: Permission denied
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
       at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:40)
       at com.facebook.imagepipeline.memory.NativeMemoryChunk.(NativeMemoryChunk.java:31)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:25)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:13)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:267)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.(MemoryPooledByteBufferOutputStream.java:51)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(MemoryPooledByteBufferFactory.java:106)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(MemoryPooledByteBufferFactory.java:24)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:96)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:73)
       at com.facebook.imagepipeline.backends.okhttp3.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:193)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)
```

### Additional Information

* Fresco version: 1.12.0
* Platform version: Android 8.0, HTC, HUWAEI

**Comment by initishbhatt** [comment]
`bug`

**Comment by fredzzt** [comment]
got a same one on  FUJITSU FMVNQ7P8 with Andorid 7.1.2
```
Caused by com.facebook.soloader.SoLoader$WrongAbiError: APK was built for a different platform
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:597)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
       at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:40)
       at com.facebook.imagepipeline.memory.NativeMemoryChunk.(SourceFile:31)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:25)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:13)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:13)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:267)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.(SourceFile:51)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(MemoryPooledByteBufferFactory.java:106)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(MemoryPooledByteBufferFactory.java:24)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(MemoryPooledByteBufferFactory.java:24)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:96)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:73)
       at com.facebook.imagepipeline.backends.okhttp3.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:177)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)


Caused by java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: "/data/app/com.maetimes.android.pokekara-1/lib/arm/libimagepipeline.so" has unexpected e_machine: 40
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
       at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
       at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:40)
       at com.facebook.imagepipeline.memory.NativeMemoryChunk.(SourceFile:31)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:25)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:13)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:13)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:267)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.(SourceFile:51)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(MemoryPooledByteBufferFactory.java:106)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(MemoryPooledByteBufferFactory.java:24)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(MemoryPooledByteBufferFactory.java:24)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:96)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:73)
       at com.facebook.imagepipeline.backends.okhttp3.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:177)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by FranziscaZarrai** [comment]
Looks like the same or at least related to https://github.com/facebook/fresco/issues/2322 and https://github.com/facebook/fresco/issues/2049

**Comment by hardapps1692** [comment]
> Looks like the same or at least related to #2322 and #2049 and we're having the same problem.

Do you get any solution?

**Comment by FranziscaZarrai** [comment]
@hardapps1692 we used a suggestion from here: https://github.com/facebook/fresco/issues/2049 

Here is our change (build.gradle file - where you also define the fresco dependency):

        /** this is workaround for open fresco issue: https://github.com/facebook/fresco/issues/2049 . This means that all our ndk library is called with 32-bit
         * possible performance issue is described here: https://developer.android.com/ndk/guides/abis.html in chapter "Android Platform ABI support"
         */
        ndk {
            abiFilters "armeabi-v7a", "x86"
        } 

Now there is a problem however - Google requires all apps to support 64Bit starting August 2019: https://developer.android.com/distribute/best-practices/develop/64-bit which means that solution can not be used anymore starting August. 

So right now we got two options: Get rid of fresco or find an alternative. Right now we're looking into trying out this suggestion: https://github.com/facebook/fresco/issues/2049#issuecomment-462880309
