### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError: com.facebook.imagepipeline.memory.NativeMemoryChunk

### ISSUE THREAD

**Issue by zetbrush** [facebook/fresco#2296]
Hi, guys I know there are already a couple of same issue raised before, but actually are closed due to inactivity.
So raising this again, and hoping for solutions.
<img width="1259" alt="screen shot 2019-02-27 at 4 53 15 pm" src="https://user-images.githubusercontent.com/8019003/53491987-2ff94b00-3ab1-11e9-8b5e-0ffc1d7fd7b7.png">
`Fatal Exception: java.lang.UnsatisfiedLinkError: com.facebook.imagepipeline.memory.NativeMemoryChunk
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(SourceFile:25)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(SourceFile:13)
       at com.facebook.imagepipeline.memory.BasePool.get(SourceFile:267)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.(SourceFile:51)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(SourceFile:106)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(SourceFile:24)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(SourceFile:96)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(SourceFile:73)
       at com.studio.fresco.backends.OkHttpNetworkFetcher$2.onResponse(SourceFile:147)
       at okhttp3.RealCall$AsyncCall.execute(SourceFile:153)
       at okhttp3.internal.NamedRunnable.run(SourceFile:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)`

### Reproduction
No reproduction steps, seems its crashing in a loop, as report time intervals < 1min

### Additional Information
proguard config
`
-keep,allowobfuscation @interface com.facebook.proguard.annotations.DoNotStrip
-keep,allowobfuscation @interface com.facebook.proguard.annotations.KeepGettersAndSetters
-keep,allowobfuscation @interface com.facebook.common.internal.DoNotStrip

-keep @com.facebook.proguard.annotations.DoNotStrip class *
-keep @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers class * {
    @com.facebook.proguard.annotations.DoNotStrip *;
    @com.facebook.common.internal.DoNotStrip *;
}

-keepclassmembers @com.facebook.proguard.annotations.KeepGettersAndSetters class * {
  void set*(***);
  *** get*();
}
`

* Fresco version: [1.11.0]
* Platform version: [Android 6 ] 96%

**Comment by zmroczek** [comment]
Hi @zetbrush 

Thanks for reporting this again. As we don't have any repro steps it's hard to investigate the issue. The list of devices affected might mean it can be connected with some specific ROMs, if you could investigate on that further and find a way to reproduce it e.g. on a specific device that would be helpful.

**Comment by zetbrush** [comment]
@zmroczek thx for note, will update here if any news

**Comment by zetbrush** [comment]
same crash with another call log
```
Fatal Exception: java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.imagepipeline.memory.NativeMemoryChunk; see exception in other thread
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(SourceFile:25)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(SourceFile:13)
       at com.facebook.imagepipeline.memory.BasePool.get(SourceFile:267)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.(SourceFile:51)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(SourceFile:73)
       at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(SourceFile:24)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(SourceFile:373)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.access$400(SourceFile:35)
       at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(SourceFile:193)
       at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(SourceFile:174)
       at bolts.Task$4.run(SourceFile:357)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(SourceFile:51)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by zetbrush** [comment]
@zmroczek do you think SoLoader crash causes this one?

**Comment by oprisnik** [comment]
Please take a look at https://github.com/facebook/fresco/issues/2049#issuecomment-473866204

The fix explained there should help with mitigating this issue.
