### ISSUE TITLE
NoSuchMethodError: at com.facebook.imagepipeline.producers.JobScheduler.scheduleJob

### ISSUE THREAD

**Issue by zetbrush** [facebook/fresco#2304]
### Description

```
Fatal Exception: java.lang.NoSuchMethodError: No static method ()J in class Landroid/os/SystemClock; or its super classes (declaration of 'android.os.SystemClock' appears in /system/framework/framework.jar)
       at com.facebook.imagepipeline.producers.JobScheduler.scheduleJob(SourceFile:140)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.onNewResultImpl(SourceFile:204)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.onNewResultImpl(SourceFile:123)
       at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(SourceFile:97)
       at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.onNewResultImpl(SourceFile:168)
       at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.onNewResultImpl(SourceFile:82)
       at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(SourceFile:97)
       at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(SourceFile:46)
       at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(SourceFile:30)
       at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(SourceFile:97)
       at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onNextResult(SourceFile:452)
       at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(SourceFile:513)
       at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(SourceFile:506)
       at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(SourceFile:97)
       at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$EncodedMemoryCacheConsumer.onNewResultImpl(SourceFile:166)
       at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$EncodedMemoryCacheConsumer.onNewResultImpl(SourceFile:111)
       at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(SourceFile:97)
       at com.facebook.imagepipeline.producers.DiskCacheReadProducer$1.then(SourceFile:106)
       at com.facebook.imagepipeline.producers.DiskCacheReadProducer$1.then(SourceFile:87)
       at bolts.Task$14.run(SourceFile:872)
       at bolts.BoltsExecutors$ImmediateExecutor.execute(SourceFile:105)
       at bolts.Task.completeImmediately(SourceFile:863)
       at bolts.Task.access$000(SourceFile:32)
       at bolts.Task$10.then(SourceFile:651)
       at bolts.Task.runContinuations(SourceFile:956)
       at bolts.Task.trySetResult(SourceFile:994)
       at bolts.TaskCompletionSource.trySetResult(SourceFile:39)
       at bolts.TaskCompletionSource.setResult(SourceFile:62)
       at bolts.Task$4.run(SourceFile:357)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(SourceFile:51)
       at java.lang.Thread.run(Thread.java:762)
```

### Reproduction
No repro steps

### Additional Information

* Fresco version: [1.11.0]
* Platform version: [Samsung Galaxy J7(2016) Android OS version 7.0]

**Comment by defHLT** [comment]
Looks like your proguard is too aggressive. JobSchedule just tries to call uptimeMillis() on SystemClock. Does it works when proguard is disabled?

**Comment by zetbrush** [comment]
@defHLT this only gets reported on specified device, could it really be pro-guard issue?
