### ISSUE TITLE
Fresco.initialize caused Application Not Responding

### ISSUE THREAD

**Issue by apue** [facebook/fresco#2320]
### Description

I called below code:
```java
ImagePipelineConfig config = ImagePipelineConfig.newBuilder(context)
        .setDownsampleEnabled(true)
        .build();

Fresco.initialize(context, config);
```
and got below ANR:
java.util.regex.Matcher in openImpl
java.util.regex.Matcher in usePattern at line 238
java.util.regex.Matcher in <init> at line 89
java.util.regex.Pattern in matcher at line 297
com.facebook.soloader.ExtractFromZipSoSource$ZipUnpacker in ensureDsos at line 79
com.facebook.soloader.ExtractFromZipSoSource$ZipUnpacker in getDsoManifest at line 137
com.facebook.soloader.UnpackingSoSource in refreshLocked at line 324
com.facebook.soloader.UnpackingSoSource in prepare at line 420
com.facebook.soloader.SoLoader in initSoSources at line 266
com.facebook.soloader.SoLoader in init at line 170
com.facebook.soloader.SoLoader in init at line 153
com.facebook.drawee.backends.pipeline.Fresco in initialize at line 61
com.facebook.drawee.backends.pipeline.Fresco in initialize at line 44
com.mycompany.FrescoImageView in init at line 294

### Reproduction

It is an online ANR, I can't reproduce it on my phone, however it happens more than 100 times per day.

### Solution

N/A

### Additional Information

* Fresco version: 1.10.0
* Platform version: from 4.4 to 9.0

**Comment by zmroczek** [comment]
Hi @apue,

Thanks for reporting. I guess this might be similar problem to the issue #2141 or another soLoader issue that you could report in soLoader repo, could you please take a look? Would be great if you could try to provide a repro, without that it might be hard to find the direct cause.

**Comment by apue** [comment]
> Hi @apue,
> 
> Thanks for reporting. I guess this might be similar problem to the issue #2141 or another soLoader issue that you could report in soLoader repo, could you please take a look? Would be great if you could try to provide a repro, without that it might be hard to find the direct cause.

@zmroczek it is a different problem, however I believe this issue lies in soloader, so I'll move this issue to soloader repo.

**Comment by RitaBags** [comment]
Is this Application Not Responding issue resolved. We are facing same ANR while initializing the liabrary  as 
```
fun init() {
        Fresco.initialize(application, imagePipelineConfig)
    }
```
 
Below are the crash logs:
at java.util.concurrent.CancellationException.<init>(CancellationException.java:61)
       at com.facebook.imagepipeline.core.ImagePipeline.<clinit>(ImagePipeline.java)
       at com.facebook.imagepipeline.core.ImagePipelineFactory.createImagePipeline(ImagePipelineFactory.java:309)
       at com.facebook.imagepipeline.core.ImagePipelineFactory.getImagePipeline(ImagePipelineFactory.java:303)
       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:55)
       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:45)
       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:38)
       at com.facebook.drawee.backends.pipeline.Fresco.initializeDrawee(Fresco.java:121)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:110)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:54)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:46)
       at com.mycompany.framework.fresco.FrescoManager.init(FrescoManager.java:13)
