### ISSUE TITLE
Fresco + Realm.io library conflicts on 64-bit devices

### ISSUE THREAD

**Issue by elikohen** [facebook/fresco#237]
If you have this:

```
compile 'io.realm:realm-android:0.80.1'
```

Added to the build.gradle file on the Sample project a crash will appear in 64bit devices (tested on Nexus 9)

Stacktrace:
```
05-06 19:38:58.356    4382-4469/com.facebook.fresco.sample E/AndroidRuntime﹕ FATAL EXCEPTION: pool-1-thread-2
    Process: com.facebook.fresco.sample, PID: 4382
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.facebook.fresco.sample-2/base.apk"],nativeLibraryDirectories=[/data/app/com.facebook.fresco.sample-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libgnustl_shared.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:366)
            at java.lang.System.loadLibrary(System.java:989)
            at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:34)
            at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
            at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:36)
            at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
            at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
            at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:264)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:98)
            at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
            at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:198)
            at com.facebook.imagepipeline.cache.BufferedDiskCache.access$300(BufferedDiskCache.java:38)
            at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:104)
            at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:88)
            at bolts.Task$2.run(Task.java:195)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by elikohen** [comment]
Does Fresco provide direct support for ARM64? 
Just want to confirm the guess from @emanuelez on this comment: https://github.com/realm/realm-java/issues/1092#issuecomment-99791863

**Comment by cmelchior** [comment]
#121 and #176 both add support for ARM64 and x86_64 so I would guess no atm.

**Comment by tyronen** [comment]
The most recent releases of Fresco don't require libgnustl_shared.so anymore though. What version are you using?

**Comment by elikohen** [comment]
We're using 0.4.0

**Comment by michalgr** [comment]
Fresco does not put any libraries in "lib/arm64", it will be fixed by https://github.com/facebook/fresco/pull/176 soon. 

There is something about the stack trace I cannot explain though. System tried to load gnustl_shared, @elikohen did you get this stack trace with fresco earlier than 0.3.0 ? Since v 0.3.0 NativeMemoryChunk does not depend on stl and unless you used old fresco version there is something else wrong as well.

**Comment by tyronen** [comment]
We have improved 64-bit handling in v0.5.1. If this issue persists there, please file a new issue.

**Comment by elikohen** [comment]
Working on version 0.5.1!

Thank you for the effort!
