### ISSUE TITLE
ThumbnailUtils: java.io.IOException: Failed to create thumbnail

### ISSUE THREAD

**Issue by waseefakhtar** [facebook/fresco#2390]
### Description

I'm trying to load some thumbnails from video file but I notice that some video formats throws a runtime exception:

```
W/ThumbnailUtils: java.io.IOException: Failed to create thumbnail
        at android.media.ThumbnailUtils.createVideoThumbnail(ThumbnailUtils.java:331)
        at android.media.ThumbnailUtils.createVideoThumbnail(ThumbnailUtils.java:286)
        at com.facebook.imagepipeline.producers.LocalVideoThumbnailProducer$1.getResult(LocalVideoThumbnailProducer.java:81)
        at com.facebook.imagepipeline.producers.LocalVideoThumbnailProducer$1.getResult(LocalVideoThumbnailProducer.java:61)
        at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:43)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
        at android.media.MediaMetadataRetriever.setDataSource(Native Method)
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:75)
        at android.media.ThumbnailUtils.createVideoThumbnail(ThumbnailUtils.java:309)
        at android.media.ThumbnailUtils.createVideoThumbnail(ThumbnailUtils.java:286) 
        at com.facebook.imagepipeline.producers.LocalVideoThumbnailProducer$1.getResult(LocalVideoThumbnailProducer.java:81) 
        at com.facebook.imagepipeline.producers.LocalVideoThumbnailProducer$1.getResult(LocalVideoThumbnailProducer.java:61) 
        at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:43) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51) 
        at java.lang.Thread.run(Thread.java:919) 
```

So I had to dig deeper to test with different video formats and for me, AVI, MPG/MPEG, and WMV throws this exception every time.

### Reproduction

Load a thumbnail from the following video file formats: AVI, MPG/MPEG, or WMV.

### Additional Information

* Fresco version: 1.13.0
* Platform version: API Q on Android Studio Emulator

**Comment by oprisnik** [comment]
Thanks. Looks like this is currently not properly supported.

**Comment by waseefakhtar** [comment]
Observing this further, I now see that users are also affected by this exception loading from mp4 files (which hasn't happened in my case), so my guess is this also occurs loading files from incomplete or corrupted files, like mentioned here: https://stackoverflow.com/a/4912714/2997806. Not sure how to check for incomplete or corrupted files in our case though.

**Comment by githubPQQ** [comment]
I met the same problem

**Comment by mdsheraj123** [comment]
I had the same problem, turns out that video was corrupted when I checked in the gallery.

**Comment by perracolabs** [comment]
I added a pull request fixing the issue, just needs to get accepted. Check the description for an explanation about the cause: https://github.com/facebook/fresco/pull/2594
