### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libnative-imagetranscoder.so caused by: dlopen failed: "/data/data/com.degoo.android/lib-main/libnative-imagetranscoder.so" is 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by waseefakhtar** [facebook/fresco#2393]
Since a similar issue #2339 was closed, I'd like to know if there's solution for the error below:

```
Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libnative-imagetranscoder.so caused by: dlopen failed: "/data/data/com.degoo.android/lib-main/libnative-imagetranscoder.so" is 64-bit instead of 32-bit
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName + 738(SoLoader.java:738)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName + 591(SoLoader.java:591)
       at com.facebook.soloader.SoLoader.loadLibrary + 529(SoLoader.java:529)
       at com.facebook.soloader.SoLoader.loadLibrary + 484(SoLoader.java:484)
       at com.facebook.imagepipeline.nativecode.NativeJpegTranscoderSoLoader.ensure + 28(NativeJpegTranscoderSoLoader.java:28)
       at com.facebook.imagepipeline.nativecode.NativeJpegTranscoder.(S:47)
       at com.facebook.imagepipeline.nativecode.NativeJpegTranscoderFactory.createImageTranscoder + 35(NativeJpegTranscoderFactory.java:35)
       at com.facebook.imagepipeline.transcoder.MultiImageTranscoderFactory.getNativeImageTranscoder + 70(MultiImageTranscoderFactory.java:70)
       at com.facebook.imagepipeline.transcoder.MultiImageTranscoderFactory.createImageTranscoder + 47(MultiImageTranscoderFactory.java:47)
       at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.onNewResultImpl + 161(ResizeAndRotateProducer.java:161)
       at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.onNewResultImpl + 83(ResizeAndRotateProducer.java:83)
       at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult + 97(BaseConsumer.java:97)
       at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl + 46(AddImageTransformMetaDataProducer.java:46)
       at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl + 30(AddImageTransformMetaDataProducer.java:30)
       at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult + 97(BaseConsumer.java:97)
       at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onNextResult + 452(MultiplexProducer.java:452)
       at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl + 513(MultiplexProducer.java:513)
       at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl + 506(MultiplexProducer.java:506)
       at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult + 97(BaseConsumer.java:97)
       at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$EncodedMemoryCacheConsumer.onNewResultImpl + 166(EncodedMemoryCacheProducer.java:166)
       at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$EncodedMemoryCacheConsumer.onNewResultImpl + 111(EncodedMemoryCacheProducer.java:111)
       at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult + 97(BaseConsumer.java:97)
       at com.facebook.imagepipeline.producers.DiskCacheReadProducer$1.then + 107(DiskCacheReadProducer.java:107)
       at com.facebook.imagepipeline.producers.DiskCacheReadProducer$1.then + 88(DiskCacheReadProducer.java:88)
       at bolts.Task$14.run + 872(Task.java:872)
       at bolts.BoltsExecutors$ImmediateExecutor.execute + 105(BoltsExecutors.java:105)
       at bolts.Task.completeImmediately + 863(Task.java:863)
       at bolts.Task.access$000 + 32(Task.java:32)
       at bolts.Task$10.then + 654(Task.java:654)
       at bolts.Task$10.then + 651(Task.java:651)
       at bolts.Task.runContinuations + 956(Task.java:956)
       at bolts.Task.trySetResult + 994(Task.java:994)
       at bolts.TaskCompletionSource.trySetResult + 39(TaskCompletionSource.java:39)
       at bolts.TaskCompletionSource.setResult + 62(TaskCompletionSource.java:62)
       at bolts.Task$4.run + 357(Task.java:357)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1115(ThreadPoolExecutor.java:1115)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 590(ThreadPoolExecutor.java:590)
       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run + 51(PriorityThreadFactory.java:51)
       at java.lang.Thread.run + 818(Thread.java:818)
```

I've tried downgrading my Android Gradle plugin with the https://github.com/facebook/SoLoader/issues/29#issuecomment-492929087 suggestion but that gives me build errors about compatibility issues with androidx dependencies like:

```
Android dependency 'androidx.core:core' has different version for the compile (1.0.0) and runtime (1.0.1) classpath. You should manually set the same version via DependencyResolution
```

After fixing them, I get an exception related to Dagger:

```
e: [kapt] An exception occurred: java.util.NoSuchElementException
	at com.sun.tools.javac.util.List$2.next(List.java:432)
	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:302)
	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:254)
	at dagger.android.processor.AndroidMapKeys.mapKeyValue(AndroidMapKeys.java:75)
	at dagger.android.processor.AndroidMapKeys.lambda$annotationsAndFrameworkTypes$5(AndroidMapKeys.java:56)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
```

So I really don't want to downgrade my Android Gradle plugin. Also, we've only noticed the error after making our app support 64-bit architecture, so it makes more sense the error is related with architecture rather the Android Gradle plugin. 

The error mostly occurs on Oppo and Android 5.1.1:

<img width="920" alt="Screen Shot 2019-08-14 at 7 29 12 PM" src="https://user-images.githubusercontent.com/4093820/63029409-f5059b00-bec9-11e9-9f4a-bbd22c33fef3.png"> 

Any idea how this could be solved?

**Comment by oprisnik** [comment]
Yeah, looks like some Oppo devices don't properly handle 64 bit SO files :(

**Comment by waseefakhtar** [comment]
@oprisnik that's odd, yes. Is there a workaround to fix this besides downgrading the Android Gradle plugin?

**Comment by oprisnik** [comment]
Can you try the suggestions mentioned in https://github.com/facebook/react-native/issues/25490 ? Looks like that fixed the issue for some folks.

**Comment by Yonghejiunian** [comment]
I try to do like this:



        try {
            ReLinker.loadLibrary(context, "imagepipeline");
        } catch (Throwable ex) {

            Fresco.shutDown();
            builder.experiment().setNativeCodeDisabled(true);
            ImagePipelineConfig configEx = builder.build();
            Fresco.initialize(context, configEx);
            if (!Fresco.hasBeenInitialized()) {
                Fresco.initialize(context);
            }
            if (ex != null)
                Z.e("FrescoHelper", "initFresco link imagepipeline.so throwable: " + ex.toString());

        }
        try {
            NativeJpegTranscoderSoLoader.ensure();
        } catch (Throwable ex) {
            Field field;
            try {
                field = NativeJpegTranscoderSoLoader.class.getDeclaredField("sInitialized");
                field.setAccessible(true);
                field.setBoolean(NativeJpegTranscoderSoLoader.class, true);
            } catch (NoSuchFieldException e) {
                e.printStackTrace();
            } catch (IllegalAccessException e) {
                e.printStackTrace();
            }
        }

**Comment by Yonghejiunian** [comment]
But I hava a other Exception : 

Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libnative-filters.so caused by: dlopen failed: "/data/data/sg.cocofun/lib-main/libnative-filters.so" is 64-bit instead of 32-bit
       at com.facebook.soloader.SoLoader.doLoadLibraryBySoName + 738(SoLoader.java:738)
       at com.facebook.soloader.SoLoader.loadLibraryBySoName + 591(SoLoader.java:591)
       at com.facebook.soloader.SoLoader.loadLibrary + 529(SoLoader.java:529)
       at com.facebook.soloader.SoLoader.loadLibrary + 484(SoLoader.java:484)
       at com.facebook.imagepipeline.nativecode.NativeFiltersLoader.load + 16(NativeFiltersLoader.java:16)
       at com.facebook.imagepipeline.nativecode.NativeBlurFilter.(SourceFile:21)
       at com.facebook.imagepipeline.postprocessors.IterativeBoxBlurPostProcessor.process + 45(IterativeBoxBlurPostProcessor.java:45)
       at com.facebook.imagepipeline.request.BasePostprocessor.process + 85(BasePostprocessor.java:85)
       at com.facebook.imagepipeline.request.BasePostprocessor.process + 61(BasePostprocessor.java:61)
       at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.postprocessInternal + 247(PostprocessorProducer.java:247)
       at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.doPostprocessing + 217(PostprocessorProducer.java:217)
       at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.onNewResultImpl + 73(PostprocessorProducer.java:73)
       at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer$2.run + 175(PostprocessorProducer.java:175)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1115(ThreadPoolExecutor.java:1115)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 590(ThreadPoolExecutor.java:590)
       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run + 51(PriorityThreadFactory.java:51)
       at java.lang.Thread.run + 818(Thread.java:818)

**Comment by waseefakhtar** [comment]
> Can you try the suggestions mentioned in [facebook/react-native#25490](https://github.com/facebook/react-native/issues/25490) ? Looks like that fixed the issue for some folks.

I tried the suggestion by making changes to packagingOptions like [here](https://github.com/facebook/react-native/issues/25490#issuecomment-521243603) which now throws an exception saying `/libimagepipeline.so" is 32-bit instead of 64-bit` instead of the other way around (I mean, I can reproduce it even on an emulator and not just on an Oppo device):

```
2019-08-20 15:40:03.430 14786-15049/com.degoo.android.dev W/System.err: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: "/data/data/com.degoo.android.dev/lib-main/libimagepipeline.so" is 32-bit instead of 64-bit com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738) 
com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591) 
com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529) 
com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484) 
com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:40) 
com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:31
com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:25)
com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:13) 
com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:267)
com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.<init (MemoryPooledByteBufferOutputStream.java:51) com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(MemoryPooledByteBufferFactory.java:73) 
com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(MemoryPooledByteBufferFactory.java:24) 
com.facebook.imagepipeline.producers.LocalFetchProducer.getByteBufferBackedEncodedImage(LocalFetchProducer.java:85) 
com.facebook.imagepipeline.producers.LocalFetchProducer.getEncodedImage(LocalFetchProducer.java:97) 
com.facebook.imagepipeline.producers.LocalResourceFetchProducer.getEncodedImage(LocalResourceFetchProducer.java:37) 
com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:50) com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:46) 
com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:43) 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51) java.lang.Thread.run(Thread.java:919)
```

**Comment by waseefakhtar** [comment]
> But I hava a other Exception :
> 
> Fatal Exception: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libnative-filters.so caused by: dlopen failed: "/data/data/sg.cocofun/lib-main/libnative-filters.so" is 64-bit instead of 32-bit
> at com.facebook.soloader.SoLoader.doLoadLibraryBySoName + 738(SoLoader.java:738)
> at com.facebook.soloader.SoLoader.loadLibraryBySoName + 591(SoLoader.java:591)
> at com.facebook.soloader.SoLoader.loadLibrary + 529(SoLoader.java:529)
> at com.facebook.soloader.SoLoader.loadLibrary + 484(SoLoader.java:484)
> at com.facebook.imagepipeline.nativecode.NativeFiltersLoader.load + 16(NativeFiltersLoader.java:16)
> at com.facebook.imagepipeline.nativecode.NativeBlurFilter.(SourceFile:21)
> at com.facebook.imagepipeline.postprocessors.IterativeBoxBlurPostProcessor.process + 45(IterativeBoxBlurPostProcessor.java:45)
> at com.facebook.imagepipeline.request.BasePostprocessor.process + 85(BasePostprocessor.java:85)
> at com.facebook.imagepipeline.request.BasePostprocessor.process + 61(BasePostprocessor.java:61)
> at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.postprocessInternal + 247(PostprocessorProducer.java:247)
> at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.doPostprocessing + 217(PostprocessorProducer.java:217)
> at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.onNewResultImpl + 73(PostprocessorProducer.java:73)
> at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer$2.run + 175(PostprocessorProducer.java:175)
> at java.util.concurrent.ThreadPoolExecutor.runWorker + 1115(ThreadPoolExecutor.java:1115)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run + 590(ThreadPoolExecutor.java:590)
> at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run + 51(PriorityThreadFactory.java:51)
> at java.lang.Thread.run + 818(Thread.java:818)

Is it specific to one device or many devices? Also, can you reproduce it yourself?

**Comment by waseefakhtar** [comment]
@oprisnik could you merge https://github.com/facebook/react-native/issues/25490#issuecomment-522968429 and release a new version for SoLoader and Fresco?

**Comment by oprisnik** [comment]
Thanks. We're on it. I've imported the PR.

**Comment by Alphabets007** [comment]
Anyone has fixed this issue?

**Comment by waseefakhtar** [comment]
Hi @oprisnik, I wonder if there's any update on this yet. When can we expect a new release with a fix?

**Comment by btxd** [comment]
HI，This is a problem in 2016, it has not been resolved; facebook developers are not fixing this problem; I can only be forced to use glide;Pealse hlep me. thanks you

**Comment by hzy00** [comment]
Similar problem here:

> Fatal Exception: java.lang.UnsatisfiedLinkError
couldn't find DSO to load: libstatic-webp.so caused by: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/app/mobi.mangatoon.comics.aphone-1/lib/arm64/libstatic-webp.so" (new hash type from the future?)
com.facebook.soloader.SoLoader.doLoadLibraryBySoName (SoLoader.java:703)
com.facebook.soloader.SoLoader.loadLibraryBySoName$6d1c7186 (SoLoader.java:564)
com.facebook.soloader.SoLoader.loadLibrary$505cff18 (SoLoader.java:500)
com.facebook.soloader.SoLoader.loadLibrary (SoLoader.java:455)
com.facebook.imagepipeline.nativecode.StaticWebpNativeLoader.ensure (StaticWebpNativeLoader.java:32)
com.facebook.animated.webp.WebPImage.create (WebPImage.java:78)
com.facebook.animated.webp.WebPImage.decode (WebPImage.java:85)
com.facebook.imagepipeline.animated.factory.AnimatedImageFactoryImpl.decodeWebP (AnimatedImageFactoryImpl.java:110)

**Comment by oprisnik** [comment]
The pull request is still under review. Once that's available, we can do a new release.

**Comment by waseefakhtar** [comment]
Thanks for the update! Looking forward.

**Comment by waseefakhtar** [comment]
> Quick update: We are going to make some slight adjustments to the new native loading API, before doing a new release.

Looking forward!

**Comment by zung** [comment]
hi, guys, in my OPPO R9m, ColorOS v3.0, android 5.1, has the same issue, and gradle is:

`implementation 'com.facebook.fresco:fresco:1.9.0'`
`implementation 'com.facebook.fresco:animated-gif:1.9.0'`
...
`ndk {abiFilters "armeabi-v7a", "arm64-v8a"}`

and i downgrade the fresco version to 0.12.0, animated-gif to 0.12.0, like this:
`implementation 'com.facebook.fresco:fresco:0.12.0'`
`implementation 'com.facebook.fresco:animated-gif:0.12.0'`

it works well now!

**Comment by waseefakhtar** [comment]
@zung downgrading is okay, but Fresco is about to launch a new release with the fix as well as making some slight adjustments to the new native loading API, like mentioned here: https://github.com/facebook/fresco/issues/2393#issuecomment-530821873

**Comment by dbrant** [comment]
> Fresco is about to launch a new release with the fix

About to?

**Comment by oprisnik** [comment]
Yes, sorry for the delays. Getting the Java Fresco version ready took a bit longer than expected. A new release will be available soon.

**Comment by lhzljl** [comment]
> 是的，对不起您的延迟。准备好Java Fresco版本花费的时间比预期的要长一点。新版本即将推出。
> 
> 同时，您应该可以[将SoLoader版本强制为0.8.0](https://github.com/facebook/react-native/issues/25490#issuecomment-534570333)。

Has the Fresco new version been released?

**Comment by oprisnik** [comment]
Yes, please use Fresco 2.1.0.

**Comment by funnyzhaov** [comment]
> Yes, please use Fresco 2.1.0.

Thanks, I will upgrade the use

**Comment by ovcharenkoa** [comment]
I tried to upgrade the Fresco v.2.6.0 to 3.0.0 and got a crash (Samsung Galaxy S21 FE 5G Android 13): 
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libnative-imagetranscoder.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
       at java.lang.Runtime.loadLibrary0(Runtime.java:998)
       at java.lang.System.loadLibrary(System.java:1661)
       at com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary(SystemDelegate.java:24)
       at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:52)
       at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
       at com.facebook.imagepipeline.nativecode.NativeJpegTranscoderSoLoader.ensure(NativeJpegTranscoderSoLoader.java:33)
       at com.facebook.imagepipeline.nativecode.NativeJpegTranscoder.<init>(NativeJpegTranscoder.java:59)
       at com.facebook.imagepipeline.nativecode.NativeJpegTranscoderFactory.createImageTranscoder(NativeJpegTranscoderFactory.java:43)
       at com.facebook.imagepipeline.transcoder.MultiImageTranscoderFactory.getNativeImageTranscoder(MultiImageTranscoderFactory.kt:59)
       at com.facebook.imagepipeline.transcoder.MultiImageTranscoderFactory.createImageTranscoder(MultiImageTranscoderFactory.kt:40)
       at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.onNewResultImpl(ResizeAndRotateProducer.java:166)
       at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.onNewResultImpl(ResizeAndRotateProducer.java:84)
       at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
       at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:49)
       at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:33)
       at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
       at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onNextResult(MultiplexProducer.java:510)
       at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:569)
       at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:562)
       at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
       at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer.produceResults(EncodedMemoryCacheProducer.java:75)
       at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.startInputProducerIfHasAttachedConsumers(MultiplexProducer.java:391)
       at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.access$000(MultiplexProducer.java:161)
       at com.facebook.imagepipeline.producers.MultiplexProducer.produceResults(MultiplexProducer.java:115)
       at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer.produceResults(AddImageTransformMetaDataProducer.java:30)
       at com.facebook.imagepipeline.producers.ResizeAndRotateProducer.produceResults(ResizeAndRotateProducer.java:79)
       at com.facebook.imagepipeline.producers.DecodeProducer.produceResults(DecodeProducer.kt:81)
       at com.facebook.imagepipeline.producers.BitmapMemoryCacheProducer.produceResults(BitmapMemoryCacheProducer.java:118)
       at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.startInputProducerIfHasAttachedConsumers(MultiplexProducer.java:391)
       at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.access$000(MultiplexProducer.java:161)
       at com.facebook.imagepipeline.producers.MultiplexProducer.produceResults(MultiplexProducer.java:115)
       at com.facebook.imagepipeline.producers.ThreadHandoffProducer$produceResults$1$statefulRunnable$1.onSuccess(ThreadHandoffProducer.kt:34)
       at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:55)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at com.facebook.imagepipeline.core.PriorityThreadFactory.newThread$lambda$0(PriorityThreadFactory.kt:37)
       at com.facebook.imagepipeline.core.PriorityThreadFactory.$r8$lambda$IPp7Vm9a1KDy8D4770JTjI9qOG4()
       at com.facebook.imagepipeline.core.PriorityThreadFactory$$ExternalSyntheticLambda0.run(:4)
       at java.lang.Thread.run(Thread.java:1012)

So, I'm compelled to return to the 2.6.0 version.
