### ISSUE TITLE
Multiple loading of the same GIF times abnormal information, only kill the app can be normal

### ISSUE THREAD

**Issue by 13716308208** [facebook/fresco#2403]
09-06 15:20:19.479 5763-5785/com.zwt.superandroid E/unknown:DefaultBitmapFramePreparer: Could not prepare frame 24.
09-06 15:20:19.509 5763-5763/com.zwt.superandroid W/unknown:BitmapAnimationBackend: Failed to create frame bitmap
    com.facebook.imagepipeline.memory.BasePool$PoolSizeViolationException: Pool hard cap violation? Hard cap = 201326592 Used size = 200232032 Free size = 0 Request size = 1300208
        at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:247)
        at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.createBitmapInternal(ArtBitmapFactory.java:51)
        at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap(PlatformBitmapFactory.java:74)
        at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap(PlatformBitmapFactory.java:41)
        at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback(BitmapAnimationBackend.java:209)
        at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback(BitmapAnimationBackend.java:237)
        at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrameOrFallback(BitmapAnimationBackend.java:237)
        at com.facebook.fresco.animation.bitmap.BitmapAnimationBackend.drawFrame(BitmapAnimationBackend.java:165)
        at com.facebook.fresco.animation.backend.AnimationBackendDelegate.drawFrame(AnimationBackendDelegate.java:59)
        at com.facebook.fresco.animation.backend.AnimationBackendDelegateWithInactivityCheck.drawFrame(AnimationBackendDelegateWithInactivityCheck.java:109)
        at com.facebook.fresco.animation.drawable.AnimatedDrawable2.draw(AnimatedDrawable2.java:206)
        at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:185)
        at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:185)
        at com.facebook.drawee.drawable.ScaleTypeDrawable.draw(ScaleTypeDrawable.java:139)
        at com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha(FadeDrawable.java:341)
        at com.facebook.drawee.drawable.FadeDrawable.draw(FadeDrawable.java:328)
        at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:185)
        at com.facebook.drawee.generic.RootDrawable.draw(RootDrawable.java:81)
        at android.widget.ImageView.onDraw(ImageView.java:1228)
        at android.view.View.draw(View.java:16245)
        at android.view.View.updateDisplayListIfDirty(View.java:15242)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3749)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3729)
        at android.view.View.updateDisplayListIfDirty(View.java:15202)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3749)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3729)
        at android.view.View.updateDisplayListIfDirty(View.java:15202)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3749)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3729)
        at android.view.View.updateDisplayListIfDirty(View.java:15202)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3749)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3729)
        at android.view.View.updateDisplayListIfDirty(View.java:15202)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3749)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3729)
        at android.view.View.updateDisplayListIfDirty(View.java:15202)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3749)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3729)
        at android.view.View.updateDisplayListIfDirty(View.java:15202)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3749)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3729)
        at android.view.View.updateDisplayListIfDirty(View.java:15202)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3749)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3729)
        at android.view.View.updateDisplayListIfDirty(View.java:15202)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3749)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3729)
        at android.view.View.updateDisplayListIfDirty(View.java:15202)
    	at android.view.ViewGrou
09-06 15:20:19.509 5763-5786/com.zwt.superandroid W/unknown:DefaultBitmapFramePreparer: Failed to create frame bitmap
    com.facebook.imagepipeline.memory.BasePool$PoolSizeViolationException: Pool hard cap violation? Hard cap = 201326592 Used size = 200232032 Free size = 0 Request size = 1300208
        at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:247)
        at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.createBitmapInternal(ArtBitmapFactory.java:51)
        at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap(PlatformBitmapFactory.java:74)
        at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap(PlatformBitmapFactory.java:41)
        at com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.prepareFrameAndCache(DefaultBitmapFramePreparer.java:143)
        at com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.prepareFrameAndCache(DefaultBitmapFramePreparer.java:167)
        at com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.run(DefaultBitmapFramePreparer.java:110)
        at com.facebook.common.executors.ConstrainedExecutorService$Worker.run(ConstrainedExecutorService.java:175)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)

**Comment by oprisnik** [comment]
Can you give us the GIF where this happens? If you're displaying many gifs at the same time, the number of bitmap will grow and might hit the bitmap cap.

**Comment by 13716308208** [comment]
> Can you give us the GIF where this happens? If you're displaying many gifs at the same time, the number of bitmap will grow and might hit the bitmap cap.

My operation is a GIF image repeated load, should not do a interception, determine whether it is the same GIF address?
