### ISSUE TITLE
BUG | FATAL EXCEPTION: mqt_native_modules when used inside PopupWindow

### ISSUE THREAD

**Issue by louisgv** [facebook/fresco#2438]
### Description

I tried to integrate Fresco with React Native inside a native module that spawn a PopupWindow, but when I tried to call setImageUri, the following error was throw:

```
2019-11-19 16:42:44.303 7835-7937/com.pleolouis E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.pleolouis, PID: 7835
    java.lang.IllegalStateException
        at com.facebook.common.internal.Preconditions.checkState(Preconditions.java:158)
        at com.facebook.drawee.components.DeferredReleaser.ensureOnUiThread(DeferredReleaser.java:100)
        at com.facebook.drawee.components.DeferredReleaser.cancelDeferredRelease(DeferredReleaser.java:95)
        at com.facebook.drawee.controller.AbstractDraweeController.onAttach(AbstractDraweeController.java:373)
        at com.facebook.drawee.view.DraweeHolder.attachController(DraweeHolder.java:266)
        at com.facebook.drawee.view.DraweeHolder.setController(DraweeHolder.java:198)
        at com.facebook.drawee.view.DraweeView.setController(DraweeView.java:131)
        at com.facebook.drawee.view.SimpleDraweeView.setImageURI(SimpleDraweeView.java:169)
        at com.facebook.drawee.view.SimpleDraweeView.setImageURI(SimpleDraweeView.java:180)
        at com.pleolouis.popup.ImagePopupModule$popImage$1.onViewTap(ImagePopupModule.kt:55)
        at me.relex.photodraweeview.DefaultOnDoubleTapListener.onSingleTapConfirmed(DefaultOnDoubleTapListener.java:42)
        at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:323)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:919)
2019-11-19 16:42:44.321 7835-7937/com.pleolouis I/Process: Sending signal. PID: 7835 SIG: 9
```

### Reproduction

The problematic code is here:
https://github.com/louisgv/mobile-challenge/blob/master/PleoLouis/android/app/src/main/java/com/pleolouis/popup/ImagePopupModule.kt#L31-L67

To test the flow, clone this project:
https://github.com/louisgv/mobile-challenge

On one terminal, run:
```
cd api/
npm start
```

On another:
```
cd PleoLouis
yarn start
```

Then open the android studio project, and run the app. If nothing load, run `yarn adb` to bridge the ports.

Once in the app, follow instruction in this issue: https://github.com/louisgv/mobile-challenge/issues/20#issuecomment-555784272

### Solution

[OPTIONAL: Do you know what needs to be done to address this issue? Ideally, provide a pull request which fixes this issue.]

### Additional Information

* Fresco version: 2.0.0
* Platform version: 28, Android Q on Google Pixel 1

**Comment by louisgv** [comment]
Debugging trace shows that the error was thrown when it tried to get into Looper:

https://github.com/facebook/fresco/blob/master/drawee/src/main/java/com/facebook/drawee/controller/AbstractDraweeController.java#L368

https://github.com/facebook/fresco/blob/26dfac78955b87c65d277da0c1d83c416c9610fa/drawee/src/main/java/com/facebook/drawee/components/DeferredReleaser.java#L65

ensureOnUiThread (2.0.0) or isOnUiThread is throwing the error. Is it because I cannot mount fresco on a PopupWindow?...

**Comment by louisgv** [comment]
After upgrading to 2.1.0, this was solved!
