### ISSUE TITLE
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: "/data/data/lib-main/libimagepipeline.so" is 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by nanchen2251** [facebook/fresco#2447]
Before I raised this issue, I have looked at all the previous issues, but it didn't solve my problem.
This is mainly a startup crash on the OPPO phone 5.1 system. Looking at the logs is basically a .so misplaced or a log that only appears without .so, but analyzing the APK is all normal.

crash phones:
OPPO A1601
OPPO A37f
OPPO A37fw
OPPO F1f

My log is as follows:
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: "/data/data/mypackage/lib-main/libimagepipeline.so" is 64-bit instead of 32-bit
	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
	at com.facebook.imageutils.FrescoSoLoader.loadLibrary(FrescoSoLoader.java:27)
	at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:40)
	at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:31)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:25)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:13)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:13)
	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:267)
	at com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.<init>(MemoryPooledByteBufferOutputStream.java:51)
	at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(MemoryPooledByteBufferFactory.java:73)
	at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(MemoryPooledByteBufferFactory.java:24)
	at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(MemoryPooledByteBufferFactory.java:24)
	at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(MemoryPooledByteBufferFactory.java:24)
	at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(MemoryPooledByteBufferFactory.java:24)
	at com.facebook.imagepipeline.producers.LocalFetchProducer.getByteBufferBackedEncodedImage(LocalFetchProducer.java:87)
	at com.facebook.imagepipeline.producers.LocalFetchProducer.getEncodedImage(LocalFetchProducer.java:99)
	at com.facebook.imagepipeline.producers.LocalResourceFetchProducer.getEncodedImage(LocalResourceFetchProducer.java:37)
	at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:52)
	at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:48)
	at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:43)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1115)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:590)
	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
	at java.lang.Thread.run(Thread.java:818)

**Comment by xuuhaoo** [comment]
I also met this error on Oppo device...Is there a way to resolve these issues?

**Comment by xuuhaoo** [comment]
I already have a way to resolve this issue by checking my lib folder, and find <***.so> is not making 64bit version in our project
