### ISSUE TITLE
 Caused by: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: cannot locate symbol "__atomic_exchange_4" referenced by "/data/app/com.xx.xxx-P0gd3ySaRB__Nc8OnWQMqg==/lib/arm/libimagepipeline.so"...

### ISSUE THREAD

**Issue by goodbranch** [facebook/fresco#2467]
### Description

how to fix

Android 9  , mac os build source from 1.13.0 use android-ndk-r16b-darwin-x86_64.zip, modify abi add armeabi . check  lib in armeabi contain "libimagepipeline.so"  ,first dex contain NativeMemoryChunk.class .

my app config:    include 'armeabi'

when launch  ,crash 

###

 java.lang.NoClassDefFoundError: com.facebook.imagepipeline.memory.NativeMemoryChunk
        at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:25)
        at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:13)
        at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:267)
        at com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.<init>(MemoryPooledByteBufferOutputStream.java:51)
        at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(MemoryPooledByteBufferFactory.java:73)
        at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(MemoryPooledByteBufferFactory.java:24)
        at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:375)
        at com.facebook.imagepipeline.cache.BufferedDiskCache.access$400(BufferedDiskCache.java:36)
        at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:194)
        at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:175)
        at bolts.Task$4.run(Task.java:357)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libimagepipeline.so caused by: dlopen failed: cannot locate symbol "__atomic_exchange_4" referenced by "/data/app/com.xx.xxx-P0gd3ySaRB__Nc8OnWQMqg==/lib/arm/libimagepipeline.so"...
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.imagepipeline.nativecode.ImagePipelineNativeLoader.load(ImagePipelineNativeLoader.java:40)
        at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:31)
        at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:25)
        at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:13)
        at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:267)
        at com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.<init>(MemoryPooledByteBufferOutputStream.java:51)
        at com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.<init>(MemoryPooledByteBufferOutputStream.java:33)
        at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(MemoryPooledByteBufferFactory.java:101)
        at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newOutputStream(MemoryPooledByteBufferFactory.java:24)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:98)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:73)
        at com.achievo.vipshop.commons.image.HttpUrlConnectionNetworkFetcher$1.run(HttpUrlConnectionNetworkFetcher.java:178)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784) 
2020-02-18 20:25:37.431 14773-15166/com.achievo.vipshop E/AndroidRuntime: FATAL EXCEPTION: FrescoIoBoundExecutor-17
    Process: com.achievo.vipshop, PID: 14773
    java.lang.NoClassDefFoundError: com.facebook.imagepipeline.memory.NativeMemoryChunk
        at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:25)
        at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:13)
        at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:267)
        at com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.<init>(MemoryPooledByteBufferOutputStream.java:51)
        at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(MemoryPooledByteBufferFactory.java:73)
        at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(MemoryPooledByteBufferFactory.java:24)
        at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:375)
        at com.facebook.imagepipeline.cache.BufferedDiskCache.access$400(BufferedDiskCache.java:36)
        at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:194)
        at com.facebook.imagepipeline.cache.BufferedDiskCache$2.call(BufferedDiskCache.java:175)
        at bolts.Task$4.run(Task.java:357)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
        at java.lang.Thread.run(Thread.java:784)

**Comment by goodbranch** [comment]
####more
copy armeabi-v7a  *.so into  my  project lib/armeabi  , run ok , fresco 1.13.0 build source no support armeabi ?

**Comment by goodbranch** [comment]
Looks like it's settled. thx for your help.

**Comment by cuibg** [comment]
why？armeabi-v7a  can support armeabi * so. If you don't this action, it will be ok!

**Comment by cuibg** [comment]
why？armeabi-v7a  can support armeabi * so. If you don't this action, it will be ok!
