### ISSUE TITLE
Always cannot show the images using in the low memory phones.  Emergency!!!

### ISSUE THREAD

**Issue by binqiangsun** [facebook/fresco#248]
Well, I found a problem, did Fresco do some limits when the memory is not enough?

Problems like this(this image is a little large.):
![cannotshow2](https://cloud.githubusercontent.com/assets/8416392/7566644/9d2b60d2-f82a-11e4-87b5-df979e403044.jpg)

and this:
![cannotshow1](https://cloud.githubusercontent.com/assets/8416392/7566653/aa33cc88-f82a-11e4-9bef-c261baacfee9.jpg)

And when I want to show 30 images, I added 30 simpledrawview dynamically. Fresco only can show about 25, and the left was as above. 

Did I config something wrong？

Uri uri = Uri.parse(strSrc);
        PipelineDraweeController controller = (PipelineDraweeController) Fresco.newDraweeControllerBuilder()
                .setUri(uri)
                .setTapToRetryEnabled(true)
                .setOldController(draweeView.getController())
                .build();
        draweeView.setController(controller);

**Comment by IanChilds** [comment]
If your images are too large, then you will run out of memory. Can you try setting a size for the images too so that they can be resized, and then hopefully you won't run out of memory?

**Comment by binqiangsun** [comment]
no, in the second case, the images are not too large.  why they were not be shown?

**Comment by IanChilds** [comment]
Because you have run out of memory - if the other 25 images are still in memory, then that's likely to be too many. Are the other images being removed from memory? What are you using to lay out the 30 SimpleDraweeViews (ListView, RecyclerView etc)?

**Comment by binqiangsun** [comment]
ok, you have a good suggestion.      

But for the first case, i think that the image is not large enough to be out of memory. even though, did fresco give me some notification for this?

**Comment by binqiangsun** [comment]
Fresco just cannot show the image forever. but other control like picasso / networkimageview can show this.

**Comment by binqiangsun** [comment]
what about this warning log?

W/View﹕ View too large to fit into drawing cache, needs 198223200 bytes, only 8294400 available

**Comment by IanChilds** [comment]
Hmm...that is a crazy number of bytes, I am not sure what's going on there. Are you getting this warning when trying to load the single image? Could you give a code snippet and the url that you are using.

**Comment by KrystalJake1989** [comment]
I also meet this problem,fresco can only load 11 bitmaps.Why?

**Comment by michalgr** [comment]
Fresco will refuse to decode more images if you hit one of the limits: https://github.com/facebook/fresco/blob/847851a8de6d223c0a6634447bddee1252e01c64/imagepipeline/src/main/java/com/facebook/imagepipeline/memory/BitmapCounterProvider.java (on dalvik) and https://github.com/facebook/fresco/blob/847851a8de6d223c0a6634447bddee1252e01c64/imagepipeline/src/main/java/com/facebook/imagepipeline/memory/DefaultBitmapPoolParams.java#L34-L41 (on art).

For changing the limit on art have a look at PoolConfig, PoolFactory and configuring ImagePipeline (http://frescolib.org/docs/configure-image-pipeline.html, http://frescolib.org/javadoc/reference/com/facebook/imagepipeline/memory/PoolConfig.html, http://frescolib.org/javadoc/reference/com/facebook/imagepipeline/memory/PoolFactory.html)

I don't think we have an API for changing the limit on dalvik, we probably should have.

**Comment by michalgr** [comment]
Anyway, bumping the limit is not necessarily the right solution. Can you use smaller images instead ?

**Comment by binqiangsun** [comment]
I found the source problem, I got the large image(like 1000px*1000px); but I used small SimpleDrawView(800px*800px); so it would use much memory. 

After I did like this:
ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri)
                .setResizeOptions(new ResizeOptions(width, height))
                .build();

the App runs better;

**Comment by plamenko** [comment]
"View too large to fit into drawing cache, needs 198223200 bytes, only 8294400 available"

Do you realize that 198223200 is nearly 200MB?

**Comment by tyronen** [comment]
Fixed in 0.5.2. Fresco will resize your image down to 2048 x 2048 maximum.

**Comment by binqiangsun** [comment]
can Fresco resize the image down to the draweeview size automatically? without using ResizeOptions?

**Comment by plamenko** [comment]
Not yet, but we are looking into adding this feature.

**Comment by saantiaguilera** [comment]
Im experiencing this issue (in 0.12), when loading big images from sdcard into low memory phones.

Currently im testing showing 5 jpg images (size of each: 11mb, 4672x3104 px). The phone is an LG Optimus L3 II (Android 4.1 / Dalvik of course)

Snippet of loading (Into a SimpleDraweeView):
```Java
            //Controller to help out, but does the fresco stuff inside (ResizeOptions in ImageRequest etc).
            FrescoImageController.create(getContext())
                    .load(someUriToTheSDCard)
                    .resize(240, 240) 
                    .autoRotate(true)
                    .into(imageView); //Note this works in better phones / normal images
```

While I initialize Fresco like this

```
        PoolFactory poolFactory = new PoolFactory(PoolConfig.newBuilder().build());

        Dispatcher dispatcher = new Dispatcher();
        dispatcher.setMaxRequests(poolFactory.getFlexByteArrayPoolMaxNumThreads());

        OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .dispatcher(dispatcher)
                .cache(null) //use fresco, avoid duplicates
                .build();

        ImagePipelineConfig pipelineConfig =
                OkHttpImagePipelineConfigFactory.newBuilder(this, okHttpClient)
                        .setPoolFactory(poolFactory)
                        .setDownsampleEnabled(true)
                        .build();

        Fresco.initialize(this, pipelineConfig);
```

I dont find any logs, but if I try to get the image through the fresco pipeline I receive a 
PoolSizeViolationException: Pool hard cap violation? Hard cap = 'ReallyBigNumber' Used size = 'ReallyBigNumber' Free size = 0 Request size = 'ReallyBigNumber'

**Comment by sparsh77** [comment]
Getting the exception  when loading the images 

STACK_TRACE=java.lang.IllegalArgumentException: bitmap size exceeds 32bits
at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java:842)
at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
at android.graphics.Bitmap.createBitmap(Bitmap.java:777)
at com.facebook.shimmer.ShimmerFrameLayout.createBitmapAndGcIfNecessary(ShimmerFrameLayout.java:943)
at com.facebook.shimmer.ShimmerFrameLayout.getMaskBitmap(ShimmerFrameLayout.java:822)
at com.facebook.shimmer.ShimmerFrameLayout.drawMasked(ShimmerFrameLayout.java:771)
at com.facebook.shimmer.ShimmerFrameLayout.dispatchDrawUsingBitmap(ShimmerFrameLayout.java:720)
at com.facebook.shimmer.ShimmerFrameLayout.dispatchDraw(ShimmerFrameLayout.java:697)
at android.view.View.draw(View.java:14536)
at android.widget.FrameLayout.draw(FrameLayout.java:472)
at android.view.View.getDisplayList(View.java:13417)
at android.view.View.getDisplayList(View.java:13459)
at android.view.View.draw(View.java:14250)
at android.view.ViewGroup.drawChild(ViewGroup.java:3119)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
at android.view.View.getDisplayList(View.java:13412)
at android.view.View.getDisplayList(View.java:13459)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
at android.view.View.getDisplayList(View.java:13355)
at android.view.View.getDisplayList(View.java:13459)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
at android.view.View.getDisplayList(View.java:13355)
at android.view.View.getDisplayList(View.java:13459)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
at android.view.View.getDisplayList(View.java:13355)
at android.view.View.getDisplayList(View.java:13459)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
at android.view.View.getDisplayList(View.java:13355)
at android.view.View.getDisplayList(View.java:13459)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
at android.view.View.getDisplayList(View.java:13355)
at android.view.View.getDisplayList(View.java:13459)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
at android.view.View.getDisplayList(View.java:13355)
at android.view.View.getDisplayList(View.java:13459)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
at android.view.View.getDisplayList(View.java:13355)
at android.view.View.getDisplayList(View.java:13459)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
at android.view.View.getDisplayList(View.java:13355)
at android.view.View.getDisplayList(View.java:13459)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3091)
at android.view.View.getDisplayList(View.java:13355)
at android.view.View.getDisplayList(View.java:13459)
at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1612)
at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1483)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2477)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2333)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1953)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1048)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5952)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:787)
at android.view.Choreographer.doCallbacks(Choreographer.java:600)
at android.view.Choreographer.doFrame(Choreographer.java:569)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:773)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5291)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665)
at dalvik.system.NativeStart.main(Native Method)


I have tried to initialize the Fresco in two ways
1) Default 
Fresco.initialize(this);--> In My Application class

2)  ActivityManager activityManager = (ActivityManager) getSystemService(ACTIVITY_SERVICE);
        ImagePipelineConfig imagePipelineConfig = ImagePipelineConfig
                .newBuilder(getApplicationContext())
                .setBitmapMemoryCacheParamsSupplier(new LollipopBitmapMemoryCacheParamsSupplier(activityManager))
                .build();

        Fresco.initialize(getApplicationContext(), imagePipelineConfig);

********************************
the "LollipopBitmapMemoryCacheParamsSupplier" class is as follows
public class LollipopBitmapMemoryCacheParamsSupplier implements Supplier<MemoryCacheParams> {


    private ActivityManager activityManager;

    public LollipopBitmapMemoryCacheParamsSupplier(ActivityManager activityManager) {
        this.activityManager = activityManager;
    }
    @Override
    public MemoryCacheParams get() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            return new MemoryCacheParams(getMaxCacheSize(), 1, 1, 1, 1);
        } else {
            return new MemoryCacheParams(
                    getMaxCacheSize(),
                    256,
                    Integer.MAX_VALUE,
                    Integer.MAX_VALUE,
                    Integer.MAX_VALUE);
        }
    }

    private int getMaxCacheSize() {
        final int maxMemory = Math.min(activityManager.getMemoryClass() * ByteConstants.MB, Integer.MAX_VALUE);

        if (maxMemory < 32 * ByteConstants.MB) {
            return 4 * ByteConstants.MB;
        } else if (maxMemory < 64 * ByteConstants.MB) {
            return 6 * ByteConstants.MB;
        } else {
            if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.GINGERBREAD) {
                return 8 * ByteConstants.MB;
            } else {
                return maxMemory / 4;
            }
        }
    }
}

Please help me in this
Thanks
