### ISSUE TITLE
Runtime exception - Could not initialise SoLoader

### ISSUE THREAD

**Issue by pnkshir** [facebook/fresco#2486]
This crash is getting reported in crashlytics for some users. Device : Motorola G (3rd Gen), Android OS 6.0

This is not reproducible or having any particular steps, but crashlytics has reported it for lot of users

### Additional Information

* Fresco version: "2.0.0"
* Platform version: few devices - Motorola 3rd Gen

Could you please help us on any suggestions on how to solve
**Code** :
 Fresco.initialize(applicationContext, config)

**Logs :** 
Fatal Exception: java.lang.RuntimeException: Unable to create application com.discoveryplus.android.mobile.DPlusApplication: java.lang.RuntimeException: Could not initialize SoLoader
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4953)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1536)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5740)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)

Caused by java.lang.RuntimeException: Could not initialize SoLoader
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:76)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:45)
       at com.discoveryplus.android.mobile.DPlusApplication.initialiseFresco(DPlusApplication.java:171)
       at com.discoveryplus.android.mobile.DPlusApplication.onCreate(DPlusApplication.java:96)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4950)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1536)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5740)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
Caused by java.io.FileNotFoundException: /data/user/10/com.discoveryplus.mobile.android/lib-2/dso_state: open failed: EMFILE (Too many open files)
       at libcore.io.IoBridge.open(IoBridge.java:487)
       at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
       at com.facebook.soloader.UnpackingSoSource.refreshLocked(UnpackingSoSource.java:293)
       at com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:420)
       at com.facebook.soloader.SoLoader.initSoSources(SoLoader.java:304)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:181)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:164)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:68)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:45)
       at com.discoveryplus.android.mobile.DPlusApplication.initialiseFresco(DPlusApplication.java:171)
       at com.discoveryplus.android.mobile.DPlusApplication.onCreate(DPlusApplication.java:96)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4950)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1536)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5740)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)

**Comment by pnkshir** [comment]
Hello, can someone please look into this and suggest

**Comment by oprisnik** [comment]
See my suggestions in #2487. Similar issue.

**Comment by pnkshir** [comment]
@oprisnik  Thanks we will check this solution
