### ISSUE TITLE
Runtime exception - Could not initialise SoLoader

### ISSUE THREAD

**Issue by pnkshir** [facebook/fresco#2487]
We are using Fresco, and getting this crash for few users
Not able to reproduce, but crashlytics reporting it for few users

* Fresco version: "2.0.0"
* Platform version: Motorola 3rd Gen Android OS 6.0

Can you please suggest if anything to  be changed with our implementation: 

**Code :** 
 val requestListeners: MutableSet<RequestListener> = HashSet()
        requestListeners.add(RequestLoggingListener())
        val activityManager = getSystemService(ACTIVITY_SERVICE) as ActivityManager
        val config = ImagePipelineConfig.newBuilder(applicationContext) // other setters
            .setRequestListeners(requestListeners)
            .setBitmapMemoryCacheParamsSupplier(ImageCacheSupplier(activityManager))
            .setDownsampleEnabled(true)
            .build()
        Fresco.initialize(applicationContext, config)

**Logs :** 

Fatal Exception: java.lang.RuntimeException: Unable to create application com.discoveryplus.android.mobile.DPlusApplication: java.lang.RuntimeException: Could not initialize SoLoader
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4731)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by java.lang.RuntimeException: Could not initialize SoLoader
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:76)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:45)
       at com.discoveryplus.android.mobile.DPlusApplication.initialiseFresco(DPlusApplication.java:171)
       at com.discoveryplus.android.mobile.DPlusApplication.onCreate(DPlusApplication.java:96)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by java.io.IOException: fcntl failed: EBADF (Bad file descriptor)
       at java.nio.FileChannelImpl.basicLock(FileChannelImpl.java:123)
       at java.nio.FileChannelImpl.lock(FileChannelImpl.java:166)
       at java.nio.channels.FileChannel.lock(FileChannel.java:185)
       at com.facebook.soloader.FileLocker.<init>(FileLocker.java:38)
       at com.facebook.soloader.FileLocker.lock(FileLocker.java:31)
       at com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:417)
       at com.facebook.soloader.SoLoader.initSoSources(SoLoader.java:304)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:181)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:164)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:68)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:45)
       at com.discoveryplus.android.mobile.DPlusApplication.initialiseFresco(DPlusApplication.java:171)
       at com.discoveryplus.android.mobile.DPlusApplication.onCreate(DPlusApplication.java:96)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by android.system.ErrnoException: fcntl failed: EBADF (Bad file descriptor)
       at libcore.io.Posix.fcntlFlock(Posix.java)
       at libcore.io.ForwardingOs.fcntlFlock(ForwardingOs.java:70)
       at java.nio.FileChannelImpl.basicLock(FileChannelImpl.java:121)
       at java.nio.FileChannelImpl.lock(FileChannelImpl.java:166)
       at java.nio.channels.FileChannel.lock(FileChannel.java:185)
       at com.facebook.soloader.FileLocker.<init>(FileLocker.java:38)
       at com.facebook.soloader.FileLocker.lock(FileLocker.java:31)
       at com.facebook.soloader.UnpackingSoSource.prepare(UnpackingSoSource.java:417)
       at com.facebook.soloader.SoLoader.initSoSources(SoLoader.java:304)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:181)
       at com.facebook.soloader.SoLoader.init(SoLoader.java:164)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:68)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:45)
       at com.discoveryplus.android.mobile.DPlusApplication.initialiseFresco(DPlusApplication.java:171)
       at com.discoveryplus.android.mobile.DPlusApplication.onCreate(DPlusApplication.java:96)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by pnkshir** [comment]
Hello, can someone please look into this and suggest

**Comment by oprisnik** [comment]
Hey! The underlying issue is `Caused by android.system.ErrnoException: fcntl failed: EBADF (Bad file descriptor)`. Can you try if Fresco 2.2.0 fixes the issue since it has a newer SoLoader cersion? Otherwise, this is an issue that has to be fixed for https://github.com/facebook/soloader

With the latest Fresco version it is also possible to not use SoLoader, which might be fine for your application. See the 2.1.0 changelog for details on how to set up: https://github.com/facebook/fresco/releases/tag/v2.1.0

**Comment by pnkshir** [comment]
@oprisnik Thanks we will check this solution
