### ISSUE TITLE
OOM at Vivo Android 5.1.1 devices

### ISSUE THREAD

**Issue by kmrinmoy07** [facebook/fresco#2496]
### Description

Hi,
I have moved to fresco only to fix my OOMs. So after I moved to fresco and updated my app with fresco I was happy to see no OOM (making my app crash free) on any devices those who updated to this version with fresco.
But yesterday I saw that a user who just updated to this version with Vivo Android 5.1.1 device was totally unable to open the app and got OOM every time he opened the app. 
My images are resized in the server too in different sizes like 800x800, 400x400, 200x200 for different SimpleDraweeView height and width. 
So I am worried about it and need some help to solve it.

Here is my gradle file 
      
        `implementation ('com.facebook.fresco:fresco:2.2.0'){
           exclude group: 'com.facebook.soloader', module: 'soloader'
           exclude group: 'com.facebook.fresco', module: 'soloader'
            exclude module: 'soloader'
           } `

My xml file are as-

        `<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
             xmlns:app="http://schemas.android.com/apk/res-auto"
             ..../>
         
         <com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/imageView_latest_list2"
            android:layout_width="90dp"
            android:layout_height="90dp"
            app:actualImageScaleType="focusCrop"
            app:failureImage="@drawable/error"
            app:failureImageScaleType="fitXY"
            app:placeholderImage="@drawable/placeholder_two"
            app:placeholderImageScaleType="fitXY"
            android:layout_marginTop="10dp"
            app:roundedCornerRadius="6dp"
        />`

I am initializing fresco in MyApplication using 

         `Fresco.initialize(this);`

The error stack trace that I got is

> Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 1000012 byte allocation with 904846 free bytes and 883KB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
       at com.facebook.imagepipeline.memory.BucketsBitmapPool.alloc(BucketsBitmapPool.java:55)
       at com.facebook.imagepipeline.memory.BucketsBitmapPool.alloc(BucketsBitmapPool.java:27)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:254)
       at com.facebook.imagepipeline.platform.DefaultDecoder.decodeFromStream(DefaultDecoder.java:217)
       at com.facebook.imagepipeline.platform.DefaultDecoder.decodeJPEGFromEncodedImageWithColorSpace(DefaultDecoder.java:155)
       at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeJpeg(DefaultImageDecoder.java:179)
       at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:58)
       at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:120)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:316)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$300(DecodeProducer.java:136)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:186)
       at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:224)
       at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:24)
       at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:90)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:50)
       at java.lang.Thread.run(Thread.java:818)

### Reproduction

I am not able to reproduce as I don't have the specific device and (may be) it is working fine on rest devices

### Solution

Can it be cause of using drawable in `app:placeholderImage`

### Additional Information

* Fresco version: 2.2.0
* Platform version: Vivo Android 5.1.1

**Comment by kmrinmoy07** [comment]
Hey, did any one have any solution to this.

**Comment by oprisnik** [comment]
It shouldn't be caused by the placeholder image. I guess you're just loading lots of images or large ones? Debugging OOMs is not easy, you can take a look at heap dumps and see what takes up memory in your application. In the report above, there was not a lot of memory left on the device.

You can also use the Flipper images plugin (https://fbflipper.com/) to figure out what images are currently marked as "on screen", i.e. we have a hard reference to the bitmap and cannot free memory / re-use. That might help you to debug what's going on.

**Comment by kmrinmoy07** [comment]
Yes, it is true that there are lots of images getting loaded but I have resized every images in the server with the minimum required dimension for various SimpleDraweeView size. Currently in all the placeholder and failureImage I am using mipmap photo instead of drawable and now it is working fine in every devices using this update of my app (but still can't say if any of the said Vivo device is running this update or not). I have also seen similar OOM crash once in test devices in firebase test lab when I mistakenly placed the placeholder image in mipmap-anydpi folder and when I moved the image to mipmap-xxhdpi, mipmap-xhdpi, ..... it just fixed the OOM in those devices. But still can't say if the problem is fixed in Vivo Android 5.1.1 devices as I am not able to test it this device.

**Comment by kmrinmoy07** [comment]
I thought the problem might have been solved by my above mentioned [comment#2496](https://github.com/facebook/fresco/issues/2496#issuecomment-627932233) but today again I got these crashes on the same mentioned device. So is there any fixes.

**Comment by kmrinmoy07** [comment]
I am facing this issue again and again so is there any fixes.
