### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by pnkshir** [facebook/fresco#2504]
We are getting following crash on Crashlytics for good number of users with Android OS 8, with more than 47 devices.
We are using "com.facebook.fresco:fresco:2.2.0"

Could you please help us, since its happening on. multiple users.

Logs : 

Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at java.util.Formatter$FormatSpecifier.addZeros(Formatter.java:3505)
       at java.util.Formatter$FormatSpecifier.print(Formatter.java:3401)
       at java.util.Formatter$FormatSpecifier.print(Formatter.java:3332)
       at java.util.Formatter$FormatSpecifier.print(Formatter.java:3317)
       at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2891)
       at java.util.Formatter$FormatSpecifier.print(Formatter.java:2844)
       at java.util.Formatter.format(Formatter.java:2523)
       at java.util.Formatter.format(Formatter.java:2458)
       at java.lang.String.format(String.java:2814)
       at com.facebook.common.logging.FLog.formatString(FLog.java:491)
       at com.facebook.common.logging.FLog.v(FLog.java:118)
       at com.facebook.imagepipeline.transcoder.DownsampleUtil.determineDownsampleRatio(DownsampleUtil.java:87)
       at com.facebook.imagepipeline.transcoder.DownsampleUtil.determineSampleSize(DownsampleUtil.java:43)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:163)
       at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:202)
       at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:22)
       at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:73)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
       at java.lang.Thread.run(Thread.java:764)

**Comment by oprisnik** [comment]
Thanks for the bug report.

That's weird, looks like the log statement is failing: https://github.com/facebook/fresco/blob/e791687a6617eaeb5f8e5524452541777ddc4aa4/imagepipeline-base/src/main/java/com/facebook/imagepipeline/transcoder/DownsampleUtil.java#L103

Setting your log level to anything that's smaller than verbose (like ERROR or WARN) should help: `FLog.setMinimumLoggingLevel(WARN)`

**Comment by tsybanov** [comment]
I was curious about the problem the other day, even without the evidence and ability to reproduce it. Here is what I've found.

Initially, I was thinking that the problem somehow related to the locale that has not been set up in `FLog.formatString()`

![Screen Shot 2020-07-13 at 2 20 27 PM](https://user-images.githubusercontent.com/5286992/87339032-027d3800-c514-11ea-986f-dbbcd7d2443a.png)

However, there are _three_ concerns.
First of all, in the particular example  `FLog.v()` works with the conversion from primitives to `String`, not vice-versa. So, probably, there is no need to worry about `Locale` problems like `,` (comma) or `.` (dot) for decimals.

Second, despite the fact of the `@NonNull` argument, `String.format()` allows passing null `Locale`

![Screen Shot 2020-07-13 at 2 26 11 PM](https://user-images.githubusercontent.com/5286992/87339574-ceeedd80-c514-11ea-9f33-bb147a025940.png)

Nevertheless, `String.format` has overloading without passing `Locale`

![Screen Shot 2020-07-13 at 2 34 13 PM](https://user-images.githubusercontent.com/5286992/87340348-ee3a3a80-c515-11ea-9f49-0e973bfd551c.png)

that sets just to default `Locale` for `Formatter`. 

![Screen Shot 2020-07-13 at 2 35 22 PM](https://user-images.githubusercontent.com/5286992/87340467-175acb00-c516-11ea-8272-f48bd6b46ed6.png)

I believe, the reason behind setting it to the `null` in the `FLog.formatString()` is that _Lint_ has a [LocaleDetector](https://android.googlesource.com/platform/tools/base/+/studio-master-dev/lint/libs/lint-checks/src/main/java/com/android/tools/lint/checks/LocaleDetector.kt) check that reminds about that decision. So, probably, that was a way to suppress it? If it is then, I believe, it's not a good practice.

And the last concern is the reason why `NPE` happens in the first place.
If to look down the road of the stack, the problem is in `Formatter.addZeroes()` where it's simply one of the arguments, `char[] v` which is not guarded

![Screen Shot 2020-07-13 at 3 04 37 PM](https://user-images.githubusercontent.com/5286992/87342998-2e032100-c51a-11ea-8c14-35f54c126e73.png)

Back to the caller, `print()` shows that this is a mantissa which converts from `double` value to `char[]` with help of `FormattedFloatingDecimal`

![Screen Shot 2020-07-13 at 3 09 39 PM](https://user-images.githubusercontent.com/5286992/87343459-e335d900-c51a-11ea-9f61-c1d7a41cb99e.png)

`FormattedFloatingDecimal` is part of the `sun.misc` package that is **not** _Android-Changed_.

![Screen Shot 2020-07-13 at 3 11 13 PM](https://user-images.githubusercontent.com/5286992/87343585-19735880-c51b-11ea-89a5-cabf5a5f9eeb.png)

And it's possible to obtain a `null` mantissa since it's not guarded.

![Screen Shot 2020-07-13 at 3 14 15 PM](https://user-images.githubusercontent.com/5286992/87343866-85ee5780-c51b-11ea-8418-3729087343da.png)

However, in all cases of the constructor logic mantissa has to be assigned, even if it's just `new char[0]`.

At the same time, I've found that `WebRTC` team that is part of the _Android SDK_ has faced [the same problem](https://webrtc.googlesource.com/src/+/1659e9776755c411dbe43a3d1dcca1fdfc6922d9) 2 years ago where they specified it as 

> crashes... on some devices

 and suggests a _Speculative_ fix by using `DecimalFormat` instead of `String.Format` for floats. 
By the way, initially, they've had used `Locale.US` in `String.Format` while getting the problem, so it's feasible to assume the problem is not related to the `Locale`.

On the other hand, `DecimalFormat` doesn't use anything from `sun.misc` packages.

**Conclusion.**

I'm curious if the problem anyhow correlated with the fact that it's about `FormattedFloatingDecimal` from `sun.misc` package. Maybe these devices have been using some sort of customized _AOSP_? I've found no other evidence of the problem than that with `WebRTC`. 

_Speculative_ fix is to use `DecimalFormat`. The problem is that it has to be done through `FLog.formatString()` since the problem is in there. 

@pnkshir it would be great to have a bit more information about the devices with crashes if it's possible.
@oprisnik Please, let me know what you think and if there are enough reasons to apply a _Speculative_ fix.

**Comment by janbolat** [comment]
Hi,
Our users are having the same problem on Android 8.1.0, but not on Fresco.
These are the devices:
![image](https://user-images.githubusercontent.com/6511056/90264162-7d6aa300-de72-11ea-8ee7-2520950b4bad.png)
Xiaomi Redmi 6 Pro
Xiaomi Redmi 5 Plus
Vivo V1818A
Vivo V1732A
Samsung Galaxy J7(2016)
Samsung Galaxy J2 Core
OPPO A5
Huawei Y3 2018

It is failing on formatting the latitude and longitude (`double`):
`String.format(Locale.ENGLISH, "%.6f", latitude)`

**Comment by oprisnik** [comment]
Hey @tsybanov - thank you for the detailed report and sorry for the late reply.

I think we should try your speculative fix, so it would be great if you could submit a PR.

**Comment by wuqian** [comment]
yet another device

vivo(vivo Y85A)

**Comment by Kritip123** [comment]
### @oprisnik 
Can you please explain the issue(#2504) a little bit to understand the issue well.

**Comment by AndroidKolla** [comment]
**Hi All Friend I Need Your Help to Fix This**
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3654)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3812)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:83)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2267)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8161)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)
Caused by: java.lang.NullPointerException: 
  at com.deepthistudio.sinhalabehethapp.Logo_Screen.onCreate (Logo_Screen.java:19)
  at android.app.Activity.performCreate (Activity.java:7963)
  at android.app.Activity.performCreate (Activity.java:7952)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1307)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3629)

**Comment by Thenitesh143** [comment]
I am a newbie and willing to contribute to this project. Can I get started with this please.

**Comment by Thenitesh143** [comment]
I am a newbie and willing to contribute to this project. Can I get started with this please.

**Comment by harsh-1806** [comment]
Can someone help me with understanding the codebase I am a newbie just starting to contribute. Please

**Comment by jacklyq** [comment]
I am curious to hear if the speculative fix has worked?

**Comment by amrouchk** [comment]
On your onStart method, you are using the Connectivity.isConnected method without checking if it returns true. If the device is not connected, it will proceed to show a Toast message but still attempt to execute the code inside the postDelayed handler, which might lead to issues.

Here's an updated version of the onStart method with proper null checks and restructured logic:
```
@Override
protected void onStart() {
    super.onStart();
    Context context = getApplicationContext();

    if (Connectivity.isConnected(context)) {
        final MySharedPreferences mySharedPreferences = new MySharedPreferences(this);
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                if (mySharedPreferences != null && mySharedPreferences.getBooleanVal(key_first_install)) {
                    Intent intent = new Intent(Logo_screen.this, dang_nhap.class);
                    startActivity(intent);
                    overridePendingTransition(R.anim.slide_in_left, R.anim.slide_out_left);
                    finish();
                } else {
                    Intent intent = new Intent(Logo_screen.this, waiting.class);
                    if (mySharedPreferences != null) {
                        mySharedPreferences.putBooleanVal(key_first_install, true);
                    }
                    startActivity(intent);
                    overridePendingTransition(R.anim.slide_in_left, R.anim.slide_out_left);
                    finish();
                }
            }
        }, SPLASH_SCREEN);
    } else {
        Toast.makeText(context, "show a toast msg ", Toast.LENGTH_SHORT).show();
    }
}
```
This modification includes null checks for mySharedPreferences before using it. Additionally, the Connectivity.isConnected check is used to decide whether to proceed with the delayed task or simply show a toast message if there is no network connectivity.

**Comment by amrouchk** [comment]
This is from the class Logo_Screen.java

**Comment by SharanyaR07** [comment]
Hey, Is anyone ready to help me out understand the issue more clearly? I've just started contributing and am curious to learn more.
