### ISSUE TITLE
ThumbnailUtils: java.io.IOException: Failed to create thumbnail

### ISSUE THREAD

**Issue by Awent** [facebook/fresco#2537]
### Description

```
I'm trying to load thumbnails from video with android Q, and I got the exception：

com.simaple W/ThumbnailUtils: java.io.IOException: Failed to create thumbnail
        at android.media.ThumbnailUtils.createVideoThumbnail(ThumbnailUtils.java:375)
        at android.media.ThumbnailUtils.createVideoThumbnail(ThumbnailUtils.java:328)
        at com.facebook.imagepipeline.producers.LocalVideoThumbnailProducer$1.getResult(LocalVideoThumbnailProducer.java:89)
        at com.facebook.imagepipeline.producers.LocalVideoThumbnailProducer$1.getResult(LocalVideoThumbnailProducer.java:63)
        at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:43)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:50)
        at java.lang.Thread.run(Thread.java:929)
     Caused by: java.lang.IllegalArgumentException
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:77)
        at android.media.ThumbnailUtils.createVideoThumbnail(ThumbnailUtils.java:351)
        at android.media.ThumbnailUtils.createVideoThumbnail(ThumbnailUtils.java:328) 
        at com.facebook.imagepipeline.producers.LocalVideoThumbnailProducer$1.getResult(LocalVideoThumbnailProducer.java:89) 
        at com.facebook.imagepipeline.producers.LocalVideoThumbnailProducer$1.getResult(LocalVideoThumbnailProducer.java:63) 
        at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:43) 
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:50) 
        at java.lang.Thread.run(Thread.java:929) 


code:
<application 
        android:requestLegacyExternalStorage="false">
</application>

Uri uri = "/external/video/media/294502"  //local video

ImageRequest imageRequest = ImageRequestBuilder
                    .newBuilderWithSource(uri)
                    .setLocalThumbnailPreviewsEnabled(true)
                    .setProgressiveRenderingEnabled(false)
                    .setResizeOptions(new ResizeOptions(imageSize, imageSize))
                    .build();
            DraweeController draweeController = Fresco.newDraweeControllerBuilder()
                    .setImageRequest(imageRequest)
                    .setOldController(imageView.getController())
                    .build();
            imageView.setController(draweeController);


```
I find  `createVideoThumbnail(@NonNull String filePath, int kind) `is Deprecated with API Q ,
[https://github.com/facebook/fresco/blob/ba8e627f328e9b84943dffe5e4e3896a1cae6fec/imagepipeline/src/main/java/com/facebook/imagepipeline/producers/LocalVideoThumbnailProducer.java#L87-L91](https://github.com/facebook/fresco/blob/ba8e627f328e9b84943dffe5e4e3896a1cae6fec/imagepipeline/src/main/java/com/facebook/imagepipeline/producers/LocalVideoThumbnailProducer.java#L87-L91)
And I found that loading local images is very slow after using `EXTERNAL_CONTENT_URI (content://media/external/images/media/xxxx)` in Android Q

### Reproduction

[Use a mobile phone with android Q system to get the local video, and use Fresco to load the video thumbnail to reproduce it.]

### Additional Information

* Fresco version: [2.3.0]
* Platform version: [android Q ,huawei mate 30 pro]

**Comment by githubPQQ** [comment]
> uri
i got the same question

**Comment by mdsheraj123** [comment]
I have the same problem.
```

12-19 13:23:50.758 10016 10016 W ThumbnailUtils: java.io.IOException: Failed to create thumbnail
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at android.media.ThumbnailUtils.createVideoThumbnail(ThumbnailUtils.java:390)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at android.media.ThumbnailUtils.createVideoThumbnail(ThumbnailUtils.java:332)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at com.example.android.camera2.video.fragments.CameraFragmentVideo.createVideoThumb(CameraFragmentVideo.kt:206)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at com.example.android.camera2.video.fragments.CameraFragmentVideo.createRoundThumb(CameraFragmentVideo.kt:209)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at com.example.android.camera2.video.fragments.CameraFragmentVideo.access$createRoundThumb(CameraFragmentVideo.kt:62)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at com.example.android.camera2.video.fragments.CameraFragmentVideo$initializeCamera$1$1.onClick(CameraFragmentVideo.kt:238)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at android.view.View.performClick(View.java:7448)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at android.view.View.performClickInternal(View.java:7425)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at android.view.View.access$3600(View.java:810)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at android.view.View$PerformClick.run(View.java:28305)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at android.os.Handler.handleCallback(Handler.java:938)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at android.os.Looper.loop(Looper.java:223)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at java.lang.reflect.Method.invoke(Native Method)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: Caused by: java.lang.NumberFormatException: s == null
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at java.lang.Integer.parseInt(Integer.java:577)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at java.lang.Integer.parseInt(Integer.java:650)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	at android.media.ThumbnailUtils.createVideoThumbnail(ThumbnailUtils.java:372)
12-19 13:23:50.758 10016 10016 W ThumbnailUtils: 	... 16 more
```

Cannot find a solution anywhere.

**Comment by Fxtong** [comment]
Encountered exception while getting thumbnail

**Comment by feihupeng** [comment]
@zeitgeist12345 
Have you solved this problem?
I encountered the same problem.

**Comment by feihupeng** [comment]
@zeitgeist12345 ok，thanks
