### ISSUE TITLE
Adapt to android 10

### ISSUE THREAD

**Issue by z2045217** [facebook/fresco#2549]
Mobile phones above android 10 load mp4, display failure

**Comment by z2045217** [comment]
@Override
          protected @Nullable CloseableReference<CloseableImage> getResult() throws Exception {
            Bitmap thumbnailBitmap;
            String path;
            try {
              path = getLocalFilePath(imageRequest);
            } catch (IllegalArgumentException e) {
              path = null;
            }
            thumbnailBitmap =
                path != null
                    ? ThumbnailUtils.createVideoThumbnail(path, calculateKind(imageRequest))
                    : createThumbnailFromContentProvider(
                        mContentResolver, imageRequest.getSourceUri());

            if (thumbnailBitmap == null) {
              return null;
            }

            CloseableStaticBitmap closeableStaticBitmap =
                new CloseableStaticBitmap(
                    thumbnailBitmap,
                    SimpleBitmapReleaser.getInstance(),
                    ImmutableQualityInfo.FULL_QUALITY,
                    0);
            producerContext.setExtra(ProducerContext.ExtraKeys.IMAGE_FORMAT, "thumbnail");
            closeableStaticBitmap.setImageExtras(producerContext.getExtras());
            return CloseableReference.<CloseableImage>of(closeableStaticBitmap);
          }

Among them, ThumbnailUtils is no longer available in the latest android 10，reference：
https://developer.android.google.cn/reference/android/content/ContentResolver#loadThumbnail(android.net.Uri,%20android.util.Size,%20android.os.CancellationSignal)

**Comment by z2045217** [comment]
ThumbnailUtils: java.io.IOException: Failed to create thumbnail
        at android.media.ThumbnailUtils.createVideoThumbnail(ThumbnailUtils.java:375)
        at android.media.ThumbnailUtils.createVideoThumbnail(ThumbnailUtils.java:328)
        at com.facebook.imagepipeline.producers.LocalVideoThumbnailProducer$1.getResult(LocalVideoThumbnailProducer.java:89)
        at com.facebook.imagepipeline.producers.LocalVideoThumbnailProducer$1.getResult(LocalVideoThumbnailProducer.java:63)
        at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:52)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalArgumentException
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:95)
        at android.media.ThumbnailUtils.createVideoThumbnail(ThumbnailUtils.java:351)
        at android.media.ThumbnailUtils.createVideoThumbnail(ThumbnailUtils.java:328) 
        at com.facebook.imagepipeline.producers.LocalVideoThumbnailProducer$1.getResult(LocalVideoThumbnailProducer.java:89) 
        at com.facebook.imagepipeline.producers.LocalVideoThumbnailProducer$1.getResult(LocalVideoThumbnailProducer.java:63) 
        at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:52) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by z2045217** [comment]
Why not adapt to android 10

**Comment by perracolabs** [comment]
I've added a pull request  https://github.com/facebook/fresco/pull/2594 fixing the issue. Let's hope it will be accepted, although the CircleCI check didn't pass yet due to unrelated code which stops a project build.

The issue and fix are quite simple. For a full explanation check the pull request description.

**Comment by Lampotrias** [comment]
Hi!

Is there any way to speed up the approval of this PR? The problem is critical

**Comment by stven0king** [comment]
May need to upgrade to a new version [#2593](https://github.com/facebook/fresco/issues/2593)
