### ISSUE TITLE
I/O on main tread (android.content.ContentResolver.getType)

### ISSUE THREAD

**Issue by florianPOLARSTEPS** [facebook/fresco#2555]
### Description

It seems on one of my test devices I am running into some laggy-ness when scrolling quickly through a recyclerview. This seems to be caused by a call to `ContentResolver.getType` which further down the trace does a SQLite query.

```
2020-10-30 10:14:14.704 26966-26966/x.x.x/D/StrictMode: StrictMode policy violation; ~duration=47 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
        at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1138)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:939)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
        at com.android.providers.media.MediaProvider.queryForSingleItem(MediaProvider.java:6069)
        at com.android.providers.media.MediaProvider.getType(MediaProvider.java:2259)
        at android.content.ContentProvider$Transport.getType(ContentProvider.java:293)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:150)
        at android.os.Binder.execTransactInternal(Binder.java:1032)
        at android.os.Binder.execTransact(Binder.java:1005)
    # via Binder call with stack:
        at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:2274)
        at android.os.Parcel.readExceptionCode(Parcel.java:2017)
        at android.os.Parcel.readException(Parcel.java:1984)
        at android.app.IActivityManager$Stub$Proxy.getProviderMimeType(IActivityManager.java:7171)
        at android.content.ContentResolver.getType(ContentResolver.java:755)
        at com.facebook.imagepipeline.core.ProducerSequenceFactory.getBasicDecodedImageSequence(ProducerSequenceFactory.java:361)
        at com.facebook.imagepipeline.core.ProducerSequenceFactory.getDecodedImageProducerSequence(ProducerSequenceFactory.java:310)
        at com.facebook.imagepipeline.core.ImagePipeline.fetchDecodedImage(ImagePipeline.java:327)
        at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilder.getDataSourceForRequest(PipelineDraweeControllerBuilder.java:168)
        at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilder.getDataSourceForRequest(PipelineDraweeControllerBuilder.java:42)
        at com.facebook.drawee.controller.AbstractDraweeControllerBuilder$2.get(AbstractDraweeControllerBuilder.java:421)
        at com.facebook.drawee.controller.AbstractDraweeControllerBuilder$2.get(AbstractDraweeControllerBuilder.java:418)
        at com.facebook.drawee.backends.pipeline.PipelineDraweeController.getDataSource(PipelineDraweeController.java:264)
        at com.facebook.drawee.controller.AbstractDraweeController.submitRequest(AbstractDraweeController.java:544)
        at com.facebook.drawee.controller.AbstractDraweeController.onAttach(AbstractDraweeController.java:440)
        at com.facebook.drawee.view.DraweeHolder.attachController(DraweeHolder.java:248)
        at com.facebook.drawee.view.DraweeHolder.attachOrDetachController(DraweeHolder.java:265)
        at com.facebook.drawee.view.DraweeHolder.onVisibilityChange(DraweeHolder.java:134)
        at com.facebook.drawee.generic.RootDrawable.setVisible(RootDrawable.java:67)
        at android.widget.ImageView.onVisibilityAggregated(ImageView.java:1686)
        at android.view.View.dispatchAttachedToWindow(View.java:20282)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3462)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5218)
        at android.view.ViewGroup.addView(ViewGroup.java:5004)
        at android.view.ViewGroup.addView(ViewGroup.java:4944)
        at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:856)
```

### Reproduction

Load a `local content-type` URI (e.g.: content://media/images/3383) using the library with StrictMode enabled.

### Solution

There can be 2 ways to solve this.
 1) The call should be offloaded to another thread, could be tricky because it would mean asynchronously creating the `ProducerSequence` 

2) Make it possible to give a hint about the `MIME type` of a certain content-uri via the `ImageRequest` for example. In my case I know the type already since the image is a result of a query to the MediaStore so that additional query is not necessary.

### Additional Information

* Fresco version: 2.3.0
* Platform version: Android 10, Device: Xiaomi Mi A2

**Comment by windoozatnick** [comment]
Still reproducible six years later, and in the work-profile case it is far worse than a StrictMode warning — it is a guaranteed ANR.

Same call site as the original report:

```
at android.content.ContentResolver$ResultListener.waitForResult(ContentResolver.java:1049)
at android.content.ContentResolver.getType(ContentResolver.java:999)
at com.facebook.imagepipeline.core.ProducerSequenceFactory.<getBasicDecodedImageSequence>(ProducerSequenceFactory.kt:117)
at com.facebook.imagepipeline.core.ImagePipeline.<fetchDecodedImage>(ImagePipeline.kt:26)
at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilder.getDataSourceForRequest(PipelineDraweeControllerBuilder.java:21)
at com.facebook.drawee.controller.AbstractDraweeControllerBuilder$2.get(AbstractDraweeControllerBuilder.java:13)
at com.facebook.drawee.backends.pipeline.PipelineDraweeController.getDataSource(PipelineDraweeController.java:38)
at com.facebook.drawee.controller.AbstractDraweeController.submitRequest(AbstractDraweeController.java:141)
...
at android.os.Looper.loop(Looper.java:397)
at android.app.ActivityThread.main(ActivityThread.java:9523)
```

**Why it escalates from "laggy" to "ANR":**

When the app runs in an Android work profile and is handed a cross-profile content URI (the system rewrites it with an explicit user id, e.g. `content://0@com.google.android.apps.photos.contentprovider/...`), the platform-side resolution throws a `SecurityException` because the app lacks `INTERACT_ACROSS_USERS`. That exception escapes `ContentProviderHelper.getMimeTypeFilterAsync()` — which wraps the resolution in `try/finally` with no `catch` — so the `RemoteCallback` is never invoked.

`ContentResolver.getType()` then waits out `REMOTE_CONTENT_PROVIDER_TIMEOUT_MILLIS`, which is **23 000 ms** (`CONTENT_PROVIDER_READY_TIMEOUT_MILLIS` 20 000 + `CONTENT_PROVIDER_TIMEOUT_MILLIS` 3 000). One call on the UI thread is therefore an immediate ANR — the threshold is 5 s.

I filed the platform half separately as https://issuetracker.google.com/issues/551541331, since the dropped callback is genuinely an AOSP bug. But the Fresco half stands on its own: **a synchronous `ContentResolver.getType()` on the caller's thread is unsafe regardless of the platform defect.** It is an IPC into an arbitrary provider, and any provider that is slow, cold-starting, or unresolvable turns `fetchDecodedImage()` into a blocking call on whatever thread invoked it — normally the UI thread, since that is where Drawee controllers are attached.

Option 2 from the original report — letting callers supply a MIME hint on `ImageRequest` — would be enough for most cases and is cheap to implement. Callers that obtained the URI from MediaStore or from a share intent almost always know the type already. Option 1 (moving the resolution off the caller's thread) is the more complete fix.

Reproduced on Android 17 (Pixel 10) with a current Fresco build. Verified the diagnosis by hooking `ContentResolver.getType()` and returning a MIME type derived from the URI without calling through: the ANRs stopped immediately and image previews still render correctly, which confirms the `getType()` result is the only thing being waited on here.
