### ISSUE TITLE
java.lang.IllegalStateException: Width or height is too small

### ISSUE THREAD

**Issue by gushaowei1992** [facebook/fresco#2558]
java.lang.IllegalStateException: Width or height is too small
	at com.facebook.animated.gif.GifFrame.nativeRenderFrame(Native Method)
	at com.facebook.animated.gif.GifFrame.renderFrame(GifFrame.java:50)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableBackendImpl.renderImageDoesNotSupportScaling(AnimatedDrawableBackendImpl.java:221)
	at com.facebook.imagepipeline.animated.impl.AnimatedDrawableBackendImpl.renderFrame(AnimatedDrawableBackendImpl.java:179)
	at com.facebook.imagepipeline.animated.impl.AnimatedImageCompositor.renderFrame(AnimatedImageCompositor.java:120)
	at com.facebook.fresco.animation.bitmap.wrapper.AnimatedDrawableBackendFrameRenderer.renderFrame(AnimatedDrawableBackendFrameRenderer.java:74)
	at com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.renderFrameAndCache(DefaultBitmapFramePreparer.java:175)
	at com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.prepareFrameAndCache(DefaultBitmapFramePreparer.java:154)
	at com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.prepareFrameAndCache(DefaultBitmapFramePreparer.java:162)
	at com.facebook.fresco.animation.bitmap.preparation.DefaultBitmapFramePreparer$FrameDecodeRunnable.run(DefaultBitmapFramePreparer.java:112)
	at com.facebook.common.executors.ConstrainedExecutorService$Worker.run(ConstrainedExecutorService.java:177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:42)
	at java.lang.Thread.run(Thread.java:818)

**Comment by gushaowei1992** [comment]
Recently, Jpush has made a lot of such mistakes,Is it about the version? I'm using 1.5.0 now

**Comment by oprisnik** [comment]
Hey! Do you have a GIF where this happens? Looks like this might be a corrupt GIF. Can you also try with the newest version, 2.3.0?

**Comment by daddivan69** [comment]
Needs-details

**Comment by daddivan69** [comment]
Needs-drugs

**Comment by daddivan69** [comment]
Needs-details I meant srry
