### ISSUE TITLE
StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

### ISSUE THREAD

**Issue by bangzhu010** [facebook/fresco#2563]
StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1955)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
        at android.renderscript.BaseObj.finalize(BaseObj.java:143)
        at android.renderscript.Allocation.finalize(Allocation.java:432)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
        at java.lang.Daemons$Daemon.run(Daemons.java:137)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.Throwable: Explicit termination method 'destroy' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:237)
        at android.renderscript.Allocation.<init>(Allocation.java:421)
        at android.renderscript.Allocation.<init>(Allocation.java:425)
        at android.renderscript.Allocation.createFromBitmap(Allocation.java:2823)
        at android.renderscript.Allocation.createFromBitmap(Allocation.java:3063)
        at com.facebook.imagepipeline.k.b.a(RenderScriptBlurFilter.java:50)
        at com.facebook.imagepipeline.n.a.process(BlurPostProcessor.java:68)
        at com.facebook.imagepipeline.o.a.process(BasePostprocessor.java:63)
        at com.facebook.imagepipeline.producers.ak$a.b(PostprocessorProducer.java:244)
        at com.facebook.imagepipeline.producers.ak$a.c(PostprocessorProducer.java:214)
        at com.facebook.imagepipeline.producers.ak$a.a(PostprocessorProducer.java:69)
        at com.facebook.imagepipeline.producers.ak$a$2.run(PostprocessorProducer.java:172)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.facebook.imagepipeline.f.m$1.run(PriorityThreadFactory.java:50)
        at java.lang.Thread.run(Thread.java:919)

### Solution

 public static void blurBitmap(
      final Bitmap dest, final Bitmap src, final Context context, final int radius) {
    Preconditions.checkNotNull(dest);
    Preconditions.checkNotNull(src);
    Preconditions.checkNotNull(context);
    Preconditions.checkArgument(radius > 0 && radius <= BLUR_MAX_RADIUS);
    RenderScript rs = null;
    try {
      rs = RenderScript.create(context);

      // Create an Intrinsic Blur Script using the Renderscript
      ScriptIntrinsicBlur blurScript = ScriptIntrinsicBlur.create(rs, Element.U8_4(rs));

      // Create the input/output allocations with Renderscript and the src/dest bitmaps
      Allocation allIn = Allocation.createFromBitmap(rs, src);
      Allocation allOut = Allocation.createFromBitmap(rs, dest);

      // Set the radius of the blur
      blurScript.setRadius(radius);
      blurScript.setInput(allIn);
      blurScript.forEach(allOut);
      allOut.copyTo(dest);
    } finally {
      if (rs != null) {
        rs.destroy();
      }
    }
  }

As far as I know,it not just destory RenderScript and ScriptIntrinsicBlur , also to destory 2 Allocation.

### Additional Information

* Fresco version: 2.1.0

**Comment by bangzhu010** [comment]
close
