### ISSUE TITLE
cannot show drawable image: Can't open

### ISSUE THREAD

**Issue by NNirvana** [facebook/fresco#257]
cannot show image of drawable, everytime:
I build a uri like this:
Uri uri = new Uri.Builder()
                .scheme(UriUtil.LOCAL_RESOURCE_SCHEME)
                .path(String.valueOf(resId))
                .build();
got error log: E/JHEAD﹕ can't open '/2130837704'

**Comment by IanChilds** [comment]
Can you print out your uri please? It needs to match something on this page: http://frescolib.org/docs/supported-uris.html#_

**Comment by NNirvana** [comment]
the uri is:  res:/2130837704
error log is:   E/JHEAD﹕ can't open '/2130837704'

**Comment by NNirvana** [comment]
If I build a string uriString = "res://2130837704", and then use Uri.parse(uriString), I will get

com.facebook.imagepipeline.request.ImageRequestBuilder$BuilderException: Invalid request builder: Resource URI must not be empty
            at com.facebook.imagepipeline.request.ImageRequestBuilder.validate(ImageRequestBuilder.java:259)
            at com.facebook.imagepipeline.request.ImageRequestBuilder.build(ImageRequestBuilder.java:235)

**Comment by IanChilds** [comment]
Please see the `Note:` section here: http://frescolib.org/docs/supported-uris.html#_

It sounds like you are trying to load an XML drawable - instead, please set the drawable to be the placeholder and set the image URI to be null.

**Comment by Nafeng** [comment]
Hi, I got the same problem;
I use the drawable png image of mipmaps;
I build the Uri String : res//"resourceId"; then I got the Exception:
 com.facebook.imagepipeline.request.ImageRequestBuilder$BuilderException: Invalid request builder: Resource URI must not be empty
            at com.facebook.imagepipeline.request.ImageRequestBuilder.validate(ImageRequestBuilder.java:259)
            at com.facebook.imagepipeline.request.ImageRequestBuilder.build(ImageRequestBuilder.java:235)
            at com.facebook.imagepipeline.request.ImageRequest.fromUri(ImageRequest.java:66)
            at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilder.setUri(PipelineDraweeControllerBuilder.java:52)
            at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilder.setUri(PipelineDraweeControllerBuilder.java:31)
            at com.facebook.drawee.view.SimpleDraweeView.setImageURI(SimpleDraweeView.java:99)
            at com.facebook.drawee.view.SimpleDraweeView.setImageURI(SimpleDraweeView.java:89)

How can I load the drawable resource from the mipmap folder?

**Comment by Nafeng** [comment]
Hi, I got the same problem;
I use the drawable png image of mipmaps;
I build the Uri String : res//"resourceId"; then I got the Exception:
 com.facebook.imagepipeline.request.ImageRequestBuilder$BuilderException: Invalid request builder: Resource URI must not be empty
            at com.facebook.imagepipeline.request.ImageRequestBuilder.validate(ImageRequestBuilder.java:259)
            at com.facebook.imagepipeline.request.ImageRequestBuilder.build(ImageRequestBuilder.java:235)
            at com.facebook.imagepipeline.request.ImageRequest.fromUri(ImageRequest.java:66)
            at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilder.setUri(PipelineDraweeControllerBuilder.java:52)
            at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilder.setUri(PipelineDraweeControllerBuilder.java:31)
            at com.facebook.drawee.view.SimpleDraweeView.setImageURI(SimpleDraweeView.java:99)
            at com.facebook.drawee.view.SimpleDraweeView.setImageURI(SimpleDraweeView.java:89)

How can I load the drawable resource from the mipmap folder?

**Comment by PankajSavaliyaGit** [comment]
two solution is here
ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithResourceId(R.drawable.image).build();
SimpleDraweeView draweeView = (SimpleDraweeView) v.findViewById(R.id.picture);
draweeView.setImageURI(imageRequest.getSourceUri());


also you are using
String uri="res:/"+R.drawable.image;
 viewHolder.home_image.setImageURI(Uri.parse(uri));

            viewHolder.title.setText(item.getTitle());

**Comment by yanxing** [comment]
@PankajSavaliyaGit ,I tried the first way,it's right,but the second way is error.
the Exception:
 com.facebook.imagepipeline.request.ImageRequestBuilder$BuilderException: Invalid request builder: Resource URI path must be a resource id.
                                                                                  at com.facebook.imagepipeline.request.ImageRequestBuilder.validate(ImageRequestBuilder.java:282)
                                                                                  at com.facebook.imagepipeline.request.ImageRequestBuilder.build(ImageRequestBuilder.java:253)
                                                                                  at com.facebook.imagepipeline.request.ImageRequest.fromUri(ImageRequest.java:68)
                                                                                  at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilder.setUri(PipelineDraweeControllerBuilder.java:54)
                                                                                  at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilder.setUri(PipelineDraweeControllerBuilder.java:33)
                                                                                  at com.facebook.drawee.view.SimpleDraweeView.setImageURI(SimpleDraweeView.java:107)

**Comment by PankajSavaliyaGit** [comment]
@yanxing i hope it will work fine.
Uri uri = new Uri.Builder()
                .scheme(UriUtil.LOCAL_RESOURCE_SCHEME) // "res"
                .path(String.valueOf(R.drawable.ic_launcher))
                .build();
// uri looks like res:/123456789
myImageView.setImageURI(uri);
