### ISSUE TITLE
UnsatisfiedLinkError: No implementation found for com.facebook.animated.gif.GifImage

### ISSUE THREAD

**Issue by zetbrush** [facebook/fresco#2582]
### Getting unusual many crash reports with this stucktrace
<a href="https://ibb.co/Zzgy0Br"><img src="https://i.ibb.co/r2pnVxh/Screen-Shot-2021-02-02-at-9-00-46-PM.png" alt="Screen-Shot-2021-02-02-at-9-00-46-PM" border="0"></a><br /><br />

Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for com.facebook.animated.gif.GifImage com.facebook.animated.gif.GifImage.nativeCreateFromDirectByteBuffer(java.nio.ByteBuffer, int, boolean) (tried Java_com_facebook_animated_gif_GifImage_nativeCreateFromDirectByteBuffer and Java_com_facebook_animated_gif_GifImage_nativeCreateFromDirectByteBuffer__Ljava_nio_ByteBuffer_2IZ)
       at com.facebook.animated.gif.GifImage.nativeCreateFromDirectByteBuffer(GifImage.java)
       at com.facebook.animated.gif.GifImage.createFromByteBuffer(GifImage.java:10)
       at com.facebook.animated.gif.GifImage.decodeFromByteBuffer(GifImage.java:115)
       at com.facebook.imagepipeline.animated.factory.AnimatedImageFactoryImpl.decodeGif(AnimatedImageFactoryImpl.java:29)
       at com.facebook.fresco.animation.factory.AnimatedFactoryV2Impl$1.decode(AnimatedFactoryV2Impl.java:8)
       at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeGif(DefaultImageDecoder.java:21)
       at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:21)
       at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:49)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.internalDecode(DecodeProducer.java:37)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:204)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$400(DecodeProducer.java:143)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:105)
       at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:30)
       at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:24)
       at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:11)
       at java.lang.Thread.run(Thread.java:919)

### Additional Information

* Fresco version: 2.3.0
* Platform version: Android 10, Samsung galaxy A10s and other devices

**Comment by wizh** [comment]
Hi! How are you loading Fresco, and in particular the animated-base module?

**Comment by zetbrush** [comment]
@wizh Hi, deppendency of com.facebook.fresco:animated-gif:2.3.0 exists as well, Fresco is initialized in application class, via
Fresco.initialize() with ImagePiplineConfig, where `imagePipelineConfigBuilder.setMemoryChunkType(MemoryChunkType.BUFFER_MEMORY);
 imagePipelineConfigBuilder.setImageTranscoderType(ImageTranscoderType.JAVA_TRANSCODER);` configs are set

**Comment by tomislavhofman** [comment]
> Hi! How are you loading Fresco, and in particular the animated-base module?

What is animated-base module and where is its usage documented?
