### ISSUE TITLE
OutOfMemoryError on android 6

### ISSUE THREAD

**Issue by ankursamarya** [facebook/fresco#2586]
### Description
We are facing OOM only on android 6 devices during image fetching from network.

#### Stacktrace:
`Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 3000012 byte allocation with 2106144 free bytes and 2MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
       at com.facebook.imagepipeline.memory.BucketsBitmapPool.alloc(BucketsBitmapPool.java:54)
       at com.facebook.imagepipeline.memory.BucketsBitmapPool.alloc(BucketsBitmapPool.java:27)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:243)
       at com.facebook.imagepipeline.platform.DefaultDecoder.decodeFromStream(DefaultDecoder.java:217)
       at com.facebook.imagepipeline.platform.DefaultDecoder.decodeJPEGFromEncodedImageWithColorSpace(DefaultDecoder.java:155)
       at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeJpeg(DefaultImageDecoder.java:179)
       at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:58)
       at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:120)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:316)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$300(DecodeProducer.java:136)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:186)
       at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:220)
       at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:23)
       at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:89)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:50)
       at java.lang.Thread.run(Thread.java:818)`

### Additional Information

* Fresco version: 2.1.0
* Platform version: Android 6
* Devices: Lenovo, vivo, Gionee

**Comment by whoislxy** [comment]
I have the same problem with Android 5.0/6.0
