### ISSUE TITLE
android10 Load local large image, thumbnail faile

### ISSUE THREAD

**Issue by 8gTong** [facebook/fresco#2593]
ExifInterface: Encountered exception while getting thumbnail
    android.system.ErrnoException: dup failed: EBADF (Bad file descriptor)
        at libcore.io.Linux.dup(Native Method)
        at libcore.io.ForwardingOs.dup(ForwardingOs.java:97)
        at libcore.io.ForwardingOs.dup(ForwardingOs.java:97)
        at android.system.Os.dup(Os.java:123)
        at android.media.ExifInterface.getThumbnailBytes(ExifInterface.java:2021)
        at android.media.ExifInterface.getThumbnail(ExifInterface.java:1990)
        at com.facebook.imagepipeline.producers.LocalExifThumbnailProducer$1.f(:101)
        at com.facebook.imagepipeline.producers.LocalExifThumbnailProducer$1.getResult(:91)
        at com.facebook.common.executors.StatefulRunnable.run(:45)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(:52)
        at java.lang.Thread.run(Thread.java:929)
2021-04-18 19:51:35.341 18724-19491/com.kad.ihealth D/ExifInterface: Encountered exception while getting thumbnail
    android.system.ErrnoException: dup failed: EBADF (Bad file descriptor)
        at libcore.io.Linux.dup(Native Method)
        at libcore.io.ForwardingOs.dup(ForwardingOs.java:97)
        at libcore.io.ForwardingOs.dup(ForwardingOs.java:97)
        at android.system.Os.dup(Os.java:123)
        at android.media.ExifInterface.getThumbnailBytes(ExifInterface.java:2021)
        at android.media.ExifInterface.getThumbnail(ExifInterface.java:1990)
        at com.facebook.imagepipeline.producers.LocalExifThumbnailProducer$1.f(:101)
        at com.facebook.imagepipeline.producers.LocalExifThumbnailProducer$1.getResult(:91)
        at com.facebook.common.executors.StatefulRunnable.run(:45)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(:52)
        at java.lang.Thread.run(Thread.java:929)

**Comment by 8gTong** [comment]
fresco:2.4.0

**Comment by 8gTong** [comment]
xifInterface: Encountered exception while getting thumbnail
android.system.ErrnoException: dup failed: EBADF (Bad file descriptor)
at libcore.io.Linux.dup(Native Method)
at libcore.io.ForwardingOs.dup(ForwardingOs.java:97)
at libcore.io.ForwardingOs.dup(ForwardingOs.java:97)
at android.system.Os.dup(Os.java:123)
at android.media.ExifInterface.getThumbnailBytes(ExifInterface.java:2021)
at android.media.ExifInterface.getThumbnail(ExifInterface.java:1990)
at com.facebook.imagepipeline.producers.LocalExifThumbnailProducer$1.f(:101)
at com.facebook.imagepipeline.producers.LocalExifThumbnailProducer$1.getResult(:91)
at com.facebook.common.executors.StatefulRunnable.run(:45)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(:52)
at java.lang.Thread.run(Thread.java:929)

**Comment by 8gTong** [comment]
fresco:2.4.0

**Comment by 8gTong** [comment]
targetSdk 29 (scoped storage) support?

**Comment by stven0king** [comment]
fresco:2.5.0 This solved my problem.
