### ISSUE TITLE
onFailure:Pool hard cap violation? 

### ISSUE THREAD

**Issue by wflian** [facebook/fresco#2596]
onFailure:Pool hard cap violation? Hard cap = 16777216 Used size = 0 Free size = 0 Request size = 17045549

com.facebook.imagepipeline.memory.BasePool$PoolSizeViolationException: Pool hard cap violation? Hard cap = 16777216 Used size = 0 Free size = 0 Request size = 17045549
    at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:238)
    at com.facebook.imagepipeline.memory.FlexByteArrayPool.get(FlexByteArrayPool.java:48)
    at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.decodeJPEGByteArrayAsPurgeable(KitKatPurgeableDecoder.java:80)
    at com.facebook.imagepipeline.nativecode.DalvikPurgeableDecoder.decodeJPEGFromEncodedImageWithColorSpace(DalvikPurgeableDecoder.java:137)
    at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeJpeg(DefaultImageDecoder.java:179)
    at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java:58)
    at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java:120)
    at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.internalDecode(DecodeProducer.java:386)
    at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:328)
    at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$400(DecodeProducer.java:145)
    at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:198)
    at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:224)
    at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:24)
    at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:52)
    at java.lang.Thread.run(Thread.java:841)

**Comment by DaxiALex** [comment]
any updates?
