### ISSUE TITLE
`v2.4.0` crashes a react native app only in release

### ISSUE THREAD

**Issue by LonelyCpp** [facebook/fresco#2601]
### Description

- use react native
- see that you need to add `'com.facebook.fresco:animated-gif:2.0.0'` to support gifs
- update version to `2.4.0` since this is the latest
- works perfectly fine in debug mode
- make a release build, crashes immediately when it tries to load an image

### Reproduction

- make a react native project
- add `'com.facebook.fresco:animated-gif:2.4.0'` as a dependency
- make an `<Image />` component with a gif as source
- run `npx react-native run-android --variant=release`

[Repo with a demo react native app that has this crash](https://github.com/LonelyCpp/FrescoRN)

### Solution

keep using `v2.0.0`

### Additional Information

tested on : 
- react native: `v0.63.4`
- android 10, 11

crash log : 
```
FATAL EXCEPTION: main
Process: com.frescorn, PID: 7667
java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/util/Set;)V in class Lcom/facebook/drawee/controller/AbstractDraweeControllerBuilder; or its super classes (declaration of 'com.facebook.drawee.controller.AbstractDraweeControllerBuilder' appears in /data/app/~~3O5wMjzrwWcDaRuvOExDuQ==/com.frescorn-tyoWE7bg57z9hhqsfRQJhQ==/base.apk)
	at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilder.<init>(PipelineDraweeControllerBuilder.java:58)
	at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.get(PipelineDraweeControllerBuilderSupplier.java:80)
	at com.facebook.drawee.backends.pipeline.Fresco.newDraweeControllerBuilder(Fresco.java:111)
	at com.facebook.react.views.image.ReactImageManager.getDraweeControllerBuilder(ReactImageManager.java:95)
	at com.facebook.react.views.image.ReactImageManager.createViewInstance(ReactImageManager.java:113)
	at com.facebook.react.views.image.ReactImageManager.createViewInstance(ReactImageManager.java:29)
	at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:83)
	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:261)
	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:186)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1112)
	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1083)
	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:727)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by comvenger-brandon** [comment]
Also happening here with 2.5.0.

**Comment by jeoEnfin** [comment]
also happening with 2.6.0
