### ISSUE TITLE
int com.facebook.cache.disk.DiskCacheConfig.getVersion()' on a null object reference

### ISSUE THREAD

**Issue by wgueter** [facebook/fresco#2616]
`java.lang.RuntimeException: Unable to create application s.h.e.l.l.S: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.facebook.cache.disk.DiskCacheConfig.getVersion()' on a null object reference
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6094)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1844)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:6861)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.facebook.cache.disk.å.getVersion()' on a null object reference
	at com.facebook.imagepipeline.core.DynamicDefaultDiskStorageFactory.get(DynamicDefaultDiskStorageFactory.java:23)
	at com.facebook.imagepipeline.core.DiskStorageCacheFactory.get(DiskStorageCacheFactory.java:45)
	at com.facebook.imagepipeline.core.ImagePipelineFactory.getMainFileCache(ImagePipelineFactory.java:223)
	at com.facebook.imagepipeline.core.ImagePipelineFactory.getMainBufferedDiskCache(ImagePipelineFactory.java:202)
	at com.facebook.imagepipeline.core.ImagePipelineFactory.getProducerFactory(ImagePipelineFactory.java:326)
	at com.facebook.imagepipeline.core.ImagePipelineFactory.getProducerSequenceFactory(ImagePipelineFactory.java:340)
	at com.facebook.imagepipeline.core.ImagePipelineFactory.getImagePipeline(ImagePipelineFactory.java:232)
	at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:48)
	at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:40)
	at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:34)
	at com.facebook.drawee.backends.pipeline.Fresco.initializeDrawee(Fresco.java:43)
	at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:33)
	at my.sport.yuedong.com.ydlibrary.YuedongSdk.initApplication(YuedongSdk.java:202)
	at cn.lnts.android.sghome.SGApplication.onCreate(SGApplication.java:120)
	at s.h.e.l.l.S.onCreate(Unknown Source:33)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6082)
	... 8 more`
### Additional Information
        Fresco.initialize(this);
    api 'com.facebook.fresco:fresco:0.11.0'

**Comment by wgueter** [comment]
java.lang.RuntimeException: Unable to create application s.h.e.l.l.S: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.facebook.cache.disk.DiskCacheConfig.getVersion()' on a null object reference
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6094)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1844)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:6861)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.facebook.cache.disk.å.getVersion()' on a null object reference
	at com.facebook.imagepipeline.core.DynamicDefaultDiskStorageFactory.get(DynamicDefaultDiskStorageFactory.java:23)
	at com.facebook.imagepipeline.core.DiskStorageCacheFactory.get(DiskStorageCacheFactory.java:45)
	at com.facebook.imagepipeline.core.ImagePipelineFactory.getMainFileCache(ImagePipelineFactory.java:223)
	at com.facebook.imagepipeline.core.ImagePipelineFactory.getMainBufferedDiskCache(ImagePipelineFactory.java:202)
	at com.facebook.imagepipeline.core.ImagePipelineFactory.getProducerFactory(ImagePipelineFactory.java:326)
	at com.facebook.imagepipeline.core.ImagePipelineFactory.getProducerSequenceFactory(ImagePipelineFactory.java:340)
	at com.facebook.imagepipeline.core.ImagePipelineFactory.getImagePipeline(ImagePipelineFactory.java:232)
	at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:48)
	at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:40)
	at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:34)
	at com.facebook.drawee.backends.pipeline.Fresco.initializeDrawee(Fresco.java:43)
	at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:33)
	at my.sport.yuedong.com.ydlibrary.YuedongSdk.initApplication(YuedongSdk.java:202)
	at cn.lnts.android.sghome.SGApplication.onCreate(SGApplication.java:120)
	at s.h.e.l.l.S.onCreate(Unknown Source:33)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6082)
	... 8 more
