### ISSUE TITLE
NullPointerException SettableDraweeHierarchy.setProgress(float, boolean)' on a null object reference

### ISSUE THREAD

**Issue by kongxiaoan** [facebook/fresco#2618]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.drawee.interfaces.SettableDraweeHierarchy.setProgress(float, boolean)' on a null object reference
       at com.facebook.drawee.controller.AbstractDraweeController.submitRequest(AbstractDraweeController.java:548)
       at com.facebook.drawee.controller.AbstractDraweeController.onAttach(AbstractDraweeController.java:447)
       at com.facebook.drawee.view.DraweeHolder.attachController(DraweeHolder.java:248)
       at com.facebook.drawee.view.DraweeHolder.attachOrDetachController(DraweeHolder.java:265)
       at com.facebook.drawee.view.DraweeHolder.onVisibilityChange(DraweeHolder.java:134)
       at com.facebook.drawee.generic.RootDrawable.setVisible(RootDrawable.java:69)
       at android.widget.ImageView.onVisibilityAggregated(ImageView.java:1544)
       at android.view.View.dispatchAttachedToWindow(View.java:16916)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3136)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3136)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3136)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3136)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3136)
       at android.view.ViewGroup.addViewInner(ViewGroup.java:4675)
       at android.view.ViewGroup.addView(ViewGroup.java:4477)
       at android.view.ViewGroup.addView(ViewGroup.java:4417)
       at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:889)
       at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:107)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8908)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8866)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8854)
       at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1645)
       at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
       at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1395)
       at androidx.recyclerview.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1136)
       at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:1972)
       at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:2071)
       at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3531)
       at android.view.View.dispatchTouchEvent(View.java:10936)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2836)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2512)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2842)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2527)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:623)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1909)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3247)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:585)
       at android.view.View.dispatchPointerEvent(View.java:11165)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5227)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5076)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4580)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4633)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4599)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4736)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4607)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4793)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4580)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4633)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4599)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4607)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4580)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7210)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7142)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7103)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7321)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7284)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7348)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930)
       at android.view.Choreographer.doCallbacks(Choreographer.java:705)
       at android.view.Choreographer.doFrame(Choreographer.java:634)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6816)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

**Comment by ajinhuang** [comment]
still having this problem, did you solve it?

**Comment by callmehanyu** [comment]
我也遇到了，日了狗
