### ISSUE TITLE
FrescoIoBoundExecutor

### ISSUE THREAD

**Issue by Haleydu** [facebook/fresco#2625]
FATAL EXCEPTION: FrescoIoBoundExecutor-1
    java.lang.IllegalStateException
        at com.facebook.common.internal.Preconditions.checkState(Preconditions.java:160)
        at com.facebook.cache.disk.DefaultDiskStorage$PurgingVisitor.isExpectedFile(DefaultDiskStorage.java:310)
        at com.facebook.cache.disk.DefaultDiskStorage$PurgingVisitor.visitFile(DefaultDiskStorage.java:283)
        at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:37)
        at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:35)
        at com.facebook.common.file.FileTree.walkFileTree(FileTree.java:35)
        at com.facebook.cache.disk.DefaultDiskStorage.purgeUnexpectedResources(DefaultDiskStorage.java:322)
        at com.facebook.cache.disk.DynamicDefaultDiskStorage.purgeUnexpectedResources(DynamicDefaultDiskStorage.java:107)
        at com.facebook.cache.disk.DiskStorageCache.evictAboveSize(DiskStorageCache.java:512)
        at com.facebook.cache.disk.DiskStorageCache.maybeEvictFilesInCacheDir(DiskStorageCache.java:466)
        at com.facebook.cache.disk.DiskStorageCache.startInsert(DiskStorageCache.java:315)
        at com.facebook.cache.disk.DiskStorageCache.insert(DiskStorageCache.java:348)
        at com.facebook.imagepipeline.cache.BufferedDiskCache.writeToDiskCache(BufferedDiskCache.java:449)
        at com.facebook.imagepipeline.cache.BufferedDiskCache.access$600(BufferedDiskCache.java:39)
        at com.facebook.imagepipeline.cache.BufferedDiskCache$4.run(BufferedDiskCache.java:308)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:52)
        at java.lang.Thread.run(Thread.java:929)

**Comment by oprisnik** [comment]
Hi! Can you please fill in the issue template with more details? Thank you!

**Comment by Haleydu** [comment]
[crash.log](https://github.com/facebook/fresco/files/7070758/crash.log)

**Comment by Haleydu** [comment]
My app didn't crash anywhere, only Fresco did, and I can't rule out the problem

**Comment by Haleydu** [comment]
![crash](https://user-images.githubusercontent.com/44172947/131222022-9f5c781d-ead6-4876-aa14-ca362c940675.png)
