### ISSUE TITLE
.Preconditions.checkState  IllegalStateException

### ISSUE THREAD

**Issue by ayyb1988** [facebook/fresco#263]
Process: com.facebook.fresco.sample, PID: 6495
    java.lang.IllegalStateException
            at com.facebook.common.internal.Preconditions.checkState(Preconditions.java:158)

**Comment by IanChilds** [comment]
Please can you give more of the stack than this - we can't work anything out from the small sample that you've given.

**Comment by nithinraja** [comment]
java.lang.IllegalStateException
            at com.facebook.common.internal.Preconditions.checkState(Preconditions.java:158)
            at com.facebook.common.references.CloseableReference.get(CloseableReference.java:154)
            at com.facebook.imagepipeline.cache.CountingMemoryCache$1.getSizeInBytes(CountingMemoryCache.java:124)
            at com.facebook.imagepipeline.cache.CountingMemoryCache$1.getSizeInBytes(CountingMemoryCache.java:121)
            at com.facebook.imagepipeline.cache.CountingLruMap.getValueSizeInBytes(CountingLruMap.java:133)
            at com.facebook.imagepipeline.cache.CountingLruMap.put(CountingLruMap.java:97)
            at com.facebook.imagepipeline.cache.CountingMemoryCache.maybeAddToExclusives(CountingMemoryCache.java:224)
            at com.facebook.imagepipeline.cache.CountingMemoryCache.releaseClientReference(CountingMemoryCache.java:213)
            at com.facebook.imagepipeline.cache.CountingMemoryCache.access$000(CountingMemoryCache.java:44)
            at com.facebook.imagepipeline.cache.CountingMemoryCache$2.release(CountingMemoryCache.java:202)
            at com.facebook.common.references.SharedReference.deleteReference(SharedReference.java:211)
            at com.facebook.common.references.CloseableReference.close(CloseableReference.java:146)
            at com.facebook.common.references.CloseableReference.finalize(CloseableReference.java:196)
            at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:185)
            at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:168)
            at java.lang.Thread.run(Thread.java:856)

**Comment by tyronen** [comment]
Is this in your app, or the sample app?

This happens if a CloseableReference has not been finalized. Are you calling the image pipeline directly or using Drawee? If the pipeline, are you closing all your CloseableReferences correctly?

**Comment by nithinraja** [comment]
Its a sample app, after closing CloseableReferences it is working fine...

**Comment by senhor** [comment]
I have same error with SimpleDraweeView
