### ISSUE TITLE
crash：libimagepipeline.so  is 64-bit instead of 32-bit result

### ISSUE THREAD

**Issue by ithour** [facebook/fresco#2659]
crash info：
com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:918)
	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:740)
	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:654)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:634)
	at com.facebook.soloader.NativeLoaderToSoLoaderDelegate.loadLibrary(NativeLoaderToSoLoaderDelegate.java:29)
	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:51)
	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
	at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:33)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:31)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:16)
	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:256)
	at com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.<init>(MemoryPooledByteBufferOutputStream.java:55)
	at com.facebook.imagepipeline.memory.MemoryPooledByteBufferOutputStream.<init>(MemoryPooledByteBufferOutputStream.java:37)
	at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(MemoryPooledByteBufferFactory.java:50)
	at com.facebook.imagepipeline.memory.MemoryPooledByteBufferFactory.newByteBuffer(MemoryPooledByteBufferFactory.java:25)

crash phone：oppo a33m

if set "debuggable true"  No crash ，On the contrary, it will crash

**Comment by arjun1194** [comment]
same issue

**Comment by alexwan02** [comment]
Looks like it was fixed by this [PR](https://github.com/facebook/SoLoader/pull/45)
