### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/infer/annotation/Assertions;

### ISSUE THREAD

**Issue by houchang1991** [facebook/fresco#2692]
### Description

Successfully compile my app with fresco lib, but while running, such crash occurs:
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/infer/annotation/Assertions;
	at com.facebook.common.util.UriUtil.<clinit>(UriUtil.java:41)
	at com.facebook.common.util.UriUtil.isLocalFileUri(UriUtil.java:96)
        ...
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.infer.annotation.Assertions" on path: DexPathList[[zip file 
...
Suppressed: java.io.IOException: Failed to open dex files from /data/app/~~qCzWekrFwP9Ah2fUri5d4Q==/com.huawei.photos-AyZDGmPkpu5Ke1c5Xm8XZg==/split_Editor.config.armeabi_v7a.apk because: Entry not found
...
```

### Additional Information

* Fresco version: 2.6.0
* Platform version: android 12

**Comment by FlyingTotoro** [comment]
add Dependence  'com.facebook.infer.annotation:infer-annotation'
