### ISSUE TITLE
Was Fresco 3.0.0 intentionally released?

### ISSUE THREAD

**Issue by darrentaft** [facebook/fresco#2714]
Before I go reporting bugs for numerous issues with Fresco 3.0.0, I just wanted to confirm that it wasn't an accidental release.  Could someone please confirm?  It seems to have too many issues for it to be intentional.

**Comment by oprisnik** [comment]
Hey! Thanks for reaching out. What issues are you seeing? We did make several changes to our release pipeline, but we do intend to release a new Fresco version.

**Comment by oprisnik** [comment]
Sorry for that!

Related to middleware: Can you try if adding com.facebook.fresco:middleware:3.0.0 fixes your issues?

https://repo1.maven.org/maven2/com/facebook/fresco/middleware/3.0.0/

**Comment by darrentaft** [comment]
That fixes the HasExtraData class, but the native library is still missing (and fetchWithRequest is still final, obviously). 

I don't want to push you guys to fix it if it wasn't ready. I genuinely expected you to say 3.0.0 was released by accident. I'm happy to wait for the final release.  The real reason I'm keen to update, is to see if it has fixed a distortion issue I'm seeing with 2.6.0.

Take this URL: https://images-live.youview.tv/images/entity/77502239/ident/1_256x144.png?overlaygradient=0

When rendered in the app with `fresco:actualImageScaleType="fitCenter"` is displays this (see the stripes either side):

![image](https://user-images.githubusercontent.com/44803864/226430604-ae94659a-d149-4882-9c3d-783eebfd23a0.png)

When rendered using centerInside, it works fine (but isn't the correct size).  This happens with all our channel logos.

**Comment by oprisnik** [comment]
Hey!
* We're going to change fetchWithRequest shortly so that it can be overridden again.
* Regarding the distortion, yes as you've mentioned that should be fixed with the new version (#2541)
* I cannot reproduce the missing native lib on my end unfortunately. I've created a new Gradle sample app and added:

Gradle deps:
```
    implementation 'com.facebook.fresco:fresco:3.0.0'
    implementation 'com.facebook.fresco:imagepipeline-okhttp3:3.0.0'
 ```

Init logic:
```
Fresco.initialize(requireContext(), OkHttpImagePipelineConfigFactory.newBuilder(requireContext(), OkHttpClient()).build())
```

XML layout:
```
    <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/drawee"
        android:layout_width="100dp"
        android:layout_height="100dp" />
```

Loading image:
```
binding.drawee.setImageURI("https://images-live.youview.tv/images/entity/77502239/ident/1_256x144.png?overlaygradient=0")

```

Your channel log seems to render fine and I don't see any crash.

**Comment by meixililu** [comment]
2.6.0 to 3.0.0:
E/AndroidRuntime: FATAL EXCEPTION: FrescoLightWeightBackgroundExecutor-1
    Process: com.messi.languagehelper, PID: 18877
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libnative-imagetranscoder.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary(SystemDelegate.java:24)
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:52)
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)

**Comment by plhjd** [comment]
implementation 'com.facebook.fresco:fresco:3.0.0'
implementation 'com.facebook.fresco:nativeimagetranscoder:3.0.0'

compileSdkVersion 33
buildToolsVersion "33.0.2"

Android 12 Emulator crash

E/AndroidRuntime: FATAL EXCEPTION: FrescoIoBoundExecutor-1
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libnative-imagetranscoder.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1656)
        at com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary(SystemDelegate.java:24)
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:52)
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
        at com.facebook.imagepipeline.nativecode.NativeJpegTranscoderSoLoader.ensure(NativeJpegTranscoderSoLoader.java:33)
        at com.facebook.imagepipeline.nativecode.NativeJpegTranscoder.<init>(NativeJpegTranscoder.java:59)
        at com.facebook.imagepipeline.nativecode.NativeJpegTranscoderFactory.createImageTranscoder(NativeJpegTranscoderFactory.java:43)
        at com.facebook.imagepipeline.transcoder.MultiImageTranscoderFactory.getNativeImageTranscoder(MultiImageTranscoderFactory.kt:59)
        at com.facebook.imagepipeline.transcoder.MultiImageTranscoderFactory.createImageTranscoder(MultiImageTranscoderFactory.kt:40)
        at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.onNewResultImpl(ResizeAndRotateProducer.java:166)
        at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.onNewResultImpl(ResizeAndRotateProducer.java:84)
        at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
        at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:49)
        at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:33)
        at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onNextResult(MultiplexProducer.java:510)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:569)
        at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:562)
        at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
        at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$EncodedMemoryCacheConsumer.onNewResultImpl(EncodedMemoryCacheProducer.java:181)
        at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$EncodedMemoryCacheConsumer.onNewResultImpl(EncodedMemoryCacheProducer.java:123)
        at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
        at com.facebook.imagepipeline.producers.StatefulProducerRunnable.onSuccess(StatefulProducerRunnable.java:50)
        at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:55)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.facebook.imagepipeline.core.PriorityThreadFactory.newThread$lambda$0(PriorityThreadFactory.kt:37)
        at com.facebook.imagepipeline.core.PriorityThreadFactory.$r8$lambda$IPp7Vm9a1KDy8D4770JTjI9qOG4(Unknown Source:0)

**Comment by oprisnik** [comment]
Can you please try adding the following Gradle dependency to your build:
```
com.facebook.fresco:nativeimagetranscoder3:3.0.0
```

That should fix the crash.

**Comment by plhjd** [comment]
Hi @oprisnik, thanks for the answer, I can't find com.facebook.fresco:**nativeimagetranscoder3**:3.0.0 in the repositories, I tried to add com.facebook.fresco:**nativeimagetranscoder**:3.0.0 which doesn't contain the '3' at the end of the name, but that still with "libnative-imagetranscoder.so" not found error message.

**Comment by AS0820075980** [comment]
รับ Outlook สำหรับ Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AS0820075980** [comment]
ในวันที่ พ. 12 เม.ย. 2023 01:54 น. ชัยวัฒน์ จันทร์ทักษ์ <
***@***.***> เขียนว่า:

**Comment by MALTF** [comment]
Can you please try adding the following Gradle dependency to your build:
【com.facebook.fresco:nativeimagetranscoder:2.6.0】
That should fix the crash.

**Comment by MALTF** [comment]
Can you please try adding the following Gradle dependency to your build:
`com.facebook.fresco:nativeimagetranscoder:2.6.0`
That should fix the crash.

**Comment by MALTF** [comment]
Can you please try adding the following Gradle dependency to your build:

`com.facebook.fresco:nativeimagetranscoder:2.6.0`

That should fix the crash.

**Comment by initialjie** [comment]
> 

Nope, this is not working.

**Comment by initialjie** [comment]
> > Can you please try adding the following Gradle dependency to your build:
> > ```
> > com.facebook.fresco:nativeimagetranscoder:2.6.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That should fix the crash.

Nope, this is not working, but this works, see https://github.com/facebook/fresco/issues/2722#issuecomment-1517160326

**Comment by MALTF** [comment]
> > > Can you please try adding the following Gradle dependency to your build:
> > > ```
> > > com.facebook.fresco:nativeimagetranscoder:2.6.0
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > That should fix the crash.
> 
> Nope, this is not working, but this works, see [#2722 (comment)](https://github.com/facebook/fresco/issues/2722#issuecomment-1517160326)

see [2714#issuecomment](https://github.com/facebook/fresco/issues/2714#issuecomment-1518925371)

**Comment by darrentaft** [comment]
I'm not sure what's happened to this project - too many seemingly accidental public releases, always with no release notes, and sometimes deleted shortly after.
I've abandoned Fresco and moved to Coil.
There are already other issues open to cover the issues with it, so I'll close this question down.
