### ISSUE TITLE
Couldn't find "libnative-imagetranscoder.so"

### ISSUE THREAD

**Issue by 779556215** [facebook/fresco#2715]
### Description
use SimpleDraweeView to show a jpeg image.

### Reproduction
StackTrace:
```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[...]couldn't find "libnative-imagetranscoder.so"
at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
at java.lang.System.loadLibrary(System.java:1667)
at com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary(SystemDelegate.java:24)
at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:52)
at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
at com.facebook.imagepipeline.nativecode.NativeJpegTranscoderSoLoader.ensure(NativeJpegTranscoderSoLoader.java:33)
at com.facebook.imagepipeline.nativecode.NativeJpegTranscoder.<init>(NativeJpegTranscoder.java:59)
...
```
### Additional Information

* Fresco version: 3.0.0
* Platform version: Android 12

**Comment by josephyanks** [comment]
@779556215 how did you end up resolving this issue?
