### ISSUE TITLE
App crashing with java.lang.UnsatisfiedLinkError: dlopen failed: library "libnative-imagetranscoder.so" not found when trying to load jpg web images

### ISSUE THREAD

**Issue by charlesBon** [facebook/fresco#2726]
### Description

App crashing with java.lang.UnsatisfiedLinkError: dlopen failed: library "libnative-imagetranscoder.so" not found when trying to load web jpg images

Using latest react-native-android 0.71.7, 
`FATAL EXCEPTION: FrescoIoBoundExecutor-2
                                                                                                    Process: com.myapp, PID: 21806
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libnative-imagetranscoder.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at com.facebook.soloader.nativeloader.SystemDelegate.loadLibrary(SystemDelegate.java:24)
                                                                                                    	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:52)
                                                                                                    	at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
                                                                                                    	at com.facebook.imagepipeline.nativecode.NativeJpegTranscoderSoLoader.ensure(NativeJpegTranscoderSoLoader.java:33)
                                                                                                    	at com.facebook.imagepipeline.nativecode.NativeJpegTranscoder.<init>(NativeJpegTranscoder.java:59)
                                                                                                    	at com.facebook.imagepipeline.nativecode.NativeJpegTranscoderFactory.createImageTranscoder(NativeJpegTranscoderFactory.java:43)
                                                                                                    	at com.facebook.imagepipeline.transcoder.MultiImageTranscoderFactory.getNativeImageTranscoder(MultiImageTranscoderFactory.kt:59)
                                                                                                    	at com.facebook.imagepipeline.transcoder.MultiImageTranscoderFactory.createImageTranscoder(MultiImageTranscoderFactory.kt:40)
                                                                                                    	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.onNewResultImpl(ResizeAndRotateProducer.java:166)
                                                                                                    	at com.facebook.imagepipeline.producers.ResizeAndRotateProducer$TransformingConsumer.onNewResultImpl(ResizeAndRotateProducer.java:84)
                                                                                                    	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
                                                                                                    	at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:49)
                                                                                                    	at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:33)
                                                                                                    	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
                                                                                                    	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onNextResult(MultiplexProducer.java:510)
                                                                                                    	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:569)
                                                                                                    	at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:562)
                                                                                                    	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
                                                                                                    	at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$EncodedMemoryCacheConsumer.onNewResultImpl(EncodedMemoryCacheProducer.java:188)
                                                                                                    	at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$EncodedMemoryCacheConsumer.onNewResultImpl(EncodedMemoryCacheProducer.java:123)
                                                                                                    	at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:89)
                                                                                                    	at com.facebook.imagepipeline.producers.DiskCacheReadProducer$1.then(DiskCacheReadProducer.java:113)
                                                                                                    	at com.facebook.imagepipeline.producers.DiskCacheReadProducer$1.then(DiskCacheReadProducer.java:93)
                                                                                                    	at bolts.Task$14.run(Task.java:872)
                                                                                                    	at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
                                                                                                    	at bolts.Task.completeImmediately(Task.java:863)
                                                                                                    	at bolts.Task.access$000(Task.java:32)
                                                                                                    	at bolts.Task$10.then(Task.java:654)
                                                                                                    	at bolts.Task$10.then(Task.java:651)
                                                                                                    	at bolts.Task.runContinuations(Task.java:956)
                                                                                                    	at bolts.Task.trySetResult(Task.java:994)
                                                                                                    	at bolts.TaskCompletionSource.trySetResult(TaskCompletionSource.java:39)
                                                                                                    	at bolts.TaskCompletionSource.setResult(TaskCompletionSource.java:62)
                                                                                                    	at bolts.Task$4.run(Task.java:357)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at com.facebook.imagepipeline.core.PriorityThreadFactory.newThread$lambda$0(PriorityThreadFactory.kt:37)
                                                                                                    	at com.facebook.imagepipeline.core.PriorityThreadFactory.$r8$lambda$IPp7Vm9a1KDy8D4770JTjI9qOG4(Unknown Source:0)
2023-04-30 14:11:44.994 21806-21926 AndroidRuntime          com.myapp                           E  	at com.facebook.imagepipeline.core.PriorityThreadFactory$$ExternalSyntheticLambda0.run(Unknown Source:4)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)`

### Reproduction
react-native: 0.71.7, 
Android Api Version 13,
fresco:animated-gif:2.5.0',
fresco:animated-webp:2.5.0',
fresco:webpsupport:2.5.0',
MacM1 pro,

### Additional Information

* Fresco version: [2.5.0]
* Platform version: [13]

**Comment by josephyanks** [comment]
@charlesBon how did you end up resolving this issue?

**Comment by luckyleongao** [comment]
> @charlesBon how did you end up resolving this issue?
@josephyanks see #2722

**Comment by luckyleongao** [comment]
@josephyanks see #2722
