### ISSUE TITLE
Bug: Crash on MIUI 14.0.5

### ISSUE THREAD

**Issue by ngoquyen45** [facebook/fresco#2750]
### Description

FATAL EXCEPTION: main
Process: com.***, PID: 13695
java.lang.IllegalStateException: Queue full
at java.util.AbstractQueue.add(AbstractQueue.java:98)
at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:329)
at com.facebook.drawee.components.DraweeEventTracker.recordEvent(DraweeEventTracker.java:75)
at com.facebook.drawee.controller.AbstractDraweeController.onFailureInternal(AbstractDraweeController.java:695)
at com.facebook.drawee.controller.AbstractDraweeController.access$200(AbstractDraweeController.java:56)
at com.facebook.drawee.controller.AbstractDraweeController$2.onFailureImpl(AbstractDraweeController.java:596)
at com.facebook.datasource.BaseDataSubscriber.onFailure(BaseDataSubscriber.java:62)
at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:196)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at android.app.ActivityThread.main(ActivityThread.java:8294)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

### Reproduction

scroll RecyclerView contains fresco images

### Additional Information

* Fresco version: 3.1.3
* Platform version: Android 13, Redmi 10

**Comment by steelrooter** [comment]
Thanks for reporting. This has been fixed with 31037eede579cf2e7f0174f5718522a901988371 and will be included in the next Fresco release.
