### ISSUE TITLE
Fresco.initialize caused Application Not Responding

### ISSUE THREAD

**Issue by RitaBags** [facebook/fresco#2771]
### Description

While executing a code on below line it is producing ANR. ANR's are reported on Crashlytics 
We are facing ANR while initializing the liabrary as

```
fun init() {
        Fresco.initialize(application, imagePipelineConfig)
    }
```

Below is the ANR report from Crashlytics:
at java.util.concurrent.CancellationException.<init>(CancellationException.java:61)
       at com.facebook.imagepipeline.core.ImagePipeline.<clinit>(ImagePipeline.java)
       at com.facebook.imagepipeline.core.ImagePipelineFactory.createImagePipeline(ImagePipelineFactory.java:309)
       at com.facebook.imagepipeline.core.ImagePipelineFactory.getImagePipeline(ImagePipelineFactory.java:303)
       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:55)
       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:45)
       at com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier.<init>(PipelineDraweeControllerBuilderSupplier.java:38)
       at com.facebook.drawee.backends.pipeline.Fresco.initializeDrawee(Fresco.java:121)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:110)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:54)
       at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:46)
       at com.myapp.framework.fresco.FrescoManager.init(FrescoManager.java:13)
       at com.myapp.FrescoInitializer.create(FrescoInitializer.kt:17)
       at com.myapp.FrescoInitializer.create(FrescoInitializer.kt:10)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)

### Reproduction

It is an online ANR, I can't reproduce it on my phone, however it happens for multiple users.

### Solution

N/A

### Additional Information

* Fresco version:  2.5.0
* Platform version:  Android version 11, 12, 13   Devices: HMD Global, Motorola, Google Cros, Oneplus, Samsung and other

**Comment by RitaBags** [comment]
Any update on it? or do I need to assign it to any specific person in order get the update ?

**Comment by STEPHENERUEAGA6** [comment]
fun init() {
        Fresco.initialize(application, imagePipelineConfig)
    }

**Comment by STEPHENERUEAGA6** [comment]
[result (7).txt](https://github.com/user-attachments/files/17089820/result.7.txt)

**Comment by STEPHENERUEAGA6** [comment]
**docs/images/ActionsPermissions.png**

**Comment by STEPHENERUEAGA6** [comment]
docs/images/ActionsPermissions.png

**Comment by zoomGitS** [comment]
how do you solved this?

**Comment by RitaBags** [comment]
I thought by updating the version it will resolve the ANR. But it seems it is still there. Reopening the issue.
