### ISSUE TITLE
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/nativecode/Bitmaps

### ISSUE THREAD

**Issue by weisine** [facebook/fresco#288]
the error code is:
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/nativecode/Bitmaps
	at com.facebook.imagepipeline.bitmaps.DalvikBitmapFactory.decodeAsPurgeableBitmap(DalvikBitmapFactory.java:164)
	at com.facebook.imagepipeline.bitmaps.DalvikBitmapFactory.doDecodeBitmap(DalvikBitmapFactory.java:136)
	at com.facebook.imagepipeline.bitmaps.DalvikBitmapFactory.decodeJPEGFromPooledByteBuffer(DalvikBitmapFactory.java:124)
	at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.decodeJPEGFromPooledByteBuffer(PlatformBitmapFactory.java:108)
	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeJpeg(ImageDecoder.java:135)
	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:83)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:231)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:92)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$3.run(DecodeProducer.java:202)
	at com.facebook.common.executors.SerialDelegatingExecutor.executeSingleCommand(SerialDelegatingExecutor.java:76)
	at com.facebook.common.executors.SerialDelegatingExecutor.access$000(SerialDelegatingExecutor.java:24)
	at com.facebook.common.executors.SerialDelegatingExecutor$1.run(SerialDelegatingExecutor.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at java.lang.Thread.run(Thread.java:856)

this error happens at samsung Gallaxy Note II(android version:4.1.2) and HUAWEI P6-T00(android version 4.2.2)

what can i do for this bug?
i need help 
thanks

**Comment by michalgr** [comment]
Most likely Bitmap class fails to load native code in its static initializer. Can you tell us what is the content of the 'lib' directory in your apk ? (you can unzip the apk to see the directory)

**Comment by weisine** [comment]
lib directory is :
 lib-------armeabi---------------libbitmaps.so
             armeabi-v7a---------libbitmaps.so
             mips--------------------(the is no libbitmaps.so)
             x86---------------------libbitmaps.so

**Comment by michalgr** [comment]
I see. Can you reproduce this once again and check logcat for earlier errors that happened when bitmaps library was being loaded ?

**Comment by weisine** [comment]
The bug comes from our users, and currently  I can't reproduction it. 
But there has another bug:

java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:264)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.&lt;init&gt;(NativePooledByteBufferOutputStream.java:53)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:98)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
	at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:197)
	at com.facebook.imagepipeline.cache.BufferedDiskCache.access$300(BufferedDiskCache.java:37)
	at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:103)
	at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:87)
	at bolts.Task$2.run(Task.java:195)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:838)

Can you find out something?
Thanks for reply.

**Comment by michalgr** [comment]
Do you have any non-fresco native libraries ? What is in the mips subdirectory ? I could totally imagine this happening on non supported architectures - mips or one of the 64 bit architectures (see https://github.com/facebook/fresco/pull/176). But none of the devices you mentioned seem to fall into this category.

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by tyronen** [comment]
Reaping.

**Comment by mufumbo** [comment]
Hello, 

Please re-open this bug. We just added to our app and here's the device through this. 

Seems a lenovo, so maybe a weird architecture. Are you able to fallback safely, instead of crashing? 

https://www.dropbox.com/s/5h4sv9nnw133233/Screenshot%202015-10-20%2011.01.28.png?dl=0

thanks
rafa

**Comment by naivor** [comment]
i meet the same problem ,how to  solve  it?

**Comment by tom161566038** [comment]
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/nativecode/Bitmaps on 4.2,4.4.2,while no problem in 5.0 and 6.0,help~

**Comment by JackPeel** [comment]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yikaton.handyshop-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yikaton.handyshop-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libimagepipeline.so"    how to solve it?  help!
