### ISSUE TITLE
This is my Fresco "sample project. May be due to the special symbols in the URL. Pictures can't show found Fresco "often happen.

### ISSUE THREAD

**Issue by liujianying** [facebook/fresco#295]
This is my project address:https://github.com/liujianying/FrescoDemo 
Use Fresco "version 0.5.0
compile 'com.facebook.fresco:fresco:0.5.0'
compile 'com.facebook.fresco:imagepipeline-okhttp:0.5.0'
This is the sample project in the URL:
http://img.v89.com/group1/M08/04/22/rBAA11OtUeqAILyjAAC2I8VNHUU462_640*640.jpg
http://img.v89.com/group1/M01/05/CF/rBAA11SJGj6ANUmYAAHYXsbUhAM483_640*640.jpg
http://img.v89.com/group1/M07/05/CF/rBAA11SJGjuAYGYwAAHthrrvYrQ279_640*640.jpg
http://img.v89.com/group1/M05/05/CE/rBAA11SIRc2AR95TAAFos2CSxNk102_640*640.jpg
http://img.v89.com/group1/M05/05/CE/rBAA11SIRcaAC81hAAHeRIw0YkE550_640*640.jpg
http://img.v89.com/group1/M05/05/CF/rBAA11SJCT2AaVvHAAFPnJV76ic597_640*640.jpg
http://img.v89.com/group1/M01/05/CF/rBAA11SJCTiAPJeLAAFPo48Ykuk249_640*640.jpg
http://img.v89.com/group1/M05/06/C9/rBAA11UhWACAcl-pAAG5ICOGh7I506_640*640.jpg
http://img.v89.com/group1/M08/05/CF/rBAA11SJCTaAXAPXAAHyIyeKNgo933_640*640.jpg

Run the project often find some of the pictures can not be loaded display,and See some anomalies in log log:
ydh.com.frescodemos W/unknown:BufferedDiskCache﹕ Failed to write to disk-cache for key http://www.sinaimg.cn/dy/slidenews/4_img/2015_12/704_1579346_230297.jpg
    com.facebook.common.file.FileUtils$CreateDirectoryException: /storage/sdcard0/com/ydh/img000
            at com.facebook.common.file.FileUtils.mkdirs(FileUtils.java:45)
            at com.facebook.cache.disk.DefaultDiskStorageSupplier.createRootDirectoryIfNecessary(DefaultDiskStorageSupplier.java:106)
            at com.facebook.cache.disk.DefaultDiskStorageSupplier.createStorage(DefaultDiskStorageSupplier.java:98)
            at com.facebook.cache.disk.DefaultDiskStorageSupplier.get(DefaultDiskStorageSupplier.java:75)
            at com.facebook.cache.disk.DiskStorageCache.createTemporaryResource(DiskStorageCache.java:246)
            at com.facebook.cache.disk.DiskStorageCache.insert(DiskStorageCache.java:287)
            at com.facebook.imagepipeline.cache.BufferedDiskCache.writeToDiskCache(BufferedDiskCache.java:224)
            at com.facebook.imagepipeline.cache.BufferedDiskCache.access$400(BufferedDiskCache.java:38)
            at com.facebook.imagepipeline.cache.BufferedDiskCache$2.run(BufferedDiskCache.java:158)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)

![device-2015-05-21-110909](https://cloud.githubusercontent.com/assets/6265414/7740852/0a04b8e4-ffaa-11e4-8404-c757473b3a34.png)
![device-2015-05-21-110929](https://cloud.githubusercontent.com/assets/6265414/7740853/0c8d78e4-ffaa-11e4-9184-9ad690e09c01.png)

Engineering sample code here to view：https://github.com/liujianying/FrescoDemo

**Comment by michalgr** [comment]
You need to specify WRITE_EXTERNAL_STORAGE permission in your manifest, don't you ? http://developer.android.com/reference/android/Manifest.permission.html#WRITE_EXTERNAL_STORAGE

**Comment by liujianying** [comment]
Yes, indeed the lack of this authority，But after adding the authority is still the same problem exists.
![device-2015-05-22-081225](https://cloud.githubusercontent.com/assets/6265414/7761605/5df839d4-005a-11e5-9484-a7e82789bfee.png)
