### ISSUE TITLE
java.lang.IllegalArgumentException: unknown image format

### ISSUE THREAD

**Issue by ICECHN** [facebook/fresco#321]
url="http://ktvme.com//getshareimage.php?id=1528511&s=1";
Fresco load fail, but Glide, Picasso and Volley  load success.
![qq 20150528100334](https://cloud.githubusercontent.com/assets/11832023/7851366/221b28e2-0521-11e5-9f21-a7ca376ccc31.jpg)

**Comment by cabbage** [comment]
I have the same issue with a JPEG file (http://www.titus.de/product-images/details/3D/Skatewachs/Banana_815739.jpg) 

And I only found out about it, after wondering why this image is not loaded. So I looked for ways to get log output. I added a RequestLoggingListener and got this output:

```
06-12 15:10:03.537   5820     6714   unknown:RequestLog..  W  time 967027485: onProducerFinishWithFailure: {requestId: 128, stage: DecodeProducer, elapsedTime: -1 ms, extraMap: null, throwable: java.lang.IllegalArgumentException: unknown image format}
06-12 15:10:03.537   5820     6714   unknown:RequestLog..  W  time 967027486: onRequestFailure: {requestId: 128, elapsedTime: -1 ms, throwable: java.lang.IllegalArgumentException: unknown image format}
```

**Comment by koptus** [comment]
@cabbage How have you solved that problem?

**Comment by cabbage** [comment]
@koptus 
One way is to get the device's user-agent from the system properties `System.getProperty("http.agent")` 

I know there was an API for this in newer API versions but I'm on vacation and don't have access to the code. You'll have to look this up.

Also, your server must accept the user-agent-string!

**Comment by massimocarli** [comment]
Writing code like this I can see the image without the mentioned problem. Do you have any updates?
```
Uri uri = Uri.parse("http://www.titus.de/product-images/details/3D/Skatewachs/Banana_815739.jpg");
ImageRequest request = ImageRequestBuilder.newBuilderWithSource(uri).build();
DraweeController controller = Fresco.newDraweeControllerBuilder()
                                          .setImageRequest(request)
                                          .build();
mDraweeView.setController(controller);
```

**Comment by cabbage** [comment]
By supplying a proper user agent string (not the default okhttp) I had no problem anymore. 

Maybe they changed the server settings to allow all user agents. Or maybe there were changes in the library. Maybe it happens only with the okhttp image pipeline.

**Comment by massimocarli** [comment]
@cabbage Thanks for you reply.

**Comment by eldk** [comment]
Hello,
I've got intermittent "java.lang.IllegalArgumentException: unknown image format" for some images.
I do not use HttpOK.

Checking apache logs on image server, I found that no request is made by Fresco, thus image is not in disk-cache.

Apache logs :
No log or error log for http://domain.tld/imagefolder/image.jpg

Android logs :
BufferedDiskCache: Did not find image for http://domain.tld/imagefolder/image.jpg in staging area
BufferedDiskCache: Disk cache read forhttp://domain.tld/imagefolder/image.jpg in staging area
BufferedDiskCache: Disk cache miss forhttp://domain.tld/imagefolder/image.jpg in staging area
SkImageDecoder::Factory returned null
BufferedDiskCache: About to write to disk-cache for key  for http://domain.tld/imagefolder/image.jpg
SkImageDecoder::Factory returned null
BufferedDiskCache: Successful disk-cache write for key http://domain.tld/imagefolder/image.jpg
AbstractDraweeController: controller 40c00f68 66: final_failed @ onFailure: failure: java.lang.IllegalArgumentException: unknown image format

Error loading 66
java.lang.IllegalArgumentException: unknown image format
at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:82)
at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:188)
at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:96)
at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:128)
at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
at java.lang.Thread.run(Thread.java:1019)

After that first error, "java.lang.IllegalArgumentException: unknown image format " are thrown on every request. Fresco doesn't try to reload on remote server.

AbstractDraweeController: controller 406ae738 67: final_failed @ onFailure: failure: java.lang.IllegalArgumentException: unknown image format
Error loading 67
 java.lang.IllegalArgumentException: unknown image format
at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:82)
at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:188)
at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:96)
at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:128)
at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
at java.lang.Thread.run(Thread.java:1019)

com.facebook.fresco:fresco:0.8.1 (without+) is used.

Greatings,

Eric

**Comment by cabbage** [comment]
The only advice I can give is to check if your request returns correctly. Maybe you use an HTTP proxy/monitor like [Charles](https://www.charlesproxy.com/) to find out what response you get from the server. If you get a `204 No Content` the server might not accept the user-agent header.

**Comment by eldk** [comment]
Hello,
I will check.

**Comment by eldk** [comment]
Hello,

I've checked with tcpflow :  tcpflow -p -c -i eth0 port 80 | grep -oE '(GET|HEAD) .* HTTP/1.[01]|Host: .*'

I've a GET from my app with Fresco and no log from Apache.

Check the response now.

Eric

**Comment by eldk** [comment]
Hello,

I'm enable to reproduce it for now (nothing changes in the app).
I check responses with TCPFLOW and always have 200 answers.
Get back when circumstances will reproduce it : high load on file server ...
Greatings,
Eric

**Comment by jianyifu** [comment]
Hello,
I have the same issue, I deleted all picture files cached in sdcard path witch I set in fresco,and reload the pictures without any changes in my codes,and it works.So I guess ,if fresco loads image failed uncompletely,when it reloads,it still thow exception the second time,is it a bug?
