### ISSUE TITLE
dalvik.system.PathClassLoader on SM G9250

### ISSUE THREAD

**Issue by hkllzh** [facebook/fresco#322]
# error info
```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file &quot;/data/app/com.bbgz.android.app-1/base.apk&quot;],nativeLibraryDirectories=[/data/app/com.bbgz.android.app-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn&#x27;t find &quot;libmemchunk.so&quot;
	at java.lang.Runtime.loadLibrary(Runtime.java:366)
	at java.lang.System.loadLibrary(System.java:989)
	at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:34)
	at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
	at com.facebook.imagepipeline.memory.NativeMemoryChunk.&lt;clinit&gt;(NativeMemoryChunk.java:36)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
	at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:260)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.&lt;init&gt;(NativePooledByteBufferOutputStream.java:53)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:98)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
	at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:60)
	at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:49)
	at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```

# phone info
```
MODEL=SM-G9250
BOOTLOADER=G9250ZTU1AOE4
BOARD=universal7420
IS_TRANSLATION_ASSISTANT_ENABLED=false
BRAND=samsung
CPU_ABI=arm64-v8a
DISPLAY=LRX22G.G9250ZTU1AOE4
```

**Comment by TarangS** [comment]
Thanks for reporting, This would be fixed in the next release

**Comment by shanus** [comment]
We are seeing this same issue on Galaxy S6 and Nexus 9 devices

**Comment by tyronen** [comment]
I believe 0.5.1 takes care of this. File a new issue if not.
