### ISSUE TITLE
Caused by: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by ixiaoluo** [facebook/fresco#328]
android.view.InflateException: Binary XML file line #10: Error inflating class 
	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at com.blink.academy.fork.ui.fragment.picture.SinglePictureFragment.onCreateView(SinglePictureFragment.java:178)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:953)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1136)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1499)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:488)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
	at com.blink.academy.fork.ui.adapter.viewpager.SinglePictureAdapter.finishUpdate(SinglePictureAdapter.java:60)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1073)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:919)
	at android.support.v4.view.ViewPager$3.run(ViewPager.java:249)
	at android.support.v4.view.ViewPager.completeScroll(ViewPager.java:1766)
	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1901)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1961)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2625)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1770)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2586)
	at android.view.View.dispatchPointerEvent(View.java:8667)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4129)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3995)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3686)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3743)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5813)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5787)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5758)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5903)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5289)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	... 60 more
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 12250012 byte allocation with 3963957 free bytes and 3MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:988)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2620)
	at android.content.res.Resources.loadDrawable(Resources.java:2527)
	at android.content.res.Resources.getDrawable(Resources.java:824)
	at android.content.res.Resources.getDrawable(Resources.java:800)
	at android.content.res.Resources.getDrawable(Resources.java:775)
	at com.facebook.drawee.view.GenericDraweeView.inflateHierarchy(GenericDraweeView.java:238)
	at com.facebook.drawee.view.GenericDraweeView.(GenericDraweeView.java:75)
	at com.facebook.drawee.view.SimpleDraweeView.(SimpleDraweeView.java:58)
	... 63 more
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at com.blink.academy.fork.ui.fragment.picture.SinglePictureFragment.onCreateView(SinglePictureFragment.java:178)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:953)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1136)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1499)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:488)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
	at com.blink.academy.fork.ui.adapter.viewpager.SinglePictureAdapter.finishUpdate(SinglePictureAdapter.java:60)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1073)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:919)
	at android.support.v4.view.ViewPager$3.run(ViewPager.java:249)
	at android.support.v4.view.ViewPager.completeScroll(ViewPager.java:1766)
	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1901)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1961)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2625)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1770)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2586)
	at android.view.View.dispatchPointerEvent(View.java:8667)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4129)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3995)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3686)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3743)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5813)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5787)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5758)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5903)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5289)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 12250012 byte allocation with 3963957 free bytes and 3MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:988)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2620)
	at android.content.res.Resources.loadDrawable(Resources.java:2527)
	at android.content.res.Resources.getDrawable(Resources.java:824)
	at android.content.res.Resources.getDrawable(Resources.java:800)
	at android.content.res.Resources.getDrawable(Resources.java:775)
	at com.facebook.drawee.view.GenericDraweeView.inflateHierarchy(GenericDraweeView.java:238)
	at com.facebook.drawee.view.GenericDraweeView.(GenericDraweeView.java:75)
	at com.facebook.drawee.view.SimpleDraweeView.(SimpleDraweeView.java:58)
	... 63 more
java.lang.OutOfMemoryError: Failed to allocate a 12250012 byte allocation with 3963957 free bytes and 3MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:988)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2620)
	at android.content.res.Resources.loadDrawable(Resources.java:2527)
	at android.content.res.Resources.getDrawable(Resources.java:824)
	at android.content.res.Resources.getDrawable(Resources.java:800)
	at android.content.res.Resources.getDrawable(Resources.java:775)
	at com.facebook.drawee.view.GenericDraweeView.inflateHierarchy(GenericDraweeView.java:238)
	at com.facebook.drawee.view.GenericDraweeView.(GenericDraweeView.java:75)
	at com.facebook.drawee.view.SimpleDraweeView.(SimpleDraweeView.java:58)
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at com.blink.academy.fork.ui.fragment.picture.SinglePictureFragment.onCreateView(SinglePictureFragment.java:178)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:953)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1136)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1499)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:488)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
	at com.blink.academy.fork.ui.adapter.viewpager.SinglePictureAdapter.finishUpdate(SinglePictureAdapter.java:60)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1073)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:919)
	at android.support.v4.view.ViewPager$3.run(ViewPager.java:249)
	at android.support.v4.view.ViewPager.completeScroll(ViewPager.java:1766)
	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1901)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1961)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2625)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1770)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2586)
	at android.view.View.dispatchPointerEvent(View.java:8667)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4129)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3995)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3686)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3743)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5813)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5787)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5758)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5903)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5289)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by TarangS** [comment]
Did I miss something or is the title misleading? 
Please use match_parent instead of fill_parent. 
Also why do you think this is a bug in the DraweeView? Need more details.

**Comment by tyronen** [comment]
Also
- What version of Android are you running?
- What are you passing to the Drawee, as either XML or code? Specifically, what is the placeholder and how large is it?

**Comment by ixiaoluo** [comment]
<com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/header_avatar_sdv"
        android:layout_width="30dp"
        android:layout_height="30dp"
        android:layout_centerVertical="true"
        android:layout_marginLeft="10dp"
        xiaoluo:roundAsCircle="true"
        xiaoluo:roundingBorderWidth="0.5dp"
        xiaoluo:roundingBorderColor="@color/colorLightgray"
        xiaoluo:placeholderImage="@drawable/blank_avatar" />

    <color name="colorLightgray">#CCCCCC</color>
   blank_avatar is blank_avatar.png file (500x500).
   Version of Android is 4.4.2.

**Comment by tyronen** [comment]
Something seems odd about this PNG. The stack trace shows you're trying to allocate a 38 MB placeholder. That works out to a size of 3000 x 3000, not 500 x 500. Can you upload it?

**Comment by plamenko** [comment]
The image requires 12MB and you only have 4MB available.
