### ISSUE TITLE
my app crashed when load libmemchunk.so

### ISSUE THREAD

**Issue by Gerald09** [facebook/fresco#342]
I received many crash reports which are caused by one error: UnsatisfiedLinkError: couldn't find "libmemchunk.so"
Only Android 5.0/5.1 got this crash.

Here is the error message:

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.jianlv.chufaba-2/base.apk"],nativeLibraryDirectories=[/data/app/com.jianlv.chufaba-2/lib/x86_64, /vendor/lib64, /system/lib64]]] couldn't find "libmemchunk.so"
at java.lang.Runtime.loadLibrary(Runtime.java:366)
at java.lang.System.loadLibrary(System.java:988)
at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:34)
at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:36)
at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:260)
at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:98)
at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:60)
at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:49)
at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

**Comment by michalgr** [comment]
64bit libraries are not included in the fresco aars. This is fixed in master.

I think you use some other native libraries as well, and those do have 64bit binaries in your apk. Because of that runtime does not accept fresco's 32bit libs. Can you try compiling and using master rather than aars from maven ?

**Comment by Gerald09** [comment]
@michalgr thank you, I'll try

**Comment by tyronen** [comment]
This should be fixed in v0.5.1. File a new bug if this is not the case.

**Comment by Gerald09** [comment]
@tyronen no crash after use 0.5.1, thank you
