### ISSUE TITLE
null pointer at <init>

### ISSUE THREAD

**Issue by lulumeya** [facebook/fresco#35]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.drawee.view.DraweeHolder.setController(com.facebook.drawee.interfaces.DraweeController)' on a null object reference
	at com.facebook.drawee.view.DraweeView.setImageDrawable(DraweeView.java:140)
	at com.kakao.topic.ui.widget.TopicImageView.setImageDrawable(TopicImageView.java:96)
	at android.widget.ImageView.<init>(ImageView.java:159)
	at android.widget.ImageView.<init>(ImageView.java:140)
	at android.widget.ImageView.<init>(ImageView.java:136)
	at com.facebook.drawee.view.DraweeView.<init>(DraweeView.java:51)
	at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:73)
	at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:58)

I overrided SimpleDraweeView, and used this view in xml.
When I add 'src' attribute, I got this error..
DraweeView.java:140
mDraweeHolder.setController(null);
mDraweeHolder can be null when ImageView class attempting to setImageDrawable in constructor

**Comment by tyronen** [comment]
The `src` attribute in XML is not supported by SimpleDraweeViews. Use the `setImageURI` method instead.
