### ISSUE TITLE
FileNotFoundException - too many open files

### ISSUE THREAD

**Issue by nguyentando** [facebook/fresco#358]
After scrolling for a while, I always get this exception.

java.io.FileNotFoundException: /data/data/com.facebook.samples.comparison/cache/imagepipeline_cache/v2.ols100.1/7/KGXrHIjGegCtOt_4ZX4DzPgJnBg.cnt: open failed: EMFILE (Too many open files)
            at libcore.io.IoBridge.open(IoBridge.java:409)
            at java.io.FileInputStream.<init>(FileInputStream.java:78)
            at com.facebook.binaryresource.FileBinaryResource.openStream(FileBinaryResource.java:36)
            at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:196)
            at com.facebook.imagepipeline.cache.BufferedDiskCache.access$300(BufferedDiskCache.java:38)
            at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:104)
            at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:88)
            at bolts.Task$2.run(Task.java:195)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: libcore.io.ErrnoException: open failed: EMFILE (Too many open files)
            at libcore.io.Posix.open(Native Method)
            at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
            at libcore.io.IoBridge.open(IoBridge.java:393)
            at java.io.FileInputStream.<init>(FileInputStream.java:78)
            at com.facebook.binaryresource.FileBinaryResource.openStream(FileBinaryResource.java:36)
            at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:196)
            at com.facebook.imagepipeline.cache.BufferedDiskCache.access$300(BufferedDiskCache.java:38)
            at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:104)
            at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:88)
            at bolts.Task$2.run(Task.java:195)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)

**Comment by erikandre** [comment]
The amount of file handles that can be open is a global limit for all processes, so it's hard to say if this is a device specific issue or perhaps some other background process causing it.
Closing as there has been no further reports of this.
