### ISSUE TITLE
Unable to render SimpleDraweeView in AndroidStudio UI Builder

### ISSUE THREAD

**Issue by ikravchenko** [facebook/fresco#374]
The following classes could not be instantiated:
- com.facebook.drawee.view.SimpleDraweeView (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE

Stacktrace:
java.lang.NullPointerException
	at com.facebook.drawee.view.DraweeView.setImageDrawable(DraweeView.java:140)
	at android.widget.ImageView.<init>(ImageView.java:148)
	at android.widget.ImageView.<init>(ImageView.java:135)
	at android.widget.ImageView.<init>(ImageView.java:131)
	at com.facebook.drawee.view.DraweeView.<init>(DraweeView.java:51)
	at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:74)
	at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:438)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:155)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:94)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:190)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:214)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:142)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:806)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater_Delegate.parseInclude(LayoutInflater_Delegate.java:154)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:858)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:802)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater_Delegate.parseInclude(LayoutInflater_Delegate.java:154)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:858)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:802)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:809)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:385)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:413)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:321)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:511)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:499)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:888)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:499)
	at com.android.tools.idea.rendering.RenderTask.access$600(RenderTask.java:72)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:611)
	at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:608)
	at com.android.tools.idea.rendering.RenderService.runRenderAction(RenderService.java:363)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:608)
	at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:630)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.doRender(AndroidLayoutPreviewToolWindowManager.java:645)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.access$1700(AndroidLayoutPreviewToolWindowManager.java:80)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7$1.run(AndroidLayoutPreviewToolWindowManager.java:587)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7.run(AndroidLayoutPreviewToolWindowManager.java:582)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
	at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)

**Comment by IanChilds** [comment]
What version are you using? It looks like that was fixed in #23, but that was a long time ago.

**Comment by ikravchenko** [comment]
I am using version 0.5.2. The view in xml looks like this:

        <com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/icon"
        android:layout_width="@dimen/list_picture_width"
        android:layout_height="@dimen/list_picture_height"
        android:layout_centerVertical="true"
        android:layout_marginEnd="16dp"
        android:contentDescription="@string/list_item_image_content_description"
        fresco:placeholderImage="@drawable/placeholder_user_list_entry" />

**Comment by FragShawn** [comment]
Not sure if I'm supposed to say this, but I'm also experiencing this same issue.

**Comment by tyronen** [comment]
I believe this was fixed in v0.8.0.

**Comment by karwagaurav** [comment]
I am facing this issue in  V0.9.0. Please check.
