### ISSUE TITLE
I have problem with use Uri scheme for local app res

### ISSUE THREAD

**Issue by blackiedm** [facebook/fresco#38]
my code:
'Uri uri =  Uri.parse("res://"+getResources().getResourcePackageName(R.raw.local_img));'

error:
'Caused by: com.facebook.imagepipeline.request.ImageRequestBuilder$BuilderException: Invalid request builder: Resource URI path must be a resource id.
            at com.facebook.imagepipeline.request.ImageRequestBuilder.validate(ImageRequestBuilder.java:217)
            at com.facebook.imagepipeline.request.ImageRequestBuilder.build(ImageRequestBuilder.java:188)
            at com.facebook.imagepipeline.request.ImageRequest.fromUri(ImageRequest.java:59)'

**Comment by adiohaion** [comment]
I tried it now, you need to do it as follow:
Uri.parse("res://" + sContext.getResources().getResourcePackageName(id) + "/" + id)

**Comment by blackiedm** [comment]
@adiohaion thanks
