### ISSUE TITLE
ZoomableDraweeView getHierarchy() NPE

### ISSUE THREAD

**Issue by petropavel13** [facebook/fresco#387]
I've just create example project with ZoomableDraweeView (https://github.com/petropavel13/ZoomableFrescoExample) and I got NPE

Layout:
```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    android:paddingBottom="@dimen/activity_vertical_margin"
    tools:context=".MainActivity">

    <com.facebook.samples.zoomable.ZoomableDraweeView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/entry_image_view"
        app:actualImageScaleType="fitCenter"
        app:failureImage="@drawable/ic_error_white_48dp"
        app:progressBarImage="@drawable/ic_autorenew_white_48dp"
        app:progressBarAutoRotateInterval="1000"
        app:retryImage="@drawable/ic_refresh_white_48dp" />

</RelativeLayout>
```

Activity:
```java
package com.github.petropavel13.zoomablefrescoexample;

import android.app.Activity;
import android.net.Uri;
import android.os.Bundle;

import com.facebook.drawee.backends.pipeline.Fresco;
import com.facebook.drawee.controller.AbstractDraweeController;
import com.facebook.samples.zoomable.ZoomableDraweeView;


public class MainActivity extends Activity {

    private ZoomableDraweeView imageView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Fresco.initialize(this);

        setContentView(R.layout.activity_main);

        imageView = (ZoomableDraweeView)findViewById(R.id.entry_image_view);
    }

    @Override
    protected void onResume() {
        super.onResume();

        final AbstractDraweeController controller = Fresco.newDraweeControllerBuilder()
                .setUri(Uri.parse("https://assets-cdn.github.com/images/modules/open_graph/github-octocat.png"))
                .setOldController(imageView.getController())
                .build();

        imageView.setController(controller);
    }
}
```

Trace:
```
06-17 13:54:51.690  16576-16576/com.github.petropavel13.zoomablefrescoexample E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.github.petropavel13.zoomablefrescoexample, PID: 16576
    java.lang.NullPointerException
            at com.facebook.common.internal.Preconditions.checkNotNull(Preconditions.java:210)
            at com.facebook.drawee.view.DraweeHolder.getHierarchy(DraweeHolder.java:251)
            at com.facebook.drawee.view.DraweeView.getHierarchy(DraweeView.java:72)
            at com.facebook.samples.zoomable.ZoomableDraweeView.updateZoomableControllerBounds(ZoomableDraweeView.java:195)
            at com.facebook.samples.zoomable.ZoomableDraweeView.onLayout(ZoomableDraweeView.java:171)
            at android.view.View.layout(View.java:15671)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by IanChilds** [comment]
You need to set a hierarchy first.

**Comment by petropavel13** [comment]
To archive my goal I should copy&paste code from https://github.com/facebook/fresco/blob/master/drawee/src/main/java/com/facebook/drawee/view/GenericDraweeView.java#L83 to ZoomableDraweeView. It's not convenient. Maybe will be possible to reuse this function somehow in future?

**Comment by spapapan** [comment]
I still have the same issue. The problem is when I don't use the View to load any image. If I don't hide it, I get this crash. The problem is that sometimes if you use it inside adapters, it might get shown and you will get a crash for no reason. Is there any other fix for this issue?
