### ISSUE TITLE
When does pipeline recycles a bitmap? (apart after the subscriber has finished executing)

### ISSUE THREAD

**Issue by KashanDanish** [facebook/fresco#388]
The issue I am having is I get the `ClosableImage` from a `DataSource`. Clone it and assign it to my custom `ImageView`. I **do not** recycle the bitmap myself anywhere. But still sometimes I get the following exception while traversing through images in `ViewPager`:
```
    java.lang.IllegalArgumentException: Cannot draw recycled bitmaps
            at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:789)
            at android.view.GLES20RecordingCanvas.drawBitmap(GLES20RecordingCanvas.java:118)
            at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:399)
            at android.widget.ImageView.onDraw(ImageView.java:1008)
            at com.convo.android.ui.widget.ZoomImageView.onDraw(ZoomImageView.java:329)
            at android.view.View.draw(View.java:14180)
            at android.view.View.getDisplayList(View.java:13118)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3006)
            at android.view.View.getDisplayList(View.java:13056)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3006)
            at android.view.View.getDisplayList(View.java:13056)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.View.draw(View.java:13896)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3024)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2893)
            at android.view.View.draw(View.java:14183)
            at android.support.v4.view.ViewPager.draw(ViewPager.java:2176)
            at android.view.View.getDisplayList(View.java:13118)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.View.draw(View.java:13896)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3024)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2893)
            at android.view.View.draw(View.java:14183)
            at android.view.View.getDisplayList(View.java:13118)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.View.draw(View.java:13896)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3024)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2893)
            at android.view.View.getDisplayList(View.java:13116)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.View.draw(View.java:13896)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3024)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2893)
            at android.view.View.getDisplayList(View.java:13116)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.View.draw(View.java:13896)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3024)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2893)
            at android.view.View.draw(View.java:14183)
            at android.view.View.getDisplayList(View.java:13118)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.View.draw(View.java:13896)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3024)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2893)
            at android.view.View.getDisplayList(View.java:13116)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.View.draw(View.java:13896)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3024)
            at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1060)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2893)
            at android.view.View.getDisplayList(View.java:13116)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.View.draw(View.java:13896)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3024)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2893)
            at android.view.View.getDisplayList(View.java:13116)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.View.draw(View.java:13896)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3024)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2893)
            at android.view.View.getDisplayList(View.java:13116)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.View.draw(View.java:13896)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3024)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2893)
            at android.view.View.getDisplayList(View.java:13116)
            at android.view.View.getDisplayList(View.java:13162)
            at android.view.View.draw(View.java:13896)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3024)
            at android.view.ViewG
```
Here is the code:
```
DataSource<CloseableReference<CloseableImage>> dataSourceThumb = Fresco.getImagePipeline().fetchDecodedImage(ImageRequest.fromUri(Uri.parse(thumbUrl)), getActivity().getApplicationContext());
DataSubscriber<CloseableReference<CloseableImage>> dataSubscriberThumb = new BaseDataSubscriber<CloseableReference<CloseableImage>>()
{
    @Override
    public void onNewResultImpl(DataSource<CloseableReference<CloseableImage>> dataSource)
    {
        CloseableReference<CloseableImage> imageReference = dataSource.getResult();
        if ((imageReference != null) )
        {
            try
            {
                if (!originalReady) {
                    CloseableImage image = imageReference.clone().get();
                    final Bitmap bitmap = ((CloseableBitmap) image).getUnderlyingBitmap();
                    thumbIV.post(new Runnable() {
                        public void run() {
                            thumbIV.setImageBitmap(bitmap);
                            placeholder.setVisibility(View.VISIBLE);
                            thumbIV.setVisibility(View.VISIBLE);
                            imageView.setVisibility(View.GONE);
                        }
                    });
                }
            }
            finally
            {
                imageReference.close();
            }
        }
    }

    @Override
    public void onFailureImpl(DataSource dataSource)
    {
    }
};
DataSource<CloseableReference<CloseableImage>> dataSourceImage = Fresco.getImagePipeline().fetchDecodedImage(ImageRequest.fromUri(Uri.parse(imageUrl)), getActivity().getApplicationContext());
DataSubscriber<CloseableReference<CloseableImage>> dataSubscriberImage = new BaseDataSubscriber<CloseableReference<CloseableImage>>()
{
    @Override
    public void onNewResultImpl(DataSource<CloseableReference<CloseableImage>> dataSource)
    {
        CloseableReference<CloseableImage> imageReference = dataSource.getResult();
        if (imageReference != null)
        {
            try
            {
                CloseableImage image = imageReference.clone().get();
                final Bitmap bitmap = ((CloseableBitmap) image).getUnderlyingBitmap();
                if (bitmap.getHeight() < 4096 && bitmap.getWidth() < 4096)
                {
                    imageView.post(new Runnable()
                    {
                        public void run()
                        {
                            imageView.setImageBitmap(bitmap);
                            placeholder.setVisibility(View.GONE);
                            thumbIV.setVisibility(View.GONE);
                            imageView.setVisibility(View.VISIBLE);
                            originalReady = true;
                        }
                    });
                }
                else
                {
                    imageView.post(new Runnable()
                    {
                        public void run()
                        {
                            placeholder.setVisibility(View.GONE);
                        }
                    });
                }
            }
            finally
            {
                imageReference.close();
            }
        }
    }

    @Override
    public void onFailureImpl(DataSource dataSource)
    {
    }
};

dataSourceThumb.subscribe(dataSubscriberThumb, CallerThreadExecutor.getInstance());
dataSourceImage.subscribe(dataSubscriberImage, CallerThreadExecutor.getInstance());
```
I also get this warning sometimes (in case it is related to the issue):
```
W/unknown:CloseableReference﹕ Finalized without closing: 448afec0 43e0c4e0 (type = CloseableStaticBitmap)
```

**Comment by IanChilds** [comment]
You should never do `CloseableImage image = imageReference.clone().get();` When you call `imageReference.clone()` you need to keep a reference to that clone so that you can close it at the correct time (when you no longer need the bitmap). Instead, that clone get finalized and the bitmap gets released before you're finished with it.

**Comment by arlindiDev** [comment]
Does anyone have a solution to this ?
