### ISSUE TITLE
RejectedExecutionException on AbstractDataSource

### ISSUE THREAD

**Issue by EugineKidoz** [facebook/fresco#417]
java.util.concurrent.RejectedExecutionException: Task com.facebook.datasource.AbstractDataSource$1@44967150 rejected from java.util.concurrent.ThreadPoolExecutor@423dbe40[Running, pool size = 5, active threads = 5, queued tasks = 128, completed tasks = 960]
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
at com.facebook.datasource.AbstractDataSource.notifyDataSubscriber(AbstractDataSource.java:172)
at com.facebook.datasource.AbstractDataSource.subscribe(AbstractDataSource.java:155)
at com.kidoz.ui.custom_views.wallpaper_view.WallpaperView.loadWallpaper(WallpaperView.java:75)
at com.kidoz.ui.activities.main_activity.MainActivity$4.onAction(MainActivity.java:463)
at com.kidoz.recievers_and_listeners.UserInterfaceUpdateBroadcastReciever.onReceive(UserInterfaceUpdateBroadcastReciever.java:92)
at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5598)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
at dalvik.system.NativeStart.main(Native Method)

**Comment by plamenko** [comment]
Something is causing executor congestion. We'll take a look.

**Comment by tyronen** [comment]
Actually I am not sure now. How are you calling this data source?
