### ISSUE TITLE
OOM crash even when the space fresco tried to allocate is less than available memory

### ISSUE THREAD

**Issue by KashanDanish** [facebook/fresco#420]
```
java.lang.OutOfMemoryError: Failed to allocate a 14745612 byte allocation with 16777056 free bytes and 23MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
       at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
       at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:260)
       at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.doDecodeStaticImage(ArtBitmapFactory.java:131)
       at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.decodeFromPooledByteBuffer(ArtBitmapFactory.java:84)
       at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.decodeFromPooledByteBuffer(PlatformBitmapFactory.java:87)
       at com.facebook.imagepipeline.decoder.ImageDecoder.decodeStaticImage(ImageDecoder.java:119)
       at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:93)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:166)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$000(DecodeProducer.java:88)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:112)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:109)
       at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:214)
       at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:30)
       at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:68)
       at com.facebook.common.executors.SerialDelegatingExecutor.executeSingleCommand(SerialDelegatingExecutor.java:76)
       at com.facebook.common.executors.SerialDelegatingExecutor.access$000(SerialDelegatingExecutor.java:24)
       at com.facebook.common.executors.SerialDelegatingExecutor$1.run(SerialDelegatingExecutor.java:47)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by plamenko** [comment]
You may have 16MB available in total for your app, but the free space doesn't necessarily have to be continuous. For example, you may have the two free chunks, one of 6MB and the other of 10MB, but you still don't have one continuous chunk of 14MB and the allocation will therefore fail.

**Comment by agustindev** [comment]
@KashanDanish use largeHeap="true" in AndroidManifest.xml, ill solve your problem.

**Comment by starktonys** [comment]
i met the same problem , @agustindev  use  largeHeap="true" , it still occur that problem.
