### ISSUE TITLE
Crash on DraweeView ,version 0.5.2

### ISSUE THREAD

**Issue by somatezyc** [facebook/fresco#426]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.guangquaner/com.guangquaner.activitys.RegisterActivity}: android.view.InflateException: Binary XML file line #249: Error inflating class com.facebook.drawee.view.SimpleDraweeView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2259)
       at android.app.ActivityThread.access$800(ActivityThread.java:149)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
       at android.os.Handler.dispatchMessage(Handler.java:122)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5122)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: android.view.InflateException: Binary XML file line #249: Error inflating class com.facebook.drawee.view.SimpleDraweeView
       at android.view.LayoutInflater.createView(LayoutInflater.java:624)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:700)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
       at android.app.Activity.setContentView(Activity.java:1956)
       at com.guangquaner.activitys.RegisterActivity.onCreate(RegisterActivity.java:76)
       at android.app.Activity.performCreate(Activity.java:5437)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1092)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2173)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2259)
       at android.app.ActivityThread.access$800(ActivityThread.java:149)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
       at android.os.Handler.dispatchMessage(Handler.java:122)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5122)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor._logged_newInstance(Constructor.java:440)
       at android.view.LayoutInflater.createView(LayoutInflater.java:597)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:700)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
       at android.app.Activity.setContentView(Activity.java:1956)
       at com.guangquaner.activitys.RegisterActivity.onCreate(RegisterActivity.java:76)
       at android.app.Activity.performCreate(Activity.java:5437)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1092)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2173)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2259)
       at android.app.ActivityThread.access$800(ActivityThread.java:149)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
       at android.os.Handler.dispatchMessage(Handler.java:122)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5122)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at com.facebook.drawee.view.DraweeView.toString(DraweeView.java:179)
       at java.lang.StringBuilder.append(StringBuilder.java:202)
       at java.util.AbstractCollection.toString(AbstractCollection.java:374)
       at java.util.Formatter.transform(Formatter.java:1421)
       at java.util.Formatter.doFormat(Formatter.java:1081)
       at java.util.Formatter.format(Formatter.java:1042)
       at java.util.Formatter.format(Formatter.java:1011)
       at java.lang.String.format(String.java:2030)
       at java.lang.String.format(String.java:2004)
       at android.droidblaze.ViewPool.findViewsByIdPair(ViewPool.java:88)
       at android.droidblaze.ViewPool.updateView(ViewPool.java:75)
       at android.view.View.onIDChanged(View.java:12461)
       at android.view.View.<init>(View.java:3818)
       at android.widget.ImageView.<init>(ImageView.java:123)
       at android.widget.ImageView.<init>(ImageView.java:119)
       at com.facebook.drawee.view.DraweeView.<init>(DraweeView.java:51)
       at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:74)
       at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:58)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor._logged_newInstance(Constructor.java:440)
       at android.view.LayoutInflater.createView(LayoutInflater.java:597)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:700)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
       at android.app.Activity.setContentView(Activity.java:1956)
       at com.guangquaner.activitys.RegisterActivity.onCreate(RegisterActivity.java:76)
       at android.app.Activity.performCreate(Activity.java:5437)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1092)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2173)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2259)
       at android.app.ActivityThread.access$800(ActivityThread.java:149)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
       at android.os.Handler.dispatchMessage(Handler.java:122)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5122)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by somatezyc** [comment]
#395
