### ISSUE TITLE
android.view.InflateException: Binary XML file line #16: Error inflating class <unknown>

### ISSUE THREAD

**Issue by oubowu** [facebook/fresco#427]
My god,how to solve these?

the bug report:
android.view.InflateException: Binary XML file line #16: Error inflating class <unknown>
	at android.view.LayoutInflater.createView(LayoutInflater.java:669)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:745)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:804)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:812)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:526)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at com.sailvan.dealsale.SearchListActivity$MyAdapter.onCreateViewHolder(SearchListActivity.java:741)
	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:4385)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3700)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3609)
	at android.support.v7.widget.LayoutState.next(LayoutState.java:83)
	at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1380)
	at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:585)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2118)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2415)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at com.sailvan.dealsale.customcontrols.RefreshableView.onLayout(RefreshableView.java:228)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2140)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1886)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1128)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6269)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:561)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5493)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
	at android.view.LayoutInflater.createView(LayoutInflater.java:643)
	... 63 more
Caused by: java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:596)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:832)
	at android.content.res.Resources.loadDrawable(Resources.java:2988)
	at android.content.res.Resources.getDrawable(Resources.java:1558)
	at com.facebook.drawee.view.GenericDraweeView.inflateHierarchy(GenericDraweeView.java:244)
	at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:75)
	at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:58)
	... 66 more
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
	at android.view.LayoutInflater.createView(LayoutInflater.java:643)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:745)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:804)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:812)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:526)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at com.sailvan.dealsale.SearchListActivity$MyAdapter.onCreateViewHolder(SearchListActivity.java:741)
	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:4385)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3700)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3609)
	at android.support.v7.widget.LayoutState.next(LayoutState.java:83)
	at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1380)
	at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:585)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2118)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2415)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at com.sailvan.dealsale.customcontrols.RefreshableView.onLayout(RefreshableView.java:228)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2140)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1886)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1128)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6269)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:561)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5493)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:596)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:832)
	at android.content.res.Resources.loadDrawable(Resources.java:2988)
	at android.content.res.Resources.getDrawable(Resources.java:1558)
	at com.facebook.drawee.view.GenericDraweeView.inflateHierarchy(GenericDraweeView.java:244)
	at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:75)
	at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:58)
	... 66 more
java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:596)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:832)
	at android.content.res.Resources.loadDrawable(Resources.java:2988)
	at android.content.res.Resources.getDrawable(Resources.java:1558)
	at com.facebook.drawee.view.GenericDraweeView.inflateHierarchy(GenericDraweeView.java:244)
	at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:75)
	at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:58)
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
	at android.view.LayoutInflater.createView(LayoutInflater.java:643)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:745)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:804)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:812)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:526)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at com.sailvan.dealsale.SearchListActivity$MyAdapter.onCreateViewHolder(SearchListActivity.java:741)
	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:4385)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3700)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3609)
	at android.support.v7.widget.LayoutState.next(LayoutState.java:83)
	at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1380)
	at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:585)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2118)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2415)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at com.sailvan.dealsale.customcontrols.RefreshableView.onLayout(RefreshableView.java:228)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:15213)
	at android.view.ViewGroup.layout(ViewGroup.java:4793)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2140)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1886)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1128)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6269)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:561)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5493)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
	at dalvik.system.NativeStart.main(Native Method)

the code:
class MyAdapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {
		
		private List<ProductInfo> list;
		private Context mContext;
		private LayoutInflater mInflater;
		private MyItemClickListener mItemClickListener;
		private View view;
		
		public MyAdapter(List<ProductInfo> list,Context mContext) {
			super();

			this.list = list;
			this.mContext = mContext;
			mInflater = LayoutInflater.from(this.mContext);
		}
		
		/**
		 * 设置Item点击监听
		 * 
		 * @param listener
		 */
		public void setOnItemClickListener(MyItemClickListener listener) {
			this.mItemClickListener = listener;
		}

		@Override
		public int getItemCount() {
			return list.size();
		}
		
		public ProductInfo getItem(int position){
			return list.get(position);
		}
		
		public void addMore(List<ProductInfo> moreData){
    		if(moreData!=null && moreData.size()>0)
    		for (int i = 0; i < moreData.size(); i++) {
    			list.add(moreData.get(i));
    		}
    	}
    	
    	public void removeAll(){
    		list.clear();
    	}
    	
		@Override
		public void onBindViewHolder(
				android.support.v7.widget.RecyclerView.ViewHolder viewHolder,
				int i) {
			MyViewHolder holder = (MyViewHolder) viewHolder;
			ProductInfo productInfo = list.get(i);
			
			if(!TextUtils.isEmpty(productInfo.product_main_image_url)){
				holder.icon.setImageURI(Uri.parse(productInfo.product_main_image_url));
			}
			holder.icon.setAspectRatio(1.0f);
//			holder.summary.setText(productInfo.product_name);
			if(!productInfo.flashgo_status.equals("1")){
				holder.endTime.setVisibility(View.GONE);
			}else{
				holder.endTime.setVisibility(View.VISIBLE);
				holder.endTime.setText("Ends at "+productInfo.special_expire_date);
			}
			
			if("0".equals(productInfo.flashgo_status)){
				holder.originalPriceNomal.setVisibility(View.VISIBLE);
				holder.originalPrice.setVisibility(View.GONE);
				holder.barginPrice.setVisibility(View.GONE);
				holder.originalPriceNomal.setText(productInfo.product_price_text);
			}else{
				holder.originalPriceNomal.setVisibility(View.GONE);
				holder.originalPrice.setVisibility(View.VISIBLE);
				holder.barginPrice.setVisibility(View.VISIBLE);
				holder.originalPrice.setText(productInfo.product_price_text);
				holder.barginPrice.setText(productInfo.product_spec_price_text);
			}
		}

		@Override
		public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup viewGroup,
				int i) {
			view = mInflater.inflate(R.layout.item_search_list_gridview,
					viewGroup, false);
			return new MyViewHolder(view, mItemClickListener);
		}
		
		class MyViewHolder extends RecyclerView.ViewHolder{
			private MyItemClickListener mListener;
			
			TextView barginPrice, originalPrice, endTime,originalPriceNomal;
			SimpleDraweeView icon;
			
			public MyViewHolder(View itemView, MyItemClickListener listener) {
				super(itemView);
				icon = (SimpleDraweeView) view.findViewById(R.id.iv_search_img);
				//summary = (TextView) findViewById(R.id.tv_goods_summary);
				barginPrice = (TextView) view.findViewById(R.id.tv_search_goods_bargain_price);
				originalPrice = (TextView) view.findViewById(R.id.tv_search_goods_original_price);
				endTime = (TextView) view.findViewById(R.id.tv_home_goods_end_time);
				originalPriceNomal = (TextView) view.findViewById(R.id.tv_original_price);
				
				this.mListener = listener;
				icon.setOnClickListener(new OnClickListener() {
					
					@Override
					public void onClick(View v) {
						if (mListener != null) {
							switch (v.getId()) {
							case R.id.iv_search_img:
								DebugLog.i("getAdapterPosition()"+getAdapterPosition()+"was clicked");
								mListener.onItemClick(v, getAdapterPosition());
								break;
							default:
								break;
							}
						}
					}
				});
			}

		}
		
	}

**Comment by plamenko** [comment]
The inflation fails because the app is running out of memory. You need to track down the real cause of the memory leaks.
Just to narrow down the issue, are you still getting these errora if you remove the `holder.icon.setImageURI(...)` line? (Note, you won't see the images after that, but that's expected.)
