### ISSUE TITLE
UnsatisfiedLinkError - Sometimes application get crashed due to imagepipeline

### ISSUE THREAD

**Issue by swatigoel** [facebook/fresco#429]
Please find logs collected after app crashed:

java.lang.UnsatisfiedLinkError: Couldn't load memchunk from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ms.officechat-1.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]: findLibrary returned null
       at java.lang.Runtime.loadLibrary(Runtime.java:355)
       at java.lang.System.loadLibrary(System.java:525)
       at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:34)
       at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
       at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:36)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:260)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:98)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:198)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.access$300(BufferedDiskCache.java:38)
       at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:104)
       at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:88)
       at bolts.Task$2.run(Task.java:195)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)

**Comment by plamenko** [comment]
Do you get random crashes for the same build, or?

**Comment by swatigoel** [comment]
yes, We get this crash random. 
When we use application for long time, we get below warning message frequently:

W/unknown:CloseableReference(9817): Finalized without closing: 42074080 42073f98 (type = NativePooledByteBuffer)

**Comment by michalgr** [comment]
`W/unknown:CloseableReference` is not related to UnsatisfiedLinkError.

I need more details to help with the crash:
- does this happen on particular devices or all devices ? What is the architecture of processor (x86, armv7, 64bit) ?
- is os version relevant ?
- what version of Fresco do you use ?

**Comment by agoodcoolman** [comment]
I get same problem.

1.it's happen all devices, 
2.Fresco version 0.6.0

**Comment by michalgr** [comment]
@agoodcoolman : do you use proguard ? does it happen all the time or sporadically ? Have you seen https://github.com/facebook/fresco/issues/172 and https://github.com/facebook/fresco/issues/105 ?

**Comment by Ctrl-Space** [comment]
`java.lang.UnsatisfiedLinkError: Couldn't load ***JNI from loader dalvik.system.PathClassLoader`
I also met this problem 
and didn't use proguard.
it happen all the time when App launch.
Fresco 0.6.0

**Comment by agoodcoolman** [comment]
get, it's work.

**Comment by swatigoel** [comment]
Hello @agoodcoolman can you please tell me how this is fixed for you?
I am building my app with fresco versiob 0.6.0+ using android studio.

But app crashed on GalaxyNexus(4.2.2) and Motorola(4.0.4)

In android studio, there are no folder for amreabi

**Comment by agoodcoolman** [comment]
sorry, I hava forgot it. maybe you need create a file be named armeabi-v7a in libs, 





At 2015-09-02 17:38:12, "Swati Goel" <notifications@github.com> wrote:


Hello @agoodcoolman can you please tell me how this is fixed for you?
I am building my app with fresco versiob 0.6.0+ using android studio.

But app crashed on GalaxyNexus(4.2.2) and Motorola(4.0.4)

In android studio, there are no folder for amreabi

**Comment by swatigoel** [comment]
I have fixed it using eclipse. In fresco project, put all .so file in armeabi-v7a folder.
.so file I got from 0.5.3 versions.
