### ISSUE TITLE
AndroidStudio  Setting proguard-rules.pro  run error

### ISSUE THREAD

**Issue by DukeLee1989** [facebook/fresco#433]
###  I added these proguard:
-keep @com.facebook.common.internal.DoNotStrip class *
-keepclassmembers class * {
    @com.facebook.common.internal.DoNotStrip *;
}

-keepclassmembers class * {
    native <methods>;
}
-dontwarn okio.**
-dontwarn javax.annotation.**

###  error log:
 Process: com.accumulation.lee.androidaccumulationproject, PID: 24061
    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.accumulation.lee.androidaccumulationproject-2/lib/arm/libgifimage.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:371)
            at java.lang.System.loadLibrary(System.java:989)
            at com.facebook.c.j.b.a(Unknown Source)
            at com.facebook.c.j.a.a(Unknown Source)
            at com.facebook.imagepipeline.gif.GifImage.g(Unknown Source)
            at com.facebook.imagepipeline.gif.GifImage.a(Unknown Source)
            at com.facebook.imagepipeline.a.b.c.a(Unknown Source)
            at com.facebook.imagepipeline.g.a.a(Unknown Source)
            at com.facebook.imagepipeline.g.a.a(Unknown Source)
            at com.facebook.imagepipeline.j.t.c(Unknown Source)
            at com.facebook.imagepipeline.j.t.a(Unknown Source)
            at com.facebook.imagepipeline.j.u.a(Unknown Source)
            at com.facebook.imagepipeline.j.u.a(Unknown Source)
            at com.facebook.imagepipeline.j.al.e(Unknown Source)
            at com.facebook.imagepipeline.j.al.a(Unknown Source)
            at com.facebook.imagepipeline.j.am.run(Unknown Source)
            at com.facebook.c.c.i.b(Unknown Source)
            at com.facebook.c.c.i.a(Unknown Source)
            at com.facebook.c.c.j.run(Unknown Source)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

Can I also add a little something？

**Comment by DukeLee1989** [comment]
I found solution #232
