### ISSUE TITLE
Jpeg use progressive render throw exception

### ISSUE THREAD

**Issue by KrystalJake1989** [facebook/fresco#440]
7940-9319/? E/unknown:JfifUtil﹕ 2a4996f5: getDimensions
    java.io.IOException: no more bytes
            at com.facebook.imageutils.StreamProcessor.readPackedInt(StreamProcessor.java:34)
            at com.facebook.imageutils.JfifUtil.moveToMarker(JfifUtil.java:129)
            at com.facebook.imageutils.JfifUtil.getDimensions(JfifUtil.java:100)
            at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer.setEncodedImageMetaData(AddImageTransformMetaDataProducer.java:64)
            at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer.access$100(AddImageTransformMetaDataProducer.java:28)
            at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:53)
            at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:40)
            at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onNextResult(MultiplexProducer.java:442)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:499)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:496)
            at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
            at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$1.onNewResultImpl(EncodedMemoryCacheProducer.java:88)
            at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$1.onNewResultImpl(EncodedMemoryCacheProducer.java:83)
            at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
            at com.facebook.imagepipeline.producers.DiskCacheProducer$DiskCacheConsumer.onNewResultImpl(DiskCacheProducer.java:184)
            at com.facebook.imagepipeline.producers.DiskCacheProducer$DiskCacheConsumer.onNewResultImpl(DiskCacheProducer.java:165)
            at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
            at com.facebook.imagepipeline.producers.NetworkFetchProducer.notifyConsumer(NetworkFetchProducer.java:167)
            at com.facebook.imagepipeline.producers.NetworkFetchProducer.maybeHandleIntermediateResult(NetworkFetchProducer.java:145)
            at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:104)
            at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:37)
            at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:72)
            at com.koudai.weidian.buyer.image.imagefetcher.WeiDianNetworkFetcher$1.run(WeiDianNetworkFetcher.java:74)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by jalpesh** [comment]
@KrystalJake1989 , Did you find any workaround for it? Am getting the same issue.

**Comment by CrystalJake** [comment]
@jalpesh , you must make your jpeg image support progressive，because fresco will read some byte to judge whether your jpeg is a progressive jpeg.

**Comment by hejie** [comment]
java.io.IOException: no more bytes
            at com.facebook.imageutils.StreamProcessor.readPackedInt(StreamProcessor.java:34)

**Comment by hejie** [comment]
http://cdnweb.b5m.com/web/cmsphp/wapcategory/201507/fd4d1cc737015132123.jpg

Loading a JPG picture is the following error, but it is not a picture of each JPG will have this error, sometimes you can see the picture shows up but quickly disappeared, print log, I hope to get help, thanks very much.


java.io.IOException: no more bytes
            at com.facebook.imageutils.StreamProcessor.readPackedInt(StreamProcessor.java:34)
            at com.facebook.imageutils.JfifUtil.moveToMarker(JfifUtil.java:129)
            at com.facebook.imageutils.JfifUtil.getDimensions(JfifUtil.java:100)
            at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:75)
            at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:46)
            at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onNextResult(MultiplexProducer.java:440)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:487)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:484)
            at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
            at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$1.onNewResultImpl(EncodedMemoryCacheProducer.java:83)
            at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$1.onNewResultImpl(EncodedMemoryCacheProducer.java:78)
            at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
            at com.facebook.imagepipeline.producers.DiskCacheProducer$DiskCacheConsumer.onNewResultImpl(DiskCacheProducer.java:186)
            at com.facebook.imagepipeline.producers.DiskCacheProducer$DiskCacheConsumer.onNewResultImpl(DiskCacheProducer.java:165)
            at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
            at com.facebook.imagepipeline.producers.NetworkFetchProducer.notifyConsumer(NetworkFetchProducer.java:165)
            at com.facebook.imagepipeline.producers.NetworkFetchProducer.maybeHandleIntermediateResult(NetworkFetchProducer.java:146)
            at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:105)
            at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:36)
            at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:73)
            at com.facebook.imagepipeline.backends.okhttp.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:117)
            at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

**Comment by plamenko** [comment]
Investigating...

**Comment by drschilling** [comment]
Any news about this issue? Having the same problem.

**Comment by hejie** [comment]
I'm sorry, I haven't been. You have solved it.

2015-09-15 4:53 GMT+08:00 drschilling <notifications@github.com>:

> Any news about this issue? Having the same problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/fresco/issues/440#issuecomment-140202942>.
>



-- 
内容：

*顺  祝  工  作  顺  利!*


*研发部     何杰*

*电话：**18667168171          **邮编：**200081*

**Comment by tyronen** [comment]
This was likely fixed in 0.6.0 or even earlier.
