### ISSUE TITLE
Fresco initialise NullPointerException

### ISSUE THREAD

**Issue by alhennessey92** [facebook/fresco#444]
Getting a NullPointerException on my 
```
Fresco.initialize(context);
```
Not sure why as i am initialising it in the onCreate
```java
@Override
    public void onCreate() {
        Fresco.initialize(context);
        super.onCreate();
        mInstance = this;

}
```
Here is the Logcat error
```
14972-14972/co.alapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: co.alapp, PID: 14972
    java.lang.RuntimeException: Unable to create application co.alapp.volley.AppController: java.lang.NullPointerException
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5010)
            at android.app.ActivityThread.access$1600(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5832)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
     Caused by: java.lang.NullPointerException
            at com.facebook.common.internal.Preconditions.checkNotNull(Preconditions.java:210)
            at com.facebook.imagepipeline.core.ImagePipelineConfig$Builder.<init>(ImagePipelineConfig.java:301)
            at com.facebook.imagepipeline.core.ImagePipelineConfig$Builder.<init>(ImagePipelineConfig.java:278)
            at com.facebook.imagepipeline.core.ImagePipelineConfig.newBuilder(ImagePipelineConfig.java:275)
            at com.facebook.imagepipeline.core.ImagePipelineFactory.initialize(ImagePipelineFactory.java:68)
            at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:32)
            at co.epicapp.epic.volley.AppController.onCreate(AppController.java:32)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5007)
            at android.app.ActivityThread.access$1600(ActivityThread.java:172)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5832)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
```

**Comment by michalgr** [comment]
Can you provide more code ? Are you sure that context is not null ?

**Comment by alfredmack** [comment]
Fresco should be initialized before 'setContentView' in oncreate method

**Comment by alhennessey92** [comment]
Hi, sorry its my mistake i set the context as context rather than ```this
