### ISSUE TITLE
Exception in SecureHashUtil initializer when building with Maven

### ISSUE THREAD

**Issue by droidwolf** [facebook/fresco#451]
ANDROID VERSION4.1.1、DEVICEU705T

```
java.lang.ExceptionInInitializerError
       at com.facebook.cache.disk.DiskStorageCache.getResourceId(DiskStorageCache.java:626)
       at com.facebook.cache.disk.DiskStorageCache.getResource(DiskStorageCache.java:197)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:185)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.access$300(BufferedDiskCache.java:38)
       at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:104)
       at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:88)
       at bolts.Task$2.run(Task.java:195)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=16
       at com.facebook.common.util.SecureHashUtil.<clinit>(SecureHashUtil.java:76)
       at com.facebook.cache.disk.DiskStorageCache.getResourceId(DiskStorageCache.java:626)
       at com.facebook.cache.disk.DiskStorageCache.getResource(DiskStorageCache.java:197)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(BufferedDiskCache.java:185)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.access$300(BufferedDiskCache.java:38)
       at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:104)
       at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(BufferedDiskCache.java:88)
       at bolts.Task$2.run(Task.java:195)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
```

**Comment by michalgr** [comment]
Do you build fresco from source or do you use aars ? Which fresco version do you use ? This bug looks suspicious. Exception is thrown in static initializer that initializes static array of 16 elements. I don't know why it tries to access 16th element of 0-length array. It should be another way around - array should have 16 elements and elements 0-15 should be accessed after the array is created. It looks as if 2 bytes are swapped in byte code. If you use aar, can you try redownloading and building once again ?

**Comment by droidwolf** [comment]
fresco 0.5.0。I use maven.

**Comment by oprisnik** [comment]
I assume that the problem has been fixed with newer Fresco versions. Please let us know if you're still experiencing this issue.
