### ISSUE TITLE
ClassCastException in memory cache

### ISSUE THREAD

**Issue by droidwolf** [facebook/fresco#456]
```
java.lang.ClassCastException: com.facebook.imagepipeline.cache.CountingMemoryCache$Entry cannot be cast to com.facebook.imagepipeline.image.CloseableImage
       at com.facebook.imagepipeline.cache.BitmapCountingMemoryCacheFactory$1.getSizeInBytes(BitmapCountingMemoryCacheFactory.java:23)
       at com.facebook.imagepipeline.cache.CountingLruMap.getValueSizeInBytes(CountingLruMap.java:133)
       at com.facebook.imagepipeline.cache.CountingLruMap.put(CountingLruMap.java:97)
       at com.facebook.imagepipeline.cache.CountingMemoryCache.maybeAddToExclusives(CountingMemoryCache.java:224)
       at com.facebook.imagepipeline.cache.CountingMemoryCache.releaseClientReference(CountingMemoryCache.java:213)
       at com.facebook.imagepipeline.cache.CountingMemoryCache.access$000(CountingMemoryCache.java:44)
       at com.facebook.imagepipeline.cache.CountingMemoryCache$2.release(CountingMemoryCache.java:202)
       at com.facebook.common.references.SharedReference.deleteReference(SharedReference.java:211)
       at com.facebook.common.references.CloseableReference.close(CloseableReference.java:146)
       at com.facebook.common.references.CloseableReference.closeSafely(CloseableReference.java:265)
       at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:217)
       at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:30)
       at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:68)
       at com.facebook.common.executors.SerialDelegatingExecutor.executeSingleCommand(SerialDelegatingExecutor.java:76)
       at com.facebook.common.executors.SerialDelegatingExecutor.access$000(SerialDelegatingExecutor.java:24)
       at com.facebook.common.executors.SerialDelegatingExecutor$1.run(SerialDelegatingExecutor.java:47)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)
```

**Comment by oprisnik** [comment]
I assume that the problem has been resolved. Please let us know if you're still experiencing this issue.
