### ISSUE TITLE
java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by droidwolf** [facebook/fresco#457]
java.util.concurrent.TimeoutException: com.facebook.common.references.CloseableReference.finalize() timed out after 10 seconds
       at com.facebook.common.references.CloseableReference.finalize(CloseableReference.java:200)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:187)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
       at java.lang.Thread.run(Thread.java:841)

**Comment by michalgr** [comment]
I see you are reporting a lot of Lollipop related issues. Obvious bug here is the fact that there is a memory leak. Finalizer timeout itself, however, has most likely nothing to do with Fresco. I am pretty sure you also see timeouts related to finalizing instances of other classes as well.

Memory leak is a bug, so let's fix it. Let me know how you use fresco. Do you use DraweeView ? What is the container view ? (ListView, ScrollView, something custom ?)

**Comment by IanChilds** [comment]
No reply, reaping
