### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by droidwolf** [facebook/fresco#459]
java.lang.StringIndexOutOfBoundsException: length=7600418; index=1107299640
       at java.lang.String.indexAndLength(String.java:589)
       at java.lang.String.codePointAt(String.java:1873)
       at com.facebook.common.references.CloseableReference.closeSafely(CloseableReference.java:265)
       at com.facebook.imagepipeline.memory.NativePooledByteBuffer.close(NativePooledByteBuffer.java:93)
       at com.facebook.cache.disk.DiskStorageCache.insert(DiskStorageCache.java:289)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.writeToDiskCache(BufferedDiskCache.java:224)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.access$400(BufferedDiskCache.java:38)
       at com.facebook.imagepipeline.cache.BufferedDiskCache$2.run(BufferedDiskCache.java:158)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)

**Comment by michalgr** [comment]
This does not seem to be legit stack trace: https://github.com/facebook/fresco/blob/96d74f385b297f364db1f719dd6ee61fc380d0d4/fbcore/src/main/java/com/facebook/common/references/CloseableReference.java#L265 there is no String operation in this line
