### ISSUE TITLE
NoClassDefFoundError on ImagePipelineConfig

### ISSUE THREAD

**Issue by swolfand** [facebook/fresco#467]
**Stack Trace**

07-16 09:20:45.291    7136-7136/ E/dalvikvm﹕ Could not find class 'com.facebook.drawee.backends.pipeline.PipelineDraweeControllerBuilderSupplier', referenced from method com.facebook.drawee.backends.pipeline.Fresco.initializeDrawee
07-16 09:20:45.291    7136-7136/ E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process:  PID: 7136
    java.lang.NoClassDefFoundError: com.facebook.imagepipeline.core.ImagePipelineFactory
            at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:32)
            at com.onCreate(CampusConnectApplication.java:30)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)
            at android.app.ActivityThread.access$1500(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

**Application class**

    public class CampusConnectApplication extends Application {
    @Override
    public void onCreate() {

        Stetho.initialize(
                Stetho.newInitializerBuilder(this)
                        .enableDumpapp(
                                Stetho.defaultDumperPluginsProvider(this))
                        .enableWebKitInspector(
                                Stetho.defaultInspectorModulesProvider(this))
                        .build());
        super.onCreate();
        new Prefs.Builder()
                .setContext(this)
                .setMode(ContextWrapper.MODE_PRIVATE)
                .setPrefsName(getPackageName())
                .setUseDefaultSharedPreference(true)
                .build();
        Fresco.initialize(this);
    }
}

**Device Specs**
![device-2015-07-16-092910](https://cloud.githubusercontent.com/assets/3825893/8723645/3d09d52a-2b9d-11e5-8164-b75726c8c4f7.png)

**Comment by michalgr** [comment]
Does your app have multiple dex files ? If yes, do you follow all steps listed here: https://developer.android.com/tools/building/multidex.html ?

**Comment by IanChilds** [comment]
No reply, reaping

**Comment by EricMo** [comment]
Yes,You must open MultiDex.
