### ISSUE TITLE
After Update to Fresco 0.6.0 Repeating Crash Occurs

### ISSUE THREAD

**Issue by EugineKKK** [facebook/fresco#477]
java.lang.OutOfMemoryError: Failed to allocate a 5038860 byte allocation with 3461756 free bytes and 3MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
	at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
	at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
	at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.createBitmap(ArtBitmapFactory.java:78)
	at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.createBitmap(PlatformBitmapFactory.java:51)
	at com.facebook.imagepipeline.request.BasePostprocessor.process(BasePostprocessor.java:50)
	at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.postprocessInternal(PostprocessorProducer.java:252)
	at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.doPostprocessing(PostprocessorProducer.java:220)
	at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer.access$600(PostprocessorProducer.java:78)
	at com.facebook.imagepipeline.producers.PostprocessorProducer$PostprocessorConsumer$2.run(PostprocessorProducer.java:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by IanChilds** [comment]
On Art, bitmaps are allocated on the java heap, and it looks like this is causing you to OOM. Perhaps this is because you are now caching the postprocessed bitmaps too, so you are using more memory? It looks like the postprocessed image is 5MB, does it need to be that big or could you resize the original image first?
