### ISSUE TITLE
java.lang.NoClassDefFoundError caused by fbcore

### ISSUE THREAD

**Issue by chunyong1991** [facebook/fresco#491]
Good day, I encountered error below at the starting of my app after include fresco by gradle

=========
java.lang.NoClassDefFoundError: com.company.app.customFragment$11
            at com.company.app.customFragment.<init>(customFragment.java:830)
            at java.lang.Class.newInstanceImpl(Native Method)
            at java.lang.Class.newInstance(Class.java:1208)
            at android.support.v4.app.Fragment.instantiate(Fragment.java:421)
            at android.support.v4.app.Fragment.instantiate(Fragment.java:396)
            at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2162)
            at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:300)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
===========

After remove and re-import the libs of fresco one by one, I found out that this issue only occurs at the presence of fbcore.jar.

I tried to run the app without importing fbcore.jar, but imagepipeline call some method from it, so the app still crash when navigate to activity that implements fresco.

Any ideas ?

Any kind of help is much appreciated, thank you.

==============

In addition, this issue does not happens on my Nexus5 (5.1.1), but it happens on all other devices 
PS :  All other devices running Android version lower than 5.0

**Comment by chunyong1991** [comment]
This issue is caused by 65k references limit, nothing to do with fresco, thank you.
