### ISSUE TITLE
sample comparison error

### ISSUE THREAD

**Issue by danhantao** [facebook/fresco#493]
07-25 03:08:37.265  28158-28518/com.facebook.samples.comparison E/unknown:JfifUtil﹕ 2e0867cb: getDimensions
    java.io.IOException: no more bytes
            at com.facebook.imageutils.StreamProcessor.readPackedInt(StreamProcessor.java:34)
            at com.facebook.imageutils.JfifUtil.moveToMarker(JfifUtil.java:129)
            at com.facebook.imageutils.JfifUtil.getDimensions(JfifUtil.java:100)
            at com.facebook.imagepipeline.image.EncodedImage.parseMetaData(EncodedImage.java:285)
            at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:46)
            at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer$AddImageTransformMetaDataConsumer.onNewResultImpl(AddImageTransformMetaDataProducer.java:32)
            at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.onNextResult(MultiplexProducer.java:442)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:499)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$ForwardingConsumer.onNewResultImpl(MultiplexProducer.java:496)
            at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
            at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$1.onNewResultImpl(EncodedMemoryCacheProducer.java:88)
            at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer$1.onNewResultImpl(EncodedMemoryCacheProducer.java:83)
            at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
            at com.facebook.imagepipeline.producers.DiskCacheProducer$DiskCacheConsumer.onNewResultImpl(DiskCacheProducer.java:184)
            at com.facebook.imagepipeline.producers.DiskCacheProducer$DiskCacheConsumer.onNewResultImpl(DiskCacheProducer.java:165)
            at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
            at com.facebook.imagepipeline.producers.NetworkFetchProducer.notifyConsumer(NetworkFetchProducer.java:167)
            at com.facebook.imagepipeline.producers.NetworkFetchProducer.maybeHandleIntermediateResult(NetworkFetchProducer.java:145)
            at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:104)
            at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:37)
            at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:72)
            at com.facebook.imagepipeline.backends.okhttp.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:117)
            at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by hejie** [comment]
Loading a JPG picture is the following error, but it is not a picture of each JPG will have this error, sometimes you can see the picture shows up but quickly disappeared

**Comment by tyronen** [comment]
Fixed in 0.6.1.
