### ISSUE TITLE
Error after adding Fresco dependency

### ISSUE THREAD

**Issue by Aurintas** [facebook/fresco#516]
After adding Fresco dependency and when compiling an app, I'm getting this error:

	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)
	com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:168)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)
	at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:277)
	UNEXPECTED TOP-LEVEL EXCEPTION:
	at com.android.dx.command.Main.main(Main.java:106)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	Error:Execution failed for task ':app:dexDebug'.
	> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: 	Process 'command 'C:\Program Files\Java\jdk1.7.0_71\bin\java.exe'' finished with non-zero exit value 2

How can I fix it?

**Comment by plamenko** [comment]
Please take a look at https://developer.android.com/tools/building/multidex.html
