### ISSUE TITLE
Resources not being closed

### ISSUE THREAD

**Issue by ewills** [facebook/fresco#517]
I'm getting lots of errors when using strict mode:

A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:184)
            at java.io.FileInputStream.<init>(FileInputStream.java:80)
            at com.facebook.imagepipeline.producers.LocalFetchProducer$3.get(LocalFetchProducer.java:128)
            at com.facebook.imagepipeline.producers.LocalFetchProducer$3.get(LocalFetchProducer.java:124)
            at com.facebook.imagepipeline.image.EncodedImage.getInputStream(EncodedImage.java:145)
            at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:73)
            at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:56)
            at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

**Comment by tyronen** [comment]
Fixed in 0.6.1

**Comment by ewills** [comment]
Great!
