### ISSUE TITLE
NativeMemoryChunk   NoClassDefError

### ISSUE THREAD

**Issue by droidekas** [facebook/fresco#540]
This occurs in lower memory phones. The stacktrace is

```
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(SourceFile:60)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(SourceFile:22)
       at com.facebook.imagepipeline.memory.BasePool.get(SourceFile:260)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.(SourceFile:53)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(SourceFile:98)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(SourceFile:26)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.readFromDiskCache(SourceFile:198)
       at com.facebook.imagepipeline.cache.BufferedDiskCache.access$300(SourceFile:38)
       at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(SourceFile:104)
       at com.facebook.imagepipeline.cache.BufferedDiskCache$1.call(SourceFile:88)
       at bolts.Task$2.run(SourceFile:195)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)
```

**Comment by michalgr** [comment]
I see. It is most likely because android failed to load native library backing NativeMemoryChunk (libmemchunk.so). Are you able to reproduce this reliably ?

**Comment by michalgr** [comment]
Could you check what is the content of lib subdirectory of your's app directory under /data/ when this happens ?

**Comment by tyronen** [comment]
This is likely the same issue as #429. The solution is to make sure the .so files are in the correct directory. If it's low-end phones, they may need to be in armeabi, not armeabi-v7a.

**Comment by ziad-halabi9** [comment]
We are getting crashes with the same stacktrace mainly on low end devices with OS 4.1.1 and 4.1.2. Regarding your proposed solution to have the .so files in the armeabi directory, I checked and found that the "libbitmaps.so", "libimagepipline.so" and "libmemchunk.so" are found in all the following folders: arm64-v8a, armeabi, armeabi-v7a, x86, x86_64. And yet the crash is still occurring. We are developing using android studio and using Fresco 0.10.0. Please elaborate more on the solution. Thank you.

**Comment by shangcongrong** [comment]
I also have this problem.But I found that phenomenon, when I use Fresco load local file and this file encoded with MD5, like this:"/mnt/sdcard/xxx/7di9tw8yj66op0wp12x61lmt4" . This happened in some special mobile ,like HUAWEI. I tried some method ,such as put so into armeabi ,or use "SoLoaderShim.loadLibrary" and so on ,but it didn't solve this problem .When I change MD5 encode to use hashcode or not encode ,this phenomenon didn't happened.But I don't know weather really solve this problem.

**Comment by saantiaguilera** [comment]
I have also ocurrences of this bug, unfortunately I cant tell how the users reproduce it (although I do have a stacktrace and info about the devices).

Most ocurrences are in:

- HTC One S
- HTC One X

Stack trace

```
java.lang.NoClassDefFoundError: com/facebook/imagepipeline/memory/NativeMemoryChunk
        at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
        at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
        at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
        at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
        at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:141)
        at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:26)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:94)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:37)
        at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:72)
        at com.facebook.imagepipeline.backends.okhttp3.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:122)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
        at java.lang.Thread.run(Thread.java:864)
```

All occurences where in android 4.1.1 (and really really few in 4.2.2)

**Comment by lambdapioneer** [comment]
@shangcongrong This seems unrelated. The paths of the image to load should not affect the loading of `.so` files. Have you followed the instructions on http://frescolib.org/docs/index.html, http://frescolib.org/docs/getting-started.html and http://frescolib.org/docs/proguard.html? Do you see the same problem when building and running the sample apps in your local setup?
