### ISSUE TITLE
java.lang.NoSuchFieldError: STROKE Bug

### ISSUE THREAD

**Issue by EugineKidoz** [facebook/fresco#546]
```
java.lang.NoSuchFieldError: STROKE
at com.facebook.drawee.drawable.RoundedBitmapDrawable.<init>(RoundedBitmapDrawable.java:61)
at com.facebook.drawee.drawable.RoundedBitmapDrawable.fromBitmapDrawable(RoundedBitmapDrawable.java:73)
at com.facebook.drawee.generic.GenericDraweeHierarchy.maybeApplyRoundingBitmapOnly(GenericDraweeHierarchy.java:353)
at com.facebook.drawee.generic.GenericDraweeHierarchy.setImage(GenericDraweeHierarchy.java:445)
at com.facebook.drawee.controller.AbstractDraweeController.onNewResultInternal(AbstractDraweeController.java:467)
at com.facebook.drawee.controller.AbstractDraweeController.access$000(AbstractDraweeController.java:47)
at com.facebook.drawee.controller.AbstractDraweeController$1.onNewResultImpl(AbstractDraweeController.java:413)
at com.facebook.datasource.BaseDataSubscriber.onNewResult(BaseDataSubscriber.java:43)
at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:181)
at com.facebook.common.executors.UiThreadImmediateExecutorService.execute(UiThreadImmediateExecutorService.java:40)
at com.facebook.datasource.AbstractDataSource.notifyDataSubscriber(AbstractDataSource.java:172)
at com.facebook.datasource.AbstractDataSource.subscribe(AbstractDataSource.java:155)
at com.facebook.drawee.controller.AbstractDraweeController.submitRequest(AbstractDraweeController.java:429)
at com.facebook.drawee.controller.AbstractDraweeController.onAttach(AbstractDraweeController.java:332)
at com.facebook.drawee.view.DraweeHolder.attachController(DraweeHolder.java:276)
at com.facebook.drawee.view.DraweeHolder.setController(DraweeHolder.java:222)
at com.facebook.drawee.view.DraweeView.setController(DraweeView.java:87)
```

**Comment by michalgr** [comment]
Thanks for reporting.

It seems that exception is thrown here: https://github.com/facebook/fresco/blob/master/drawee/src/main/java/com/facebook/drawee/drawable/RoundedBitmapDrawable.java#L61. According to the documentation Paint.Style.STROKE is available since API level 1 (http://developer.android.com/reference/android/graphics/Paint.Style.html). This looks suspicious.

Can you tell us which Android version do you run when you hit this issue ? What is the phone model ? Does it happen all the time or sporadically ?

**Comment by EugineKKK** [comment]
Hi.

Android 4.4 , Device : Y25 (y25) .

No. it happened only couple of times.

**Comment by massimocarli** [comment]
@EugineKidoz Is the problems till there?
Thanks

**Comment by EugineKidoz** [comment]
Seems ok now.
