### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by mheras** [facebook/fresco#574]
Hello,

I'm using Fresco in a `RecyclerView`. I'm recycling the views properly and, of course, initializing Fresco just once in the `Application` class.

I see that there are other OOM issues reported, but all of them seem to occur due to huge images trying to be loaded into the memory.

In my case, as you can see in the following screenshots, the images are small.

![screen shot 2015-08-27 at 10 41 42](https://cloud.githubusercontent.com/assets/323266/9522066/e0da72e6-4ca8-11e5-9781-a3b5a376a090.png)

![screen shot 2015-08-27 at 10 47 50](https://cloud.githubusercontent.com/assets/323266/9522102/17c75ee0-4ca9-11e5-9df4-6ed1382cd6f6.png)

It seems it's only happening on Android 5.0+ with ART:

![screen shot 2015-08-27 at 10 48 28](https://cloud.githubusercontent.com/assets/323266/9522116/3f201d2e-4ca9-11e5-96e3-7a43bb482f77.png)

Any idea how to solve this issue? I have too many occurrences of these crashes :(

**EDIT 1:**

I am loading 6~8 images on-screen, at most. All of them are JPEGs of ~~250~~ 25 kB max.
Here's the [hprof file (heap dump)](https://www.dropbox.com/s/jxxgpkueo661g7h/heap.hprof?dl=0).

Thank you in advance,
Martin

**Comment by tyronen** [comment]
How many images do you have loaded on-screen? 

Could you attach a hprof file? See the [instructions](https://developer.android.com/tools/debugging/debugging-memory.html#ViewHeap) on how to generate them.

**Comment by mheras** [comment]
@tyronen we are loading 6~8 images on-screen, at most. All of them are JPEGs of 250 kB max.

**Comment by mheras** [comment]
@tyronen Do you need more details?

**Comment by tbruceyu** [comment]
This issue occured on my project too. Hope resolve this ASAP

**Comment by sensen** [comment]
Hey @mheras and @tbruceyu,

We encounter similar issue at work. Our team finally ended up create a custom BitmapMemoryCacheParamsSupplier to be supplied when initialising Fresco, as a workaround for this issue. The code is at https://gist.github.com/sensen/a61eb1e7a1b7ea649cb0.

Hopefully the Fresco team could crack this issue on their end.

**Comment by mheras** [comment]
@sensen good workaround! Thanks :)

**Comment by ffelini** [comment]
Gus after implemting the workaround proposed above I'm geting this crash 

1669-2240/com.namshi.android.debug E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-18644
    java.lang.NoClassDefFoundError: com.facebook.imagepipeline.producers.DiskCacheProducer$1
            at com.facebook.imagepipeline.producers.DiskCacheProducer.produceResults(DiskCacheProducer.java:75)
            at com.facebook.imagepipeline.producers.EncodedMemoryCacheProducer.produceResults(EncodedMemoryCacheProducer.java:125)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.startNextProducerIfHasAttachedConsumers(MultiplexProducer.java:336)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.access$000(MultiplexProducer.java:125)
            at com.facebook.imagepipeline.producers.MultiplexProducer.produceResults(MultiplexProducer.java:87)
            at com.facebook.imagepipeline.producers.AddImageTransformMetaDataProducer.produceResults(AddImageTransformMetaDataProducer.java:29)
            at com.facebook.imagepipeline.producers.ResizeAndRotateProducer.produceResults(ResizeAndRotateProducer.java:69)
            at com.facebook.imagepipeline.producers.DecodeProducer.produceResults(DecodeProducer.java:93)
            at com.facebook.imagepipeline.producers.BitmapMemoryCacheProducer.produceResults(BitmapMemoryCacheProducer.java:87)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.startNextProducerIfHasAttachedConsumers(MultiplexProducer.java:336)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer.access$000(MultiplexProducer.java:125)
            at com.facebook.imagepipeline.producers.MultiplexProducer.produceResults(MultiplexProducer.java:87)
            at com.facebook.imagepipeline.producers.ThreadHandoffProducer$1.onSuccess(ThreadHandoffProducer.java:45)
            at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:54)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
            at java.lang.Thread.run(Thread.java:841)

**Comment by gajicm93** [comment]
+1

**Comment by ThomasWang2014** [comment]
OOM when i load this gif.![3e01211e0b6bdf6e9877f9193cf6844b](https://cloud.githubusercontent.com/assets/7620668/9866934/5d6df0ac-5b9b-11e5-934c-5730bedbe1ed.gif)

**Comment by xialixue007** [comment]
+ 1 @tyronen

**Comment by mheras** [comment]
@tyronen just wanted to know if there is any update on this. Thank you!

**Comment by mheras** [comment]
@tyronen any news? Sorry to bother you, but this is killing our app.

**Comment by tyronen** [comment]
@mheras: Your heap dump shows a total memory footprint of 56 MB. I'm going to assume this was on a device with a 64 MB heap, so the OOM risk is high.

On such a device, the bitmap cache is by default limited to 16 MB. If your app is finding that hard, there are two possible solutions:

1) Set `android:largeHeap=true` in your app's manifest.
2) Adjust the size of the cache along the lines @sensen suggested. His code limits the cache to just one entry on Lollipop, which is probably not what you want. You can try changing the code of `getMaxCacheSize` instead to give you a smaller cache for the 64MB devices - perhaps 8MB would work better for you, rather than the 16MB we use by default.

I notice also you seem to be using Picasso and Fresco simultaneously. Each of these libraries operates its own memory cache; putting both together on a low-end device is going to be hard. Do you need both? Are there features Picasso provides your app that Fresco does not?

**Comment by tyronen** [comment]
@ThomasWang2014: your issue should be fixed in v0.8.0.

**Comment by mheras** [comment]
@tyronen 

We are transitioning from Picasso to Fresco, but the app is huge and we are still working on it.

Aside from that, my question is:

If the available heap is not enough for the upcoming image, shouldn't the library try send the least recently used images back to disk so that more heap memory becomes available for such image? Am I missing something else?

Thanks

**Comment by tyronen** [comment]
@mheras we do do this. Your app's problem is this:

Fresco uses 1/4 of the heap size. If this is filled up, images are swapped out but remain on disk.
Picasso uses 1/7 of the heap size. If this is filled up, images are swapped out but remain on disk.

The rest of your app is thus limited to around 60% of the normal heap. If your app ever needs more than that, it will OOM.

You either have to reduce Picasso or Fresco's memory footprint by reducing the cache size, OR reduce the rest of your app's footprint.
