### ISSUE TITLE
java.lang.NoSuchFieldError: no field with name='mNativeContext' signature='J' in class Lcom/facebook/imagepipeline/gif/GifImage;

### ISSUE THREAD

**Issue by ICECHN** [facebook/fresco#580]
java.lang.NoSuchFieldError: no field with name='mNativeContext' signature='J' in class Lcom/facebook/imagepipeline/gif/GifImage;
	at java.lang.Runtime.nativeLoad(Native Method)
	at java.lang.Runtime.doLoad(Runtime.java:421)
	at java.lang.Runtime.loadLibrary(Runtime.java:362)
	at java.lang.System.loadLibrary(System.java:526)
	at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(Unknown Source)
	at com.facebook.common.soloader.SoLoaderShim.setHandler(Unknown Source)
                                              loadLibrary
                                              setInTestMode
	at com.facebook.imagepipeline.gif.GifImage.ensure(Unknown Source)
	at com.facebook.imagepipeline.gif.GifImage.create(Unknown Source)
                                            create
                                            dispose
                                            getFrame
	at com.facebook.imagepipeline.animated.factory.AnimatedImageFactory.decodeGif(Unknown Source)
                                                                     getCloseableImage
                                                                     createPreviewBitmap
                                                                     decodeAllFrames
                                                                     createBitmap
	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(Unknown Source)
                                                    decodeGif
                                                    decodeStaticImage
                                                    decodeJpeg
	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(Unknown Source)
                                                    decodeGif
                                                    decodeStaticImage
                                                    decodeJpeg
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(Unknown Source)
                                                                           handleError
                                                                           getQualityInfo
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.onFailureImpl(Unknown Source)
                                                                           onCancellationImpl
                                                                           updateDecodeJob
                                                                           getExtraMap
                                                                           maybeFinish
                                                                           handleResult
                                                                           getIntermediateImageEndOffset
                                                                           onNewResultImpl
                                                                           access$200
                                                                           access$400
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(Unknown Source)
	at com.facebook.imagepipeline.producers.JobScheduler.doJob(Unknown Source)
	at com.facebook.imagepipeline.producers.JobScheduler.clearJob(Unknown Source)
                                                      updateJob
                                                      enqueueJob
                                                      access$000
	at com.facebook.imagepipeline.producers.JobScheduler$1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:841)

**Comment by tyronen** [comment]
Is this a debug or release build?
Are you using ProGuard?
Can we see where you include Fresco in your build.gradle?

**Comment by sualvi** [comment]
Hi @tyronen , having the same issue. For mine, it is a debug build.

Yes I'm using ProGuard. Included Fresco in build.gradle

```
buildTypes {
   debug {
            debuggable true
            signingConfig sconfigs.debug
            minifyEnabled true
            proguardFiles 'proguard-obsfucate-only.txt', 'proguard-debug.txt'
        }
}

dependencies {
       compile project(':commons')
       compile project(':analytics')
       compile 'com.android.support:multidex:1.0.1'
       compile 'com.android.support:support-v4:22.2.1'
       compile 'com.android.support:appcompat-v7:22.2.1'
       compile 'com.android.support:recyclerview-v7:22.2.1'
       compile 'com.facebook.fresco:fresco:0.7.0+'
}
````

**Comment by sualvi** [comment]
Fixed the problem with the Proguard rules stated in issue https://github.com/facebook/fresco/issues/105
