### ISSUE TITLE
Image doesn't show up after being downloaded

### ISSUE THREAD

**Issue by sourabhv** [facebook/fresco#590]
I have a weird issue, sometimes the image would load from server (as seen by the progress drawable) but doesn't show up. Instead I get the reload drawable for every image loaded after that point. I don't have much info on that and neither a way to reproduce the bug, but I have a logs of when this happened

	09-03 23:31:07.766  10828-10828/com.example I/Timeline﹕ Timeline: Activity_launch_request id:com.example time:25287392
	09-03 23:31:07.896  10828-10828/com.example I/Choreographer﹕ Skipped 33 frames!  The application may be doing too much work on its main thread.
	09-03 23:31:08.196  10828-10828/com.example D/dalvikvm﹕ VFY: replacing opcode 0x70 at 0x0000
	09-03 23:31:08.256  10828-10828/com.example D/dalvikvm﹕ GC_FOR_ALLOC freed 2716K, 18% free 27431K/33100K, paused 21ms, total 21ms
	09-03 23:31:08.276  10828-10828/com.example I/dalvikvm-heap﹕ Grow heap (frag case) to 39.850MB for 5241616-byte allocation
	09-03 23:31:08.476  10828-10828/com.example W/dalvikvm﹕ VFY: unable to resolve direct method 16515: Landroid/view/View;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
	09-03 23:31:08.476  10828-10828/com.example D/dalvikvm﹕ VFY: replacing opcode 0x70 at 0x0000
	09-03 23:31:08.636  10828-11048/com.example D/dalvikvm﹕ Trying to load lib /data/app-lib/com.example-1/libmemchunk.so 0x422c10a8
	09-03 23:31:08.636  10828-11048/com.example D/dalvikvm﹕ Added shared lib /data/app-lib/com.example-1/libmemchunk.so 0x422c10a8
	09-03 23:31:08.656  10828-11046/com.example D/dalvikvm﹕ Trying to load lib /data/app-lib/com.example-1/libbitmaps.so 0x422c10a8
	09-03 23:31:08.656  10828-11046/com.example D/dalvikvm﹕ Added shared lib /data/app-lib/com.example-1/libbitmaps.so 0x422c10a8
	09-03 23:31:09.756  10828-10828/com.example D/dalvikvm﹕ GC_FOR_ALLOC freed 5579K, 14% free 35163K/40808K, paused 30ms, total 31ms
	09-03 23:31:10.156  10828-10828/com.example I/dalvikvm﹕ Could not find method android.content.res.Resources.getDrawable, referenced from method android.support.v7.internal.widget.ResourcesWrapper.getDrawable
	09-03 23:31:10.156  10828-10828/com.example W/dalvikvm﹕ VFY: unable to resolve virtual method 492: Landroid/content/res/Resources;.getDrawable (ILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
	09-03 23:31:10.156  10828-10828/com.example D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0002
	09-03 23:31:10.156  10828-10828/com.example I/dalvikvm﹕ Could not find method android.content.res.Resources.getDrawableForDensity, referenced from method android.support.v7.internal.widget.ResourcesWrapper.getDrawableForDensity
	09-03 23:31:10.156  10828-10828/com.example W/dalvikvm﹕ VFY: unable to resolve virtual method 494: Landroid/content/res/Resources;.getDrawableForDensity (IILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
	09-03 23:31:10.156  10828-10828/com.example D/dalvikvm﹕ VFY: replacing opcode 0x6e at 0x0002
	09-03 23:31:10.266  10828-10828/com.example I/Choreographer﹕ Skipped 126 frames!  The application may be doing too much work on its main thread.
	09-03 23:31:12.996  10828-10828/com.example I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@427117f8 time:25292628
	09-03 23:31:13.186  10828-11048/com.example D/dalvikvm﹕ GC_FOR_ALLOC freed 4752K, 12% free 38605K/43424K, paused 35ms, total 35ms
	09-03 23:31:25.266  10828-10835/com.example I/dalvikvm﹕ Jit: resizing JitTable from 4096 to 8192

I'm guessing this has something to do with it

    09-03 23:31:07.896  10828-10828/com.example I/Choreographer﹕ Skipped 33 frames!  The application may be doing too much work on its main thread.

**Update**

I attached `ControllerListener` to all images and when the problem started all images started giving this exception

      09-05 14:48:34.781  31849-31849/com.wedmegood E/unknown:﹕ Error loading 70
          com.facebook.imagepipeline.bitmaps.TooManyBitmapsException
                  at com.facebook.imagepipeline.bitmaps.DalvikBitmapFactory.pinBitmap(DalvikBitmapFactory.java:150)
                  at com.facebook.imagepipeline.bitmaps.DalvikBitmapFactory.decodeJPEGFromEncodedImage(DalvikBitmapFactory.java:130)
                  at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.decodeJPEGFromEncodedImage(PlatformBitmapFactory.java:108)
                  at com.facebook.imagepipeline.decoder.ImageDecoder.decodeJpeg(ImageDecoder.java:148)
                  at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:82)
                  at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:188)
                  at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:96)
                  at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:128)
                  at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                  at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                  at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                  at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                  at java.lang.Thread.run(Thread.java:841)

**Comment by sourabhv** [comment]
Maybe this is because I am using `LinearLayoutManager` with `getExtraLayoutSpace` to device height. Does `prefetchToBitmapCache` ignore duplicate requests? And does it move cache to disk in case memory starts becoming full?

**Comment by tyronen** [comment]
TooManyBitmapsException happens when you've filled up the available memory with visible bitmaps. If you're giving yourself a lot of extra screen space for layout and filling it with bitmaps, that would explain it.

Duplicate requests are ignored if there is already a request in-flight.

If memory gets full, cache entries will be evicted *if* there are no references to them - that is, views hosting said images. It sounds like in your case there are.
