### ISSUE TITLE
failure for the image,error message is "java.lang.RuntimeException: Failed to pin Bitmap"

### ISSUE THREAD

**Issue by szn0212** [facebook/fresco#616]
failure for the image,error message is "java.lang.RuntimeException: Failed to pin Bitmap"

**Comment by massimocarli** [comment]
This is usually due to an invalid image. Have you tested the app with different Android version? Does it happen always with the same images?

**Comment by csechuan** [comment]
It happens to my app too. Yes, always the same image, at least one for now. 

```
java.lang.RuntimeException: Failed to pin Bitmap
            at com.facebook.imagepipeline.nativecode.Bitmaps.nativePinBitmap(Native Method)
            at com.facebook.imagepipeline.nativecode.Bitmaps.pinBitmap(Bitmaps.java:50)
            at com.facebook.imagepipeline.bitmaps.DalvikBitmapFactory.pinBitmap(DalvikBitmapFactory.java:142)
            at com.facebook.imagepipeline.bitmaps.DalvikBitmapFactory.decodeJPEGFromEncodedImage(DalvikBitmapFactory.java:130)
            at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.decodeJPEGFromEncodedImage(PlatformBitmapFactory.java:108)
            at com.facebook.imagepipeline.decoder.ImageDecoder.decodeJpeg(ImageDecoder.java:148)
            at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:82)
            at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:188)
            at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:96)
            at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:128)
            at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
            at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
            at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
            at java.lang.Thread.run(Thread.java:856)
```

**Comment by tyronen** [comment]
Can you show us the image in question?

**Comment by szn0212** [comment]
it happen always with the same images in my phone,but not happen in others phone.

**Comment by 605575912** [comment]
Excuse me, how do you solve this problem, and I also have this problem，thanks

**Comment by yline** [comment]
this happed to mine too; for many phone;

**Comment by yline** [comment]
the usage:

**Comment by yline** [comment]
ImageRequestBuilder imageRequestBuilder = ImageRequestBuilder.newBuilderWithSource(imageUri);
        imageRequestBuilder.setProgressiveRenderingEnabled(isProgressiveRendering);
        ImageRequest imageRequest = imageRequestBuilder.build();

        PipelineDraweeControllerBuilder controllerBuilder = Fresco.newDraweeControllerBuilder();
        // controllerBuilder.setOldController(frescoView.getController());
        controllerBuilder.setImageRequest(imageRequest);
        DraweeController controller = controllerBuilder.build();

        // GenericDraweeHierarchy genericDraweeHierarchy = frescoView.getHierarchy();

        frescoView.setController(controller);

**Comment by wangrunxiang** [comment]
Excuse me, how do you solve this problem, and I also have this problem，thanks

**Comment by ajaystha005** [comment]
any solution?

**Comment by zengyimou** [comment]
i happens only on Android4.0. gif?
