### ISSUE TITLE
OOMs on Lollipop when using ViewPager for large images

### ISSUE THREAD

**Issue by ixiaoluo** [facebook/fresco#624]
java.lang.OutOfMemoryError: Failed to allocate a 2560012 byte allocation with 392548 free bytes and 383KB until OOM
     at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
     at android.graphics.Bitmap.nativeCreate(Native Method)
     at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
     at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
     at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
     at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
     at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
     at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
     at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.decodeStaticImageFromStream(ArtBitmapFactory.java:124)
     at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.decodeJPEGFromEncodedImage(ArtBitmapFactory.java:116)
     at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.decodeJPEGFromEncodedImage(PlatformBitmapFactory.java:106)
     at com.facebook.imagepipeline.decoder.ImageDecoder.decodeJpeg(ImageDecoder.java:148)
     at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:82)
     at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:188)
     at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:96)
     at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:128)
     at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
     at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
     at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
     at java.lang.Thread.run(Thread.java:818)

**Comment by tyronen** [comment]
We need more details than this.
* How often do you get these OOMs?
* Does it happen consistently?
* What size of image are you displaying? Are you resizing or downsampling them?
* What format of image is it (jpeg, png, gif)?

**Comment by ixiaoluo** [comment]
ViewPager+Fragment(Support.V4), and Fragment has 800 x 800 .png photo.
Slide to the right until the 12 item appears OOM.
Only 5.0 system will appear this kind of circumstance.(4.4 no happen)

**Comment by benjaminbarbe** [comment]
+1

**Comment by benjaminbarbe** [comment]
@tyronen Do you have any hint to fix that manually? I force the remove of my ```SimpleDraweeView``` each time a fragment is uninstantiated :
```
            this.removeView(mInternalImageView);
            mInternalImageView = null;
```

The byte array is retained and I can't view incoming reference (MAT)...

Thanks :smiley:

**Comment by miladehghani** [comment]
@ixiaoluo  I have exactly this problem, did you find any solution?

**Comment by 544531645** [comment]
I also happen who can help me

**Comment by erikandre** [comment]
Closing due to lack of updates and not enough available information to investigate further.
