### ISSUE TITLE
IllegalStateException in closeIfOwnedBy function

### ISSUE THREAD

**Issue by leofirespotter** [facebook/fresco#629]
Seeing this crash in logs. No idea what is causing it, or how to reproduce. Has happened to 3 people so far, on 5.1.1 and 5.0.2

```	
java.lang.IllegalStateException	
at com.squareup.okhttp.Connection.closeIfOwnedBy(Connection.java:137)	
at com.squareup.okhttp.OkHttpClient$1.closeIfOwnedBy(OkHttpClient.java:75)
at com.squareup.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:577)
at com.squareup.okhttp.Call.cancel(Call.java:122)
at com.facebook.imagepipeline.backends.okhttp.OkHttpNetworkFetcher$1$1.run(OkHttpNetworkFetcher.java:98)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```

Does anyone have any ideas on what could be causing this? Or what I can do to prevent it?

**Comment by leofirespotter** [comment]
Any update on this?

**Comment by leofirespotter** [comment]
@tyronen is there any update on this?

**Comment by kirwan** [comment]
Since Fresco 0.10.0 the OkHttp version being used is 2.7.4 (or 3.0.1 if you switch to the OkHttp 3 module). Let us know if the problem still occurs but I don't think it should.
