### ISSUE TITLE
imagePipeline.fetchEncodedImage with local image Uri ("file://...") throws exception

### ISSUE THREAD

**Issue by MRusinov** [facebook/fresco#655]
Next code:

``` javascript
    private void makeImageThumbnail(final String imgFile) {
        int width = ImageSize, height = ImageSize;
        ImageRequest imageRequest = ImageRequestBuilder.newBuilderWithSource(Uri.parse("file:/" + imgFile))
                .setResizeOptions(new ResizeOptions(width, height))
                .build();

        ImagePipeline imagePipeline = Fresco.getImagePipeline();

        DataSource<CloseableReference<PooledByteBuffer>>
                dataSource = imagePipeline.fetchEncodedImage(imageRequest, getActivity());
```

throws exception on last line:

```
java.lang.IllegalArgumentException
at com.facebook.common.internal.Preconditions.checkArgument(Preconditions.java:108)
at com.facebook.imagepipeline.core.ProducerSequenceFactory.validateEncodedImageRequest(ProducerSequenceFactory.java:119)
at com.facebook.imagepipeline.core.ProducerSequenceFactory.getEncodedImageProducerSequence(ProducerSequenceFactory.java:93)
```

Why aren't local files supported in fetchEncodedImage?

**Comment by massimocarli** [comment]
Actually theres not reason for that but we planned to add this feature asap. 
Thanks

**Comment by MRusinov** [comment]
I really hope that it will happen soon :)
Thanks for your answer!

**Comment by shawyou** [comment]
this feature is important!

**Comment by MRusinov** [comment]
Are there any news on this?

**Comment by shawyou** [comment]
Are there any news on this?

**Comment by MRusinov** [comment]
Checked in 0.9.0. Still not working :(

**Comment by erikandre** [comment]
Closing as this is enhancement is not prioritized to be implemented.
Still, please feel free to submit a pull request for any missing functionality.
