### ISSUE TITLE
FC when OkHttpClient is used to create your ImagePipelineConfig

### ISSUE THREAD

**Issue by kssilvoza** [facebook/fresco#66]
Trying to use OkHttp for my image pipeline but it causes a force close when it tries to download several images in a listview

```
android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
            at com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative(OpenSSLSocketImpl.java:1090)
            at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1085)
            at com.squareup.okhttp.Connection.closeIfOwnedBy(Connection.java:141)
            at com.squareup.okhttp.OkHttpClient$1.closeIfOwnedBy(OkHttpClient.java:71)
            at com.squareup.okhttp.internal.http.HttpConnection.closeIfOwnedBy(HttpConnection.java:134)
            at com.squareup.okhttp.internal.http.HttpTransport.disconnect(HttpTransport.java:135)
            at com.squareup.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:468)
            at com.squareup.okhttp.Call.cancel(Call.java:118)
            at com.facebook.imagepipeline.backends.okhttp.OkHttpNetworkFetchProducer$1.onCancellationRequested(OkHttpNetworkFetchProducer.java:86)
            at com.facebook.imagepipeline.producers.SettableProducerContext.cancel(SettableProducerContext.java:127)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$1.onCancellationRequested(MultiplexProducer.java:270)
            at com.facebook.imagepipeline.producers.SettableProducerContext.cancel(SettableProducerContext.java:127)
            at com.facebook.imagepipeline.producers.MultiplexProducer$Multiplexer$1.onCancellationRequested(MultiplexProducer.java:270)
            at com.facebook.imagepipeline.producers.SettableProducerContext.cancel(SettableProducerContext.java:127)
            at com.facebook.imagepipeline.datasource.AbstractProducerToDataSourceAdapter.close(AbstractProducerToDataSourceAdapter.java:99)
            at com.facebook.drawee.controller.AbstractDraweeController.releaseFetch(AbstractDraweeController.java:173)
            at com.facebook.drawee.controller.AbstractDraweeController.release(AbstractDraweeController.java:165)
            at com.facebook.drawee.components.DeferredReleaser$1.run(DeferredReleaser.java:64)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by tyronen** [comment]
Pull request #54 should take care of this.

**Comment by yongjhih** [comment]
PR #21
