### ISSUE TITLE
SimpleDraweeView was not initialized

### ISSUE THREAD

**Issue by goodboywt** [facebook/fresco#666]
android.view.InflateException: Binary XML file line #8: Error inflating class com.facebook.drawee.view.SimpleDraweeView
	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at com.coohuaclient.ui.activity.LockScreenNewActivity$AdvPageAdapter.getItemView(SourceFile:839)
	at com.coohuaclient.ui.activity.LockScreenNewActivity$AdvPageAdapter.instantiateItem(SourceFile:814)
	at com.coohuaclient.ui.customview.verticalviewpager.VerticalViewPager.addNewItem(SourceFile:729)
	at com.coohuaclient.ui.customview.verticalviewpager.VerticalViewPager.populate(SourceFile:879)
	at com.coohuaclient.ui.customview.verticalviewpager.VerticalViewPager.populate(SourceFile:811)
	at com.coohuaclient.ui.customview.verticalviewpager.VerticalViewPager.onMeasure(SourceFile:1334)
	at android.view.View.measure(View.java:17824)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:846)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:512)
	at android.view.View.measure(View.java:17824)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:846)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:512)
	at android.view.View.measure(View.java:17824)
	at com.coohuaclient.ui.customview.DrawerLayout.onMeasure(SourceFile:729)
	at android.view.View.measure(View.java:17824)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5630)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
	at android.view.View.measure(View.java:17824)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5630)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
	at android.view.View.measure(View.java:17824)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5630)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2641)
	at android.view.View.measure(View.java:17824)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2374)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1389)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1613)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1267)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6501)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
	at android.view.Choreographer.doCallbacks(Choreographer.java:603)
	at android.view.Choreographer.doFrame(Choreographer.java:572)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:179)
	at android.app.ActivityThread.main(ActivityThread.java:5537)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	... 49 more
Caused by: java.lang.NullPointerException: SimpleDraweeView was not initialized!
	at com.facebook.common.internal.Preconditions.checkNotNull(SourceFile:226)
	at com.facebook.drawee.view.SimpleDraweeView.init(SourceFile:71)
	at com.facebook.drawee.view.SimpleDraweeView.<init>(SourceFile:59)
	... 52 more
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at com.coohuaclient.ui.activity.LockScreenNewActivity$AdvPageAdapter.getItemView(SourceFile:839)
	at com.coohuaclient.ui.activity.LockScreenNewActivity$AdvPageAdapter.instantiateItem(SourceFile:814)
	at com.coohuaclient.ui.customview.verticalviewpager.VerticalViewPager.addNewItem(SourceFile:729)
	at com.coohuaclient.ui.customview.verticalviewpager.VerticalViewPager.populate(SourceFile:879)
	at com.coohuaclient.ui.customview.verticalviewpager.VerticalViewPager.populate(SourceFile:811)
	at com.coohuaclient.ui.customview.verticalviewpager.VerticalViewPager.onMeasure(SourceFile:1334)
	at android.view.View.measure(View.java:17824)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:846)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:512)
	at android.view.View.measure(View.java:17824)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:846)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:512)
	at android.view.View.measure(View.java:17824)
	at com.coohuaclient.ui.customview.DrawerLayout.onMeasure(SourceFile:729)
	at android.view.View.measure(View.java:17824)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5630)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
	at android.view.View.measure(View.java:17824)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5630)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
	at android.view.View.measure(View.java:17824)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5630)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2641)
	at android.view.View.measure(View.java:17824)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2374)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1389)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1613)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1267)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6501)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
	at android.view.Choreographer.doCallbacks(Choreographer.java:603)
	at android.view.Choreographer.doFrame(Choreographer.java:572)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:179)
	at android.app.ActivityThread.main(ActivityThread.java:5537)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)
Caused by: java.lang.NullPointerException: SimpleDraweeView was not initialized!
	at com.facebook.common.internal.Preconditions.checkNotNull(SourceFile:226)
	at com.facebook.drawee.view.SimpleDraweeView.init(SourceFile:71)
	at com.facebook.drawee.view.SimpleDraweeView.<init>(SourceFile:59)
	... 52 more
java.lang.NullPointerException: SimpleDraweeView was not initialized!
	at com.facebook.common.internal.Preconditions.checkNotNull(SourceFile:226)
	at com.facebook.drawee.view.SimpleDraweeView.init(SourceFile:71)
	at com.facebook.drawee.view.SimpleDraweeView.<init>(SourceFile:59)
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at com.coohuaclient.ui.activity.LockScreenNewActivity$AdvPageAdapter.getItemView(SourceFile:839)
	at com.coohuaclient.ui.activity.LockScreenNewActivity$AdvPageAdapter.instantiateItem(SourceFile:814)
	at com.coohuaclient.ui.customview.verticalviewpager.VerticalViewPager.addNewItem(SourceFile:729)
	at com.coohuaclient.ui.customview.verticalviewpager.VerticalViewPager.populate(SourceFile:879)
	at com.coohuaclient.ui.customview.verticalviewpager.VerticalViewPager.populate(SourceFile:811)
	at com.coohuaclient.ui.customview.verticalviewpager.VerticalViewPager.onMeasure(SourceFile:1334)
	at android.view.View.measure(View.java:17824)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:846)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:512)
	at android.view.View.measure(View.java:17824)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:846)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:512)
	at android.view.View.measure(View.java:17824)
	at com.coohuaclient.ui.customview.DrawerLayout.onMeasure(SourceFile:729)
	at android.view.View.measure(View.java:17824)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5630)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
	at android.view.View.measure(View.java:17824)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5630)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
	at android.view.View.measure(View.java:17824)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5630)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:459)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2641)
	at android.view.View.measure(View.java:17824)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2374)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1389)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1613)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1267)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6501)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
	at android.view.Choreographer.doCallbacks(Choreographer.java:603)
	at android.view.Choreographer.doFrame(Choreographer.java:572)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:179)
	at android.app.ActivityThread.main(ActivityThread.java:5537)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

Hello,I encounter this error many times.I initialized fresco in subclass of Application.
![image](https://cloud.githubusercontent.com/assets/3954558/10573148/677f5e28-7680-11e5-8f24-d0f45dae7a69.png)

But I also encounter this,My app is running in multiprocess. Is there any problem? please help me!!!
THX

**Comment by michalgr** [comment]
Can you verify that Initialization runs in the process that uses SimpleDraweeView ? Logging to logcat after `Fresco.initialize` will be enough to verify that.

**Comment by goodboywt** [comment]
I had not initialize in every process,I just initialize in the main process names com.coohuaclient,I used SimpleDraweeView in process names  com.coohuaclient:lock. Is there any problem?But I didn't encounter this error every time.
![image](https://cloud.githubusercontent.com/assets/3954558/10595966/33143fbe-7711-11e5-8536-fbb8917fed27.png)

In subclass of Application, I will judge the process name , if it equals  com.coohuaclient,I will run Fresco.initialize or I won't;

**Comment by goodboywt** [comment]
By the way ,can you give me a filter word to find the initialization log? I used initialize,fresco,facebook and so on,I never find any log about initialization.

**Comment by michalgr** [comment]
Fresco.initialize(this) initializes caches and other components required by SimpleDraweeView within calling process. It should be called in every process that uses SimpleDraweeView.
