### ISSUE TITLE
DraweeEventTracker queue fills up

### ISSUE THREAD

**Issue by karun2189** [facebook/fresco#678]
App is crash because I dont know why??

```
java.lang.IllegalStateException: Queue full
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at java.util.AbstractQueue.add(AbstractQueue.java:69)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:282)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at com.facebook.drawee.components.DraweeEventTracker.recordEvent(DraweeEventTracker.java:52)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at com.facebook.drawee.view.DraweeHolder.onDetach(DraweeHolder.java:127)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at com.facebook.drawee.view.DraweeView.onStartTemporaryDetach(DraweeView.java:116)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.View.dispatchStartTemporaryDetach(View.java:8335)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.ViewGroup.dispatchStartTemporaryDetach(ViewGroup.java:2663)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.ViewGroup.dispatchStartTemporaryDetach(ViewGroup.java:2663)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.ViewGroup.dispatchStartTemporaryDetach(ViewGroup.java:2663)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.widget.AbsListView$RecycleBin.addScrapView(AbsListView.java:6551)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.widget.GridView.onMeasure(GridView.java:1080)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.View.measure(View.java:17547)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.widget.RelativeLayout.measureChild(RelativeLayout.java:697)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.View.measure(View.java:17547)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.View.measure(View.java:17547)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.widget.RelativeLayout.measureChild(RelativeLayout.java:697)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.View.measure(View.java:17547)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:607)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:674)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.View.measure(View.java:17547)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.View.measure(View.java:17547)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:940)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.View.measure(View.java:17547)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.View.measure(View.java:17547)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.View.measure(View.java:17547)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.View.measure(View.java:17547)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.View.measure(View.java:17547)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.View.measure(View.java:17547)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1781)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
10-21 10:31:27.699 8966-8966/com.zoho.notebook E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:550)
```

**Comment by michalgr** [comment]
Do you create controllers or manipulate drawee components on non-ui thread ?

**Comment by karun2189** [comment]
No i am create and assign the controller in UI Thread only

**Comment by kirwan** [comment]
We're cleaning up long-untouched issues so I'm closing this one.

If you think this is still an issue, feel free to comment and we can re-open.

**Comment by geetgobindsingh** [comment]
Hi, I am getting the same issue  - **java.lang.IllegalStateException: Queue full**
Here is the stack trace, hope it help to identify the reason

Fatal Exception: java.lang.IllegalStateException: Queue full
       at java.util.AbstractQueue.add(AbstractQueue.java:69)
       at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:282)
       at com.facebook.drawee.components.DraweeEventTracker.recordEvent(SourceFile:77)
       at com.facebook.drawee.controller.AbstractDraweeController.submitRequest(SourceFile:439)
       at com.facebook.drawee.controller.AbstractDraweeController.onAttach(SourceFile:361)
       at com.facebook.drawee.view.DraweeHolder.attachController(SourceFile:264)
       at com.facebook.drawee.view.DraweeHolder.attachOrDetachController(SourceFile:281)
       at com.facebook.drawee.view.DraweeHolder.onAttach(SourceFile:93)
       at com.facebook.drawee.view.DraweeView.doAttach(SourceFile:180)
       at com.facebook.drawee.view.DraweeView.onAttach(SourceFile:166)
       at com.facebook.drawee.view.DraweeView.onAttachedToWindow(SourceFile:140)
       at android.view.View.dispatchAttachedToWindow(View.java:13393)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2683)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2683)
       at android.view.ViewGroup.addViewInner(ViewGroup.java:3826)
       at android.view.ViewGroup.addView(ViewGroup.java:3636)
       at android.view.ViewGroup.addView(ViewGroup.java:3581)
       at android.support.v7.widget.RecyclerView$5.addView(SourceFile:746)
       at android.support.v7.widget.ChildHelper.addView(SourceFile:107)
       at android.support.v7.widget.RecyclerView$LayoutManager.addViewInt(SourceFile:8003)
       at android.support.v7.widget.RecyclerView$LayoutManager.addView(SourceFile:7961)
       at android.support.v7.widget.RecyclerView$LayoutManager.addView(SourceFile:7949)
       at android.support.v7.widget.GridLayoutManager.layoutChunk(SourceFile:579)
       at android.support.v7.widget.LinearLayoutManager.fill(SourceFile:1516)
       at android.support.v7.widget.LinearLayoutManager.scrollBy(SourceFile:1330)
       at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(SourceFile:1074)
       at android.support.v7.widget.GridLayoutManager.scrollVerticallyBy(SourceFile:381)
       at android.support.v7.widget.RecyclerView$ViewFlinger.run(SourceFile:4838)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
       at android.view.Choreographer.doCallbacks(Choreographer.java:613)
       at android.view.Choreographer.doFrame(Choreographer.java:582)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5692)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
       at dalvik.system.NativeStart.main(NativeStart.java)
