### ISSUE TITLE
Canvas: trying to use a recycled bitmap

### ISSUE THREAD

**Issue by karun2189** [facebook/fresco#709]
My scenario is : I am having 2 fragment in single activity, I am using show and hide technology for fragment. If i am switch between 2 fragments fastly then i am getting this error.. Both fragment having gridview.

Thanks

java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@25249957
                                                                       at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1282)
                                                                       at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:599)
                                                                       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:538)
                                                                       at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:140)
                                                                       at com.facebook.drawee.drawable.ScaleTypeDrawable.draw(ScaleTypeDrawable.java:108)
                                                                       at com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha(FadeDrawable.java:306)
                                                                       at com.facebook.drawee.drawable.FadeDrawable.draw(FadeDrawable.java:293)
                                                                       at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:140)
                                                                       at com.facebook.drawee.generic.GenericDraweeHierarchy$RootDrawable.draw(GenericDraweeHierarchy.java:133)
                                                                       at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:140)
                                                                       at com.facebook.drawee.drawable.ScaleTypeDrawable.draw(ScaleTypeDrawable.java:108)
                                                                       at com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha(FadeDrawable.java:306)
                                                                       at com.facebook.drawee.drawable.FadeDrawable.draw(FadeDrawable.java:293)
                                                                       at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:140)
                                                                       at com.facebook.drawee.generic.GenericDraweeHierarchy$RootDrawable.draw(GenericDraweeHierarchy.java:133)
                                                                       at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:140)
                                                                       at com.facebook.drawee.drawable.ScaleTypeDrawable.draw(ScaleTypeDrawable.java:108)
                                                                       at com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha(FadeDrawable.java:306)
                                                                       at com.facebook.drawee.drawable.FadeDrawable.draw(FadeDrawable.java:293)
                                                                       at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:140)
                                                                       at com.facebook.drawee.generic.GenericDraweeHierarchy$RootDrawable.draw(GenericDraweeHierarchy.java:133)
                                                                       at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:140)
                                                                       at com.facebook.drawee.drawable.ScaleTypeDrawable.draw(ScaleTypeDrawable.java:108)
                                                                       at com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha(FadeDrawable.java:306)
                                                                       at com.facebook.drawee.drawable.FadeDrawable.draw(FadeDrawable.java:293)
                                                                       at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:140)
                                                                       at com.facebook.drawee.generic.GenericDraweeHierarchy$RootDrawable.draw(GenericDraweeHierarchy.java:133)
                                                                       at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:140)
                                                                       at com.facebook.drawee.drawable.ScaleTypeDrawable.draw(ScaleTypeDrawable.java:108)
                                                                       at com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha(FadeDrawable.java:306)
                                                                       at com.facebook.drawee.drawable.FadeDrawable.draw(FadeDrawable.java:293)
                                                                       at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:140)
                                                                       at com.facebook.drawee.generic.GenericDraweeHierarchy$RootDrawable.draw(GenericDraweeHierarchy.java:133)
                                                                       at android.widget.ImageView.onDraw(ImageView.java:1158)
                                                                       at android.view.View.draw(View.java:15231)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:14167)
                                                                       at android.view.View.getDisplayList(View.java:14189)
                                                                       at android.view.View.draw(View.java:14959)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:14162)
                                                                       at android.view.View.getDisplayList(View.java:14189)
                                                                       at android.view.View.draw(View.java:14959)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:14162)
                                                                       at android.view.View.getDisplayList(View.java:14189)
                                                                       at android.view.View.draw(View.java:14959)
                                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                                       at android.view.View.updateDisplayListIfDirty(View.java:14162)
                                                                   	at android.view.View.getDisplayList(View.java:1418

**Comment by massimocarli** [comment]
Probably the same problem of this: https://github.com/facebook/fresco/issues/717
