### ISSUE TITLE
Fresco OOM in Android 5.x 

### ISSUE THREAD

**Issue by a1510312433** [facebook/fresco#715]
Here is the log:
java.lang.OutOfMemoryError: Failed to allocate a 52515852 byte allocation with 16777216 free bytes and 48MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:817)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:794)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:761)
	at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
	at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
	at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.decodeStaticImageFromStream(ArtBitmapFactory.java:126)
	at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.decodeJPEGFromEncodedImage(ArtBitmapFactory.java:118)
	at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.decodeJPEGFromEncodedImage(PlatformBitmapFactory.java:106)
	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeJpeg(ImageDecoder.java:144)
	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:82)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:177)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$100(DecodeProducer.java:93)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:121)
	at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
	at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
	at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by a1510312433** [comment]
https://github.com/facebook/fresco/issues/404
My problem seems like this answer, means the size of a image is 52515852 byte(50M) ?
and is there any other issues for the problem ?  Thanks

**Comment by tyronen** [comment]
I cannot imagine why you could possibly need a 50M jpeg on a mobile device.

You should [resize](http://frescolib.org/docs/resizing-rotating.html#resizing) the image first. If you absolutely cannot get it down to a reasonable size, you can try setting `android:largeHeap=true` in your manifest file.

**Comment by a1510312433** [comment]
OK , I got my problem.
I have a BaseActivity , new Activity will extends it ,and I put "Fresco.initialize(getApplicationContext());" in BaseActivity.
Now I put the initialize in BaseApplication , the problem  significantly reduced。

**Comment by zhangdanyang6677** [comment]
who can help me? have a lot of phone with this problem;

**Comment by ashokkumar88** [comment]
@AndroidLearner2018 did you find any solution?
