### ISSUE TITLE
fresco:pressedStateOverlayImage error 

### ISSUE THREAD

**Issue by chonamdoo** [facebook/fresco#72]
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_pressed="true" android:drawable="@drawable/folder_bg_pressed" />
    <item android:drawable="@drawable/folder_bg_normal" />
</selector>

<com.facebook.drawee.view.SimpleDraweeView
            android:id="@+id/thumb"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scaleType="fitXY"
            fresco:fadeDuration="100"
             fresco:pressedStateOverlayImage="@drawable/xml_folder_bg_pressed"
            fresco:placeholderImage="@drawable/thumb_basic_logo"
            fresco:placeholderImageScaleType="fitCenter"/>

    java.lang.NullPointerException
            at com.facebook.drawee.drawable.ArrayDrawable.mutate(ArrayDrawable.java:182)
            at com.facebook.drawee.generic.GenericDraweeHierarchy.<init>(GenericDraweeHierarchy.java:278)
            at com.facebook.drawee.generic.GenericDraweeHierarchyBuilder.build(GenericDraweeHierarchyBuilder.java:431)
            at com.couchgram.privacycall.activity.GalleryActivity$ImageAdapter.getView(GalleryActivity.java:375)

**Comment by blackiedm** [comment]
you can see #33

**Comment by chonamdoo** [comment]
blackiedm thx
