### ISSUE TITLE
OOM Exception Why this occur 

### ISSUE THREAD

**Issue by karun2189** [facebook/fresco#723]
java.lang.OutOfMemoryError: Failed to allocate a 7990284 byte allocation with 1407372 free bytes and 1374KB until OOM
                                                                       at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                       at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
                                                                       at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
                                                                       at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
                                                                       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
                                                                       at com.facebook.imagepipeline.platform.ArtDecoder.decodeStaticImageFromStream(ArtDecoder.java:137)
                                                                       at com.facebook.imagepipeline.platform.ArtDecoder.decodeJPEGFromEncodedImage(ArtDecoder.java:120)
                                                                       at com.facebook.imagepipeline.decoder.ImageDecoder.decodeJpeg(ImageDecoder.java:151)
                                                                       at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:85)
                                                                       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:188)
                                                                       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:96)
                                                                       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:128)
                                                                       at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                                                                       at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                                                                       at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by tyronen** [comment]
Follow #574.
