### ISSUE TITLE
Suddanly started to crash with UnsatisfiedLinkError

### ISSUE THREAD

**Issue by nikslushkin** [facebook/fresco#732]
Hello, our released app have started to crash with UnsatisfiedLinkError on Fly, Asus, Lenovo devices. All of them have MediaTek processor. After one month since release on Friday 30 October we have got first report of this crash.
We are using fresco as-is without compiling it from source code. Reproduced on 0.7.0 and on 0.8.1.
If you need I can share full report from Crashlytics. 

```
Fatal Exception: java.lang.UnsatisfiedLinkError: Couldn't load memchunk from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/system/app/com.hotellook.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]: findLibrary returned null
       at java.lang.Runtime.loadLibrary(Runtime.java:365)
       at java.lang.System.loadLibrary(System.java:526)
       at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
       at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
       at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:36)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
       at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:141)
       at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newOutputStream(NativePooledByteBufferFactory.java:26)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:94)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:37)
       at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:72)
       at com.facebook.imagepipeline.backends.okhttp.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:116)
       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841) 
```

![2015-11-05 12 48 35](https://cloud.githubusercontent.com/assets/1586158/10965080/ae3392d8-83bb-11e5-8c7c-ccbd44c34a01.png)

**Comment by tyronen** [comment]
Your app went out on Oct 30? Did you have a previous release that was also using Fresco? If so, what version was that?

**Comment by tyronen** [comment]
please answer in #410
