### ISSUE TITLE
Error inflating class com.facebook.drawee.view.SimpleDraweeView

### ISSUE THREAD

**Issue by ppamorim** [facebook/fresco#74]
Hi.
I've tried to inflate this guy on adapter, but don't work!
I'm using the last version.

    <com.facebook.drawee.view.SimpleDraweeView
      android:id="@+id/camera_image"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      app:placeholderImage="@mipmap/ic_launcher"/>

android.view.InflateException: Binary XML file line #7: Error inflating class com.facebook.drawee.view.SimpleDraweeView...

**Comment by IanChilds** [comment]
Is there anything else in the error message? That should probably be `fb:placeholderImage=` instead of `app:placeholderImage=`

**Comment by ppamorim** [comment]
@IanChilds, This hasn't relation with the problem.

**Comment by andforce** [comment]
<com.facebook.drawee.view.SimpleDraweeView
            android:layout_gravity="center"
            android:layout_height="100dp"
            android:layout_width="100dp"
            android:background="@color/white"
            android:id="@+id/cover"/>


i hava same trouble~

**Comment by andforce** [comment]
@ppamorim I have solve this problem.
 add :Fresco.initialize(this); to your Aoolication.

**Comment by jpicoquares** [comment]
Thanks for your response andforce

**Comment by lkw103037** [comment]
it's right

**Comment by passos** [comment]
This is so tricky. The error message seems totally irrelevant with the solution.

**Comment by ManMegh** [comment]
I have placed the Fresco.initialize(this); in my application, but still error is there...

 
![image](https://cloud.githubusercontent.com/assets/12906510/8176378/fdeab13a-1417-11e5-9ed2-14ece2e1c9ae.png)


In the screen shot you can see the library files and the code along with the logcat meassages.... Please Help Me

**Comment by IvanAliaga** [comment]
In case you want to implement using a fragment as would be? I have the same problem as everyone else. Best Regards!

**Comment by tyronen** [comment]
Is this the same stack trace as issue #395?

**Comment by yrizk** [comment]
you guys sure you registered the application in the manifest? its a small step,but your context wont be valid when you try to init Fresco without 
`android:name="your application name" `

**Comment by vivian8725118** [comment]
I have the same problem too~how can i solve it?

**Comment by vivian8725118** [comment]
ok,I solved it.
just put    
   > Fresco.initialize(this); 

above 

   > setContentView(R.layout.activity_main);

and ,it works now.

**Comment by goodlifechris** [comment]
thanks it worked

**Comment by andforce** [comment]
@ManMegh @vivian8725118 You should only call Fresco.initialize once. Your Application class would be a good place. Doing it in each Activity is wrong.

**Comment by goodlifechris** [comment]
Thanks bro worked perfectly though not using fresco am using picasso.
Regards

**Comment by goodlifechris** [comment]
ssup bro,

I would like more of your tutorials how can i get them.
Regards

**Comment by saumil11** [comment]
In my case writing `Fresco.initialize(this);` before `setContentView(R.layout.activity_home);` worked

**Comment by arenaq** [comment]
My problem was not specifing the whole path `com.facebook.drawee.view.SimpleDraweeView` (I had just `SimpleDraweeView`). IF that is not your case, check the line of XML file on which the error occured.

**Comment by iDaniel19** [comment]
I have the same problem and none of the solutions above is working for me.

**Comment by arenaq** [comment]
@iDaniel19 paste in your XML

**Comment by iDaniel19** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:fresco="http://schemas.android.com/apk/res-auto"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="vertical">


<com.facebook.drawee.view.SimpleDraweeView
        android:id="@+id/profileImage"
        fresco:actualImageScaleType="centerCrop"
        android:layout_width="200dp"
        android:layout_gravity="center_horizontal"
        android:layout_height="200dp" />
</LinearLayout>
```

**Comment by iDaniel19** [comment]
I found the problem . I had FacebookSdk.sdkInitialize(this); instead of Fresco.initialize(this);. Now I have both and it's working. Should I keep only one, or both ?

**Comment by arenaq** [comment]
@iDaniel19 Glad you solved it. Cheers!

**Comment by huopochuan** [comment]
3Q

**Comment by aneeshATgithub** [comment]
use following version, and you can initialize fresco in Application class

compile 'com.facebook.fresco:fresco:0.12.0'

**Comment by Pinkal7600** [comment]
Error : android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.facebook.drawee.view.SimpleDraweeView

I have initialize `Fresco.initialize(this);` in `Application` `onCreate()`.

XML 
        
       <com.facebook.drawee.view.SimpleDraweeView        

        android:id="@+id/draweeView"
        
        android:layout_width="200dp"
       
        android:layout_height="100dp"

Can anyone tell me what is a problem?
       
        android:padding="5dp" />

**Comment by ravivlb** [comment]
facing same issue after updating 1.3.0

FATAL EXCEPTION: main
                                                                                 Process: com.fetchr.driver.android.alpha, PID: 29053
                                                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fetchr.driver.android.alpha/com.fetchr.driver.android.screens.welcome.WelcomeActivity}: android.view.InflateException: Binary XML file line #22: Binary XML file line #22: Error inflating class com.facebook.drawee.view.SimpleDraweeView
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
                                                                                     at android.app.ActivityThread.access$1100(ActivityThread.java:221)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:158)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                                  Caused by: android.view.InflateException: Binary XML file line #22: Binary XML file line #22: Error inflating class com.facebook.drawee.view.SimpleDraweeView
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
                                                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                     at com.fetchr.driver.android.base.ButterAppCompatActivity.setContentView(ButterAppCompatActivity.java:49)
                                                                                     at com.fetchr.driver.android.screens.welcome.WelcomeActivity.onCreate(WelcomeActivity.java:45)
                                                                                     at android.app.Activity.performCreate(Activity.java:6876)
                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                                     at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:158) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:7225) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                                  Caused by: android.view.InflateException: Binary XML file line #22: Error inflating class com.facebook.drawee.view.SimpleDraweeView
                                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:657)
                                                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
                                                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
                                                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
                                                                                     at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:192)
                                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766)
                                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
                                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
                                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
                                                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60) 
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                     at com.fetchr.driver.android.base.ButterAppCompatActivity.setContentView(ButterAppCompatActivity.java:49) 
                                                                                     at com.fetchr.driver.android.screens.welcome.WelcomeActivity.onCreate(WelcomeActivity.java:45) 
                                                                                     at android.app.Activity.performCreate(Activity.java:6876) 
                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                                     at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:158) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:7225) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                                                     at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:631)
                                                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211) 
                                                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20) 
                                                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302) 
                                                                                     at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:192) 
                                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766) 
                                                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                                     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                                     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60) 
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                                     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                     at com.fetchr.driver.android.base.ButterAppCompatActivity.setContentView(ButterAppCompatActivity.java:49) 
                                                                                     at com.fetchr.driver.android.screens.welcome.WelcomeActivity.onCreate(WelcomeActivity.java:45) 
                                                                                     at android.app.Activity.performCreate(Activity.java:6876) 
                                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                                     at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:158) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:7225) 
                                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                                  Caused by: java.lang.NumberFormatException: Invalid int: "res/drawable-xxxhdpi-v4/icn_profile_main.png"
                                                                                     at java.lang.Integer.invalidInt(Integer.java:138)
                                                                                     at java.lang.Integer.parse(Integer.java:410)
                                                                                     at java.lang.Integer.parseInt(Integer.java:367)
                                                                                     at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:133)
                                                                                     at android.content.res.TypedArray.getInt(TypedArray.java:357)
                                                                                     at com.facebook.drawee.generic.GenericDraweeHierarchyInflater.updateBuilder(GenericDraweeHierarchyInflater.java:127)
                                                                                 	at com.facebook.drawee.generic.GenericDraweeHierarchyInflater.inflateBuilder(GenericDrawee

**Comment by sajjadiq95** [comment]
solved thank you vivian8725118

**Comment by livingstonantony** [comment]
> In my case writing `Fresco.initialize(this);` before `setContentView(R.layout.activity_home);` worked

thank you brother , i got the output
