### ISSUE TITLE
libcore.io.ErrnoException: open failed: EMFILE (Too many open files)

### ISSUE THREAD

**Issue by liujigang** [facebook/fresco#747]
when i fast scroll ; then Application Not Responding   (fresco_0.8.1  Samsung Galaxy S4   Android4.4.2)

```
4864-5328/ W/unknown:BufferedDiskCache﹕ Failed to write to disk-cache for key http://pic1.xxx.com/lwtmq2izfmhfyk5vq_180_180.jpg?t=5&qa=75
    java.io.IOException: open failed: EMFILE (Too many open files)
            at java.io.File.createNewFile(File.java:946)
            at java.io.File.createTempFile(File.java:1011)
            at com.facebook.cache.disk.DefaultDiskStorage$FileInfo.createTempFile(DefaultDiskStorage.java:626)
            at com.facebook.cache.disk.DefaultDiskStorage.createTemporary(DefaultDiskStorage.java:356)
            at com.facebook.cache.disk.DefaultDiskStorage.createTemporary(DefaultDiskStorage.java:39)
            at com.facebook.cache.disk.DiskStorageCache.createTemporaryResource(DiskStorageCache.java:246)
            at com.facebook.cache.disk.DiskStorageCache.insert(DiskStorageCache.java:287)
            at com.facebook.imagepipeline.cache.BufferedDiskCache.writeToDiskCache(BufferedDiskCache.java:329)
            at com.facebook.imagepipeline.cache.BufferedDiskCache.access$500(BufferedDiskCache.java:38)
            at com.facebook.imagepipeline.cache.BufferedDiskCache$3.run(BufferedDiskCache.java:214)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: libcore.io.ErrnoException: open failed: EMFILE (Too many open files)
            at libcore.io.Posix.open(Native Method)
            at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
            at java.io.File.createNewFile(File.java:939)
            at java.io.File.createTempFile(File.java:1011)
            at com.facebook.cache.disk.DefaultDiskStorage$FileInfo.createTempFile(DefaultDiskStorage.java:626)
            at com.facebook.cache.disk.DefaultDiskStorage.createTemporary(DefaultDiskStorage.java:356)
            at com.facebook.cache.disk.DefaultDiskStorage.createTemporary(DefaultDiskStorage.java:39)
            at com.facebook.cache.disk.DiskStorageCache.createTemporaryResource(DiskStorageCache.java:246)
            at com.facebook.cache.disk.DiskStorageCache.insert(DiskStorageCache.java:287)
            at com.facebook.imagepipeline.cache.BufferedDiskCache.writeToDiskCache(BufferedDiskCache.java:329)
            at com.facebook.imagepipeline.cache.BufferedDiskCache.access$500(BufferedDiskCache.java:38)
            at com.facebook.imagepipeline.cache.BufferedDiskCache$3.run(BufferedDiskCache.java:214)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
```

**Comment by IanChilds** [comment]
Are you just using normal Fresco? Or do you configure the disk cache or anything like that yourself?

**Comment by liujigang** [comment]
@IanChilds this is my fresco:
```java


public class FrescoConfig {
    private static final int MAX_HEAP_SIZE = (int) Runtime.getRuntime().maxMemory();
    public static final int MAX_MEMORY_CACHE_SIZE = MAX_HEAP_SIZE / 8;

    public static final int MAX_SMALL_DISK_VERYLOW_CACHE_SIZE = 5 * ByteConstants.MB;
    public static final int MAX_SMALL_DISK_LOW_CACHE_SIZE = 10 * ByteConstants.MB;

    public static final int MAX_DISK_CACHE_VERYLOW_SIZE = 10 * ByteConstants.MB;
    public static final int MAX_DISK_CACHE_LOW_SIZE = 30 * ByteConstants.MB;
    public static final int MAX_DISK_CACHE_SIZE = 50 * ByteConstants.MB;


    private static final String IMAGE_PIPELINE_SMALL_CACHE_DIR = "fresco_images_small";
    private static final String IMAGE_PIPELINE_CACHE_DIR = "fresco_images";

    private static ImagePipelineConfig sImagePipelineConfig;

    private FrescoConfigConstants() {
    }

    public static ImagePipelineConfig getImagePipelineConfig(Context context) {
        if (sImagePipelineConfig == null) {
            sImagePipelineConfig = configureCaches(context);
        }
        return sImagePipelineConfig;
    }

    private static ImagePipelineConfig configureCaches(Context context) {
        final MemoryCacheParams bitmapCacheParams = new MemoryCacheParams(
                FrescoConfigConstants.MAX_MEMORY_CACHE_SIZE,
                Integer.MAX_VALUE,
                FrescoConfigConstants.MAX_MEMORY_CACHE_SIZE,
                Integer.MAX_VALUE,
                Integer.MAX_VALUE);

        Supplier<MemoryCacheParams> mSupplierMemoryCacheParams = new Supplier<MemoryCacheParams>() {
            @Override
            public MemoryCacheParams get() {
                return bitmapCacheParams;
            }
        };

        File cacheDir;
        if (Environment.getExternalStorageState().equals(Environment.MEDIA_MOUNTED)) {
            cacheDir = context.getExternalCacheDir();
        } else {
            cacheDir = context.getCacheDir();
        }
        DiskCacheConfig diskSmallCacheConfig = DiskCacheConfig.newBuilder()
                .setBaseDirectoryPath(cacheDir)
                .setBaseDirectoryName(IMAGE_PIPELINE_SMALL_CACHE_DIR)
                .setMaxCacheSize(FrescoConfigConstants.MAX_DISK_CACHE_SIZE)
                .setMaxCacheSizeOnLowDiskSpace(MAX_SMALL_DISK_LOW_CACHE_SIZE)
                .setMaxCacheSizeOnVeryLowDiskSpace(MAX_SMALL_DISK_VERYLOW_CACHE_SIZE)
                .build();


        DiskCacheConfig diskCacheConfig = DiskCacheConfig.newBuilder()
                .setBaseDirectoryPath(cacheDir)
                .setBaseDirectoryName(IMAGE_PIPELINE_CACHE_DIR)
                .setMaxCacheSize(FrescoConfigConstants.MAX_DISK_CACHE_SIZE)
                .setMaxCacheSizeOnLowDiskSpace(MAX_DISK_CACHE_LOW_SIZE)
                .setMaxCacheSizeOnVeryLowDiskSpace(MAX_DISK_CACHE_VERYLOW_SIZE)
                .build();

        ImagePipelineConfig.Builder configBuilder = ImagePipelineConfig.newBuilder(context)
//               .setDecodeFileDescriptorEnabled(false)
//               .setBitmapsConfig(Bitmap.Config.RGB_565)
//               .setDownsampleEnabled(true)
              .setBitmapMemoryCacheParamsSupplier(mSupplierMemoryCacheParams)
              .setMainDiskCacheConfig(diskCacheConfig)
              .setSmallImageDiskCacheConfig(diskSmallCacheConfig);
        return configBuilder.build();
    }
}


```

**Comment by IanChilds** [comment]
Are you using SimpleDraweeView to download the images? Or are you doing it yourself?

**Comment by liujigang** [comment]
@IanChilds  
[example image](http://pic1.58cdn.com.cn/zhuanzh/n_v1bkuymcyzbizfnleexa3a_800_800.jpg?t=5&qa=75)  ,the image is webp, convers by server.

SimpleDraweeView i only show image. download used ImagePipeline, in this issues, not used image download. thanks.

**Comment by tyronen** [comment]
You should be able to just use the SimpleDraweeView and not use the pipeline directly. Are you experiencing this on devices other than Samsung? We have had problems before with file descriptors on Samsung.

**Comment by liujigang** [comment]
@tyronen @laneyk  it's  ok in new version 0.9.0,thanks!
