### ISSUE TITLE
OOM happened on a specific device

### ISSUE THREAD

**Issue by tianlang** [facebook/fresco#750]
More than 90 percent of ooms happen on a specific device,named m2 note(魅族的魅蓝note2),it happened  hundreds times every day.
so is there any solutions to avoid oom for this device?

**Comment by tianlang** [comment]
java.lang.OutOfMemoryError: Failed to allocate a 1638412 byte allocation with 436016 free bytes and 425KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
	at com.facebook.imagepipeline.memory.BitmapPool.alloc(SourceFile:55)
	at com.facebook.imagepipeline.memory.BitmapPool.alloc(SourceFile:30)
	at com.facebook.imagepipeline.memory.BasePool.get(SourceFile:259)
	at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.decodeStaticImageFromStream(SourceFile:124)
	at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.decodeJPEGFromEncodedImage(SourceFile:116)
	at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.decodeJPEGFromEncodedImage(SourceFile:106)
	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeJpeg(SourceFile:148)
	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(SourceFile:82)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(SourceFile:188)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(SourceFile:96)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(SourceFile:128)
	at com.facebook.imagepipeline.producers.JobScheduler.doJob(SourceFile:207)
	at com.facebook.imagepipeline.producers.JobScheduler.access$000(SourceFile:27)
	at com.facebook.imagepipeline.producers.JobScheduler$1.run(SourceFile:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(SourceFile:43)
	at java.lang.Thread.run(Thread.java:818)


one of the ooms error log

**Comment by IanChilds** [comment]
Is it because this device is running ART and the other devices you are using run on Dalvik? Maybe try making the memory cache a bit smaller, if you can?

**Comment by tianlang** [comment]
Actually, it happened on many devices, these devices are all running android 5.0+,but more than 90 percent of ooms happened on this device.
I already change the memory cache to this:

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {

            System.out.println(getMaxCacheSize());
            return new MemoryCacheParams(getMaxCacheSize()/4, 256, Integer.MAX_VALUE,
                    Integer.MAX_VALUE,
                    Integer.MAX_VALUE);
        }


private int getMaxCacheSize() {
        final int maxMemory = Math.min(activityManager.getMemoryClass() * ByteConstants.MB, Integer.MAX_VALUE);

        if (maxMemory < 32 * ByteConstants.MB) {
            return 4 * ByteConstants.MB;
        } else if (maxMemory < 64 * ByteConstants.MB) {
            return 6 * ByteConstants.MB;
        } else {
            if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.GINGERBREAD) {
                return 8 * ByteConstants.MB;
            } else {
                return maxMemory / 4;
            }
        }
    }

but it's not working for  this device.
