### ISSUE TITLE
crash by oom when load an large image

### ISSUE THREAD

**Issue by Raphael-Xi** [facebook/fresco#761]
in my listview, there is one large image(300k+), others are smaller(50k+/-)
when load the large image,my app crashed by oom
log:(used 0.8.1)

 java.lang.OutOfMemoryError: Failed to allocate a 69596748 byte allocation with 16770800 free bytes and 53MB until OOM
     at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
     at android.graphics.Bitmap.nativeCreate(Native Method)
     at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
     at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
     at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
     at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
     at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
     at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
     at com.facebook.imagepipeline.platform.ArtDecoder.decodeStaticImageFromStream(ArtDecoder.java:137)
     at com.facebook.imagepipeline.platform.ArtDecoder.decodeJPEGFromEncodedImage(ArtDecoder.java:120)
     at com.facebook.imagepipeline.decoder.ImageDecoder.decodeJpeg(ImageDecoder.java:151)
     at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:85)
     at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:188)
     at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:96)
     at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:128)
     at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
     at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
     at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
     at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
     at java.lang.Thread.run(Thread.java:818)

**Comment by IanChilds** [comment]
This image is 69MB! I suggest you download something a bit smaller :)

**Comment by Raphael-Xi** [comment]
in fact,this image is 356kb

**Comment by IanChilds** [comment]
What's the URL? In the error it says that we're trying to allocate 69596748 bytes

**Comment by Raphael-Xi** [comment]
url : http://chuantu.biz/t2/18/1447412758x-1376436578.jpg

**Comment by IanChilds** [comment]
Do you have any special configuration for Fresco? How are you loading the image? This is a bit weird. Are you sure that is the image that it's OOMing on, and there isn't another one that is really huge?

**Comment by Raphael-Xi** [comment]
There is no special configuration for Fresco.
And I used another image,it works well.

**Comment by Raphael-Xi** [comment]
I have found the case. The image is 6378*2728, too large.
