### ISSUE TITLE
crash frequently on 5.0 +  caused by oom

### ISSUE THREAD

**Issue by qluan** [facebook/fresco#768]
java.lang.OutOfMemoryError: Failed to allocate a 4857780 byte allocation with 3664448 free bytes and 3MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
	at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
	at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
	at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.decodeStaticImageFromStream(ArtBitmapFactory.java:126)
	at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.decodeJPEGFromEncodedImage(ArtBitmapFactory.java:118)
	at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.decodeJPEGFromEncodedImage(PlatformBitmapFactory.java:106)
	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeJpeg(ImageDecoder.java:144)
	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:82)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:177)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$100(DecodeProducer.java:93)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:121)
	at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
	at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
	at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by IanChilds** [comment]
Make sure you are using a recent version of Fresco, and that you are only receiving images of the size you need (do resizing if possible). 

If you absolutely cannot get it down to a reasonable size, you can try setting `android:largeHeap=true` in your manifest file.
