### ISSUE TITLE
Caused by: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by loulijun** [facebook/fresco#780]
Many OutOfMemoryError occur, what's wrong with it?

```
Caused by: java.lang.OutOfMemoryError
at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:597)
at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:432)
at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:840)
at android.content.res.Resources.createFromResourceStream(Resources.java:2477)
at android.content.res.Resources.loadDrawable(Resources.java:2136)
at android.content.res.Resources.getDrawable(Resources.java:710)
at com.facebook.drawee.view.GenericDraweeView.inflateHierarchy(GenericDraweeView.java:260)
at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:92)
at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:62)
```

**Comment by aagnes** [comment]
How big you pic is? I guess you're running in 5.0+.
Double check with your pic, and do a resize or downsampling for your picture.

**Comment by 157688302** [comment]
我也遇到了这个问题，就是不能解决这个问题。
I also encountered this problem is a failure to solve the problem.

**Comment by yhb612** [comment]
may be too eggs' bug

**Comment by bunnyswe** [comment]
usage of local resource may produce this exception

**Comment by twoeggs** [comment]
我觉得可以优化下,把placeHolder也单做uri资源放到缓存里面共用,目前之所有大量出现placeHolder加载不了,大多数都是同一个placeHolder被多次加载导致,重复占用内存,如果放到缓存管理,同一个uri的图片只会在缓存中存在一份

**Comment by loulijun** [comment]
@aagnes The issue happened on 4.0+ and very common, you are right the placeholder's resolution ratio is 1242x400 without resize operation， after replace big picture with color then reduce a lot...

**Comment by hcadoid** [comment]
I also appeared OOM, but is the device on LOLLIPOP, 4.X and the following did not happen, do not know how to solve

**Comment by balazsbalazs** [comment]
I would say this is just because the placeholder is too big but multiple people are saying the same things and 1242x400 doesn't seem extremely big -> so I suspect there might be some problem here.
I tried to reproduce/catch this but I wasn't able. Can anyone help reproduce it?

- how often do you see this?
- what device are you using?
- is this in a list or just a simple image?

Can someone create a very simple sample app where this is reproducible?

**Comment by balazsbalazs** [comment]
Similar thing is reported here:
https://github.com/facebook/fresco/issues/734

**Comment by tyronen** [comment]
Folding all OOM issues into #574
