### ISSUE TITLE
FileTree: symbolic link causes infinite recursion

### ISSUE THREAD

**Issue by xjy2061** [facebook/fresco#788]
![image](https://cloud.githubusercontent.com/assets/2942953/11360370/fef767a0-92be-11e5-94fb-e619a925fda2.png)

This may be caused by the file is symbolic link, the `isDirectory` method returns true, then the tree traversal is endless. But I'm not sure, and I don't know why there is a symbolic link file.

**Comment by balazsbalazs** [comment]
What are you doing exactly? Can you paste the code that fails?

**Comment by xjy2061** [comment]
Sorry, this stack trace is from our crash report system, so I don't know what exactly happened.

**Comment by balazsbalazs** [comment]
ok, can you post the full stacktrace please?

**Comment by xjy2061** [comment]
This is the fullest stacktrace I can get.
Caused by: java.lang.StackOverflowError
	at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:145)
	at java.lang.StringBuilder.append(StringBuilder.java:216)
	at java.io.File.join(File.java:215)
	at java.io.File.<init>(File.java:157)
	at java.io.File.<init>(File.java:124)
	at java.io.File.filenamesToFiles(File.java:850)
	at java.io.File.listFiles(File.java:789)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:37)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.file.FileTree.walkFileTree(ProGuard:41)
	at com.facebook.common.f

**Comment by erikandre** [comment]
Duplicating to the newer issue #1696
