### ISSUE TITLE
android.view.InflateException: Binary XML file line #149: Error inflating class com.facebook.drawee.view.SimpleDraweeView

### ISSUE THREAD

**Issue by scdqs** [facebook/fresco#795]
Caused by: java.lang.NullPointerException
	at com.facebook.drawee.view.DraweeView.toString(DraweeView.java:179)
	at java.lang.StringBuilder.append(StringBuilder.java:202)
	at java.util.AbstractCollection.toString(AbstractCollection.java:374)
	at java.util.Formatter.transform(Formatter.java:1421)
	at java.util.Formatter.doFormat(Formatter.java:1081)
	at java.util.Formatter.format(Formatter.java:1042)
	at java.util.Formatter.format(Formatter.java:1011)
	at java.lang.String.format(String.java:2030)
	at java.lang.String.format(String.java:2004)
	at android.droidblaze.ViewPool.findViewsByIdPair(ViewPool.java:88)
	at android.droidblaze.ViewPool.updateView(ViewPool.java:75)
	at android.view.View.onIDChanged(View.java:12466)
	at android.view.View.<init>(View.java:3823)
	at android.widget.ImageView.<init>(ImageView.java:123)
	at android.widget.ImageView.<init>(ImageView.java:119)
	at com.facebook.drawee.view.DraweeView.<init>(DraweeView.java:51)
	at com.facebook.drawee.view.GenericDraweeView.<init>(GenericDraweeView.java:74)
	at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:58)
	... 31 more

**Comment by Kroderia** [comment]
Same issues. Can be temporary fix by a few rebuild try.

**Comment by balazsbalazs** [comment]
When is this happening? What are you doing? Which version of Fresco?
