### ISSUE TITLE
java.lang.OutOfMemoryError: Failed to allocate a 48000012 byte allocation with 4194304 free bytes and 18MB until OOM

### ISSUE THREAD

**Issue by tianjack** [facebook/fresco#802]
java.lang.OutOfMemoryError: Failed to allocate a 48000012 byte allocation with 4194304 free bytes and 18MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
	at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:55)
	at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java:30)
	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
	at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.decodeStaticImageFromStream(ArtBitmapFactory.java:126)
	at com.facebook.imagepipeline.bitmaps.ArtBitmapFactory.decodeJPEGFromEncodedImage(ArtBitmapFactory.java:118)
	at com.facebook.imagepipeline.bitmaps.PlatformBitmapFactory.decodeJPEGFromEncodedImage(PlatformBitmapFactory.java:106)
	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeJpeg(ImageDecoder.java:144)
	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:82)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:177)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$100(DecodeProducer.java:93)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:121)
	at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
	at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
	at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by balazsbalazs** [comment]
You process ran out of memory - not much we can do about it. Try to use large heap, other than that we can't do much on ART.
