### ISSUE TITLE
 java.lang.Throwable: Explicit termination method 'close' not called

### ISSUE THREAD

**Issue by atomd** [facebook/fresco#823]
I got the exception:

```
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                            java.lang.Throwable: Explicit termination method 'close' not called
                                                                at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                at android.content.ContentResolver$CursorWrapperInner.<init>(ContentResolver.java:2507)
                                                                at android.content.ContentResolver.query(ContentResolver.java:515)
                                                                at android.content.ContentResolver.query(ContentResolver.java:434)
                                                                at com.facebook.imagepipeline.producers.LocalExifThumbnailProducer.getRealPathFromUri(LocalExifThumbnailProducer.java:149)
                                                                at com.facebook.imagepipeline.producers.LocalExifThumbnailProducer.getExifInterface(LocalExifThumbnailProducer.java:112)
                                                                at com.facebook.imagepipeline.producers.LocalExifThumbnailProducer$1.getResult(LocalExifThumbnailProducer.java:81)
                                                                at com.facebook.imagepipeline.producers.LocalExifThumbnailProducer$1.getResult(LocalExifThumbnailProducer.java:75)
                                                                at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                at java.lang.Thread.run(Thread.java:818)
```

**Comment by michalgr** [comment]
Thanks for reporting. Which version of Fresco do you use ?

**Comment by michalgr** [comment]
Nevermind, someone is already fixing this.
