### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by wangmeng1989** [facebook/fresco#845]
Fatal Exception: java.lang.OutOfMemoryError
       at com.facebook.imagepipeline.memory.GenericByteArrayPool.alloc(GenericByteArrayPool.java:67)
       at com.facebook.imagepipeline.memory.GenericByteArrayPool.free(GenericByteArrayPool.java:29)
       at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
       at com.facebook.imagepipeline.memory.FlexByteArrayPool.get(FlexByteArrayPool.java:51)
       at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.decodeJPEGByteArrayAsPurgeable(KitKatPurgeableDecoder.java:85)
       at com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.decodeJPEGFromEncodedImage(DalvikPurgeableDecoder.java:89)
       at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.pinBitmap(KitKatPurgeableDecoder.java:32)
       at com.facebook.imagepipeline.decoder.ImageDecoder.decodeJpeg(ImageDecoder.java:151)
       at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:85)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:188)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.getIntermediateImageEndOffset(DecodeProducer.java:96)
       at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:128)
       at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
       at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
       at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
       at java.lang.Thread.run(Thread.java:841)

**Comment by massimocarli** [comment]
@wangmeng1989 Is this fixed? Can you provide more information on the images you're trying to load please?
Thanks
