### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by DTHeaven** [facebook/fresco#861]
Samsung Galaxy S4 GT-I9508V
```
java.lang.OutOfMemoryError: Failed to allocate a 1960012 byte allocation with 196800 free bytes and 192KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
	at com.facebook.imagepipeline.memory.BitmapPool.alloc(Unknown Source)
	at com.facebook.imagepipeline.memory.BitmapPool.getBucketedSizeForValue(Unknown Source)
                                                 free
                                                 alloc
	at com.facebook.imagepipeline.memory.BasePool.initialize(Unknown Source)
                                               get
                                               release
                                               initBuckets
	at com.facebook.imagepipeline.platform.ArtDecoder.decodeFromEncodedImage(Unknown Source)
                                                   decodeJPEGFromEncodedImage
                                                   decodeStaticImageFromStream
	at com.facebook.imagepipeline.platform.ArtDecoder.decodeFromEncodedImage(Unknown Source)
                                                   decodeJPEGFromEncodedImage
                                                   decodeStaticImageFromStream
	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(Unknown Source)
                                                    decodeGif
                                                    decodeStaticImage
                                                    decodeJpeg
	at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(Unknown Source)
                                                    decodeGif
                                                    decodeStaticImage
                                                    decodeJpeg
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(Unknown Source)
                                                                           handleError
                                                                           getQualityInfo
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.onFailureImpl(Unknown Source)
                                                                           onCancellationImpl
                                                                           updateDecodeJob
                                                                           getExtraMap
                                                                           maybeFinish
                                                                           handleResult
                                                                           getIntermediateImageEndOffset
                                                                           onNewResultImpl
                                                                           access$200
                                                                           access$400
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(Unknown Source)
	at com.facebook.imagepipeline.producers.JobScheduler.doJob(Unknown Source)
	at com.facebook.imagepipeline.producers.JobScheduler.clearJob(Unknown Source)
                                                      updateJob
                                                      enqueueJob
                                                      access$000
	at com.facebook.imagepipeline.producers.JobScheduler$1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by aagnes** [comment]
please do a resize for your image. you image is too big. You don't need a full 1.96MB image to load in.
