### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by YuhuihuiYang** [facebook/fresco#865]
java.lang.OutOfMemoryError

at com.facebook.imagepipeline.memory.GenericByteArrayPool.alloc(GenericByteArrayPool.java:67)
at com.facebook.imagepipeline.memory.GenericByteArrayPool.alloc(GenericByteArrayPool.java:29)
at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
at com.facebook.imagepipeline.memory.FlexByteArrayPool.get(FlexByteArrayPool.java:51)
at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.decodeJPEGByteArrayAsPurgeable(KitKatPurgeableDecoder.java:85)
at com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.decodeJPEGFromEncodedImage(DalvikPurgeableDecoder.java:89)
at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.decodeJPEGFromEncodedImage(KitKatPurgeableDecoder.java:32)
at com.facebook.imagepipeline.decoder.ImageDecoder.decodeJpeg(ImageDecoder.java:151)
at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:85)
at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:188)
at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:96)
at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:128)
at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
at java.lang.Thread.run(Thread.java:856)

The problem occurs when the list is sliding fast.
Fresco 0.8.1

**Comment by aagnes** [comment]
please do a resize for you jpg to see if it can solve your problem

**Comment by aagnes** [comment]
and how big each image is? how many of those are showing on a screen at the same time?

**Comment by YuhuihuiYang** [comment]
setResizeOptions(new ResizeOptions(200, 200))   I've already done it.

**Comment by YuhuihuiYang** [comment]
I loaded the local picture, some are loaded into the thumbnail path, but some are original.

**Comment by IanChilds** [comment]
Are they all JPEGs? If not, then you need to use downsampling.

**Comment by YuhuihuiYang** [comment]
setDownsampleEnabled(true)

**Comment by kirwan** [comment]
We're cleaning up long-untouched issues so I'm closing this one.

If you think this is still an issue, feel free to comment and we can re-open.
