### ISSUE TITLE
Not support .ico format ?

### ISSUE THREAD

**Issue by KynoYang** [facebook/fresco#868]
Hi, guys. I'm trying to display a .ico image file with SimpleDrawee. But it turns out not working. Below is the  exception I got, and the url is http://douban.com/favicon.ico

```
java.lang.IllegalArgumentException: unknown image format
at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:82)
at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:188)
at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:96)
at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:128)
at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
at java.lang.Thread.run(Thread.java:841)
```

Is it indeed that fresco doesn't support ico image, or I do something mistake?

**Comment by aagnes** [comment]
unfortunately fresco don't support ico at the moment.

**Comment by KynoYang** [comment]
@aagnes  Any plan to support it? If not, let me know since I need to do this in another way. Thanks very much!

**Comment by aagnes** [comment]
we don't have a plan to support ico as it's not commonly used. I believe you can transform it to jpg/png format.

**Comment by KynoYang** [comment]
Well, I understand. Thanks for reply.

**Comment by zhangmaoyong34** [comment]
picasso support ico fromat

**Comment by dongorigin** [comment]
I have the same problem.
Application needs to load the image on the network, the image format is not necessarily png/jpg.

**Comment by oprisnik** [comment]
Fresco supports custom image decoders. You can just add a custom decoder and image format header checker (you don't need a DrawableFactory, just return a `CloseableStaticBitmap`) and then you're good to go.

If somebody wants to add one to the Showcase sample app for .ico, that would be great. Pull requests are welcome!

Simple color example: https://github.com/facebook/fresco/tree/master/samples/showcase/src/main/java/com/facebook/fresco/samples/showcase/imageformat/color

**Comment by LomikXP** [comment]
Use this, for example https://github.com/divStar/ico4a
and create some classes
```
public class IcoFormat {
	public static final ImageFormat ICO = new ImageFormat("ICO", "ico");
	public static class Decoder implements ImageDecoder {
		@Override
		public CloseableImage decode(EncodedImage encodedImage, int length, QualityInfo qualityInfo, ImageDecodeOptions options) {
			CloseableImage closeableImage = null;
			try {
				closeableImage = new CloseableStaticBitmap(ICODecoder.read(encodedImage.getInputStream()).get(0), SimpleBitmapReleaser.getInstance(), ImmutableQualityInfo.FULL_QUALITY, 0);
			} catch (Exception e) {
			}
			return closeableImage;
		}
	}
	public static class FormatChecker implements ImageFormat.FormatChecker {
		private static final byte[] HEADER = new byte[]{0x00, 0x00, 0x01, 0x00};
		@Override
		public int getHeaderSize() {
			return HEADER.length;
		}
		@Nullable
		@Override
		public ImageFormat determineFormat(byte[] headerBytes, int headerSize) {
			if (headerSize < getHeaderSize()) {
				return null;
			}
			if (ImageFormatCheckerUtils.startsWithPattern(headerBytes, HEADER)) {
				return ICO;
			}
			return null;
		}
	}
}
```
and to global config
```
FrescoImageLoader.with(app,
	OkHttpImagePipelineConfigFactory.newBuilder(app, 
		OkClient.getInstance()).setImageDecoderConfig(
		`ImageDecoderConfig.newBuilder().addDecodingCapability(IcoFormat.ICO, new IcoFormat.FormatChecker(), new IcoFormat.Decoder()).build()).build()))
```

**Comment by lambdapioneer** [comment]
Supported with #2189 :)
