### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by huangshengsen** [facebook/fresco#869]
Q：How? 
A：When loading the images I rotating  the phone screen 

fresco version：0.8.+

java.lang.OutOfMemoryError: Failed to allocate a 1960012 byte allocation with 196800 free bytes and 192KB until OOM
    at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
    at android.graphics.Bitmap.nativeCreate(Native Method)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:939)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:912)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:879)

**Comment by aagnes** [comment]
please do a resize for your image. you don't need a 1.96mb image.
