### ISSUE TITLE
libmemchunk.so

### ISSUE THREAD

**Issue by kim-cy** [facebook/fresco#893]
I wrote as followed 

```java
FLog.setMinimumLoggingLevel(FLog.VERBOSE);

        Fresco.initialize(this);

        setContentView(R.layout.temp_webp);

        mAnimatedWebpView = (SimpleDraweeView) findViewById(R.id.animated_webp);

 Uri uri = new Uri.Builder()
                .scheme(UriUtil.LOCAL_ASSET_SCHEME) // "res"
                .path("emoticons/emot_001.webp")
                .build();

        DraweeController animatedWebpController = Fresco.newDraweeControllerBuilder()
                .setAutoPlayAnimations(true)
                .setUri(uri)
                .build();
        mAnimatedWebpView.setController(animatedWebpController);
```
my app has fatal exception as followed

```
Process: com.exp.couple, PID: 26296
                                                                java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.exp.couple-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libmemchunk.so"
                                                                    at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                    at java.lang.System.loadLibrary(System.java:989)
                                                                    at com.facebook.common.soloader.SoLoaderShim$DefaultHandler.loadLibrary(SoLoaderShim.java:32)
                                                                    at com.facebook.common.soloader.SoLoaderShim.loadLibrary(SoLoaderShim.java:56)
                                                                    at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:36)
                                                                    at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:60)
                                                                    at com.facebook.imagepipeline.memory.NativeMemoryChunkPool.alloc(NativeMemoryChunkPool.java:22)
                                                                    at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:259)
                                                                    at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(NativePooledByteBufferOutputStream.java:53)
                                                                    at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:98)
                                                                    at com.facebook.imagepipeline.memory.NativePooledByteBufferFactory.newByteBuffer(NativePooledByteBufferFactory.java:26)
                                                                    at com.facebook.imagepipeline.producers.LocalFetchProducer.getByteBufferBackedEncodedImage(LocalFetchProducer.java:99)
                                                                    at com.facebook.imagepipeline.producers.LocalFetchProducer.getEncodedImage(LocalFetchProducer.java:119)
                                                                    at com.facebook.imagepipeline.producers.LocalAssetFetchProducer.getEncodedImage(LocalAssetFetchProducer.java:42)
                                                                    at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:66)
                                                                    at com.facebook.imagepipeline.producers.LocalFetchProducer$1.getResult(LocalFetchProducer.java:62)
                                                                    at com.facebook.common.executors.StatefulRunnable.run(StatefulRunnable.java:45)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                    at java.lang.Thread.run(Thread.java:818)
```

**Comment by kim-cy** [comment]
I only add 
compile 'com.facebook.fresco:fresco:0.8.1' in build.gradle in my app.

**Comment by tyronen** [comment]
See #410
