### ISSUE TITLE
 java.lang.NoClassDefFoundError: com.facebook.imagepipeline.core.ImagePipelineFactory

### ISSUE THREAD

**Issue by dung90it** [facebook/fresco#894]
FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: com.facebook.imagepipeline.core.ImagePipelineFactory
            at com.facebook.drawee.backends.pipeline.Fresco.initialize(Fresco.java:32)
            at vn.mecorp.mobo.MoboApp.onCreate(MoboApp.java:163)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4419)
            at android.app.ActivityThread.access$1300(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5069)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by tyronen** [comment]
Are you building with Gradle, or Eclipse? How is your build environment set up?

**Comment by dung90it** [comment]
thanks @tyronen it worked
MultiDex.install(this);

**Comment by Aheadboy** [comment]
i got this:can not find symbol MultiDex
![image](https://cloud.githubusercontent.com/assets/8358046/21496411/54dc4f12-cc59-11e6-8b23-a9560dd3f1d9.png)

**Comment by dung90it** [comment]
Configure your app for multidex
https://developer.android.com/studio/build/multidex.html#mdex-gradle

**Comment by Aheadboy** [comment]
i have already done this :
![image](https://cloud.githubusercontent.com/assets/8358046/21512886/cfdea58c-ccec-11e6-8588-630f13819f70.png)
but problem still there
