### ISSUE TITLE
How to enable webp support in Fresco 0.9.0

### ISSUE THREAD

**Issue by eldk** [facebook/fresco#917]
Hello,

I've updated to Fresco 0.9.0.
How to enable webpSupport all the way back to Android 2.3. ?

I have set : 
`ImagePipelineConfig config = ImagePipelineConfig.newBuilder(context)`
`.setWebpSupportEnabled(true)`
`.build();`
`Fresco.initialize(context, config);`

But have the error below : 
>WebpTranscodeConsumer: unhandled exception
                                                                                            java.lang.NullPointerException
                                                                                                at com.facebook.imagepipeline.producers.WebpTranscodeProducer.shouldTranscode(WebpTranscodeProducer.java:160)
                                                                                                at com.facebook.imagepipeline.producers.WebpTranscodeProducer.access$000(WebpTranscodeProducer.java:37)
                                                                                                at com.facebook.imagepipeline.producers.WebpTranscodeProducer$WebpTranscodeConsumer.onNewResultImpl(WebpTranscodeProducer.java:75)
                                                                                                at com.facebook.imagepipeline.producers.WebpTranscodeProducer$WebpTranscodeConsumer.onNewResultImpl(WebpTranscodeProducer.java:59)
                                                                                                at com.facebook.imagepipeline.producers.BaseConsumer.onNewResult(BaseConsumer.java:49)
                                                                                                at com.facebook.imagepipeline.producers.NetworkFetchProducer.notifyConsumer(NetworkFetchProducer.java:168)
                                                                                                at com.facebook.imagepipeline.producers.NetworkFetchProducer.handleFinalResult(NetworkFetchProducer.java:155)
                                                                                                at com.facebook.imagepipeline.producers.NetworkFetchProducer.onResponse(NetworkFetchProducer.java:110)
                                                                                                at com.facebook.imagepipeline.producers.NetworkFetchProducer.access$000(NetworkFetchProducer.java:37)
                                                                                                at com.facebook.imagepipeline.producers.NetworkFetchProducer$1.onResponse(NetworkFetchProducer.java:72)
                                                                                                at com.facebook.imagepipeline.backends.okhttp.OkHttpNetworkFetcher$2.onResponse(OkHttpNetworkFetcher.java:120)
                                                                                                at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
                                                                                                at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
                                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
                                                                                                at java.lang.Thread.run(Thread.java:1019)

Greatings,

Eric

https://github.com/facebook/fresco/commit/fde9dbdd393f84a8d71c236562419642eb7704fe

**Comment by massimocarli** [comment]
Hi @eldk. If you're building from the source you should just add this 

```compile project(':static-webp')```

to the dependencies of imagepipeline module.

**Comment by eldk** [comment]
Hello @massimocarli ,
I'm not building from source but use Gradle in Android Studio.

**Comment by massimocarli** [comment]
@eldk , in that case just add this:

```compile 'com.facebook.fresco:webpsupport:0.9.0+'```

**Comment by eldk** [comment]
thanks

**Comment by eldk** [comment]
Ok,
Now I have this :

>RequestLoggingListener: time 379510351: onProducerFinishWithFailure: {requestId: 1, stage: DecodeProducer, elapsedTime: 52 ms, extraMap: {queueTime=0, imageType=DEFAULT, isFinal=true, hasGoodQuality=true}, throwable: java.lang.NullPointerException: BitmapFactory returned null}
01-15 17:47:57.549 31179-31219/net.opalesurfcasting.lamaille W/unknown:RequestLoggingListener: time 379510361: onRequestFailure: {requestId: 1, elapsedTime: 618 ms, throwable: java.lang.NullPointerException: BitmapFactory returned null}
01-15 17:47:57.559 31179-31179/net.opalesurfcasting.lamaille V/unknown:AbstractDraweeController: controller 40712cd8 1: final_failed @ onFailure: failure: java.lang.NullPointerException: BitmapFactory returned null
01-15 17:47:57.569 31179-31179/net.opalesurfcasting.lamaille E/unknown:: Error loading 1
                                                                         java.lang.NullPointerException: BitmapFactory returned null
                                                                             at com.facebook.common.internal.Preconditions.checkNotNull(Preconditions.java:226)
                                                                             at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.decodeByteArrayAsPurgeable(KitKatPurgeableDecoder.java:62)
                                                                             at com.facebook.imagepipeline.platform.DalvikPurgeableDecoder.decodeFromEncodedImage(DalvikPurgeableDecoder.java:60)
                                                                             at com.facebook.imagepipeline.platform.KitKatPurgeableDecoder.decodeFromEncodedImage(KitKatPurgeableDecoder.java:32)
                                                                             at com.facebook.imagepipeline.decoder.ImageDecoder.decodeStaticImage(ImageDecoder.java:127)
                                                                             at com.facebook.imagepipeline.decoder.ImageDecoder.decodeImage(ImageDecoder.java:94)
                                                                             at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java:189)
                                                                             at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$200(DecodeProducer.java:97)
                                                                             at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java:129)
                                                                             at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java:207)
                                                                             at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java:27)
                                                                             at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java:78)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
                                                                             at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:43)
                                                                             at java.lang.Thread.run(Thread.java:1019)

**Comment by massimocarli** [comment]
@eldk Please, just as a test, try to set 

```.setWebpSupportEnabled(false)```

or don't use that method at all. 

Thanks

**Comment by eldk** [comment]
ok,
I'm testing on a Gingerbread device.
I have disabled all okHttp (switched to 0.9.0)  stuff and use default Fresco fetcher :

`ImagePipelineConfig config = ImagePipelineConfig
                .newBuilder(context)
                .setDownsampleEnabled(true)
                .setWebpSupportEnabled(false)
                .setRequestListeners(requestListeners)
                .build();`

Test OK, but image aren't fetched as webp as expected.

The error occur when using okHttp and force userAgent and accept headers  to fetch webp pictures.

I try with old okHttp (0.8.0) and .setWebpSupportEnabled(false) or true

**Comment by eldk** [comment]
1 - Android Gingerbread (API 10), Fresco default fetcher, webpsupport disabled : OK but only jpeg are fetched.

`ImagePipelineConfig config = ImagePipelineConfig
                .newBuilder(context)
                .setDownsampleEnabled(true)
                .setWebpSupportEnabled(false)
                .setRequestListeners(requestListeners)
                .build();`

2  - Android Gingerbread (API 10), Fresco default fetcher, webpsupport enabled: OK but only jpeg are fetched.

`ImagePipelineConfig config = ImagePipelineConfig
                .newBuilder(context)
                .setDownsampleEnabled(true)
                .setWebpSupportEnabled(true)
                .setRequestListeners(requestListeners)
                .build();`

**Comment by massimocarli** [comment]
I've created a very simple app which  just load a webp images and without webpsupport library I get, as right, a NPE while when I define the webpsupport as dependency all works fine. I've tested with webp images and on GB. Can you provide us the URL of the image you're try to load please?
Thanks

**Comment by eldk** [comment]
@massimocarli should you give a mail please ?

**Comment by zenghuikun** [comment]
I meet some problem with these device:
Samsung GT-I9220  4.1.2
HTC	One(802d)	4.2.2
Motorola ME865(ME865)	4.0.4
lenovo A390	4.0.4
ZTE Q705U 4.2.2
HTC Desire V(T328w)	4.0.3

and i soveld by added compile 'com.facebook.fresco:webpsupport:0.9.0+', thanks for your job @massimocarli

**Comment by eldk** [comment]
Hello,

So .setWebpSupportEnabled(true) in  ImagePipelineConfig is never needed

To add webp support For OS < Android 4.0, the only needed config to enableit is to add Fresco webpsupport library.

That is described here :
http://frescolib.org/docs/webp-support.html#

Thanks,

Eric
