### ISSUE TITLE
Error inflating class com.facebook.drawee.view.SimpleDraweeView after restore application

### ISSUE THREAD

**Issue by nikslushkin** [facebook/fresco#929]
Steps: 
1 - launch application with target 23 on Android 6
2 - adb shell bmgr fullbackup PACKAGE
3 - adb shell bmgr restore PACKAGE
4 - launch application - crash

Library initialized in Application class in onCreate

```
  Caused by: android.view.InflateException: Binary XML file line #79: Binary XML file line #31: Binary XML file line #7: Binary XML file line #7: Error inflating class com.facebook.drawee.view.SimpleDraweeView
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
```

**Comment by nikslushkin** [comment]
reproduced on 0.9.0

**Comment by chenenyu** [comment]
+1

**Comment by plamenko** [comment]
Can you provide the piece of XML that specifies SimpleDraweeView?

**Comment by aneeshATgithub** [comment]
use following version, and you can initialize fresco in Application class

compile 'com.facebook.fresco:fresco:0.12.0'

**Comment by ek1209** [comment]
android.view.InflateException: Binary XML file line #31: Binary XML file line #31: Error inflating class com.facebook.drawee.view.SimpleDraweeView
                                                                        Caused by: android.view.InflateException: Binary XML file line #31: Error inflating class com.facebook.drawee.view.SimpleDraweeView
                                                                        Caused by: java.lang.reflect.InvocationTargetException
                                                                            at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                            at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                            at com.example.ekta.appgw.ImageListFragment$SimpleStringRecyclerViewAdapter.onCreateViewHolder(ImageListFragment.java:112)
                                                                            at com.example.ekta.appgw.ImageListFragment$SimpleStringRecyclerViewAdapter.onCreateViewHolder(ImageListFragment.java:84)
                                                                            at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6078)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5248)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5158)
                                                                            at android.support.v7.widget.LayoutState.next(LayoutState.java:100)
                                                                            at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1568)
                                                                            at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:678)
                                                                            at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:600)
                                                                            at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3379)
                                                                            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3188)
                                                                            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3632)
                                                                            at android.view.View.layout(View.java:17535)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5616)
                                                                            at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1799)
                                                                            at android.view.View.layout(View.java:17535)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5616)
                                                                            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                            at android.view.View.layout(View.java:17535)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5616)
                                                                            at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                            at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                            at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1367)
                                                                            at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:849)
                                                                            at android.view.View.layout(View.java:17535)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5616)
                                                                            at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                            at android.view.View.layout(View.java:17535)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5616)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                            at android.view.View.layout(View.java:17535)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5616)
                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                            at android.view.View.layout(View.java:17535)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5616)
11-25 12:19:52.851 18357-18357/com.example.ekta.appgw E/AndroidRuntime:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                            at android.view.View.layout(View.java:17535)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5616)
                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                            at android.view.View.layout(View.java:17535)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5616)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                            at com.android.internal.policy.DecorView.onLayout(DecorView.java:724)
                                                                            at android.view.View.layout(View.java:17535)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5616)
                                                                            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2354)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2081)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1258)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6348)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
                                                                         Caused by: java.lang.NullPointerException: SimpleDraweeView was not initialized!
                                                                            at com.facebook.common.internal.Preconditions.checkNotNull(Preconditions.java:226)
                                                                            at com.facebook.drawee.view.SimpleDraweeView.init(SimpleDraweeView.java:81)
                                                                            at com.facebook.drawee.view.SimpleDraweeView.<init>(SimpleDraweeView.java:63)
                                                                            	... 78 more


I am getting this error can you please help me with this
