### ISSUE TITLE
upgrade app java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by QiuSean** [facebook/fresco#950]
java.lang.UnsatisfiedLinkError: No implementation found for long com.facebook.imagepipeline.memory.NativeMemoryChunk.nativeAllocate(int) (tried Java_com_facebook_imagepipeline_memory_NativeMemoryChunk_nativeAllocate and Java_com_facebook_imagepipeline_memory_NativeMemoryChunk_nativeAllocate__I)
	at com.facebook.imagepipeline.memory.NativeMemoryChunk.nativeAllocate(Native Method)
	at com.facebook.imagepipeline.memory.NativeMemoryChunk.<init>(SourceFile:58)
	at com.facebook.imagepipeline.memory.n.i(SourceFile:60)
	at com.facebook.imagepipeline.memory.n.b(SourceFile:22)
	at com.facebook.imagepipeline.memory.BasePool.a(SourceFile:259)
	at com.facebook.imagepipeline.memory.NativePooledByteBufferOutputStream.<init>(SourceFile:53)
	at com.facebook.imagepipeline.memory.p.a(SourceFile:141)
	at com.facebook.imagepipeline.memory.p.b(SourceFile:26)
	at com.facebook.imagepipeline.producers.at.a(SourceFile:94)
	at com.facebook.imagepipeline.producers.at.a(SourceFile:37)
	at com.facebook.imagepipeline.producers.au.a(SourceFile:72)
	at com.facebook.imagepipeline.a.a.e.onResponse(SourceFile:116)
	at com.ss.squareup.okhttp.Call$AsyncCall.execute(SourceFile:168)
	at com.ss.squareup.okhttp.internal.NamedRunnable.run(SourceFile:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:831)

**Comment by QiuSean** [comment]
![image](https://cloud.githubusercontent.com/assets/5205759/12541201/937c1884-c34e-11e5-91a0-e57ceef6df39.png)

**Comment by plamenko** [comment]
Duplicate #410
