### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by zhanxiuwen** [facebook/fresco#993]
when i use Fresco on  Z7 Max Nubia there will  be a Crash ，but other mobile is normal
java.lang.NullPointerException: Attempt to invoke virtual method 'long android.graphics.Bitmap.ni()' on a null object reference
	at android.graphics.BitmapShader.(BitmapShader.java:45)
	at com.facebook.drawee.drawable.RoundedBitmapDrawable.updatePaint(RoundedBitmapDrawable.java:242)
	at com.facebook.drawee.drawable.RoundedBitmapDrawable.draw(RoundedBitmapDrawable.java:165)
	at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:140)
	at com.facebook.drawee.drawable.ScaleTypeDrawable.draw(ScaleTypeDrawable.java:108)
	at com.facebook.drawee.drawable.FadeDrawable.drawDrawableWithAlpha(FadeDrawable.java:306)
	at com.facebook.drawee.drawable.FadeDrawable.draw(FadeDrawable.java:293)
	at com.facebook.drawee.drawable.ForwardingDrawable.draw(ForwardingDrawable.java:140)
	at com.facebook.drawee.generic.GenericDraweeHierarchy$RootDrawable.draw(GenericDraweeHierarchy.java:133)
	at android.widget.ImageView.onDraw(ImageView.java:1158)
	at android.view.View.draw(View.java:15515)
	at android.view.View.updateDisplayListIfDirty(View.java:14398)
	at android.view.View.getDisplayList(View.java:14427)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
	at android.view.View.updateDisplayListIfDirty(View.java:14348)
	at android.view.View.getDisplayList(View.java:14427)
	at android.view.View.draw(View.java:15224)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3532)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3325)
	at android.view.View.updateDisplayListIfDirty(View.java:14390)
	at android.view.View.getDisplayList(View.java:14427)
	at android.view.View.draw(View.java:15224)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3532)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3325)
	at android.view.View.updateDisplayListIfDirty(View.java:14390)
	at android.view.View.getDisplayList(View.java:14427)
	at android.view.View.draw(View.java:15224)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3532)
	at android.widget.ListView.drawChild(ListView.java:3483)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3325)
	at android.widget.AbsListView.dispatchDraw(AbsListView.java:2762)
	at android.widget.ListView.dispatchDraw(ListView.java:3478)
	at android.view.View.draw(View.java:15527)
	at android.widget.AbsListView.draw(AbsListView.java:4507)
	at android.view.View.updateDisplayListIfDirty(View.java:14398)
	at android.view.View.getDisplayList(View.java:14427)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
	at android.view.View.updateDisplayListIfDirty(View.java:14348)
	at android.view.View.getDisplayList(View.java:14427)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
	at android.view.View.updateDisplayListIfDirty(View.java:14348)
	at android.view.View.getDisplayList(View.java:14427)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
	at android.view.View.updateDisplayListIfDirty(View.java:14348)
	at android.view.View.getDisplayList(View.java:14427)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
	at android.view.View.updateDisplayListIfDirty(View.java:14348)
	at android.view.View.getDisplayList(View.java:14427)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
	at android.view.View.updateDisplayListIfDirty(View.java:14348)
	at android.view.View.getDisplayList(View.java:14427)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
	at android.view.View.updateDisplayListIfDirty(View.java:14348)
	at android.view.View.getDisplayList(View.java:14427)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
	at android.view.View.updateDisplayListIfDirty(View.java:14348)
	at android.view.View.getDisplayList(View.java:14427)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
	at android.view.View.updateDisplayListIfDirty(View.java:14348)
	at android.view.View.getDisplayList(View.java:14427)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:279)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:285)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:335)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2939)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2753)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2367)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1292)
	at

**Comment by IanChilds** [comment]
Looks like this is happening in Android itself, can you dig into the code to see why that's happening please?
